### PR TITLE
chore: Remove Static from File.flix

### PR DESCRIPTION
**Pull request by paulbutcher**
As per #5131

This goes some way towards removing `Static` from `File.flix`, on the assumption that [this](https://github.com/flix/flix/issues/5131#issuecomment-1362754812) is correct.

I've not been able to go as far as I'd like because it turns out that Java interop doesn't know how to cope with arrays in any region other than `Static`. So I'll address that next.

### CODE REVIEW

**Comment by paulbutcher** [comment]
> I've not been able to go as far as I'd like because it turns out that Java interop doesn't know how to cope with arrays in any region other than Static. So I'll address that next.

Hmm, I think I may have got myself confused. Hold fire reviewing this for now.

**Comment by magnus-madsen** [comment]
I am not happy with the introduction of `unsafe_cast`, but I will accept it as a step on the path to removing `Scoped` and then hopefully later we can drop these casts.

**Comment by paulbutcher** [comment]
> I am not happy with the introduction of `unsafe_cast`, but I will accept it as a step on the path to removing `Scoped` and then hopefully later we can drop these casts.

Your answer to [this](https://github.com/flix/flix/issues/5131#issuecomment-1362747390) question suggested that that won't be possible until the two effect systems are unified?

**Comment by magnus-madsen** [comment]
Yeah and/or changes to Iterator/introduction of Stream

**Pull request merged**
