### PR TITLE
feat: add `--Xno-set-effects`

### PR DESCRIPTION
**Pull request by mlutze**
Now effects are enabled by default.

Related to https://github.com/flix/vscode-flix/issues/208

This will make prototyping a lot easier. We can revisit before release.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Rename to `Xno-set-effects` thanks!

**Comment by magnus-madsen** [comment]
Ill hold of merging this before a few more things are ready and we have that ticket information.

**Comment by magnus-madsen** [comment]
@stephentetley 

We thinking our new effect system is fairly stable now.

Does your projects work with master with `--Xeffects` or alternatively with this PR?

**Comment by magnus-madsen** [comment]
!!!jar

**Comment by magnus-madsen** [comment]
@mlutze Build failure.

**Comment by magnus-madsen** [comment]
Maybe we should release a new Flix stable before flipping the flag?

**Comment by mlutze** [comment]
> Maybe we should release a new Flix stable before flipping the flag?

Yes, good thought

**Comment by stephentetley** [comment]
> @stephentetley
> 
> We thinking our new effect system is fairly stable now.
> 
> Does your projects work with master with `--Xeffects` or alternatively with this PR?

My lower level libs work with effects `--Xeffects` . I'm still working on an refactoring that's got somewhat out of hand, so my higher level libraries are broken due to generally being out-of-date.

**Comment by magnus-madsen** [comment]
> > @stephentetley
> > We thinking our new effect system is fairly stable now.
> > Does your projects work with master with `--Xeffects` or alternatively with this PR?
> 
> My lower level libs work with effects `--Xeffects` . I'm still working on an refactoring that's got somewhat out of hand, so my higher level libraries are broken due to generally being out-of-date.

Oh no. Did we break something fundamental or is it just due to our many recent changes?

**Comment by stephentetley** [comment]
> Oh no. Did we break something fundamental or is it just due to our many recent changes?

Moving to regions was quite a lot of work. But the substantive problem has been the code was up to two years old, so Flix has moved on quite a bit, I'm more proficient with Java so I'd do "wrapper" libraries differently, and of course I'm better at Flix now as well - so there are general design decisions I'd do differently.

**Comment by magnus-madsen** [comment]
@mlutze Conflicted, but I think we are ready.

**Comment by magnus-madsen** [comment]
This PR together with https://github.com/flix/flix/issues/4340 will make us available to move forward 🚀

**Comment by magnus-madsen** [comment]
I would like to enable both effect systems by default and add two (mutually exclusive??) flags to toggle between them.

Perhaps: `--Xno-bool-effects` and `--Xno-set-effects`. 

Maybe they don't have to be exclusive?

**Pull request closed without merging**
