### PR TITLE
feat: `toIteratorKeys` function to `RedBlackTree`

### PR DESCRIPTION
**Pull request by ninaandrup**
#2998

### CODE REVIEW

**Comment by ninaandrup** [comment]
The code is very ugly. I will refine it later.

**Comment by ninaandrup** [comment]
@magnus-madsen I found a better solution using Preorder tree walk. Would you prefer Inorder tree walk?

**Comment by magnus-madsen** [comment]
The walk should be left-to-right which I think means in-order. That is, the order should be the same as when you call `toList`.

**Comment by ninaandrup** [comment]
> The walk should be left-to-right which I think means in-order. That is, the order should be the same as when you call `toList`.

Alright. It also makes more sense to keep the order when doing the iteration

**Comment by magnus-madsen** [comment]
> > The walk should be left-to-right which I think means in-order. That is, the order should be the same as when you call `toList`.
> 
> Alright. It also makes more sense to keep the order when doing the iteration

We would want `X.toList === x.toIterator.toList`. Makes sense? :)

**Comment by magnus-madsen** [comment]
When I asked for a `toIterator` on RBTree I did not realize how complicated it would be. I spent several hours yesterday looking into it, but I could not really come up with a satisfying solution. In the end I came close with something called "functional Zippers". Your solution is close to a mutable version of that (so props for the discovery!). In any case, I still feel like I personally don't have a good handle/understanding of "how" this should work. So I am going to mark this as blocked, while I try to think of the implementation I would like to have. (Your solution probably works, but I am looking for the *exact right one*-- whatever that is).

**Comment by magnus-madsen** [comment]
I will mark this as blocked - so leave it as-is for now. Ill return when I come up with something.

Meanwhile, take a look at: http://learnyouahaskell.com/zippers

**Comment by ninaandrup** [comment]
> When I asked for a `toIterator` on RBTree I did not realize how complicated it would be. I spent several hours yesterday looking into it, but I could not really come up with a satisfying solution. In the end I came close with something called "functional Zippers". Your solution is close to a mutable version of that (so props for the discovery!). In any case, I still feel like I personally don't have a good handle/understanding of "how" this should work. So I am going to mark this as blocked, while I try to think of the implementation I would like to have. (Your solution probably works, but I am looking for the _exact right one_-- whatever that is).

Sounds good :)
I struggled a bit, but played around with different solution. This one was the best I could come up with without storing too much of the tree. But I'll look into "functional Zippers".

**Comment by magnus-madsen** [comment]
Whats the status on this?

**Comment by ninaandrup** [comment]
> Whats the status on this?

I think you marked it as `blocked` to figure out, what you wanted the solution to look like.
Did you want me to make a solution using "functional zippers" like haskall? Or was it just one way of doing it?

**Comment by magnus-madsen** [comment]
Ah right- so its blocked on me. I will have to think more then :)

**Comment by magnus-madsen** [comment]
I am closing this. Not because we don't want to solve this problem, but because we need a new approach and the code is outdated anyway.

**Pull request closed without merging**
