### PR TITLE
test: refactor tests to prepare for namespace migration

### PR DESCRIPTION
**Pull request by mlutze**
related to #4967

### CODE REVIEW

**Comment by magnus-madsen** [comment]
RFR/RFM?

**Comment by mlutze** [comment]
Ready

**Comment by magnus-madsen** [comment]
What's the TLDR on the changes?

**Comment by mlutze** [comment]
> What's the TLDR on the changes?

1. Changing to qualify cases everywhere
2. Moving `CyclicBarrier` into companion position

**Pull request merged**
