### PR TITLE
ci: update community build

### LINKED ISSUE #5845: Update community build
- [ ] Add `stephentetley/flix-either`
- [ ] Add `stephentetley/flix-time`
- [ ] Drop `magnus-madsen/helloworld`

Anything else?

### PR DESCRIPTION
**Pull request by mlutze**
Fixes #5845

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@stephentetley There is a small issue in `htmldoc` it seems.

**Comment by magnus-madsen** [comment]
Ah wait, my bad I think

**Comment by magnus-madsen** [comment]
Ah- seems there is still a small issue.

**Comment by mlutze** [comment]
> Ah- seems there is still a small issue.

Yes, I opened a PR here https://github.com/stephentetley/flix-htmldoc/pull/1

**Comment by stephentetley** [comment]
Thanks. 

I've applied the PR to `flix-htmldoc` - I'll turn that module into proper tests this week (or remove it and flesh out the other test module).

**Pull request merged**
