### PR TITLE
fix: `run` arguments

### LINKED ISSUE #5521: `Environment.getArgs` doesn't work when running with `run` command

### PR DESCRIPTION
**Pull request by JonathanStarup**
Fixes #5521

### CODE REVIEW

**Comment by JonathanStarup** [comment]
@mlutze can you think of any reason that `Console.withOut ...` wouldn't catch the output of the flix main?

**Comment by mlutze** [comment]
Maybe if running Flix inside scala starts a new "process" of some sort where stdout is reset... but I don't know.

**Comment by JonathanStarup** [comment]
Ready to merge, but as untested as the other packager things

**Comment by magnus-madsen** [comment]
I don't think the bug has been fixed, but the PR has to be redone because we made changes.

**Pull request closed without merging**
