### PR TITLE
feat: remove relational choice from backend

### LINKED ISSUE #5888: Remove choice
Do you approve @magnus-madsen? Alternatively the required translation should be moved from the simplified into lowering (I don't know what difficulties that might cause)

### PR DESCRIPTION
**Pull request by JonathanStarup**
Fixes #5888

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I would like to keep the test cases for the type system. Like I would like to keep everything in the frontend, is that possible?

**Comment by magnus-madsen** [comment]
For example, maybe we can just remove the `@test` annotations. That should still check that code compiles -- which is the interesting research part.

**Comment by JonathanStarup** [comment]
> For example, maybe we can just remove the `@test` annotations. That should still check that code compiles -- which is the interesting research part.

Yes, i Just remembered. Should all be good now :)

**Comment by magnus-madsen** [comment]
Merged.

**Pull request merged**
