### PR TITLE
ci: add community build script

### PR DESCRIPTION
**Pull request by mlutze**
A basic initial version. Takes a list of projects and installs and builds each individually.

Future work includes:
* actually adding projects to the list
* collecting a list of failures instead of failing fast
* dependency management

Depends on https://github.com/flix/flix/pull/3044
Related to #2943

### CODE REVIEW

**Comment by magnus-madsen** [comment]
What projects should be in the community build?

**Comment by mlutze** [comment]
> What projects should be in the community build?

I guess the main criterion is that the project should be actively maintained, so in case there are breaking changes in the compiler, the project will catch up. I think several of Stephen's repos qualify for this if they're modified to match the Flix "standard project structure" and he releases them. (There are also some questions about dependency management)

**Comment by magnus-madsen** [comment]
Do we have a single trial project we can include?

**Comment by magnus-madsen** [comment]
https://github.com/magnus-madsen/helloworld ?

**Comment by magnus-madsen** [comment]
So what happens when I merge?

**Comment by mlutze** [comment]
> So what happens when I merge?

Then `helloworld` will be built for every PR. If it fails then there will be a notification,but it should not block merging.

**Comment by magnus-madsen** [comment]
@stephentetley If you want, we could include one of your repositories in the community build.

It would ensure that we only break your code when actually intend to ;)

(NB: The code must be organized as a Flix project-- and released too on GitHub, right @mlutze ?)

**Comment by mlutze** [comment]
> @stephentetley If you want, we could include one of your repositories in the community build.
> 
> It would ensure that we only break your code when actually intend to ;)
> 
> (NB: The code must be organized as a Flix project-- and released too on GitHub, right @mlutze ?)

Right. And since we don't have dependency resolution yet, it would have to be a project without dependencies.

**Comment by stephentetley** [comment]
Thanks @mlutze and @magnus-madsen 

I think my PrettyPrint library is probably the closest to being stable (probably because it is small). I look towards making it a proper Flix project.

**Pull request merged**
