### PR TITLE
test: update datalog examples

### PR DESCRIPTION
**Pull request by JonathanStarup**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
OK, I understand what you meant now.. But these are intended to be examples for our end users. I am not sure if they should be setup like test cases.

**Comment by magnus-madsen** [comment]
I think they should just contain a main.

**Comment by JonathanStarup** [comment]
But many are already almost tests, FloydWarshall even has the expected output as a comment. Maybe we could also just have a test and no main since theyre basically examples

**Comment by magnus-madsen** [comment]
> But many are already almost tests, FloydWarshall even has the expected output as a comment. Maybe we could also just have a test and no main since theyre basically examples

The example folder exists not to serve us, but to serve our users, so I would say they should have a main so they are easy to run.

**Comment by JonathanStarup** [comment]
> > But many are already almost tests, FloydWarshall even has the expected output as a comment. Maybe we could also just have a test and no main since theyre basically examples
> 
> The example folder exists not to serve us, but to serve our users, so I would say they should have a main so they are easy to run.

Alright, now it is just a bit of improvements on the two examples along with the inclusion that the compiler also runs the tests in misc

**Comment by JonathanStarup** [comment]
> RFR?

yes

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
