### PR TITLE
Refactor: import syntax in library part 4

### PR DESCRIPTION
**Pull request by ninaandrup**
Related to #3148

In this PR

- [x] `Prelude.flix`
- [x] `Result.flix`
- [x] `ToString.flix`
- [x] `Test.Exp.Interpolation.flix`
- [x] `using-laziness-for-logging.flix`

### CODE REVIEW

**Comment by ninaandrup** [comment]
@magnus-madsen I'm not sure what to do with `pub def bug!(m: String): a` in `Prelude.flix`.
If I refactor to use the new syntax, I get the error
```
>> Useless expression: It has no side-effect(s) and its result is discarded.

14 |         prt("**") ;

             ^^^^^^^^^
             useless expression.
```

**Comment by ninaandrup** [comment]
And should I change the import in the example `using-laziness-for-logging.flix`.

**Comment by magnus-madsen** [comment]
> And should I change the import in the example `using-laziness-for-logging.flix`.

Yes

**Comment by magnus-madsen** [comment]
You should import `print` as Impure since it is impure. Then you leave the last cast of f.

**Comment by magnus-madsen** [comment]
@mlutze Once this is merged in, the library will have been refactored to use an effect on import. Do we want to change the import syntax to require an annotation now or what is the plan?

**Comment by magnus-madsen** [comment]
Right now there is `OptAscription`, but we could make it mandatory.

**Comment by mlutze** [comment]
> @mlutze Once this is merged in, the library will have been refactored to use an effect on import. Do we want to change the import syntax to require an annotation now or what is the plan?

I'm not sure. I lean toward requiring an effect annotation, it's but probably worth debating.

**Pull request merged**
