### PR TITLE
refactor: change java solver interface

### PR DESCRIPTION
**Pull request by JonathanStarup**
Dont merge this before #8444 !

move known type checking into the solver instead of being external

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Maybe talk to Matt first? And maybe do some simpler cleanup first too?

**Comment by JonathanStarup** [comment]
The diff looks big but ive just moved code around.

Instead of `isKnown -> lookup` its now `lookup (using isKnown, it might now answer UnresolvedTypes)`

**Comment by JonathanStarup** [comment]
you think its okay @mlutze? its only concerning behaviour inside the java constraints

**Comment by mlutze** [comment]
I think it's OK. I'm planning on ripping a lot of this out anyway.

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
I merged in the wrong order 💀  sorry

**Pull request merged**
