### PR TITLE
feat: simplify region evars

### PR DESCRIPTION
**Pull request by JonathanStarup**
for `Xperf --frontend --n 11` this PR moves the median throughput from 21.228 to  20.410 (-4%)

### CODE REVIEW

**Comment by magnus-madsen** [comment]
> for `Xperf --frontend --n 11` this PR moves the median throughput from 21.228 to 20.410 (-4%)

Hmm. You could try n 51 to see if it is really true that it is slower.

**Comment by JonathanStarup** [comment]
I should probably also use the server instead of my laptop

**Comment by magnus-madsen** [comment]
> I should probably also use the server instead of my laptop

Use server, fix n at 250, grab beverage of choice.

**Comment by mlutze** [comment]
!!!rerun

**Comment by magnus-madsen** [comment]
I am not against this, but it should be a principled an step-wise approach. Also we should have some evidence that it actually improves performance since it just complicates the code.

**Comment by magnus-madsen** [comment]
Also probably best to wait for the new solver.

**Pull request closed without merging**
