### PR TITLE
refactor: `Benchmark` to use regions

### LINKED ISSUE #3887: Refactor benchmarks to use arrays with regions

### PR DESCRIPTION
**Pull request by ninaandrup**
Closes #3887 
Related to #3841

### CODE REVIEW

**Comment by ninaandrup** [comment]
@magnus-madsen `Bench.Fusion` uses `Stream` which seem to have been deleted

**Comment by magnus-madsen** [comment]
> @magnus-madsen `Bench.Fusion` uses `Stream` which seem to have been deleted

Ah yes. Can you try to replace `Stream` by `DelayList` and see if that works?

**Comment by ninaandrup** [comment]
> > @magnus-madsen `Bench.Fusion` uses `Stream` which seem to have been deleted
> 
> Ah yes. Can you try to replace `Stream` by `DelayList` and see if that works?

All the functions are defined for both `DelayList` and `Stream`. Is it okay, that I just deleted all the `Stream` related functions?

**Comment by magnus-madsen** [comment]
> > > @magnus-madsen `Bench.Fusion` uses `Stream` which seem to have been deleted
> > 
> > 
> > Ah yes. Can you try to replace `Stream` by `DelayList` and see if that works?
> 
> All the functions are defined for both `DelayList` and `Stream`. Is it okay, that I just deleted all the `Stream` related functions?

Yes

**Pull request merged**
