### PR TITLE
refactor: use `foreach`-loop in `ToString` instances

### LINKED ISSUE #4162: Add `MultiMap.iterator`

### PR DESCRIPTION
**Pull request by jaschdoc**
Related to #4224
Closes  #4162

### CODE REVIEW

**Comment by jaschdoc** [comment]
RFR

**Comment by jaschdoc** [comment]
I'm not quite sure why the compiler suite is failing. Something to do with the purity casts?

**Comment by jaschdoc** [comment]
@mlutze do you have any idea what's up with this?

**Comment by mlutze** [comment]
> @mlutze do you have any idea what's up with this?

Is the `ForEach` class in the core library?

**Comment by jaschdoc** [comment]
> Is the `ForEach` class in the core library?

Yes, but we're using `Iterable` (which is in the library).

**Comment by mlutze** [comment]
> > Is the `ForEach` class in the core library?
> 
> Yes, but we're using `Iterable` (which is in the library).

Ah, but StringBuilder is not in there.

**Comment by mlutze** [comment]
> Do we want `StringBuilder` in the core library? Also, Iterable and Iterator were not in the core library but I've moved them there now (I thought std lib = core lib).

Yeah, probably fine.

**Comment by jaschdoc** [comment]
I tried running tests locall with `StringBuilder`, `Iterable` and `Iterator` in the core lib and the tests still fail. How is the following test related to `ToString` instances?

```scala
  test("Test.IllegalEntryPointArg.Main.01") {
    val input =
      """
        |def main(blah: Array[String, _]): Unit & Impure = ??? as & Impure
        |""".stripMargin
    val result = compile(input, Options.TestWithLibMin)
    expectError[EntryPointError.IllegalEntryPointArgs](result)
  }
```

**Comment by jaschdoc** [comment]
We're already using `StringBuilder` in the `MultiMap` `ToString` instance and that's on the main branch. Intuitively, adding `ToString` shouldn't affect the entry point tests. I've tried reverting the array instance so it doesn't use stringbuilder but just simple strings (and not including stringbuilder in the core lib) and it still doesn't pass the tests.

**Comment by mlutze** [comment]
It looks like there are actually a bunch of transitive dependencies:

StringBuilder, Iterator, Newable, Iterable, Scoped, Option, Map, and probably a bunch more once the whole list is exhausted.

For the entrypoint tests, let's just change from `TestWithLibMin` to `TestWithLibAll`

It's likely that the other tests can be similarly fixed.

**Comment by magnus-madsen** [comment]
I think there was some confusion about the goal. But first, reflect on the fact that we should never add casts to pure. Doing so is inherently unsafe. Everyone is really treating this too lightly :-) If I ask you to do that you should immediately challenge me :)

Now, what I actually wanted for this PR, which I explained poorly, was to use our new `foreach` loop inside our `ToString` instances-- inside those that are pure, but where we use a string builder (which should be all of them, AFAIK).

**Comment by jaschdoc** [comment]
RFR

I've also added an iterator override to the foldable instances so we avoid converting the collection to an array when using the top level `iterator` and `enumerator` functions.

**Comment by jaschdoc** [comment]
RFR

**Pull request merged**
