### PR TITLE
Disallow `()` for unit type

### PR DESCRIPTION
**Pull request by mlutze**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@stephentetley This might impact you.

This change is in preparation for some more painful changes to records that will arrive soon. (More details in the future).

**Comment by mlutze** [comment]
> @mlutze Do we still have allow the expression `() -> 123` 

Yes, we allow it.

> and should we?

I don't think there's a reason not to allow it. The alternative for users is either `_ -> 123` or `_: Unit -> 123`. I think `() -> 123` communicates the expression best.

**Comment by magnus-madsen** [comment]
OK, agreed.

**Comment by stephentetley** [comment]
> 
> 
> @stephentetley This might impact you.
> 
> This change is in preparation for some more painful changes to records that will arrive soon. (More details in the future).

Thanks Magnus, this has been flagged for a while, so I should have already changed any code that would have been affected.

**Pull request merged**
