### PR TITLE
fix: make TestFile.flix use the temp directory for creating outfile01.bin

### PR DESCRIPTION
**Pull request by stephentetley**
This PR updates TestFile.flix to write `outfile01.bin` to the temp directory identified by `Environment.getTemporaryDirectory` rather than the `{tests-path}/library/testdata` folder as was reported on Flightdeck.

As far as I can tell the answer from `Environment.getTemporaryDirectory` is already suffixed with a path separator so we don't need to add one directly.

Not done / should I do? - I don't delete `outfile01.bin` at the end of the tests. Should I write a test at the end of the file that does this?

### CODE REVIEW

**Comment by magnus-madsen** [comment]
No need to delete anything from the temp directory. That should happen automatically (on process exit?)

**Comment by stephentetley** [comment]
> No need to delete anything from the temp directory. That should happen automatically (on process exit?)

That doesn't seem to happen when running inside IntelliJ on Windows (outfile01.bin remains after closing IntelliJ)

**Comment by stephentetley** [comment]
Uh oh, I didn't see failing test `setLength01` failing on Windows - I have to see what's going on.

**Comment by stephentetley** [comment]
> Uh oh, I didn't see failing test `setLength01` failing on Windows - I'll have to see what's going on.

I think the problem was not due to not making a proper path on Linux. The root directory on Windows had a separator at the end so it worked with string concatenation but Linux needs the path forming properly.

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
Thanks Stephen

**Pull request merged**
