### PR TITLE
feat: better type location for let

### PR DESCRIPTION
**Pull request by JonathanStarup**
If a let-bound variable is of a wrong type, the use site is now blamed instead of the declaration. For this program:
```flix
def main(_args: Array[String]): Int32 & Impure =
    let s = Set#{"1"};
    let e = Set.find(_ -> true, s);
    let x = e == Some(1);
    println(x);
    0
```
The error reported in this PR is (whitespace squashed):
```
-- Type Error -------------------------------------------------- examples\misc\test.flix
>> Unable to unify the types: 'String' and 'Int32'.
4 |     let x = e == Some(1);
                ^^^^^^^^^^^^
                mismatched types.
Type One: a -> a -> Bool
Type Two: Option[String] -> Option[Int32] -> t661064 & b661065
Compilation failed with 1 error(s).
Process finished with exit code 1
```
In master this is reported (whitespace squashed):
```
-- Type Error -------------------------------------------------- examples\misc\test.flix
>> Unable to unify the types: 'Int32' and 'String'.
2 |>     let s = Set#{"1"};
3 |>     let e = Set.find(_ -> true, s);
4 |>     let x = e == Some(1);
5 |>     println(x);
6 |>     0
mismatched types.
Type One: Set[Int32]
Type Two: Set[String]
Compilation failed with 1 error(s).
Process finished with exit code 1
```

### CODE REVIEW

**Comment by magnus-madsen** [comment]
We can use this PR as a starting point for: https://github.com/flix/flix/issues/3271

**Comment by JonathanStarup** [comment]
> We can use this PR as a starting point for: #3271

Does that mean you want more in this PR?

**Comment by magnus-madsen** [comment]
> > We can use this PR as a starting point for: #3271
> 
> Does that mean you want more in this PR?

Yes, or at least, I don't think there is any reason to merge in one line change. Instead someone should focus on the core issues.

**Comment by magnus-madsen** [comment]
Does not have to be you of course, but it could be :)

**Comment by magnus-madsen** [comment]
See #3409

**Pull request closed without merging**
