### PR TITLE
refactor: remove type vars from upcast ast node

### PR DESCRIPTION
**Pull request by jaschdoc**
Related to #4264

### CODE REVIEW

**Comment by magnus-madsen** [comment]
+ Add some negative tests to `TestTyper`.

**Comment by magnus-madsen** [comment]
Conflict.

**Comment by magnus-madsen** [comment]
This is becoming big. Can we do one PR that refactors just the ASTs but nothing else? (Sorry for the extra work), but I want to be able to review each part carefully.

**Comment by jaschdoc** [comment]
Oh okay hehe. Just finished :)

**Comment by jaschdoc** [comment]
Alright RFR (only with AST rewrite)

**Comment by magnus-madsen** [comment]
Tests fail

**Comment by magnus-madsen** [comment]
Feel free to comment tests if needed.

**Comment by jaschdoc** [comment]
Sorry fixed the tests now :)

**Comment by jaschdoc** [comment]
I just removed the upcast tests now since the implementation is broken but there are lots of tests in https://github.com/flix/flix/pull/4390

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
