### PR TITLE
feat: require type and effect annotations on imports

### PR DESCRIPTION
**Pull request by mlutze**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Ah- there is one more PR for me to look at.

**Comment by magnus-madsen** [comment]
@mlutze I see you also changed the signatures for field access. I guess that is the right decision (?)

**Comment by magnus-madsen** [comment]
@ninaandrup There are still some failing tests. Could you have a look at those? :)

**Comment by ninaandrup** [comment]
> @ninaandrup There are still some failing tests. Could you have a look at those? :)

Yes, will do :)

**Comment by magnus-madsen** [comment]
@ninaandrup Still some tests failing, but seem like fewer :)

**Comment by magnus-madsen** [comment]
Yay! Green bar... Now we should update the documentation.

**Comment by magnus-madsen** [comment]
@stephentetley This will probably impact you. Sorry about that!

**Pull request merged**
