### PR TITLE
refactor: remove special cases in codegen for `AtomicOp.New`

### PR DESCRIPTION
**Pull request by jaschdoc**
Related to https://github.com/flix/flix/issues/5917

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@jaschdoc I am not sure this approach can work. Note that all of these are different:

`Object[]`
`int[]`
`Integer[]`
`int[][]`
`Object[][]`

and may be required in different contexts. Maybe you can find Jonathan and have him help explain?

**Comment by jaschdoc** [comment]
> @jaschdoc I am not sure this approach can work. Note that all of these are different:
> 
> `Object[]` `int[]` `Integer[]` `int[][]` `Object[][]`
> 
> and may be required in different contexts. Maybe you can find Jonathan and have him help explain?

Roger that, thanks :)

**Comment by jaschdoc** [comment]
By the way, this was just meant as a small PR that changed the original `if-else` to a simpler pattern match

**Comment by magnus-madsen** [comment]
> By the way, this was just meant as a small PR that changed the original `if-else` to a simpler pattern match

Oh I see, but then some cases are missing or?

**Comment by jaschdoc** [comment]
It *should* be equivalent to what we had, because it matched on the mono type and the erased jvm type to figure out if it were a string, native, object, or a primitive. I looked into the code, and it seems that if we just match on the jvm type instead of the erased jvm type, the string, native, and object cases are captured by the `Reference` case and the primitive cases are handled by the wild case.

**Comment by jaschdoc** [comment]
However, currently it generates byte code for the specific reference type instead of just `Object` for anything that's not string, native, or primitive. I'm thinking, though, since it generated arrays for specific types of native classes (which would be anything imported by the user) then it should also handle the complex types the compiler generates the same way. Thus, this PR *should not* result in any observable change in behavior.

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
