### PR TITLE
feat: introduce `eidentity` and make `identity` pure

### LINKED ISSUE #6559: Introduce `eidentity`
So we have:

```
pub def identity(x: a): a = x
pub def eidentity(x: a): a \ ef = checked_ecast(x)
```

and refactor the library to use `identity` wherever possible.

### PR DESCRIPTION
**Pull request by sockmaster27**
Fixes #6559

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I see a test failure (???)

**Comment by magnus-madsen** [comment]
Ah-- I guess the change here is breaking.

**Comment by magnus-madsen** [comment]
@stephentetley This PR breaks some of your code. You just have to replace `identity` with `eidentity` where needed. Is that OK?

**Comment by stephentetley** [comment]
Thanks for the notice Magnus, I'll get htmldoc fixed...

**Comment by stephentetley** [comment]
!!!jar

**Comment by stephentetley** [comment]
`flix-htmldoc` and its dependency `flix-rosetree` have been updated - community-build should now work.

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
