### PR TITLE
test: add modulo tests

### LINKED ISSUE #2751: Rename remainder tests
Currently the tests for `a rem b` are still named `testBinaryModulo` but should be called `testBinaryRemainer` in the file `Test.Exp.Binary.Arithmetic.flix`. We should probably also add tests for the `a mod b` expression.

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes  #2751

We should consider truncating or flooring the result of performing `mod` on decimal numbers as euclidean modulo is only defined for integers.
https://en.wikipedia.org/wiki/Modulo_operation#Variants_of_the_definition
https://en.wikipedia.org/wiki/Modulo_operation#In_programming_languages

We have constructs as Ada which floors the result.

We also have some weird results for floats: `12.34 mod 56.78` can yield some weird results. Computing this yielded `12.340000000000003` which is clearly not `12.34`.

Perhaps @JonathanStarup and / or @mlutze have thoughts on this?

### CODE REVIEW

**Comment by mlutze** [comment]
What invariants/laws does Euclidian mod give us? Is there an equivalent for floats that preserves those invariants?

If there's not an equivalent, we should probably just leave `mod` undefined for floats.

Same for `rem`.

(Is that not just the nearest binary representation to `12.34`?

**Comment by jaschdoc** [comment]
Okay, I did some quick googling. It may not be entirely trivial. C has `fmod` for modulo for floats and as one person pointed out on [this stackexchange thread](https://retrocomputing.stackexchange.com/questions/10865/why-is-modulo-operation-an-operator-for-integer-types-but-only-a-function-for-fl) it is only defined for Euclidean rings.

> Because mathematically speaking, the modulo operation or division with remainder makes only sense on integers (or more generally on Euclidean Rings). This operation doesn't make sense on any (mathematical) field like the real numbers (or there computer approximations float and double) at all, because in such a structure a division can always be done without any remainder.
>
> As a consequence, on an Euclidean Ring like the integers Z you get the derived quotient rings Z_n which consist (formally) of elements of Z with the same reminder module n, and these have applications in coding theory etc. There is nothing equivalent for the real numbers R.
>
> So fmod is an afterthought which takes one particular definition of division with reminder and implements it in an ad-hoc way on floats and doubles by truncating the result of the division. The only use for such a function is if you have accidentally stored integers in float or double variables, and if you want to save yourself the trouble of conversion to integer variables.
> 
> So from this point of view, it's completely logically that % is an integral part of the language, while fmod is just a library function.

**Euclidean Rings**
https://en.wikipedia.org/wiki/Euclidean_domain

Rust handles it this way (by truncation)
https://github.com/rust-lang/rfcs/blob/c76963d53e0f28c9b36b09192079c413cb528032/text/2169-euclidean-modulo.md?plain=1#L71
https://rust-lang.github.io/rfcs/2169-euclidean-modulo.html

**However, as far as I can see, it is only defined mathematically for integers.**

**Comment by magnus-madsen** [comment]
I am not an expert, but how about we drop `mod` and `rem` completely for floats?

(We can always add them back should the need arise or an expert appear).

**Comment by mlutze** [comment]
> I am not an expert, but how about we drop `mod` and `rem` completely for floats?
> 
> (We can always add them back should the need arise or an expert appear).

Reasonable to me. I cannot recall ever using `mod` on a float.

**Comment by magnus-madsen** [comment]
With Flix, its fine if we omit some functionality until we are sure how it should be. This seems to be one of those situations.

**Comment by jaschdoc** [comment]
Sane defaults, right?

**Comment by jaschdoc** [comment]
Ready to merge

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
