### PR TITLE
chore: update import syntax in `Result.flix`

### PR DESCRIPTION
**Pull request by magnus-madsen**

### CODE REVIEW

**Comment by mlutze** [comment]
This isn't a feat :P

**Review by mlutze — APPROVED** [review]

**Comment by magnus-madsen** [comment]
@mlutze Is the CI broken? Can you merge?

**Comment by mlutze** [comment]
> @mlutze Is the CI broken? Can you merge?

It's the VSCode stuff.

**Comment by magnus-madsen** [comment]
> > @mlutze Is the CI broken? Can you merge?
> 
> It's the VSCode stuff.

What controls if it is optional to pass or not?

**Comment by mlutze** [comment]
> > > @mlutze Is the CI broken? Can you merge?
> > 
> > It's the VSCode stuff.
> 
> What controls if it is optional to pass or not?

Something in the settings, maybe branch protections?

**Pull request merged**
