### PR TITLE
Feat: add `pushAllFront` and `pushAllBack` to `MutDeque`

### PR DESCRIPTION
**Pull request by ninaandrup**
Related to #2999

### CODE REVIEW

**Comment by magnus-madsen** [comment]
> 

Good point. I never thought of that. @JonathanStarup @mlutze What do you think? What is the normal expectation here?

**Comment by JonathanStarup** [comment]
I think I'd guess that it was the same as `it |> foreach(pushFront)` i.e. the last element is first in the queue

**Comment by mlutze** [comment]
I'm not sure. Are there any implementations in the wild?

**Comment by magnus-madsen** [comment]
Is this confusion evidence that we should not have these operations?

**Comment by mlutze** [comment]
> Is this confusion evidence that we should not have these operations?

Or a name with a more obvious interpretation

**Comment by magnus-madsen** [comment]
My conclusion is that we should not do it. The programmer can easily write `foo.foreach(MutList.add())`.

**Comment by ninaandrup** [comment]
What about `pushAllBack`?

**Comment by magnus-madsen** [comment]
Lets drop both, no pushAllFront/Back

**Pull request closed without merging**
