### PR TITLE
Visit classes and instances in Lowering

### PR DESCRIPTION
**Pull request by mlutze**
Fixes https://github.com/flix/flix/issues/1985

I noticed there was no `TestLowering.scala` (I assume because there's no `LoweringError`).

What would be a good test case (or set of test cases) to add to ensure things are working properly? A schema in a signature/class/instance?

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Test cases:

You could use the Datalog solver inside an instance definition expression.

**Comment by magnus-madsen** [comment]
FYI: Build failing.

**Comment by mlutze** [comment]
> FYI: Build failing.

At least we know the test is working!

**Comment by mlutze** [comment]
I added the Fixpoint-related library to core.

**Comment by mlutze** [comment]
Ah, fixpoint stuff depends on the full stdlib. Guess it's not that easy.

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
