### PR TITLE
feat: add `{Map, Set}.toMutDeque`

### PR DESCRIPTION
**Pull request by ninaandrup**
Related to #3761

### CODE REVIEW

**Comment by ninaandrup** [comment]
I do not understand, why I get this error message, when running the tests:
```
-- Tests -------------------------------------------------- TestMap

  ? toMutDeque01: Cannot read field "field0" because "<local34>" is null (C:\Users\Nina\Documents\Flix\Develop\test\TestMap.flix:9:5)
  ? toMutDeque02: Cannot read field "field0" because "<local34>" is null (C:\Users\Nina\Documents\Flix\Develop\test\TestMap.flix:21:5)

  Tests Failed! (Passed: 1 / 3)
```

**Comment by magnus-madsen** [comment]
@JonathanStarup Is this error from the backend? I have never seen anything like it.

**Comment by JonathanStarup** [comment]
hmm doesn't look familiar to me but could very well be. i can look at it later tonight.

**Comment by JonathanStarup** [comment]
It doesn't look like any of my recent work has introduced the error. I'll analyze the generated code Monday the latest. I'm not sure where the null pointer originates from. If you run the test as an entry point you can at least see the generated call stack.

**Comment by ninaandrup** [comment]
Here is the call stack
```
Exception in thread "main" java.lang.NullPointerException: Cannot read field "field0" because "<local34>" is null
        at Array.Clo%sameElements%156792.invoke(Unknown Source)
        at Cont%Bool.unwind(Cont%Bool)
        at MutDeque.Def%sameElements%146035.invoke(Unknown Source)
        at Cont%Bool.unwind(Cont%Bool)
        at Def%main%.invoke(Unknown Source)
        at Cont%Obj.unwind(Cont%Obj)
        at Ns.m_main%(Unknown Source)
        at Main.main(Main)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)      
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at ca.uwaterloo.flix.language.phase.jvm.Bootstrap$.mainFunction$1(Bootstrap.scala:79)  
        at ca.uwaterloo.flix.language.phase.jvm.Bootstrap$.$anonfun$bootstrap$9(Bootstrap.scala:88)
        at ca.uwaterloo.flix.language.phase.jvm.Bootstrap$.$anonfun$bootstrap$9$adapted(Bootstrap.scala:88)
        at ca.uwaterloo.flix.Main$.main(Main.scala:226)
        at ca.uwaterloo.flix.Main.main(Main.scala)
```

**Comment by JonathanStarup** [comment]
The issue is the interplay of `MutDeque.flix` and `Array.flix`.
1) If you create a new MutDeque is contains an array of length 8 filled with `$DEFAULT$` (which is `null` for tuples like the test above)
2) When `MutDeque.sameElements` is callled on two empty mutdeques their whole array (including the non-initialized parts) is compared with -
3) `Array.sameElements` that calls `a[i] == b[i]` for all indices which fails on null elements.

I think two things should be changed
1) MutDeque should not involve unused parts of the internal array in its sameElements computation
2) Array.sameElements should not break from null elements

**Pull request merged**
