### PR TITLE
test: move debug tests to testPrelude

### PR DESCRIPTION
**Pull request by mlutze**
related to #4664

### CODE REVIEW

**Comment by JonathanStarup** [comment]
I ruined your tests, now magnus can decide who has to correct them 😅

**Comment by mlutze** [comment]
Dang, I wish you did that an hour ago :P

**Comment by magnus-madsen** [comment]
Huh. What happened?

**Comment by mlutze** [comment]
Jonathan just improved the output for tuples etc. so my tests that look for `Tuple2` instead of `(abc, 123)` are invalid.

**Comment by magnus-madsen** [comment]
Ah. Well it seems you should fix the tests then ;)

**Comment by magnus-madsen** [comment]
Its interesting that by separating the implementer from the tester you found some bugs/improvements.

**Pull request merged**
