### PR TITLE
refactor: fix MonoDefs

### PR DESCRIPTION
**Pull request by JonathanStarup**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
What's the plan here? This seems to make some design changes.

**Comment by JonathanStarup** [comment]
Just to do the same thing with clearer design

**Comment by magnus-madsen** [comment]
@mlutze @JonathanStarup Let's have a chat about this at somepoint. Then if the this is the way to go, the PR needs to be cleaned.

**Comment by magnus-madsen** [comment]
Can I close?

**Pull request closed without merging**
