### PR TITLE
perform occurs check in rewriteRow

### LINKED ISSUE #1142: Think I found an infinite loop in type unification
I got this error that just keeps on with the same 5 lines (the one repeated once here):

```
Exception in thread "Thread-1" java.lang.StackOverflowError
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.apply(Substitution.scala:82)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.$anonfun$unifyTypes$3(Unification.scala:97)
	at ca.uwaterloo.flix.util.Result.flatMap(Result.scala:51)
	at ca.uwaterloo.flix.util.Result.flatMap$(Result.scala:50)
	at ca.uwaterloo.flix.util.Result$Ok.flatMap(Result.scala:70)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.unifyTypes(Unification.scala:94)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.$anonfun$unifyTypes$3(Unification.scala:97)
	at ca.uwaterloo.flix.util.Result.flatMap(Result.scala:51)
	at ca.uwaterloo.flix.util.Result.flatMap$(Result.scala:50)
	at ca.uwaterloo.flix.util.Result$Ok.flatMap(Result.scala:70)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.unifyTypes(Unification.scala:94)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.$anonfun$unifyTypes$3(Unification.scala:97)
```

After trying to run 

```
rel Train(src: City, dst: City)
rel Bus(src: City, dst: City)
rel Path(src: City, dst: City)

type alias City = Int

def travel(tg: #{Train| r}, bg: #{Bus| r}, src:City ,dst:City): Option[#{Path}] =
    let p = #{
        Path(x,y) :- Train(x,y).
        Path(x,z) :- Path(x,y), Train(y,z).
        Path(x,y) :- Bus(x,y),not Train(x,y).
        Path(x,z) :- Path(x,y), Bus(y,z),not Train(x,y).
    };
    let m = solve (tg <+> bg <+> p);
    if (m |= Path(src, dst).)
        Some(project Path m)
    else
        None
```
And I know that the type of travel does not make sense, but I don't like getting an error like this from the compiler.

### PR DESCRIPTION
**Pull request by mlutze**
Fixes #1142 

I'd like to add tests and refactor, but this seems to address the issue.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
This is great! Looking forward to it!

**Comment by mlutze** [comment]
I experimented a little with refactoring rewriteRows to use a common helper method. I considered a couple possibilities:
* Use an anonymous structural type with `apply` and `unapply` methods to generalize `Schema` and `Record`
* Make `SchemaExtend` and `RecordExtend` extend a common abstract case class


Neither of these seemed totally satisfying, so I left it as the two similar methods.

**Comment by magnus-madsen** [comment]
> 
> 
> I experimented a little with refactoring rewriteRows to use a common helper method. I considered a couple possibilities:
> 
>     * Use an anonymous structural type with `apply` and `unapply` methods to generalize `Schema` and `Record`
> 
>     * Make `SchemaExtend` and `RecordExtend` extend a common abstract case class
> 
> 
> Neither of these seemed totally satisfying, so I left it as the two similar methods.

I think, while schemas and records use the same theoretical ideas, their implementation is sufficiently different that we want to keep them separate.

**Comment by magnus-madsen** [comment]
Is this ready for review?

**Comment by mlutze** [comment]
Yes, ready.

**Comment by magnus-madsen** [comment]
It looks good to me, but can I ask you to add some tests where unification explicitly fails because of the occurs check?

**Comment by mlutze** [comment]
The added tests should do so. I can modify the assert to ensure the error type is correct.

**Comment by magnus-madsen** [comment]
Are you sure? Which ones? I guess checking for the right type error would be a nice bonus 👍

**Comment by mlutze** [comment]
> 
> 
> Are you sure? Which ones? I guess checking for the right type error would be a nice bonus 👍

Oops, you are right. I've replaced the tests with ones that do actually check for the `OccursCheck`.

Because of the signature of the utility method `expectError` is written, I'm not able to reuse it here.
It expects a `Validation[CompilationResult, CompilationError]` whereas unification returns a `Result[Substitution, UnificationError]`.

So for checking the error type, options are:
1. Rewrite test to use source code instead of constructed types
2. Rewrite `expectError` to have a much looser signature

**Comment by magnus-madsen** [comment]
How about we let the unification tests just use isOk and then we add some source code tests that check for the right type error?

**Comment by mlutze** [comment]
I added a source code test for schema. I haven't found a way to induce the error for records.

**Comment by magnus-madsen** [comment]
Great! Merged :)

**Pull request merged**
