### PR TITLE
refactor: remove `Fixpoint.unsafePrint` from examples

### LINKED ISSUE #3529: Remove use of `Fixpoint.unsafePrint` from examples

### PR DESCRIPTION
**Pull request by ninaandrup**
Closes #3529

### CODE REVIEW

**Comment by ninaandrup** [comment]
@magnus-madsen I'm not sure, if this is how you wanted it to be done

**Comment by magnus-madsen** [comment]
Ok, I should clarify. I still want to print, just using `println` :)

**Comment by magnus-madsen** [comment]
Hmm. I think I need to have a look myself :)

**Comment by magnus-madsen** [comment]
I decided to leave the code as is.

**Pull request closed without merging**
