### PR TITLE
feat: introduce debug interpolation

### PR DESCRIPTION
**Pull request by mlutze**
related to #4664. I went with % instead of # since there were some parsing weirdnesses related to schemas and we use # for e.g. Map#{

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I will merge this, but I actually liked `#`. What's the parsing problem? Will `%` not be confused for some format specifier?

**Comment by mlutze** [comment]
> I will merge this, but I actually liked `#`. What's the parsing problem? Will `%` not be confused for some format specifier?

I wasn't able to figure out exactly what the parsing problem was, only that changing the sigil fixed it. `%` was an arbitrary choice so I'm fine going with something else.

**Comment by magnus-madsen** [comment]
Rust uses `?` or `#?` am I reading that right?

https://doc.rust-lang.org/std/fmt/trait.Debug.html

**Comment by mlutze** [comment]
> Rust uses `?` or `#?` am I reading that right?
> 
> https://doc.rust-lang.org/std/fmt/trait.Debug.html

Yes, seems like it.

**Comment by magnus-madsen** [comment]
Failed :(

**Pull request merged**
