### PR TITLE
Reintroduce `reifyEff`

### PR DESCRIPTION
**Pull request by magnus-madsen**
This PR reintroduces `reifyEff`. The long-term goal is to replace `reifyEff` by a more general `reify` construct. In meanwhile, the `reifyEff` construct is sound whereas soundness for the other reify constructs (w.r.t. Booleans) is still an open question.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@jaschdoc Please take a look at `LazyList` to see how I changed to use `reifyEff` but also to use effect polymorphism (instead of impure) in the eager cases.

**Comment by magnus-madsen** [comment]
@mlutze If you could just check that I did not make any silly mistakes. (Swapping e2 for e3 etc).

**Comment by magnus-madsen** [comment]
This coded is not intended to be here permanently, but it is a better starting point than what we have.

**Review by mlutze — APPROVED** [review]
I don't see any issues

**Pull request merged**
