### PR TITLE
feat: clarify `Adaptor.toOptional`

### PR DESCRIPTION
**Pull request by JonathanStarup**
Not fixing the bug, just making the bump softer to hit your head on.

Related to #7876

### CODE REVIEW

**Comment by mlutze** [comment]
> OptionalInt doesnt inherit/implement anything. I don't this function can exist 🤔 At least not in an injective way since both `Int32` and `java.lang.integer` would be mapped to the same type if we do boxing.

I think it's OK if it's not injective. We have to specify the type on the way back anyway.

**Comment by JonathanStarup** [comment]
I just think its very error prone, since you manually have to remember it. But I'm also not sure since this is not used anywhere, so its hard to know what the good design is

**Comment by mlutze** [comment]
What do you have to remember?

If we just box the Int in the type match, then we have a total function, right?

**Comment by JonathanStarup** [comment]
If was imagining that i want to use some `Option[t] -> Option[t]` java function, så `Optional -> Optional`.

If I then want to wrap it in a flix option then I can call `toOptional` on my `Int32` just fine but when I call `fromOptional` to `Int32` then I crash. Kind of a niche situation perhaps

**Comment by JonathanStarup** [comment]
I think we could explore checking casts after monomorphization

**Comment by magnus-madsen** [comment]
We could also box?

**Comment by magnus-madsen** [comment]
I guess this is complicated. Lets discuss at the workshop.

**Comment by JonathanStarup** [comment]
In a world with java generics (i.e. `java.lang.Optional[t]`) the typematch+box version of the function can't be typed

**Comment by mlutze** [comment]
> In a world with java generics (i.e. `java.lang.Optional[t]`) the typematch+box version of the function can't be typed

Good point. Let's rediscuss at the next Flix workshop :P

**Comment by JonathanStarup** [comment]
@mlutze could a constraint like `_ !~ Int32` be okay because the rhs is simple and ground? Maybe we could allow `a not primitive` as a constraint

**Comment by magnus-madsen** [comment]
We should discuss more before PR.

**Pull request closed without merging**
