### PR TITLE
Removed assert, assertEq and asssertNot from library tests.

### PR DESCRIPTION
**Pull request by stephentetley**
See issue...

Remove assert!, assertEq!, and assertNot! From Prelude #1136

This PR removes the assert functions from the standard library tests.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Fixes #1136

**Comment by magnus-madsen** [comment]
Do we want to clean this up:

```
def nan01(): Bool = Float32.isNan(Float32.nan()) == true
```

or should we leave it to be explicit?

**Comment by stephentetley** [comment]
I prefer the explicit `... == true` so it matches the false cases that need it, but some of the lines do get very long. Happy to remove them if you prefer...

There are still a good number of asserts in the language test suite so #1136 needs some more work before the assert functions can be removed.

**Comment by magnus-madsen** [comment]
Looks good. Thanks!

**Comment by stephentetley** [comment]
Thanks Magnus - I'll take a look at the Language tests over this week, but I'm back at work tomorrow (it's been a holiday weekend in the UK), so I might be a bit "leisurely".

**Pull request merged**
