### PR TITLE
feat: improve error handling in Weeder

### PR DESCRIPTION
**Pull request by jaschdoc**
Adds `recoverOne` to more cases.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
The intent was  good; but this is not the right path. This would be like adding try-catch everywhere to a program.

Instead, we should only use recoverOne directly around a place that could "throw".

**Comment by magnus-madsen** [comment]
Unfortunately, the types are not strong enough to tell us where this can be.

**Comment by magnus-madsen** [comment]
Make sense?

**Comment by jaschdoc** [comment]
Roger :)

**Pull request closed without merging**
