### PR TITLE
wip: introduce region syms

### PR DESCRIPTION
**Pull request by mlutze**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
What's the exact cause this fails -- compared to the current implementation?

**Comment by mlutze** [comment]
In theory the implementations are semantically equivalent, so I think it has something to do with the ordering of the variables, but I am not sure.

**Comment by magnus-madsen** [comment]
Can you try to debug it a bit? I would like this refactoring without opting into some hack :)

Maybe these Boolean constants are not being treated correctly in during Unification?

**Comment by magnus-madsen** [comment]
Maybe the PR can be split into two or three: One that introduces the symbols and one that starts to use them?

**Comment by magnus-madsen** [comment]
The conflicts look overwhelming. Should we close?

**Comment by mlutze** [comment]
> The conflicts look overwhelming. Should we close?

Yep

**Pull request closed without merging**
