### PR TITLE
feat: remove support for `##`

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes https://github.com/flix/flix/issues/8087

### CODE REVIEW

**Comment by jaschdoc** [comment]
@mlutze @stephentetley the `##` syntax is on its way out so you should import all of your java types with the `import` mechanism once this is merged :)

**Comment by magnus-madsen** [comment]
@jaschdoc Could we split this PR into two: one with the actual change and one with the changes to the tests? 
(Then the latter can be merged immediately). Thanks!

**Comment by mlutze** [comment]
!!!rerun

**Comment by jaschdoc** [comment]
Now depends on #8502

**Comment by magnus-madsen** [comment]
Perhaps this breaks too much of @stephentetley code and we should put it behind the deprecated flag instead?

**Comment by jaschdoc** [comment]
Yeah I thought about that too.

**Comment by stephentetley** [comment]
I'm happy without a deprecated flag.

All my code that use Java interop was broken anyway and I'm starting to get it back compiling again. `charset-locale` which is the one in community build should be up to date with the new interop,

**Comment by magnus-madsen** [comment]
Thanks @stephentetley. We appreciate your patience. It must be a lot of work keeping up with all of our changes. At least, I hope it feels like things are moving in the right direction.

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
