### PR TITLE
feat: add `Null` subtyping support

### PR DESCRIPTION
**Pull request by chanattan**

### CODE REVIEW

**Comment by chanattan** [comment]
Well, it works on my branch, I wonder why it does that.

**Comment by chanattan** [comment]
Ah no, it indeed doesn't work. This is probably related to null values that are not yet fully supported.

**Comment by magnus-madsen** [comment]
Can you give some more information?

**Comment by chanattan** [comment]
There is a mismatched type error from unsubstituted return types. I believe there are some tricky things with null values, but I think I have to add full support for null subtyping for Flix values to see if it works.

**Pull request closed without merging**
