### PR TITLE
feat: Setformula generator

### PR DESCRIPTION
**Pull request by JonathanStarup**
Adding 100 % test coverage to `SetFormula` (except throwing cases)

### CODE REVIEW

**Comment by magnus-madsen** [comment]
If this is for testing I think it should be with the tests.

**Comment by magnus-madsen** [comment]
How much does this increase test time by?

**Comment by magnus-madsen** [comment]
RFR/RFM?

**Comment by magnus-madsen** [comment]
What's the impact on test time?

**Comment by JonathanStarup** [comment]
It is in the test folder

The test is around 2 seconds on my computer - varying a little depending on the seed you get

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
