### PR TITLE
feat: add `toValidation` to `Result`

### PR DESCRIPTION
**Pull request by dtwelch**
Adds a `toValidation` conversion function to the flix library `Result` type (related to #5532)
(full disclosure: not sure if I flubbed the semantic commit msg format)

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@dtwelch Looks good!

Please add your name to `AUTHORS.md` :)

**Comment by dtwelch** [comment]
Looks like I messed up the second test (should be: `Result.toValidation(Ok("s"): Result[String, Unit]) == Success("s")`).

Is the path of least resistance here to just close and resubmit the pr? I can do one with the updated name too: `feat: add toValidation to Result #5556`

**Comment by magnus-madsen** [comment]
> Looks like I messed up the second test (should be: `Result.toValidation(Ok("s"): Result[String, Unit]) == Success("s")`).
> 
> Is the path of least resistance here to just close and resubmit the pr? I can do one with the updated name too: `feat: add toValidation to Result #5556`

You can just add an additional commit to your branch and then the PR should update automatically :)

**Comment by magnus-madsen** [comment]
Thanks and congrats your first merged PR 🥳

**Comment by dtwelch** [comment]
thanks! :-) I'll keep chipping away at various issues that I think I might be able to realistically handle while at the same time continuing to poke around inside the namer/resolver phase (eventually getting to the typer).

I have to say: I'm pretty impressed by the whole incremental compilation scheme at work here and how robust LSP support is even at this early-ish time!

I think I'm still experiencing 'post-traumatic stress' from my thesis work where I ended up basically having to re-write the compiler for our research language in order to integrate into a plugin for IntelliJ ( the grammar had to be moved to their propriety .bnf format, typechecker, symbol resolution, etc. into the Jetbrains specific "PSI" -- "program structure interface" format ). 

Anyhoo, it looks like the Jetbrains people are going to support the LSP more fully with their new IDE: Fleet (guess this is their answer to VSCode -- though I suppose we'll see :-)

**Comment by magnus-madsen** [comment]
Thanks-- I'd be happy to point out more issues that are reasonable "starter issues" :)

**Comment by dtwelch** [comment]
Please do! Happy to help out when/where I can

**Comment by magnus-madsen** [comment]
I sent you a DM on Gitter :)

**Pull request merged**
