### PR TITLE
feat: add `RedBlackTree.count` for `{Map, Set}.count`

### PR DESCRIPTION
**Pull request by jaschdoc**
Related to #2054

### CODE REVIEW

**Comment by jaschdoc** [comment]
Tests are coming up but apparently the RBTree tests were never added to the test suite and now I'm just fixing tons of errors.

**Comment by magnus-madsen** [comment]
> Tests are coming up but apparently the RBTree tests were never added to the test suite and now I'm just fixing tons of errors.

OK

**Comment by jaschdoc** [comment]
I've made the tests run but I commented out a lot of tests that had both type errors (or maybe relied on old syntax) and an instance of Eq that is either no longer implemented for RBTree or unable to be derived. I'll make an issue so we remember to fix those tests.

**Comment by magnus-madsen** [comment]
Looks good. Note that `default` has been renamed to `$DEFAULT`. 

What's the status with the tests? I am a bit confused.

**Comment by jaschdoc** [comment]
I've re-used the tests from `mapWithKey` but we never really landed on any proper way to test parallelism. Other than that I've commented out code that did not compile. There's another PR which fixes that code. I'll use `Array.new` instead of `[default; n]` :)

**Comment by magnus-madsen** [comment]
> I've re-used the tests from `mapWithKey` but we never really landed on any proper way to test parallelism. Other than that I've commented out code that did not compile. There's another PR which fixes that code. I'll use `Array.new` instead of `[default; n]` :)

Its not too important to test that it runs in parallel. Its important to test that it does NOT run in parallel when it should not! :)

**Comment by jaschdoc** [comment]
@magnus-madsen ready to merge

**Comment by magnus-madsen** [comment]
Does this solve the issues with the tests or is that for another time?

**Comment by jaschdoc** [comment]
This does **not** solve the issue. I have another PR pending which resolves it - https://github.com/flix/flix/pull/2800

**Comment by magnus-madsen** [comment]
Roger!

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
