### PR TITLE
feat: introduce reference equality

### LINKED ISSUE #6330: Reference equality
Could likely be used as a base case to speed up a lot of equality implementations

### PR DESCRIPTION
**Pull request by mlutze**
fixes #6330. Not sure if Reflect is the right place for it.

### CODE REVIEW

**Comment by mlutze** [comment]
maybe it should be in `Object` instead?

**Comment by magnus-madsen** [comment]
I am not even sure I want this feature. Does it not raise all kinds of problems? In particular, it seems it would fix our bytecode-level representation of objects?

**Comment by mlutze** [comment]
It's something that has to be used carefully. But I think it is at the same level of danger as the `default` function

**Comment by magnus-madsen** [comment]
I am closing this until we have had a longer discussion.

**Pull request closed without merging**
