### PR TITLE
fix: rework `CompletionProvider` to use dot namespaces

### PR DESCRIPTION
**Pull request by mR4smussen**
Related to https://github.com/flix/flix/issues/5306

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Looks good.

**Comment by magnus-madsen** [comment]
More to be done or should we mark this as non-draft?

**Comment by mR4smussen** [comment]
The current status is that I haven’t tested this initial solution. I’m not completely sure I’m testing this in the right way, which is one of the things I wanted to discuss on **Friday**, @magnus-madsen

**Comment by mR4smussen** [comment]
Testing that we are now suggesting `Fixpoint.AST` seems to work as intended. I think we should merge this @magnus-madsen

**Pull request merged**
