### PR TITLE
Add default implementations to Boxable

### PR DESCRIPTION
**Pull request by mlutze**
Fixes https://github.com/flix/flix/issues/2144

Setting up for https://github.com/flix/flix/issues/2159

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Do we have tests for Boxable? I forget.

**Comment by mlutze** [comment]
> Do we have tests for Boxable? I forget.

There was no dedicated test file for it. Should I add one, and if so, what should the tests look like? Just `unbox(box(x)) == x`?

**Comment by magnus-madsen** [comment]
> 
> 
> > Do we have tests for Boxable? I forget.
> 
> There was no dedicated test file for it. Should I add one, and if so, what should the tests look like? Just `unbox(box(x)) == x`?

Yes. Are you sure there is nothing?

**Comment by mlutze** [comment]
> > > Do we have tests for Boxable? I forget.
> > 
> > 
> > There was no dedicated test file for it. Should I add one, and if so, what should the tests look like? Just `unbox(box(x)) == x`?
> 
> Yes. Are you sure there is nothing?

That seemed like a rhetorical question so I went back to check. There is no `TestBoxable` file in the project, and no occurrences of the string `box` in `*.flix` files revealed an specific testing of the `Boxable` class.

**Comment by magnus-madsen** [comment]
> 
> 
> > > > Do we have tests for Boxable? I forget.
> > > 
> > > 
> > > There was no dedicated test file for it. Should I add one, and if so, what should the tests look like? Just `unbox(box(x)) == x`?
> > 
> > 
> > Yes. Are you sure there is nothing?
> 
> That seemed like a rhetorical question so I went back to check. There is no `TestBoxable` file in the project, and no occurrences of the string `box` in `*.flix` files revealed an specific testing of the `Boxable` class.

I am surprised. I can't find them either. But I guess we should add a stack of tests then.

**Comment by mlutze** [comment]
I just used the ToString tests as a template. So there aren't currently test cases for e.g. `List`, `Map`. Since the implementation is the same everywhere, I wasn't sure whether it was worthwhile to write those tests from scratch.

**Review by magnus-madsen — COMMENTED** [review]
Looks good! This is clever. Not sure why I did not start with this design. Perhaps there was not override support at that time?

One thing I would like is a few tests - at least for all the prims and one object type- that operations on boxed values also work.

**Comment by magnus-madsen** [comment]
I see you added some tests for ToString- but I am actually much more interested in Order because `==` and `<=` actually affect the semantics of the program whereas ToString is not really that "important". You can keep the tests of course.

**Comment by mlutze** [comment]
I added both comparison tests as well. Should they be more extensive?

**Comment by magnus-madsen** [comment]
> I added both comparison tests as well. Should they be more extensive?

I was maybe too fast. Ill take another look later.

**Comment by magnus-madsen** [comment]
I did not see the forest for the trees.

**Pull request merged**
