### PR TITLE
feat: add 'invalid' to possible test results

### LINKED ISSUE #4287: Crash when putting `@test` on non-unit function
```scala
@test
def testOne(x: Int32): Int32 = x
```

Running this test causes a crash, but we should instead issue a compilation error or test failure

### PR DESCRIPTION
**Pull request by mlutze**
fixes #4287

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Why not catch this in the type system? And why is it invalid to have a Unit test? (If you execute it for its effect?)

**Comment by mlutze** [comment]
> Why not catch this in the type system?

Per some ticket for a principle on annotations, annotations should not have an effect on compilation (or at least this is how I interpreted it)

> And why is it invalid to have a Unit test? (If you execute it for its effect?)

This is not concerning return type but rather the argument type. If the argument is not a unit then we can't execute the test.

**Comment by magnus-madsen** [comment]
> Per some ticket for a principle on annotations, annotations should not have an effect on compilation (or at least this is how I interpreted it)

That's true, but is it still not much better to have a compile-time check? I mean, the implementation would be shorter and less brittle!

**Comment by mlutze** [comment]
> > Per some ticket for a principle on annotations, annotations should not have an effect on compilation (or at least this is how I interpreted it)
> 
> That's true, but is it still not much better to have a compile-time check? I mean, the implementation would be shorter and less brittle!

I totally agree, I just didn't want to go against principle :)

**Comment by magnus-madsen** [comment]
Let's add a small compiler check and not tell anyone.

**Pull request closed without merging**
