### PR TITLE
feat: `SetFormula.Xor`

### PR DESCRIPTION
**Pull request by JonathanStarup**
Added without "deep" integration

This code is currently unused

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Can you hook it up and report back from running on the server? Thanks

**Comment by JonathanStarup** [comment]
Xperf on frontend or?

**Comment by magnus-madsen** [comment]
> Xperf on frontend or?

Xperf --frontend --n 100

and then w/ without zhegalkin.

**Comment by JonathanStarup** [comment]
```
jls@Debian-bookworm-latest-amd64-base:~$ java -jar flixxor.jar Xperf --frontend --n 100 --Xzhegalkin
~~~~ Flix Compiler Performance ~~~~

Throughput (best): 130,502 lines/sec (with 20 threads.)

  min: 87,323, max: 130,502, avg: 116,759, median: 115,427

Finished 100 iterations on 67,310 lines of code in 57 seconds.
jls@Debian-bookworm-latest-amd64-base:~$ java -jar flixxor.jar Xperf --frontend --n 100
~~~~ Flix Compiler Performance ~~~~

Throughput (best): 131,200 lines/sec (with 20 threads.)

  min: 96,976, max: 131,200, avg: 115,834, median: 114,695

Finished 100 iterations on 67,310 lines of code in 58 seconds.

```

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
