### PR TITLE
Implement let+

### PR DESCRIPTION
**Pull request by mlutze**
To complement `let*`

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@felixwiemuth is also working on this.

The real challenge is that `let+` should be "parallel/independent" by relying on an applicative. What does it mean? It means that it should be more like our `mapN` combinators. See https://jobjo.github.io/2019/04/24/ocaml-has-some-new-shiny-syntax.html

I am not sure this implements the "right" semantics. 

This might be a good topic for our next group meeting.

**Comment by magnus-madsen** [comment]
TLDR:

I believe you would allow (correct me if I am wrong):

```
let+ x = ...
let+ y = ... use x ...
```

but that is not what is intended- because with applicatives the evaluation of each variable is separate.

**Comment by mlutze** [comment]
I see. This was my minimal-effort attempt to emulate Scala's `for`-comprehension, which does allow use of previous bindings. Didn't realize there was so much to consider!

**Comment by magnus-madsen** [comment]
> 
> 
> I see. This was my minimal-effort attempt to emulate Scala's `for`-comprehension, which does allow use of previous bindings. Didn't realize there was so much to consider!

It is a actually a very deep topic. Our let* is possibly broken and should use both map and flatMap. let+ is even more difficult.

But yes, I can see that it looked like an easy task ;)

**Pull request closed without merging**
