### PR TITLE
chore: update gradle: 7.6 → 8.1

### PR DESCRIPTION
**Pull request by fabianhjr**
Via `./gradlew wrapper --gradle-version=8.1` split from #5751

### CODE REVIEW

**Comment by magnus-madsen** [comment]
which gradle-wrapper.jar is it? I don't get the right checksum.

**Comment by fabianhjr** [comment]
:O

Good observation

```
sha256sum gradle/wrapper/gradle-wrapper.jar                                            Thu 20 Apr 2023 08:59:38 AM CST
c5a643cf80162e665cc228f7b16f343fef868e47d3a4836f62e18b7e17ac018a  gradle/wrapper/gradle-wrapper.jar
```

https://gradle.org/release-checksums/

Seems like the checksum for v7.6.1

Need to investigate what happened since this is a bit unexpected.

**Comment by fabianhjr** [comment]
After re-running the upgrade via `./gradlew wrapper --gradle-version=8.1` the hash now seems to match:

```
sha256sum gradle/wrapper/gradle-wrapper.jar                             1609ms  Thu 20 Apr 2023 09:46:25 AM CST
ed2c26eba7cfb93cc2b7785d05e534f07b5b48b5e7fc941921cd098628abca58  gradle/wrapper/gradle-wrapper.jar
```
to the one published for v8.1 on https://gradle.org/release-checksums/

**Comment by magnus-madsen** [comment]
Ill wait a few hours for arewefast for the other PR and then I can hit the button.

**Comment by magnus-madsen** [comment]
I also need a rebase on this one.

**Comment by fabianhjr** [comment]
Bebased

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
