### PR TITLE
feat: define IDE example transfer functions in terms of IR instructions

### PR DESCRIPTION
**Pull request by olhotak**
Define IDE example transfer functions in terms of IR instructions instead of hard-coding the transfer function for each CFG node.

Depends on #7137

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@olhotak Do you want me to merge this or wait for more changes on the CFG?

**Comment by olhotak** [comment]
We can go either way, either discuss it first or merge it first and discuss additional tweaks to it afterwards.

**Comment by magnus-madsen** [comment]
Ill leave it open then.

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
I will merge this now because that way its subject to our tests. We can open a new PR with further changes.

**Pull request merged**
