### PR TITLE
feat: pretty print types in DocAst

### PR DESCRIPTION
**Pull request by JonathanStarup**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Can I close this or?

**Comment by JonathanStarup** [comment]
I'm working on it, just not priority right now

**Comment by JonathanStarup** [comment]
@magnus-madsen rfr - this PR is the baseline of type pretty printing, but there is still work left for n-ary unions and things like that

**Comment by magnus-madsen** [comment]
In one sentence, what does this add that was not there before?

**Review by magnus-madsen — APPROVED** [review]

**Comment by JonathanStarup** [comment]
> In one sentence, what does this add that was not there before?

1) a uniform way to print monotypes / types / unkinded types (upcoming)
2) a way to print types that can support automatic line breaks

**Pull request merged**
