### PR TITLE
Fix #1541

### LINKED ISSUE #1541: The use of ??? should not disable variable shadowing check
Right now, if a function contains an `???` then we remove all redundancy warnings inside that function.

### PR DESCRIPTION
**Pull request by magnus-madsen**
Fixes #1541

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I removed the latticeOps because that map is now empty at this point in the pipeline.

**Comment by magnus-madsen** [comment]
My face when I submit a PR for review that does not even pass all tests:

image

Let me get back to you :)

**Comment by magnus-madsen** [comment]
OK. Got it done, there is really not much to it.

**Review by mlutze — COMMENTED** [review]
Looks reasonable to me. Can we just add a regression test?

**Review by mlutze — APPROVED** [review]

**Pull request merged**
