### PR TITLE
feat: add `build-fatjar` functionality

### PR DESCRIPTION
**Pull request by ZentsuGo**
This pull request aims to implement the build-fatjar functionality mentioned in the #7224 ticket issue.

The following tasks have been achieved:
    - Added build-fatjar command in both shell and argument.
    - Updated the help command.
    - Added buildFatJar function in Bootstrap.scala: essentially, it looks up jar files in the lib folder and adds the classes into the generated jar file.

The command has been tested on project with maven dependencies, either with or without other flix dependencies.
The running of the generated fatjar-file was done on two distinct computers with the same java version.

### CODE REVIEW

**Comment by ZentsuGo** [comment]
Thank you, I just tested it and the program ran compared to the classic buildJar.
However it doesn't seem to find an SLF4J provider.

```SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
```

From a quick search it seems a jar file should be contained in the classpath, but maybe not extracted.
I will have a deeper look at this problem after I finish class.

**Comment by magnus-madsen** [comment]
Forget about SLF4J. Thats always been a problem. Dont worry about it.

**Comment by magnus-madsen** [comment]
Do you want to do any cleanup and documentation of the code before we look at it?

**Comment by magnus-madsen** [comment]
One request, instead of your `search` can you use `getAllFilesWithExt` from the same class?

**Comment by ZentsuGo** [comment]
Ok I will do that just after.

**Comment by ZentsuGo** [comment]
Now it should be fine. The code is also already commented.

**Comment by magnus-madsen** [comment]
!!!jar

**Comment by magnus-madsen** [comment]
@ZentsuGo I would like to merge this in. Could I ask you to add your name to `AUTHORS.md` to confirm you agree to make your contributions open source. Could I also ask you to fix the conflict in `Bootstrap.scala`. Thanks!

**Comment by ZentsuGo** [comment]
Hello, I added my name and the import conflict should be fixed. Tell me if it is not working.

**Comment by magnus-madsen** [comment]
@ZentsuGo Merged! Congrats on landing your first PR :)

**Comment by ZentsuGo** [comment]
Thank you!

**Pull request merged**
