### PR TITLE
proposal: better and simpler block comments

### PR DESCRIPTION
**Pull request by JonathanStarup**
Improves block comments as discussed in  #6531.
- This simplifies the implementation
- This has the property that you can _always_ add a block comment around anything, no matter its content

The rule is simple:
- There is no block comment nesting
- If you open with `/*`, you close with `*/`. If you open with `/**`, you close with `**/`. and so on

This means that there is always some number of `*` such that your block comment lexes correctly. An editor can quite easily find this number by just going through the selection naively, so with that, an editor block comment shorthand just always works.

### CODE REVIEW

**Comment by JonathanStarup** [comment]
This breaks some existing code because they use `/** some doc comments */`. This could easily be fixed with `/** **/` but all of these cases should actually just be proper flix doc comments with `///` so I did that instead.

**Comment by magnus-madsen** [comment]
Does this support Java-style block comments? E.g.

```java
/**
 * bla bla
 */
```

https://google.github.io/styleguide/javaguide.html#s7.1.1-javadoc-multi-line

or that what we are giving up?

**Comment by magnus-madsen** [comment]
I agree this change would simplify the language, but looking at the implementation: both are pretty small and self-contained?

**Comment by JonathanStarup** [comment]
I think so yeah, its mostly that it is better and simpler to understand as a user. There is always an easy answer if someone has a block comment around some text that doesn't lex. "just use /***" or whatever fits in their case. In the current system there is sometimes no answer, like the rust ticket.

**Comment by magnus-madsen** [comment]
I am open to further discussions. A convincing argument would be if this can significantly speed up incremental compilation. 

But until we take it open again, I am closing this PR.

**Pull request closed without merging**
