### PR TITLE
feat: Add the Identity Functor/Monad - #3092

### PR DESCRIPTION
**Pull request by stephentetley**
This PR adds the Identity type and instances - see issue Add Identity type and instances #3092

The PR adds the derivable instances and:

SemiGroup
Monoid
Functor
Applicative
Monad
Foladble
Traversable

It also adds the "number" instances: 

Add
Sub
Mul
Div
Neg

Haskell's Identity functor has the equivalent number instances so I have added them too.

The test suite is very simple as there isn't really anything "mechanical" about the Identity functor - if one test works for a class method any other should work.

### CODE REVIEW

**Comment by stephentetley** [comment]
Ah, there's a relation in `examples\analysis\IFDS.flix` called `Identity` that is causing a name clash.  

This didn't come up with `TestLibrary` but becomes an issue with `TestAll`.

Could the relation in IFDS be renamed to `Id`?

**Comment by magnus-madsen** [comment]
> Ah, there's a relation in `examples\analysis\IFDS.flix` called `Identity` that is causing a name clash.
> 
> This didn't come up with `TestLibrary` but becomes an issue with `TestAll`.
> 
> Could the relation in IFDS be renamed to `Id`?

Yes. That's fine.

**Comment by stephentetley** [comment]
I've changed IDFS.flix. TestAll should now work.

**Comment by magnus-madsen** [comment]
If only everything was as easy as implementing the Identity functor :)

**Pull request merged**
