### PR TITLE
feat: add `List.toMutDeque`

### PR DESCRIPTION
**Pull request by ninaandrup**
Related to #3761

### CODE REVIEW

**Comment by ninaandrup** [comment]
I haven't worked with regions yet, so I'm not sure, if this is the way to do it

**Comment by ninaandrup** [comment]
Also I noticed that `List.toMutList` has the parameters switched around. I would think the subject `l: List[a]` should be last, but is it preferable to have `r: Region[r]` as the last parameter?

**Comment by magnus-madsen** [comment]
@ninaandrup The region stuff is right!

We have not decided on the order of arguments.. But for now we are trying to have the *region last*.

So I think we should do that here too, even if it is not necessarily the final decision :)

**Comment by ninaandrup** [comment]
> @ninaandrup The region stuff is right!
> 
> We have not decided on the order of arguments.. But for now we are trying to have the _region last_.
> 
> So I think we should do that here too, even if it is not necessarily the final decision :)

Better to be consistent :-)

**Pull request merged**
