### PR TITLE
feat: remove `equals` and `hashcode` from backend objects

### LINKED ISSUE #7101: Remove Equals and HashCode from FlixErrors
Does't seem to me like they are used

### PR DESCRIPTION
**Pull request by JonathanStarup**
Fixes #7101

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I remembered the reason these are here. I can expand, but the simple reason was that if you want to write automated testing tools you may need to know when two errors are the same.

**Comment by JonathanStarup** [comment]
So you want to leave them in / keep supporting it for UnhandledEffectError? On the other hand I don't think its too hard to add back in

**Comment by magnus-madsen** [comment]
> So you want to leave them in / keep supporting it for UnhandledEffectError? On the other hand I don't think its too hard to add back in

Give me some time to think on it.

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
We can still manually inspect the fields to check for equality, so I guess its OK.

**Comment by JonathanStarup** [comment]
The fields of matcherror is also deleted in this PR, so you'd have to compare the strings of error message i think

**Pull request merged**
