### PR TITLE
feat: remove monomorphism restriction on effect ops

### PR DESCRIPTION
**Pull request by mlutze**
Per discussion, only the effects themselves must be monomorphic. Operations may be polymorphic.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Note, we can't compile these programs though, because we cannot monomorph.

**Comment by mlutze** [comment]
Ah, should we leave the restriction then until we determine a way to support polymorphism (if ever)?

**Comment by magnus-madsen** [comment]
> Ah, should we leave the restriction then until we determine a way to support polymorphism (if ever)?

I think so, because since we cannot support it without a ton of work, it would just be dead code for a long time.

Everything else we are doing we want to work "as soon as possible", right?

**Comment by mlutze** [comment]
> > Ah, should we leave the restriction then until we determine a way to support polymorphism (if ever)?
> 
> I think so, because since we cannot support it without a ton of work, it would just be dead code for a long time.
> 
> Everything else we are doing we want to work "as soon as possible", right?

Makes sense to me.

**Pull request closed without merging**
