### PR TITLE
feat: remove `Validation.map`

### PR DESCRIPTION
**Pull request by jaschdoc**
Related to https://github.com/flix/flix/issues/6746

### CODE REVIEW

**Comment by jaschdoc** [comment]
Blocked until we resolve https://github.com/flix/flix/issues/6746#issuecomment-1868320988

**Comment by magnus-madsen** [comment]
Suggestion: Can we add `mapN` for a single element and use it everywhere except for `Flix.scala`? Then we can come up with a solution for that place.

**Comment by magnus-madsen** [comment]
Looks good, just needs a conflict resolved.

**Comment by jaschdoc** [comment]
Conflict resolved :)

Also, re-run `semantic commit message` GitHub action... apparently it had an internal server error :/

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
