### PR TITLE
feat: Working structs

### PR DESCRIPTION
**Pull request by dghosef**
This PR should probably be split into multiple at some point. It includes:`struct` declarations and expressions(new, field get, field put) in all compiler phases.

The flaw that makes structs not quite practically usable is that currently struct get/put expressions assume the struct name is the same as the module name

### CODE REVIEW

**Comment by JonathanStarup** [comment]
If you want feedback on anything just let me know :)

**Comment by magnus-madsen** [comment]
!!!jar

**Comment by magnus-madsen** [comment]
Very nice! I played a bit with the implementation.

I suggest we discuss next steps on Monday. 

We have some design decisions to make and then we should also discuss how to break the PR into smaller parts.

**Comment by dghosef** [comment]
Everything from here is now in `master` or is a separate PR in progress

**Pull request closed without merging**
