### PR TITLE
feat: add restrictable choose to typed ast

### PR DESCRIPTION
**Pull request by JonathanStarup**
Related to #5229

### CODE REVIEW

**Review by mlutze — APPROVED** [review]

**Comment by magnus-madsen** [comment]
I can merge this, but there are many trivial `???` which I think might as well be fixed immediately.

**Comment by magnus-madsen** [comment]
Let me know when ready.

**Comment by magnus-madsen** [comment]
RFR/RFM?

**Comment by JonathanStarup** [comment]
Should be RFM

**Pull request merged**
