### PR TITLE
refactor: remove `Validation` from `EntryPoint`

### PR DESCRIPTION
**Pull request by jaschdoc**
Related to https://github.com/flix/flix/issues/8815

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Conflicted.

**Comment by jaschdoc** [comment]
Merged

**Comment by magnus-madsen** [comment]
Aaaand again

**Review by mlutze — APPROVED** [review]

**Comment by jaschdoc** [comment]
Merged

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
