### PR TITLE
test: add `Test.Handler.Spawn.X.flix`

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes https://github.com/flix/flix/issues/7098

### CODE REVIEW

**Comment by jaschdoc** [comment]
Hmm got this error. Is this correct?
```
Unable to compile. Failed with: 1 errors.


>> Expected effect: 'rc' but found effect: 'e0'.

26 |>         try {
27 |>             try {
28 |>                 do Ask.ask(do Gen.gen())
29 |>             } with Gen {
30 |>                 def gen(k) = k(21)
31 |>             }
32 |>         } with Ask {
33 |>             def ask(x, _) = Channel.send(21 + x, tx)
34 |>         }

expression has unexpected effect.

'rc' appears to be a superset of 'e0'.
Consider using 'checked_ecast'?
```

**Comment by magnus-madsen** [comment]
> `AtomicInteger` does not have a `Sendable` instance, so should we drop those tests?

Yeah

**Comment by magnus-madsen** [comment]
> Hmm got this error. Is this correct?
> 
> ```
> Unable to compile. Failed with: 1 errors.
> 
> 
> >> Expected effect: 'rc' but found effect: 'e0'.
> 
> 26 |>         try {
> 27 |>             try {
> 28 |>                 do Ask.ask(do Gen.gen())
> 29 |>             } with Gen {
> 30 |>                 def gen(k) = k(21)
> 31 |>             }
> 32 |>         } with Ask {
> 33 |>             def ask(x, _) = Channel.send(21 + x, tx)
> 34 |>         }
> 
> expression has unexpected effect.
> 
> 'rc' appears to be a superset of 'e0'.
> Consider using 'checked_ecast'?
> ```

Do you still get it?

**Comment by jaschdoc** [comment]
Yes

**Comment by magnus-madsen** [comment]
Can you paste the snippet that causes it?

**Comment by jaschdoc** [comment]
```scala

    def runGenAsk(tx: Sender[Int32, rc]): Unit \ rc =
        try {
            try {
                do Ask.ask(do Gen.gen())
            } with Gen {
                def gen(k) = k(42)
            }
        } with Ask {
            def ask(x, _) = Channel.send(x + x, tx)
        }
```

**Comment by magnus-madsen** [comment]
I am a bit lost. Will look tomorrow.

**Comment by magnus-madsen** [comment]
I feel like there must be a bug. Marking this as blocked.

**Comment by jaschdoc** [comment]
Now same style as requested in https://github.com/flix/flix/pull/7113#issuecomment-1909453942

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
