### PR TITLE
feat: case set unification

### PR DESCRIPTION
**Pull request by mlutze**
related to #5229

### CODE REVIEW

**Comment by magnus-madsen** [comment]
!!!jar

**Comment by magnus-madsen** [comment]
I tried some examples, but I guess reassembly is not yet there?

**Comment by JonathanStarup** [comment]
oh, yes, forgot about that part with al the debugging. but typability can be observed 😄

**Comment by JonathanStarup** [comment]
list of hacks:
* bodies of choose* not unified
* cannot write `Tag` in choose patterns for nullary enums (must do `Tag(_)`)
* The universe of tags is the universe of the Exp example
* Must refer to tags by enum namespace (`Expr.tag`)
* No tag/kind syntax

**Comment by mlutze** [comment]
> Must refer to tags by enum namespace (Expr.tag)

This one is kind of by design

**Review by JonathanStarup — APPROVED** [review]
Looks good 👍 Then we can correct the last typing details in the next PR

**Comment by magnus-madsen** [comment]
@JonathanStarup Maybe move the list of hacks into the main ticket?

**Pull request merged**
