### PR TITLE
refactor: use `SourcePosition` in `Token`

### PR DESCRIPTION
**Pull request by magnus-madsen**
The idea is to store store source positions in Token.

Note: We require that source positions are one-indexed.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@herluf-ba I would like a careful review :)

**Comment by magnus-madsen** [comment]
My next step is to use two source positions to define source location

**Review by herluf-ba — APPROVED** [review]
Looks good to me!

**Comment by magnus-madsen** [comment]
@herluf-ba Maybe you can approve the changes (under Files changed)

Otherwise @mlutze or @JonathanStarup can do it.

**Review by herluf-ba — APPROVED** [review]

**Comment by herluf-ba** [comment]
@magnus-madsen Since I don't have write access my approval does not count towards merging 
> At least 1 approving review is required by reviewers with write access.
Screenshot 2024-05-30 at 09 42 06

**Comment by magnus-madsen** [comment]
> @magnus-madsen Since I don't have write access my approval does not count towards merging
> 
> > At least 1 approving review is required by reviewers with write access.
> > Screenshot 2024-05-30 at 09 42 06

Oh

**Comment by magnus-madsen** [comment]
We need one of the big boys then.

**Review by mlutze — APPROVED** [review]

**Pull request merged**
