### PR TITLE
refactor: introduce SemanticCompletionProvider

### PR DESCRIPTION
**Pull request by stormckey**
As said in #8762. We introduce SemanticCompletionProvider to hold the method to provide semantic completions.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Conflicted.

**Comment by stormckey** [comment]
Solved

**Comment by magnus-madsen** [comment]
Do we want this now given that we are going for a big switch?

**Comment by stormckey** [comment]
Emmm you're right, I think we no longer need to refactor the code this way. Maybe close this PR?

**Pull request closed without merging**
