### PR TITLE
test: add tests for chained `Apply` and `RecordSelect` exps

### PR DESCRIPTION
**Pull request by jaschdoc**
This program crashes with the following error:
```scala
def foo(): Int32 =
    let f = () -> { g = () -> { h = () -> 12 } };
    f()#

def main(): Unit = ()
```
```
key not found: printUnlessUnit
java.util.NoSuchElementException: key not found: printUnlessUnit
	at scala.collection.immutable.Map$Map2.apply(Map.scala:316)
	at ca.uwaterloo.flix.language.phase.EntryPoint$.mkEntryPoint(EntryPoint.scala:234)
	at ca.uwaterloo.flix.language.phase.EntryPoint$.$anonfun$visitEntryPoint$1(EntryPoint.scala:138)
	at ca.uwaterloo.flix.util.Validation$.$anonfun$curry$2(Validation.scala:362)
	at ca.uwaterloo.flix.util.Validation$.ap(Validation.scala:337)
	at ca.uwaterloo.flix.util.Validation$.mapN(Validation.scala:439)
	at ca.uwaterloo.flix.language.phase.EntryPoint$.visitEntryPoint(EntryPoint.scala:136)
	at ca.uwaterloo.flix.language.phase.EntryPoint$.$anonfun$run$2(EntryPoint.scala:71)
	at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:524)
	at ca.uwaterloo.flix.language.phase.EntryPoint$.$anonfun$run$1(EntryPoint.scala:68)
	at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:611)
	at ca.uwaterloo.flix.language.phase.EntryPoint$.run(EntryPoint.scala:82)
	at ca.uwaterloo.flix.api.Flix.$anonfun$check$12(Flix.scala:505)
	at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:127)
	at ca.uwaterloo.flix.api.Flix.$anonfun$check$11(Flix.scala:504)
	at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:133)
	at ca.uwaterloo.flix.api.Flix.$anonfun$check$9(Flix.scala:502)
	at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:127)
	at ca.uwaterloo.flix.api.Flix.$anonfun$check$8(Flix.scala:501)
	at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:127)
	at ca.uwaterloo.flix.api.Flix.$anonfun$check$7(Flix.scala:500)
	at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:127)
	at ca.uwaterloo.flix.api.Flix.$anonfun$check$6(Flix.scala:499)
	at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:127)
	at ca.uwaterloo.flix.api.Flix.$anonfun$check$5(Flix.scala:498)
	at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:127)
	at ca.uwaterloo.flix.api.Flix.$anonfun$check$3(Flix.scala:496)
	at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:133)
	at ca.uwaterloo.flix.api.Flix.$anonfun$check$2(Flix.scala:495)
	at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:127)
	at ca.uwaterloo.flix.api.Flix.$anonfun$check$1(Flix.scala:494)
	at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:127)
	at ca.uwaterloo.flix.api.Flix.check(Flix.scala:493)
	at ca.uwaterloo.flix.TestUtils.check(TestUtils.scala:36)
	at ca.uwaterloo.flix.TestUtils.check$(TestUtils.scala:35)
	at ca.uwaterloo.flix.language.phase.TestParserRecovery.check(TestParser.scala:31)
	at ca.uwaterloo.flix.language.phase.TestParserRecovery.$anonfun$new$57(TestParser.scala:715)
```

Related to https://github.com/flix/flix/pull/7978
Related to https://github.com/flix/flix/issues/7897

### CODE REVIEW

**Comment by magnus-madsen** [comment]
What's the "status" on this?

**Comment by jaschdoc** [comment]
Stuck currently but I will take another look. I remember it as being somewhat difficult to debug. Maybe @JonathanStarup has an idea of what's wrong since he implemented the parser change :)

**Comment by JonathanStarup** [comment]
I get this error
```
-- Type Error -------------------------------------------------- C:\Work\github\flix\test.flix

>> Expected type: '{ g = Unit -> { h = Unit -> Int32 } }' but found type: 'Int32'.

3 |     f()#
        ^^^
        expression has unexpected type.

-- Parse Error (OtherDecl) -------------------------------------------------- C:\Work\github\flix\test.flix

>> Expected <declaration> before '#'.

3 |     f()#
           ^
           Here
```

**Comment by jaschdoc** [comment]
Ok works now

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
