### PR TITLE
feat: allow effectful holes

### LINKED ISSUE #6851: Add a free effect to `?hole` or `???`
Currently, if I have a function where I know I'm going to need an effect, such as `IO`, in the future, I cannot mark it with that and use a hole to leave it unimplemented, as follows:
```
def my_future_io_function(): Unit \ IO = ?hole
```

The compiler will complain `Expected effect 'IO' but found effect: 'Pure'.`

I can work around this with `checked_ecast(?hole)` instead, but I feel like I shouldn't need to write extra code depending on what kind of unimplemented function I want.

Flix version `0.42.0`.

### PR DESCRIPTION
**Pull request by mlutze**
an experiment

Fixes #6851

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Why do we need this? And won't sub-effecting solve it anyway?

**Comment by magnus-madsen** [comment]
It was disabled for performance reasons. Not sure if those issues are fixed yet.

**Review by JonathanStarup — APPROVED** [review]

**Comment by JonathanStarup** [comment]
I support this - I use `???()` anyway, which have the same behaviour as this `???`

**Comment by JonathanStarup** [comment]
> It was disabled for performance reasons. Not sure if those issues are fixed yet.

is `???` used that often? one var per `???` doesn't seem that bad

**Comment by mlutze** [comment]
> > It was disabled for performance reasons. Not sure if those issues are fixed yet.
> 
> is `???` used that often? one var per `???` doesn't seem that bad

I think it could be bad if e.g. we generate a match for a big enum and put `???` in all the bodies.

**Comment by magnus-madsen** [comment]
Do we want to polish and merge?

**Comment by JonathanStarup** [comment]
I vote yes

**Comment by mlutze** [comment]
> What happened here?

Thought it was merged already so I deleted the branch

**Comment by mlutze** [comment]
!!!rerun

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
