### PR TITLE
fix: ignore enums prefixed with `_` in Redundancy

### PR DESCRIPTION
**Pull request by sockmaster27**

### CODE REVIEW

**Comment by mlutze** [comment]
Can we get a test for this?

**Comment by magnus-madsen** [comment]
I would like a description of how this changes the language.

**Comment by sockmaster27** [comment]
> Can we get a test for this?

I don't see any tests for the other cases like tags, defs and effects. There are the `HiddenVarSym` ones that ensure that formal parameters and local variables can't be used if they are prefixed, but not that they aren't marked as redundant (at least directly).

Should these tests be added for all cases?

**Comment by sockmaster27** [comment]
> I would like a description of how this changes the language.

This makes enum names consistent with other symbols checked by the Redundancy phase, in that they can be prefixed with an underscore to ignore an 'Unused enum' error.

Doing this will also ignore all the enums unused tags.

In the same way that it was already the case with effects, trying to use a prefixed enum as a type fails with a parsing error: 
image

Trying to instantiate it currently gives a resolution error:
image

**Comment by magnus-madsen** [comment]
We need tests. At least for new code. Ideally for all code :)

**Comment by sockmaster27** [comment]
Should I add tests for the other cases in a new PR?

**Comment by magnus-madsen** [comment]
> Should I add tests for the other cases in a new PR?

Yes, but let us finish with HtmlDocumentor first.

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
