### PR TITLE
feat: finish `DelayMap`

### PR DESCRIPTION
**Pull request by jaschdoc**

### CODE REVIEW

**Comment by jaschdoc** [comment]
@magnus-madsen RFR.

- [ ] Fixed annotations
- [ ] Added (parallel) `DelayMap.count`
- [ ] Parallelized `DelayMap.sumWith`
- [ ] Parallelized `DelayMap.productWith`

**Comment by jaschdoc** [comment]
Anything else? :smile:

**Comment by magnus-madsen** [comment]
Ill take a look soon! 

Does Map and DelayMap now have "more or less" the same parallel functions?

**Comment by magnus-madsen** [comment]
Excellent! Thanks :)

**Comment by jaschdoc** [comment]
> Ill take a look soon! 
> 
> 
> 
> Does Map and DelayMap now have "more or less" the same parallel functions?

Yes, but DelayMap has parallelized sumwith and productwith. Do you want those in the regular Map too?

**Comment by magnus-madsen** [comment]
> > Ill take a look soon!
> > Does Map and DelayMap now have "more or less" the same parallel functions?
> 
> Yes, but DelayMap has parallelized sumwith and productwith. Do you want those in the regular Map too?

Yes, create a ticket. Its not too urgent for now.

**Pull request merged**
