### PR TITLE
refactor: move var resolution to resolver

### PR DESCRIPTION
**Pull request by mlutze**
related to #4967

### CODE REVIEW

**Comment by magnus-madsen** [comment]
RFR?

**Comment by magnus-madsen** [comment]
What is the TLDR on what this does? and what are the next steps?

**Comment by mlutze** [comment]
> RFR?

Ready



> What is the TLDR on what this does? and what are the next steps?

The main thing this does is to move the resolution of variables and type variables to the Resolver. Several errors were also consequently moved to the resolver.

I think the next step is to go through all the easy TODOs and clean up the messes I have made. Then we do the painful step of moving enum cases into their own namespaces.

**Comment by magnus-madsen** [comment]
Merged. Looking forward to the cleanup :)

**Pull request merged**
