### PR TITLE
feat: add `do`, `trywith`, `without`, and `resume` to `TypedAst`

### PR DESCRIPTION
**Pull request by mlutze**
related to #4050 

Depends on
- #4195

### CODE REVIEW

**Comment by magnus-madsen** [comment]
What does this do and what's with the TODOs?

**Comment by mlutze** [comment]
It adds effect-related expressions to the TypedAst. Previously they were erased down to `Unit`, which of course is unhelpful for getting the hover information.

The TODOs are nonessential LSP features, such as highlighting references to an effect, etc. What's important to us right now is just being able to see the effect of an expression.

**Comment by magnus-madsen** [comment]
Could you fix those TODOs. I don't think it should be too hard?

**Comment by magnus-madsen** [comment]
(Just afraid otherwise we forget one or two in the future).

**Comment by mlutze** [comment]
Can I do it as an immediate follow-up? This PR touches a lot of files and I'd prefer a more focused one for the LSP changes.

**Comment by mlutze** [comment]
(I've added to the effect cleanup #4146 to-do list, just in case)

**Comment by mlutze** [comment]
Looking at it more, the LSP stuff is more substantial as we need to add the effect and op declarations (here we have only the expressions)

**Comment by magnus-madsen** [comment]
> Looking at it more, the LSP stuff is more substantial as we need to add the effect and op declarations (here we have only the expressions)

Okay

**Pull request merged**
