### PR TITLE
chore: cleanup whitespace to avoid clashing with IDEA

### PR DESCRIPTION
**Pull request by paulbutcher**
Fix whitespace to avoid unnecessary diffs (e.g. #4159)

### CODE REVIEW

**Comment by paulbutcher** [comment]
BTW, have we thought about using [Scalafmt](https://scalameta.org/scalafmt/) to standardise our formatting? (I don't have any strong feelings about this either way, just wondering whether it's something that's been considered).

**Comment by magnus-madsen** [comment]
> BTW, have we thought about using [Scalafmt](https://scalameta.org/scalafmt/) to standardise our formatting? (I don't have any strong feelings about this either way, just wondering whether it's something that's been considered).

The informal rule is that we all use Intellij IDEAs formatting (we have open source licenses) but of course there is no CI way to enforce that. Any chance you could want to use IDEA too? :)

**Comment by paulbutcher** [comment]
I did briefly try, and found it heavyweight and slow compared to VSCode (which is where I've spent most of the last 5 years, and for which my fingers are well trained). I've recently been experimenting with the Scala Metals extension for VSCode which seems to give me most of what IDEA would.

But I shouldn't let personal preference get in the way of being a good citizen, so if IDEA is the way to go, I'll force myself to get used to it...

**Comment by magnus-madsen** [comment]
I can give you an open source license for your work on Flix. (DM me the e-mail you want to use on Gitter).

**Pull request merged**
