### PR TITLE
feat: add gradle `vscode` task

### PR DESCRIPTION
**Pull request by magnus-madsen**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@JonathanStarup @mlutze CC

**Comment by mlutze** [comment]
Any details about what this means?

**Comment by magnus-madsen** [comment]
I just allows you to copy the build JAR into your VSCode folder.

**Comment by mlutze** [comment]
How do I set that folder?

**Comment by magnus-madsen** [comment]
gradle.properties:

```
dev.flix.vscode.project=C:/tmp/flix
```

**Pull request merged**
