### PR TITLE
experiment: integrate user-defined effects into the Boolean effect language

### PR DESCRIPTION
**Pull request by magnus-madsen**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@mlutze Thoughts? 

My plan is that this will enable us to:

- Work with the current Bool effect system, allowing us to: Work on the semantics in the backend.
- In parallel: Remove the compiler to have one effect system with a toggle to the set-based once, which should be the future, once we learn how to minimize its formulas.

**Comment by mlutze** [comment]
How do we ensure that those vars are rigid in every situation?

**Comment by magnus-madsen** [comment]
> How do we ensure that those vars are rigid in every situation?

Every time they enter the substitution?

**Comment by magnus-madsen** [comment]
@mlutze This should be possible to port now.

**Comment by mlutze** [comment]
I don't think using rigid vars is the right design. IMO we can achieve the same more cleanly with a dedicated type.

**Comment by magnus-madsen** [comment]
Until the set system.

**Comment by mlutze** [comment]
Yes, I am just not convinced that a constant masquerading as a rigid variable is the best option. I'm afraid it might break assumptions we make about variables. If we instead augment the Boolean translator to handle effect constants (which it did previously) then we should have the same behavior without that compromise.

**Comment by magnus-madsen** [comment]
Okay

**Pull request closed without merging**
