### PR TITLE
test: add `Test.Exp.New`

### LINKED ISSUE #3404: Add test cases for `new`

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes #3404

### CODE REVIEW

**Comment by jaschdoc** [comment]
Note that
```flix
namespace Test/Exp/New {

    @test
    def testNew01(): MutList[Int32, Impure] & Impure =
        new MutList(static)

}
```
Crashes with **Error**
```
#
# An unexpected error has been detected by the Flix compiler:
#
#   Unexpected type: '53572443[false]
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : v0.28.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 17.0.1 (2021-10-19)
# JVM Vendor   : Oracle Corporation
# JAVA_HOME    : /home/jaschn/.sdkman/candidates/java/17.0.1-open
# System       : Linux (5.17.9-200.fc35.x86_64)
#
# -- Stack Trace --
ca.uwaterloo.flix.util.InternalCompilerException: Unexpected type: '53572443[false]
	at ca.uwaterloo.flix.language.phase.Finalize$.visit$2(Finalize.scala:406)
	at ca.uwaterloo.flix.language.phase.Finalize$.$anonfun$visitType$1(Finalize.scala:401)
	at scala.collection.immutable.List.map(List.scala:250)
	at ca.uwaterloo.flix.language.phase.Finalize$.visit$2(Finalize.scala:401)
	at ca.uwaterloo.flix.language.phase.Finalize$.visitType(Finalize.scala:507)
	at ca.uwaterloo.flix.language.phase.Finalize$.visitDef(Finalize.scala:49)
	at ca.uwaterloo.flix.language.phase.Finalize$.$anonfun$run$2(Finalize.scala:36)
	at scala.collection.StrictOptimizedMapOps.map(StrictOptimizedMapOps.scala:28)
	at scala.collection.StrictOptimizedMapOps.map$(StrictOptimizedMapOps.scala:27)
	at scala.collection.immutable.HashMap.map(HashMap.scala:39)
	at ca.uwaterloo.flix.language.phase.Finalize$.$anonfun$run$1(Finalize.scala:35)
	at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:566)
	at ca.uwaterloo.flix.language.phase.Finalize$.run(Finalize.scala:31)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$10(Flix.scala:527)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$9(Flix.scala:526)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$8(Flix.scala:525)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$7(Flix.scala:524)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$6(Flix.scala:523)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$5(Flix.scala:522)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$4(Flix.scala:521)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$3(Flix.scala:520)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$2(Flix.scala:519)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$1(Flix.scala:518)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.codeGen(Flix.scala:517)
	at ca.uwaterloo.flix.api.Flix.$anonfun$compile$1(Flix.scala:551)
	at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:252)
	at ca.uwaterloo.flix.api.Flix.compile(Flix.scala:551)
	at ca.uwaterloo.flix.util.FlixSuite.compileAndRun(FlixSuite.scala:65)
	at ca.uwaterloo.flix.util.FlixSuite.$anonfun$mkTest$1(FlixSuite.scala:48)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.invokeWithFixture$1(FunSuiteLike.scala:184)
	at org.scalatest.FunSuiteLike.$anonfun$runTest$1(FunSuiteLike.scala:196)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
	at org.scalatest.FunSuiteLike.runTest(FunSuiteLike.scala:196)
	at org.scalatest.FunSuiteLike.runTest$(FunSuiteLike.scala:178)
	at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.$anonfun$runTests$1(FunSuiteLike.scala:229)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
	at org.scalatest.FunSuiteLike.runTests(FunSuiteLike.scala:229)
	at org.scalatest.FunSuiteLike.runTests$(FunSuiteLike.scala:228)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
	at org.scalatest.Suite.run(Suite.scala:1124)
	at org.scalatest.Suite.run$(Suite.scala:1106)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.$anonfun$run$1(FunSuiteLike.scala:233)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
	at org.scalatest.FunSuiteLike.run(FunSuiteLike.scala:233)
	at org.scalatest.FunSuiteLike.run$(FunSuiteLike.scala:232)
	at org.scalatest.FunSuite.run(FunSuite.scala:1560)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1349)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1343)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1343)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1033)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1011)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1509)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1011)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:38)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:25)
```

**Comment by magnus-madsen** [comment]
Roger-- thanks. 

(The reason is that the mut list has no type for the param a, but the of course that should be a compiler error and not a crash)

**Comment by magnus-madsen** [comment]
Can you write a few tests that use new, but also add elements to the collections? 

And then open a ticket for your crashing program.

**Comment by jaschdoc** [comment]
Hmm weird now it crashes on `testNew04` with error
```
Unable to compile. Failed with: 1 errors.

-- Type Error -------------------------------------------------- main/test/flix/Test.Exp.New.flix

>> No instance of the 'Newable' class for the type ''53589494'.

23 |         let l = new MutList(r);
                         ^^^^^^^
                         missing instance


ScalaTestFailureLocation: ca.uwaterloo.flix.util.FlixSuite at (FlixSuite.scala:70)
org.scalatest.exceptions.TestFailedException: Unable to compile. Failed with: 1 errors.

```

**Comment by jaschdoc** [comment]
@magnus-madsen RFR

**Comment by jaschdoc** [comment]
Roger :+1:

**Comment by jaschdoc** [comment]
These tests are somewhat chaotically organized, but they do test for different combinations of regions and their usage. Not sure about coverage... :sweat_smile:

**Comment by magnus-madsen** [comment]
Yeah, its a bit of a mess. Perhaps we could identify the moving parts:

- The data structure used (MutList, MutMap, etc)
- The region layout: 1 region, 2 regions (not nested), 2 regions nested (and with one data structure inside the other).

Then we could create tests like:

`testNewMutMap1Region`
`testNewMutMap2RegionsFlat`
`testNewMutMap2RegionsNested`

or something like this.

Can we cook up something more principled like the above? :)

**Comment by jaschdoc** [comment]
What do you think of the `MutList` tests so far?

**Comment by magnus-madsen** [comment]
Thanks! This is very good :)

**Pull request merged**
