### PR TITLE
feat: add functor-applicative-monad combinators and test suites

### PR DESCRIPTION
**Pull request by stephentetley**
This PR adds a small set of combinators to Functor, Applicative and Monad and adds test suites for those modules.

I've limited the combintors in this PR to named ones (no operators) and avoided traversals (examples would be `mapM` etc). I'd like Flix to have operators and effectful traversals soon, but there is probably more bikeshedding about naming and typing for these functions so I've left them out.

The PR adds:

`ignore` to Functor - this is called `void` in Haskell but I wanted to avoid the name.

`seqLeft` to Applicative - this is `(<*)` in Haskell 

`seqRight` to Applicative - this is `(*>)` in Haskell 

`whenTrue` to Applicative - this is `when` in Haskell / PureScript

`whenFalse` to Applicative - this is `unless` in Haskell / PureScript

`join` to Monad

`bind` to Monad - this is `flatMap` with the arguments flipped

`kleisliLeft` to Monad - this is `(<=<)` in Haskell 

`kleisliRight` to Monad - this is `(>=>)` in Haskell 

`whenTrueM` to Applicative - this is `whenM` in PureScript

`whenFalseM` to Applicative - this is `unlessM` in PureScript 

I've always disliked the `when` and `unless` pair in Haskell. To me the names don't sufficiently imply which should be for the true case and which for the false case so I've gone for longer but more explicit names.

I re-indented Functor to use 4 spaces so the module looks like it has more changes than it actually has.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Hello Stephen and happy holidays!

I agree that we should have these operations, but I want to bikeshed the names. In particular, I have slight preference for less academic names (despite being an academic) and slight preference for the names used in the Scala ecosystem. I am also open to new names. For example, I chose `map` and `flatMap` because I think they are slight more meaningful and less intimidating than their 'traditional' names. Anyway, here we go (from more certain to less certain):

- [ ] `join -> flatten`. It fits better with `flatMap` and it avoids confusion with `JoinLattice` etc.
- [ ] `seqLeft/seqRight -> productL/productR`. I think it fits nicely with `product` which we should add. 
- [ ] `ignore` OK, I also dislike `void`. `ignore` is not great, but I don't have a better suggestion.
- [ ] `kleisliLeft/right` - I have never used these, so I guess I am okay with their names. Is that their Haskell names? I don't see them in Scaladoc for Monad in Cats.
- [ ] `whenTrueM / whenFalseM` I note that Cats uses `ifM`. There is also `ifF` but no `ifA`. Moreover they have `Applicative.whenA/unlessA` so I am confused what their naming strategy is.
- [ ] `bind` - whats' the purpose of having it if we already have `flatMap`? I am worried it could lead to a lot of confusion. (e.g. programmers trying to implement `bind` for `Monad` etc. etc.)

Note that we can have `<*` and friends as long as we also have full ASCII names for these. Thus even if we call it `productL` you will probably just be writing `<*`.

Unrelated: Did you have a chance to checkout https://api.flix.dev/ ?

**Comment by stephentetley** [comment]
Thanks Magnus, Happy Christmas to you too.

`join` => `flatten` - I'm happy with `flatten`

`seqLeft` / `seqRight` -> `productL` / `productR`. I'm happy to change but I think we should add `product` if I do. Also, should they be `productLeft` and `productRight` ? I think this would be more consistent and aren't some functions are now using the "L" suffix for Lazy?

Would `product` be this one? Shall I add it to the PR ...

~~~

pub def product(fa: m[a], fb : m[b]): m[(a, b)] with Applicative[m] =
    Applicative.liftA2((a, b) -> (a, b), fa, fb)

~~~

I hadn't thought about `ifM` - I think we should add it...

~~~

///
/// Perform the monadic action `test`, if it evaluates to true perform `mthen` otherwise perform `melse`.
///
pub def ifM(test: m[Bool], mthen: m[a], melse: m[a]): m[a] with Monad[m] =
    bind(test, x1 -> if (x1) mthen else melse)

~~~

The Functor "if-then-else" function is a bit different to `ifM` - the "then" and "else" arguments are pure values. I'm happy to add it but I'd prefer a different name to `ifF` as it doesn't really match `ifM`. I would want `ifM` to have the _better_ name as I think it would be used more often.

Currently I'd pick `choose` or `ifThenElse`:

~~~

///
/// Functor choice function.
///
/// Perform the action `test`, if it evaluates to `true` return `m(a)`
/// otherwise return `m(b)`.
///
pub def choose(test: m[Bool], a: a, b: a): m[a] with Functor[m] =
    Functor.map(cond -> if (cond) a else b, test)
        
~~~

I'd be okay about losing `bind` although I usually prefer it to flatMap for one liners - in `ifM` for instance, `test` starts "dangling" in the flatMap version: 

~~~

pub def ifM(test: m[Bool], mthen: m[a], melse: m[a]): m[a] with Monad[m] =
    flatMap(x1 -> if (x1) mthen else melse, test)

~~~

When I come to make a PR for the operators, I would propose both `(=<<)` for `flatMap` and `(>>=)` for its flipped version so we would get `bind` back.

> Unrelated: Did you have a chance to checkout https://api.flix.dev/ ?

Looks good! I usual keep IntelliJ open with a Flix sandbox so I can search the library - having docs will be very useful.

**Comment by magnus-madsen** [comment]
I'd like to understand the whenTrue/whenFalse/ifM thing in more detail - i.e. read up a bit when I have some time :) 

How about we update the PR to add these for now: flatten, product, productLeft, productRight, kleisleLeft, kleisleRight (sp?)

In a separate PR we can add their symbols. 

In a subsequent PR we can deal with whenTrue/whenFalse/ifM etc.

Meanwhile I will also think about whether L should be for left or lazy or neither.

Sounds good? :)

**Comment by stephentetley** [comment]
Thanks Magnus - I've pushed those changes.

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
