### PR TITLE
feat: add struct field autocompletion

### PR DESCRIPTION
**Pull request by dghosef**
#8308

### CODE REVIEW

**Comment by dghosef** [comment]
Screenshot 2024-08-14 at 5 22 56 PM
Screenshot 2024-08-14 at 5 23 10 PM

**Comment by dghosef** [comment]
Screenshot 2024-08-14 at 5 24 16 PM
Screenshot 2024-08-14 at 5 24 26 PM

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
Looks nice

**Comment by magnus-madsen** [comment]
Do you want to show the field type as part of the label?

**Pull request merged**
