### PR TITLE
chore: update import syntax in test files from `main/src/library`: `Chain.flix`, `Char.flix`, `CodePoint.flix`, `Console.flix` and `Debug.flix`

### PR DESCRIPTION
**Pull request by chanattan**
Related to #8096.
WIP.

### CODE REVIEW

**Comment by chanattan** [comment]
There seems to have problems with consecutive calls/field access then method call.
E.g., `print` and `println` in `Console.flix` and `System.out.println` in `Debug.flix`. I am thinking about it.

**Comment by chanattan** [comment]
Apart the three mentioned above functions, everything is refactored.

**Review by magnus-madsen — APPROVED** [review]

**Comment by chanattan** [comment]
I'll split to ensure fast refactoring.

**Comment by magnus-madsen** [comment]
You can open a new PR with CodePoint

**Pull request closed without merging**
