### PR TITLE
Add Kind Ascriptions

### PR DESCRIPTION
**Pull request by magnus-madsen**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Unrelated changed are because of the auto formatter.

**Comment by magnus-madsen** [comment]
I would merge this, and then your PR on top. I don't think they conflict.

**Review by mlutze — COMMENTED** [review]
What happens if I provide a bad kind ascription (e.g. on a non-var, `Int :# Bool`)? It looks like this is just ignored. Is there any checking we should do for that?

Alternately, we could allow ascriptions only on variable kinds for now.

**Comment by magnus-madsen** [comment]
> 
> 
> What happens if I provide a bad kind ascription (e.g. on a non-var, `Int :# Bool`)? It looks like this is just ignored. Is there any checking we should do for that?
> 
> Alternately, we could allow ascriptions only on variable kinds for now.

It is just ignored. This is more of a temporary fix than a permanent solution. 

Unlike type casts, I think an actual kind cast would always fail.

**Pull request merged**
