### PR TITLE
refactor: remove `Validation` from `Namer`

### PR DESCRIPTION
**Pull request by jaschdoc**
This is one big PR containing all changes to `Namer`. We can either choose to merge it all or just split it out into smaller PRs.

Depends on https://github.com/flix/flix/pull/8056
Closes https://github.com/flix/flix/issues/7875

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@jaschdoc This became conflicted. Why did that happen? Because we use rebase? If so, would the solution be for you to squash the PR before building another PR on top?

**Comment by jaschdoc** [comment]
I can try to rebase locally :)

**Comment by jaschdoc** [comment]
Done

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
Excellent. Thanks!

**Pull request merged**
