### PR TITLE
docs: add `region` example

### LINKED ISSUE #3392: Add region example
Add an example of regions that goes like this:

```
def deduplicate(l: List[a]): List[a] with Eq[a] = 
  region r {
     ... allocate mut set...
     ... l.foreach(push to mut set)...
     ... l.filter(mut set member of)...
```

Add some comments.

It would be nice if this example could be added to examples but also used on the front page of flix.dev

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes #3392

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Is this automatically included in the tests? I forget.

**Comment by jaschdoc** [comment]
> Is this automatically included in the tests? I forget.

Yes!

**Comment by jaschdoc** [comment]
It fits within the top-most box on the website now. Tried pasting it into the box and everything looks good.

**Comment by jaschdoc** [comment]
> I think I am stupid :) 
> 
> 
> 
> My initial proposal does not make too much sense.
> 
> 
> 
> I think this is better:
> 
> 
> 
> ```
> 
> let s = new MutSet ...
> 
> List.filter(elm => if (memberOf(elm, s)) { /* elm already seen*/ false } else { mutSet.add(elm); true }
> 
> ```
> 
> 
> 
> Makes sense? 
> 
> 
> 
> Like the current solution works, but it is more complicated than necessary right?

Yes this is much more reasonable:)

**Comment by jaschdoc** [comment]
Should be much simpler now. This version also fits into the code box on the website.

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
