### PR TITLE
fix: Force :: to use List.Cons

### PR DESCRIPTION
**Pull request by paulbutcher**
I've spent ages trying to work out why this isn't working and am clearly missing something. So probably faster to ask for help. What am I missing?

These changes result in errors of the form:

```
-- Resolution Error -------------------------------------------------- Array.flix

>> Undefined type 'List'.

125 |                 loop(i - 1, x :: acc)
                                    ^^
                                    type not found.
```

### CODE REVIEW

**Comment by mlutze** [comment]
Do these errors only come up in tests using the minimal library? (Something like `TestWithMinLib`)

**Comment by paulbutcher** [comment]
> Do these errors only come up in tests using the minimal library? (Something like `TestWithMinLib`)

Sadly not: they occur with all of the tests within CompilerSuite.

**Comment by mlutze** [comment]
I think it's an unrelated namespace issue. This also causes an error on latest release.

```scala
namespace X {
    def x(): List[Int32] = List.Nil
}
```

**Comment by paulbutcher** [comment]
> I think it's an unrelated namespace issue. This also causes an error on latest release.
> 
> ```scala
> namespace X {
>     def x(): List[Int32] = List.Nil
> }
> ```

Wait, really?! How is *anything* working?!

**Comment by paulbutcher** [comment]
This isn't new behaviour, I've gone back through previous releases of `flix.jar` and it's still failing as far back as 0.28.0 (released in May)

```
paulbutcher@Pauls-MBP flix-playground % java -jar flix.jar --version
The Flix Programming Language v0.28.0
paulbutcher@Pauls-MBP flix-playground % java -jar flix.jar check 
-- Resolution Error -------------------------------------------------- /Users/paulbutcher/Projects/Flix/flix-playground/src/Main.flix

>> Undefined type 'List'.

3 |         List.Cons(1, List.Cons(2, List.Nil))
            ^^^^^^^^^
            type not found.


-- Resolution Error -------------------------------------------------- /Users/paulbutcher/Projects/Flix/flix-playground/src/Main.flix

>> Undefined type 'List'.

3 |         List.Cons(1, List.Cons(2, List.Nil))
                         ^^^^^^^^^
                         type not found.


-- Resolution Error -------------------------------------------------- /Users/paulbutcher/Projects/Flix/flix-playground/src/Main.flix

>> Undefined type 'List'.

3 |         List.Cons(1, List.Cons(2, List.Nil))
                                      ^^^^^^^^
                                      type not found.

```

**Comment by JonathanStarup** [comment]
@paulbutcher This is currently a compile error, so you can only `use` it as in an expression not on namespace level, I'm not sure whether this is known so that's why I put it here.
```
namespace A {
    pub enum EnumA(Int32)

    namespace B {
        use A.EnumA
    }
}
```

**Comment by paulbutcher** [comment]
@JonathanStarup was this comment intended for this PR? Or possibly for #4746?

Or am I missing something?

**Comment by JonathanStarup** [comment]
> @JonathanStarup was this comment intended for this PR? Or possibly for #4746?
> 
> Or am I missing something?

oh yes, my bad

**Pull request merged**
