### PR TITLE
test: add stratifier tests

### PR DESCRIPTION
**Pull request by JonathanStarup**

### CODE REVIEW

**Comment by JonathanStarup** [comment]
@magnus-madsen is this the right kind of tests? Do you have any feedback?

**Comment by magnus-madsen** [comment]
You are the expert :) Its a bit hard to read because there is no documentation and the names are auto-generated, but if you feel they cover the right cases then yes. But I think its more important to get this done soon, and it does not have to use an automated approach. (Any automated approach tends to just generate the same kinds of programs. Ideally we should generate programs that correspond to each of our design choices.)

**Comment by JonathanStarup** [comment]
> You are the expert :) Its a bit hard to read because there is no documentation and the names are auto-generated, but if you feel they cover the right cases then yes. But I think its more important to get this done soon, and it does not have to use an automated approach. (Any automated approach tends to just generate the same kinds of programs. Ideally we should generate programs that correspond to each of our design choices.)

These are manual tests I just named them systematically to have unique predicates. These are covered:
* Arity
* Term types
* denotation
* rule based filtering (also in combination with the above)

There should maybe be more, and the unification aspect is not very well tested since I assumed unification is pretty well tested.

**Comment by magnus-madsen** [comment]
Merged!

**Pull request merged**
