### PR TITLE
chore: Switch from jar files in lib to Gradle dependencies

### PR DESCRIPTION
**Pull request by paulbutcher**
This goes most of the way towards addressing #5199. Draft only from an excess of caution. Some notes:

1. This gets rid of all files in `lib` except for PJBDD, the most recently released version of which seems to be earlier than the one we're currently using. At some point we might want to nag them to make a release, but for now we can stick with the JAR file.
2. All versions are pinned (so we're using exactly the same versions as previously)
3. The resulting JAR file is significantly (approx 3MB) smaller than previously because I've stopped the ScalaTest dependency from being included.
4. Initial compile time will be slightly slower (because dependencies will be downloaded: takes less than 10 seconds on my network connection), but subsequent compilations should be identical.
    1. GitHub CI builds will be slower as things stand because they will download dependencies each time. We can address this if we want to by [cacheing dependencies](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows).
    2. I imagine that arewefast.flix.dev will cache dependencies automatically, although I don't know exactly how it's setup so can't be 100% sure.
5. I haven't yet looked at what needs to be done (if anything) to get this working with IntelliJ (this "just works" in VSCode via Metals, so I'm sure we can get it working in IntelliJ too: I just haven't looked at this yet).
6. We don't need to specify the following dependencies explicitly because they're sub-dependencies of others:
    1. scala-library
    3. scala-reflect
    4. json4s-ast
    5. json4s-core
    6. scala-xml
    7. shapeless

This is the dependency tree which results from this configuration:

```
+--- org.java-websocket:Java-WebSocket:1.3.9
+--- org.jline:jline:3.5.1
+--- org.json4s:json4s-native_2.13:3.5.5
|    +--- org.scala-lang:scala-library:2.13.0 -> 2.13.4
|    \--- org.json4s:json4s-core_2.13:3.5.5
|         +--- org.scala-lang:scala-library:2.13.0 -> 2.13.4
|         +--- org.json4s:json4s-ast_2.13:3.5.5
|         |    \--- org.scala-lang:scala-library:2.13.0 -> 2.13.4
|         +--- org.json4s:json4s-scalap_2.13:3.5.5
|         |    \--- org.scala-lang:scala-library:2.13.0 -> 2.13.4
|         +--- com.thoughtworks.paranamer:paranamer:2.8
|         \--- org.scala-lang.modules:scala-xml_2.13:1.2.0
|              \--- org.scala-lang:scala-library:2.13.0 -> 2.13.4
+--- org.ow2.asm:asm:9.2
+--- org.parboiled:parboiled_2.13:2.2.1
|    +--- org.scala-lang:scala-library:2.13.3 -> 2.13.4
|    \--- com.chuusai:shapeless_2.13:2.3.3
|         \--- org.scala-lang:scala-library:2.13.0 -> 2.13.4
+--- org.scalactic:scalactic_2.13:3.0.8
|    +--- org.scala-lang:scala-library:2.13.0 -> 2.13.4
|    \--- org.scala-lang:scala-reflect:2.13.0
|         \--- org.scala-lang:scala-library:2.13.0 -> 2.13.4
+--- org.scala-lang.modules:scala-parallel-collections_2.13:0.2.0
|    \--- org.scala-lang:scala-library:2.13.0 -> 2.13.4
+--- com.github.scopt:scopt_2.13:4.0.1
|    \--- org.scala-lang:scala-library:2.13.4
\--- com.google.guava:guava:25.1-jre
     +--- com.google.code.findbugs:jsr305:3.0.2
     +--- org.checkerframework:checker-qual:2.0.0
     +--- com.google.errorprone:error_prone_annotations:2.1.3
     +--- com.google.j2objc:j2objc-annotations:1.1
     \--- org.codehaus.mojo:animal-sniffer-annotations:1.14
```

You can see from this that there are a few dependencies being included which weren't before, specifically these are:

* Sub-dependencies of json4s:
    * json4s-scalap
    * paranamer
* Sub-dependencies of Guava:
    * jsr305
    * checker-qual
    * error_prone_annotations
    * j2objc-annotations
    * animal-sniffer-annotations

We can, if we choose, exclude these dependencies, but I wouldn't recommend doing so unless there's a strong reason to do so: they aren't large (we've already made the JAR several megabytes smaller by not including ScalaTest) and almost certainly don't do any harm. The complexity of excluding them is probably OTT (but we can do it if we choose to).

### CODE REVIEW

**Comment by paulbutcher** [comment]
So this seems to "just work" in IntelliJ IDEA too: I pulled the project from source control, switched to the branch, and asked IntellIJ to compile it. After selecting a Scala runtime, it all just worked. I could build and run the Flix runtime, searching works, etc.

But I'm not an IntelliJ power user by any means, so it's quite possible that I'm missing something.

**Comment by magnus-madsen** [comment]
We will try it out and see how it goes.

**Comment by magnus-madsen** [comment]
@JonathanStarup  @mlutze @jaschdoc If I could ask you all to try out this PR and see if it works with your workflow. In particular, do you still have fast compiles and so forth.

**Comment by magnus-madsen** [comment]
I tried this in IDEA (Not sure if this is the right approach):

- Check out branch.
- Right-click on `build.gradle` and pick `Link Gradle`.
- I then had to create new Run Targets.


One thing that is annoying is when running we get all this garbage output:

```
12.19.17: Executing ':Main.main()'...

> Task :compileJava NO-SOURCE
> Task :compileScala UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE

> Task :Main.main()
Running 1 tests...

   PASS  testBug 1.2ms

Passed: 1, Failed: 0. Skipped: 0. Elapsed: 3.7ms.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 5s
2 actionable tasks: 1 executed, 1 up-to-date
12.19.23: Execution finished ':Main.main()'.
```

Running the tests gives me:

```
Execution failed for task ':test'.
> No tests found for given includes: [ca.uwaterloo.flix.TestAll](--tests filter)
```

Not sure what that is about.

I tried to make a small change to see if incremental compilation works. With Gradle it took 54s. With IDEA it took 56s. So that seems to work.

**Comment by paulbutcher** [comment]
Hmm, I didn’t have to do a “Link Gradle” step. Let me see if I can re-create my steps and see if it’s any better.

**Comment by paulbutcher** [comment]
So, here are the steps I followed:

* Start IDEA with no Project loaded
* "Get from VCS" to check out a clean copy
* This automatically detects the Gradle script (no further input from me whatsoever) and starts a build with the following output:
    ```
    Starting Gradle Daemon...
    Gradle Daemon started in 586 ms
    > Task :prepareKotlinBuildScriptModel UP-TO-DATE
    
    BUILD SUCCESSFUL in 4s
    ```
* Checkout "gradledeps" branch
* Open `Main.scala`
* "Run|Run 'Main.scala'" which compiles and starts the REPL as follows:
    ```
    12:15:24: Executing ':Main.main()'...
    
    > Task :compileJava NO-SOURCE
    > Task :compileScala
    Unexpected javac output: warning: [options] system modules path not set in conjunction with -source 11
    1 warning.
    
    > Task :processResources NO-SOURCE
    > Task :classes
    
    > Task :Main.main()
         __   _   _
        / _| | | (_)            Welcome to Flix v0.34.0
       | |_  | |  _  __  __
       |  _| | | | | \ \/ /     Enter an expression to have it evaluated.
       | |   | | | |  >  <      Type ':help' for more information.
       |_|   |_| |_| /_/\_\     Type ':quit' or press 'ctrl + d' to exit.
          
    flix> 
    ```
* I can run the full test suite by running the "testAll" task from the "Gradle" pane

The bit that doesn't seem to work "out of the box" is running a single test (I get the same error as you do). I think the reason for this is that we've broken Gradle's `:test` task. I'll see if I can work out how to unbreak it.

**Comment by paulbutcher** [comment]
OK, I think I've worked out what was going on and found an acceptable fix. Gradle doesn't understand how to run ScalaTest tests directly, instead it needs to use `JUnitRunner`.

Notes:

* There doesn't seem to be any JUnit integration available for the version of ScalaTest we were using, so I've upgraded to the most recent (3.2.13)
    * This unfortunately requires a number of follow-on changes because of changes that have happened within ScalaTest: primarily the fact that `FunSuite` is now called `AnyFunSuite`, and is in a separate package.
* These changes allow us to do away with the `testAll` target, and all the associated machinery:
    * We no longer need `TestAll` or any of the various different suites that collect together tests from various places, which simplifies things somewhat.
    * In the process of looking at this, I discovered that there was one test which was never being run (because it wasn't included in any suites): `TestProgramArgs`.
* This not only allows IDEA to run the tests that it used to be able to run with the previous setup, but it also allows it to run things like `CompilerSuite` (I don't think that this used to work previously, although please feel free to disabuse me if I'm mistaken).
* I've confirmed that the same number of tests run (modulo `TestProgramArgs` as mentioned above) and that they run in the same elapsed time.
* The way that gradle reports test runs is rather different: it doesn't "scroll up" as tests run (instead showing the current test and count on a single line each). I think that this is nicer (it doesn't have the problem with the elapsed time "polluting" test results), but is a change.
    * If you want to see each individual test reported, you can run `gradle test -i`
    * Because one of our tests tests the Flix test framework, the final output looks like it's only run a single test `test01`. We might want to tidy this up, but I don't think it's a huge problem.
* I did look at https://github.com/maiflai/gradle-scalatest which is a ScalaTest runner for Gradle. I couldn't get it to work immediately, and didn't invest much time in it as the JUnit approach seems to be the officially sanctioned approach (see https://docs.gradle.org/current/userguide/scala_plugin.html)

**Comment by magnus-madsen** [comment]
I wrote to PJBDD authors asking them to publish on Maven. We will see if they do.

**Comment by magnus-madsen** [comment]
Some observations:

- How can we suppress gradle output when running `Main`?
- Do you also get this? `Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.`?
- JProfiler seems to work. 
- Debugging seems slow, e.g. I see `Gradle Daemon started in 6 s 926 ms`, but it works.
- I cannot seem to click on a test to jump to its definition.
- Not sure how I can run a test suite again:
  image
- "Rerun failed tests" does not work if there was a crash.

**Comment by paulbutcher** [comment]
OK, there's a completely different way to skin this cat. I've reverted the changes which switch to JUnit (we might still want to make these changes, because I do think that they're an improvement over the current setup, but they're no longer necessary for this task I think).

I've also reinstated the Scala library version in `build.gradle` (which isn't necessary for Gradle, but does seem to be necessary for IDEA to configure things correctly).

If you open IntelliJ "Settings" and navigate to "Build, Execution, Deployment"|"Build Tools"|"Gradle" you can change "Build and run using" and "Run tests using" both to "IntelliJ IDEA" (instead of Gradle). This should get you back to exactly what you had before (except using the dependencies from the Gradle build).

You might have to clean the project and/or check out a fresh version first to avoid cruft from previous builds getting in the way).

**Comment by paulbutcher** [comment]
I've marked this as "ready for review" because with the IDEA configuration above, I think that this is basically identical to what we had before, apart from the fact that we're downloading dependencies from Maven instead of having them hard-coded in the "lib" directory.

**Comment by magnus-madsen** [comment]
Ill try that tomorrow 👍

**Comment by paulbutcher** [comment]
> Ill try that tomorrow 👍

Have you had a chance to take a look at this yet, Magnus?

**Comment by magnus-madsen** [comment]
No, not yet. We also need to hear from the other guys.

**Comment by magnus-madsen** [comment]
Just tried it out. Seems to work well.

**Comment by JonathanStarup** [comment]
It works perfectly for me. I checked out this PR, gradle did something, and then everything still works (my setup had idea as build/tests already).

**Comment by jaschdoc** [comment]
I tried it out on a fresh GitHub code space just to see if anything had changed but neither the main branch or this PR worked with Gradle (I only installed Java plugins and Gradle plugin just to see if Gradle just worked out of the box). But since neither branch works I guess we haven't gained or lost anything.

Haven't had time to try locally yet but hopefully it won't be an issue as it seems to work for the others.

Are there any plans to make Gradle *just work*? :)

**Comment by magnus-madsen** [comment]
> I tried it out on a fresh GitHub code space just to see if anything had changed but neither the main branch or this PR worked with Gradle (I only installed Java plugins and Gradle plugin just to see if Gradle just worked out of the box). But since neither branch works I guess we haven't gained or lost anything.
> 
> Haven't had time to try locally yet but hopefully it won't be an issue as it seems to work for the others.
> 
> Are there any plans to make Gradle _just work_? :)

_Why_ does is not work? Can you paste the error? `gradle test` should work -- already -- both on master and here (?).

**Comment by magnus-madsen** [comment]
@paulbutcher We need to update the build instructions in `docs`.

**Comment by magnus-madsen** [comment]
I am also still waiting to hear from the PJBDD group.

**Comment by paulbutcher** [comment]
> @paulbutcher We need to update the build instructions in `docs`.

Will do.

**Comment by paulbutcher** [comment]
> I am also still waiting to hear from the PJBDD group.

It would be nice to have this addressed, but I don't think we need to wait for it before merging this PR.

**Comment by jaschdoc** [comment]
> _Why_ does is not work? Can you paste the error? `gradle test` should work -- already -- both on master and here (?).


It has exit code 127 so it ran out of memory in the code space. I'll try building in a code space with better specs. For the sake of completeness I should also mention that I got an error telling me it had 100% CPU utilization right before it crashed. The recommended action was to shut down the process.


## This branch

```
> Task :compileScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileScala'.
> Failed to run Gradle Worker Daemon
   > Process 'Gradle Worker Daemon 1' finished with non-zero exit value 137

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 47s
1 actionable task: 1 executed
```

## Master

```
> Task :compileScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileScala'.
> Failed to run Gradle Worker Daemon
   > Process 'Gradle Worker Daemon 1' finished with non-zero exit value 137

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 47s
1 actionable task: 1 executed
@jaschdoc ➜ /workspaces/flix (master ✗) $ gradle test
> Task :compileScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileScala'.
> Failed to run Gradle Worker Daemon
   > Process 'Gradle Worker Daemon 2' finished with non-zero exit value 137

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 54s
1 actionable task: 1 executed
```

**Comment by magnus-madsen** [comment]
> Would you like me to followup with a PR which switches to using JUnitRunner?

Not yet, no.

@mlutze @jaschdoc Does this work with your setups?

**Comment by mlutze** [comment]
When I click the button to run only `LibrarySuite` tests, it seems to try to run _all_ the tests.

**Comment by paulbutcher** [comment]
> When I click the button to run only `LibrarySuite` tests, it seems to try to run _all_ the tests.

Can you describe exactly which button you're talking about, and what differs between this setup and the previous one?

**Comment by paulbutcher** [comment]
(Clarification: when I say differ I mean what differs in behaviour).

**Comment by mlutze** [comment]
> > When I click the button to run only `LibrarySuite` tests, it seems to try to run _all_ the tests.
> 
> Can you describe exactly which button you're talking about, and what differs between this setup and the previous one?

If I open `LibrarySuite.scala`, there is a green button next to the declaration. I click this button to run the tests in this suite.

Normally this would pull up the IntelliJ test window and run only run the tests in the `LibrarySuite`. On this branch it instead says "initializing tests..." and when I look at the Build window, it seems to be running the entire test suite (i.e. `testAll`)

**Comment by mlutze** [comment]
> > If I open `LibrarySuite.scala`, there is a green button next to the declaration. I click this button to run the tests in this suite.
> > Normally this would pull up the IntelliJ test window and run only run the tests in the `LibrarySuite`. On this branch it instead says "initializing tests..." and when I look at the Build window, it seems to be running the entire test suite (i.e. `testAll`)
> 
> Can you double-check that you have set "Run tests using" to "IntelliJ IDEA"? The behaviour you describe is precisely what I get if it's set to "Gradle" but if I set it to "IntelliJ IDEA" then it runs 63 tests only.

That fixed it. (sorry :) )

**Comment by magnus-madsen** [comment]
Ill merge this soon.

**Comment by magnus-madsen** [comment]
@JonathanStarup @mlutze @jaschdoc @stephentetley I will merge this tomorrow, so last chance for objections/issues :)

**Comment by magnus-madsen** [comment]
Its done. You may need to follow Pauls instructions to setup IDEA.

**Pull request merged**
