### PR TITLE
test: add negative test cases for `IO` and effects

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes https://github.com/flix/flix/issues/7145

### CODE REVIEW

**Comment by jaschdoc** [comment]
`TestIOAndCustomEffect.03` produces `PossibleCheckedEffectCast` even when wrapping in `checked_ecast`:
```
>> Expected effect: 'IO' but found effect: 'e2 + e0 + e1'.

12 |> pub def f(): Unit \ IO = checked_ecast({
13 |>     let _ = try {
14 |>         do Gen.gen();
15 |>         do AskTell.askTell(42)
16 |>     } with Gen {
17 |>         def gen(k) = k("a")
18 |>     };
19 |>     checked_ecast(())
20 |> })

expression has unexpected effect.

'IO' appears to be a superset of 'e2 + e0 + e1'.
Consider using 'checked_ecast'?
```

**Comment by magnus-madsen** [comment]
Can you drop the checked casts? The goal is for the program not to type check.

**Comment by magnus-madsen** [comment]
If it gives PossibleCheckCast that is OK for now. It is still an error at least. (Just the wrong one).

**Comment by jaschdoc** [comment]
> Can you drop the checked casts? The goal is for the program not to type check.

The effect casts are only around the `()` (unit values) to avoid using a library function so tests are faster. The errors messages posted above are checked in VSCode both with and without the effect casts around the `try-with` expression.

**Comment by magnus-madsen** [comment]
What errors? I don't want a checked cast. I just want that if you have a user-defined effect then you cannot write IO.

**Comment by jaschdoc** [comment]
> What errors? I don't want a checked cast. I just want that if you have a user-defined effect then you cannot write IO.

This error: https://github.com/flix/flix/pull/7154#issuecomment-1914342895

No checked casts at all?

**Comment by jaschdoc** [comment]
Ah wait I understand now

**Comment by magnus-madsen** [comment]
Yeah, I should explain better.

Old days: IO was the biggest effect. So if you had the Ask and Print effect they were subsumed by IO.
New days: IO just an effect like any other. It should _NOT_ subsume any effects.

**Comment by jaschdoc** [comment]
Error is pipeline-related, not this PR itself

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
