### PR TITLE
refactor: optional fixpoint

### PR DESCRIPTION
**Pull request by JonathanStarup**
~1.5 % frontend throughput speedup

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Why would this give a speedup?

**Comment by JonathanStarup** [comment]
I would've also guessed it would do nothing since the lists are size 1 basically always - but it does avoid re-applying the substitution

**Comment by magnus-madsen** [comment]
I don't think we should have this optimization. And if we really should then it suggests the architecture is broken and should be reworked.

**Comment by JonathanStarup** [comment]
It's fine to close, yeah - but certainly, knowing things upfront about fixpoint behavior will allow that rule to run faster. i don't think that means that anything is broken

**Comment by magnus-madsen** [comment]
> It's fine to close, yeah - but certainly, knowing things upfront about fixpoint behavior will allow that rule to run faster. i don't think that means that anything is broken

Perhaps. But this suggests the old approach -- with more distinct phases -- was better then?

**Comment by JonathanStarup** [comment]
I mean you can have both like shown here. you can have both control and avoid duplication

**Comment by magnus-madsen** [comment]
> I mean you can have both like shown here. you can have both control and avoid duplication

Yes... But my point was that the other implementation was even more fine-grained about how it applied the substitution. You could support that by adding even more Boolean flags, but at some point it becomes unwieldy.

**Comment by JonathanStarup** [comment]
at some point everything becomes unwieldy. I think its possible not to have duplicated fixpoints with individual bugs and unclear differences

**Pull request closed without merging**
