### PR TITLE
feat: add `{DelayList, MutList}.shuffle`

### PR DESCRIPTION
**Pull request by ninaandrup**
Related to https://github.com/flix/flix/issues/3697

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Iterator- due to its nature - should not have a shuffle.

**Comment by magnus-madsen** [comment]
Otherwise looks fine.

**Comment by ninaandrup** [comment]
These are the rest of the collections, where both the collection has a `toArray` function, and `Array` has a function that converts to the specific collection. Should it close the ticket then?

**Comment by magnus-madsen** [comment]
> These are the rest of the collections, where both the collection has a `toArray` function, and `Array` has a function that converts to the specific collection. Should it close the ticket then?

What do you mean? I don't understand :)

**Pull request merged**
