### PR TITLE
fix: code generation of letrec

### LINKED ISSUE #237: Add support for let-rec
Add support for let-rec (or similar primitive) to allow the use of recursive nested functions.

For example (proposed syntax):

```
def length[a](xs: List[a]): Int = {
  def visit[a](ys: List[a], c: Int): Int = match ys with {
    case Nil => c
    case r :: rs => visit(rs, c + 1)
  };  // <----- semi colon required
  visit(xs, 0)
}
```

(The outer block expression is just for readability.)

This ticket needs to address two issues:

(1) The syntax for nested functions.
(2) The compilation to letrec and/or interactions with lambda lifting.

### PR DESCRIPTION
**Pull request by JonathanStarup**
fixes #237

### CODE REVIEW

**Comment by JonathanStarup** [comment]
waiting for #2775

**Comment by magnus-madsen** [comment]
Merged #2775

**Comment by JonathanStarup** [comment]
Does the self-reference have a consistent index in the list of free variables? I have a problem right now that I don't know what field the self-reference is in

**Comment by JonathanStarup** [comment]
progress in #2783

**Pull request closed without merging**
