### PR TITLE
refactor: change rem and mod to functions (issue #5338)

### PR DESCRIPTION
**Pull request by stephentetley**
__Work in Progress__ 

I think I've done most of the work to change `rem` and `mod` to functions rather than operators, unfortunately this makes a mess of the `coreLibrary` list in Flix.scala, what should we do about bringing in extra modules into `coreLibrary` ?

### CODE REVIEW

**Comment by magnus-madsen** [comment]
> I think I've done most of the work to change rem and mod to functions rather than operators, unfortunately this makes a mess of the coreLibrary list in Flix.scala, what should we do about bringing in extra modules into coreLibrary ?

Can we keep them out and just modify those tests that depend on them to use a larger version of the library?

**Comment by stephentetley** [comment]
All tests compiled with `Options.TestWithLibMin` or `DefaultOptions` are failing so that 's quite a lot.

The only "outside" function that the current coreLibrary needs is Int64.mod used by `Thread.flix` - what about either defining a local version in that module or adding an "Internal/Boot.flix" module to `coreLibrary` with `int64Mod` and then both `Thread.flix` and `Int64.flix` can reference that?

By convention only standard lib code should use "Internal/Boot.flix" functions directly.

**Comment by magnus-madsen** [comment]
> The only "outside" function that the current coreLibrary needs is Int64.mod used by Thread.flix - what about either defining a local version in that module or adding an "Internal/Boot.flix" module to coreLibrary with int64Mod and then both Thread.flix and Int64.flix can reference that?

I think we can just use the intrinsic there. $INT64_MOD` or whatever.

**Comment by stephentetley** [comment]
I've changed the nanosecond calculation in `Thread.flix` to this - I hope its right due to the `>0` guard.

> let ns: Int32 = if (nsTotal > 0i64) intValue(valueOf($INT64_REM$(nsTotal, 1_000_000i64))) else 0;

I think the code should now be ready for review...

As far as I could tell, the `mod` and `rem` operators were pretty "shallow" within the compiler code and only appeared in `Parser.scala` and `Weeder.scala` where they have been eliminated.

The `mod` and `rem` operator tests originally in `Test.Exp.Binary.Arithmetic.flix` have been transplanted into the respective `TestIntX.flix` modules. Generally I've quotes to use the function versions of `mod` and `rem` as infix. Occasionally in functions like `logicalRightShift` I've used them with normal function application as they were in expressions with other infix operations.

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
