### PR TITLE
fix: copy closure objects before invocation

### LINKED ISSUE #2741: closures have thread-safety issues
When a closure is transported and used on different threads, they all operate on the same set of argument- and result fields. To fix this we need to ensure unique objects for each thread. My solution:

* Add a `fetchFunctionObject(): Fni$...` function that conservatively could make a new dublicate of `this` for each call (the current behaviour is to always return `this`).
* The call protocal work like usual, except you need to call this function on your closure object and work on the closure returned from the function. ( we can later optimzie the object allocation, maybe store a thread ID of the closure creater/last dublicator)

### PR DESCRIPTION
**Pull request by JonathanStarup**
every closure call invokes `getUniqueThreadClosure` and operates on that. An abstract class between specific closure classes and the abstract function class is added that declares this method abstractly (fixes #2741).

### CODE REVIEW

**Comment by JonathanStarup** [comment]
[This program](https://github.com/flix/flix/issues/2336#issuecomment-980541504) returns `Nil`

**Comment by JonathanStarup** [comment]
The new generated classes:
```
public final class Clo%println%121804 extends Clo1%Obj%Obj {
    public Object clo0;

    public final Cont%Obj invoke() {
        Object var1 = this.clo0;
        Object var2 = this.arg0;
        ((PrintStream)((PrintStream)var1)).println((String)((String)var2));
        this.result = Unit.INSTANCE;
        return null;
    }

    public Clo1%Obj%Obj getUniqueThreadClosure() {
        Clo%println%121804 var10000 = new Clo%println%121804();
        var10000.clo0 = this.clo0;
        return var10000;
    }

    public Clo_println_121804/* $FF was: Clo%println%121804*/() {
    }
}
```
```
public abstract class Clo1%Obj%Obj extends Fn1%Obj%Obj {
    public Clo1_Obj_Obj/* $FF was: Clo1%Obj%Obj*/() {
    }

    public abstract Clo1%Obj%Obj getUniqueThreadClosure();
}
```

**Comment by JonathanStarup** [comment]
Small benchmarks
benchmark |Master | PR
--- | --- | ---
JvmBackend phase | ? | 1018,8 ms (27,2%)

**Comment by magnus-madsen** [comment]
Its not so much the compiler throughput, but the actual benchmark running times.

**Comment by magnus-madsen** [comment]
Does the benchmark with `parMap` run?

**Comment by JonathanStarup** [comment]
> Does the benchmark with `parMap` run?

which one?

**Comment by magnus-madsen** [comment]
> > Does the benchmark with `parMap` run?
> 
> which one?

See https://github.com/flix/flix/issues/2336

**Comment by JonathanStarup** [comment]
> [This program](https://github.com/flix/flix/issues/2336#issuecomment-980541504) returns `Nil`

Yes, it's supposed to return Nil right?

**Comment by JonathanStarup** [comment]
Branch | benchmark01 | benchmark02 | benchmark03 | benchmark04 | benchmark05 | benchmark06 | benchmark07 | benchmark08 | benchmark09 | benchmark10 | benchmark11 | benchmark12 | benchmark13 | benchmark14 | benchmark15 | benchmark16 | benchmark17 | benchmark18
:--- | ---: | ---: | -- | ---: | ---: | ---: | ---: | ---:| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---:
Master | 17.640 ns. | 31.697 ns. | 22.138 ns. | 31.184 ns. | 37.739 ns. | 65.333 ns. | 48.628 ns. | 20.833 ns. | 29.707 ns. | 39.850 ns. | 65.349 ns. | 86.099 ns. | 27.976 ns. | 26.784 ns. | 61.112 ns. | 95.296 ns. | 22.727 ns. | 43.720 ns.
PR | 21.579 ns. | 32.767 ns. | 24.016 ns. | 35.284 ns. | 38.921 ns. | 72.073 ns. | 48.804 ns. | 26.182 ns. | 38.971 ns. | 43.577 ns. | 70.283 ns. | 95.579 ns. | 29.460 ns. | 24.371 ns. | 62.138 ns. | 115.304 ns. | 26.982 ns. | 46.703 ns.

**Comment by magnus-madsen** [comment]
Appears to work! 👍

**Pull request merged**
