### PR TITLE
feat: add `NewObject` completion

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes https://github.com/flix/flix/issues/6326

### CODE REVIEW

**Comment by jaschdoc** [comment]
Was testing out the completers and got an error from the program below (which is not a valid program but I was midway through typing it).

```scala
pub def main(): Unit \ IO =
    println("The sum from 0..42 is")


pub def f(x: Option[a]): Option[a] = match
```


```
#
# An unexpected error has been detected by the Flix compiler:
#
#   head of empty list
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : 0.46.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 21.0.1 (2023-10-17)
# JVM Vendor   : GraalVM Community
# JAVA_HOME    : /home/_/.sdkman/candidates/java/21.0.1-graalce
# System       : Linux
#
# -- Stack Trace --
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:662)
	at scala.collection.immutable.Nil$.head(List.scala:661)
	at ca.uwaterloo.flix.language.phase.TypeReconstruction$.visitExp(TypeReconstruction.scala:195)
	at ca.uwaterloo.flix.language.phase.TypeReconstruction$.visitDef(TypeReconstruction.scala:35)
	at ca.uwaterloo.flix.language.phase.Typer$.$anonfun$visitDef$1(Typer.scala:179)
	at ca.uwaterloo.flix.util.Validation$.mapN(Validation.scala:429)
	at ca.uwaterloo.flix.language.phase.Typer$.visitDef(Typer.scala:178)
	at ca.uwaterloo.flix.language.phase.Typer$.$anonfun$visitDefs$2(Typer.scala:162)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parTraverseValues$1(ParOps.scala:106)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMap$2(ParOps.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by magnus-madsen** [comment]
Thanks-- can you open a ticket for the bug?

**Comment by magnus-madsen** [comment]
For the completer, it should fill in all methods you have to implement.

**Comment by magnus-madsen** [comment]
For example, if you write `new java.util.Comparator` then it should fill in the `compare` method you have to implement.

**Comment by jaschdoc** [comment]
> For example, if you write `new java.util.Comparator` then it should fill in the `compare` method you have to implement.

Thanks! Working on it :smile: :runner: :hammer:
Just had to figure out what I was doing and what the goal was hehe

**Comment by magnus-madsen** [comment]
Goal is like Intellij IDEA when you get it to fill out everything you have to implement. So a bit like `InstanceCompleter`.

**Comment by jaschdoc** [comment]
Hmm it's kind of awkward to do completions as the new parser fails when writing `new ##java.lang.Runnable` or just `new java.lang.Runnable` so it seems the completion is not even run? I'm not sure if the parser has anything to do with the LSP side of things, though.

**Comment by magnus-madsen** [comment]
> Hmm it's kind of awkward to do completions as the new parser fails when writing `new ##java.lang.Runnable` or just `new java.lang.Runnable` so it seems the completion is not even run? I'm not sure if the parser has anything to do with the LSP side of things, though.

You can disable the new parser if you need to then we can look into when you have something.

**Comment by jaschdoc** [comment]
Ok I think this is blocked...
When writing `import java.lang.Comparable` the compiler succeeds with parsing so the `ImportCompleter` is fired. However, when writing `new java.lang.Comparable` it fails parsing after `new` until a word followed by `{}` is encountered. The weird thing is that it follows the same syntax / structure as `match exp { }` but I can't reproduce the behavior of the `MatchCompleter` either (i.e., matching the regex).
I'm clueless at this point. Maybe @sockmaster27 knows what's up?

**Comment by magnus-madsen** [comment]
What if you write `new new java.lang.R` then you should be able to select runnable and have everything filled out

**Comment by jaschdoc** [comment]
> What if you write `new new java.lang.R` then you should be able to select runnable and have everything filled out

Doesn't work

**Comment by magnus-madsen** [comment]
Are you trying in an expression context?

**Comment by magnus-madsen** [comment]
I guess we should remember it is now called `java_new`

**Comment by jaschdoc** [comment]
> I guess we should remember it is now called `java_new`

Good point.

**Comment by jaschdoc** [comment]
> Are you trying in an expression context?

The term that comes after `new` is a `Type` not `Exp`.

**Comment by jaschdoc** [comment]
I think I'm starting to narrow down how it works. So on the design side of things, do we want it to work like `ImportNewCompleter` where it fetches next package prefix and finally lists the classes / types in the package and then finally fills out the required functions (this is difficult)? Or do we only want to look at imported classes / interfaces (which is much easier to do at the moment)?

**Comment by jaschdoc** [comment]
Ok, the core sort of works now. It finds the abstract classes and interfaces in the package we typed. However, I have no idea why no vscode suggestions appear...

**Comment by magnus-madsen** [comment]
A few screenshots of different completions?

**Comment by mlutze** [comment]
> Ok this is close to done. The only thing I'm not sure how to approach is that `formatType` doesn't prepend `##` to native types. This means that `NewObjectCompleter` has to do it manually. However, Arrays pose a bit of a challenge, since we want `formatType` to format these but also add `##` if the type argument is a native class. E.g., `Array[Array[java.lang.Object]]` should be `Array[Array[##java.lang.Object]]` (not adding regions). Maybe @mlutze has a suggestion for a fix?

I think our best option is probably to make a new formatter for generated code. We might be able to use the SimpleType interface.

**Comment by jaschdoc** [comment]
> > Ok this is close to done. The only thing I'm not sure how to approach is that `formatType` doesn't prepend `##` to native types. This means that `NewObjectCompleter` has to do it manually. However, Arrays pose a bit of a challenge, since we want `formatType` to format these but also add `##` if the type argument is a native class. E.g., `Array[Array[java.lang.Object]]` should be `Array[Array[##java.lang.Object]]` (not adding regions). Maybe @mlutze has a suggestion for a fix?
> 
> I think our best option is probably to make a new formatter for generated code. We might be able to use the SimpleType interface.

Roger that. I was afraid you were going to say that hehe :D

**Comment by magnus-madsen** [comment]
Before writing a lot of code, just reuse FormatType. Perfect is the enemy of good here. We don't want yet another formatter to main.

**Comment by jaschdoc** [comment]
Screenshot from 2024-05-01 11-56-50
Screenshot from 2024-05-01 11-56-55
Screenshot from 2024-05-01 11-57-09
Screenshot from 2024-05-01 11-57-34

**Review by magnus-madsen — COMMENTED** [review]
General comments:

- We should also add support to Parser2. Maybe @herluf-ba can help?
- Add some doc comments for the helper functions.
- I don't think you need System.lineSeparator. I think \n is sufficient because it is interpreted by VSCode.

**Comment by jaschdoc** [comment]
@herluf-ba I'm not sure how to add the `NewObject` syntactic context to `Parser2`. Is this something you can help me with?

**Comment by magnus-madsen** [comment]
I think you want to mark `IllegalQualifiedNameInInvokeConstructor` in `CompletionProvider.getSyntacticContext` as `Expr.NewObject`

**Comment by jaschdoc** [comment]
Should we postpone this until the new java interop is ready?

**Comment by magnus-madsen** [comment]
> Should we postpone this until the new java interop is ready?

Its low priority, but the new expression stuff will not change much.

**Comment by jaschdoc** [comment]
Seems like this is quite hard with the new parser. I think I might need some help.
It tries to parse an `ArgumentList` after `new` but I can't figure out what the syntactic context is nor make it print any debug information at that point.

**Comment by magnus-madsen** [comment]
> Seems like this is quite hard with the new parser. I think I might need some help. It tries to parse an `ArgumentList` after `new` but I can't figure out what the syntactic context is nor make it print any debug information at that point.

Yeah, it seems tricky. We probably have to look at it together.

**Comment by jaschdoc** [comment]
- [ ] Merge
- [ ] Add syntactic context to `pick` in `Weeder2`

**Comment by magnus-madsen** [comment]
We are stuck because the parser cannot give us the information we need. We will have to revisit later.

**Pull request closed without merging**
