### PR TITLE
feat: experiment with laziness in DelayList fold

### PR DESCRIPTION
**Pull request by jaschdoc**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
A description of the idea would be nice :)

**Comment by jaschdoc** [comment]
Yes, of course. My idea is that maybe we could use reflection to check whether the function passed to `fold(left/right)` is pure and returns a delaylist. In that case we could apply the fold lazily, improving on the "maximally lazy" design

**Comment by magnus-madsen** [comment]
> Yes, of course. My idea is that maybe we could use reflection to check whether the function passed to `fold(left/right)` is pure and returns a delaylist. In that case we could apply the fold lazily, improving the "maximally lazy" design

But is the result of a fold not always eager?

**Comment by jaschdoc** [comment]
Maybe? I think I view it as a generalized `map` function when mapping back to delaylist (of course without any proof to back up this claim). I thought it would be interesting to play around with but it doesn't even compile currently :D

**Pull request closed without merging**
