### PR TITLE
Fix printing `explain` message as `Optional`

### PR DESCRIPTION
**Pull request by jaschdoc**
Fixes errors messages containing a `Some(...)` or `None` at the end of an error message.

Tested as a freshly built jar in a small flix project.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I think we should add a hard line break just before the explanation (if there is one). Just to ensure that they occur on different lines.

**Comment by jaschdoc** [comment]
Okay, some error messages have a bit of formatting with line separators already. I'll remove extraneous lines in all errors so the messages look consistent.

**Comment by magnus-madsen** [comment]
> ~Okay, some error messages have a bit of formatting with line separators already. I'll remove extraneous lines in all errors so the messages look consistent.~ Scratch that. All error messages end with newlines. Adding an additional line separator with result in messages + explanation looking like this (notice the double new lines between message and explanation):
> 
> ```
> >> Unused definition 'impFun'. The definition is never referenced.
> 
> 7 | def impFun(x: a): a & Impure = {
>         ^^^^^^
>         unused definition.
> 
> 
> Possible fixes:
> 
>   (1)  Use the definition.
>   (2)  Remove the definition.
>   (3)  Mark the definition as public.
>   (4)  Prefix the definition name with an underscore.
> ```
> 
> The question is then: Do we want double line breaks or just a single one?

OK, fair point. I was thinking that maybe we should always print something like:

```
underline("Explanation:")

Actual text here.
```

What do you think?

**Comment by jaschdoc** [comment]
Yeah that would make each part of the message more clear. However, in the situation outlined above, the explanation is more of a hint or solution rather than an explanation. Should we consider changing the phrasing then?

**Comment by magnus-madsen** [comment]
> Yeah that would make each part of the message more clear. However, in the situation outlined above, the explanation is more of a hint or solution rather than an explanation. Should we consider changing the phrasing then?

I think I would like it to say Explanation. Then I plan to revise all the error messages not to say tip, but rather to include it in some longer prose.

**Comment by jaschdoc** [comment]
Makes sense. I'll add the explanation heading :)

**Comment by magnus-madsen** [comment]
This heading also needs to happen when running Flix from main.

it is a bit of a mess that it has to happen in three places. But maybe that is just the way it is.

**Comment by jaschdoc** [comment]
I think we should merge this, and I'll fix this in #2700

**Pull request merged**
