### PR TITLE
fix: remove redundancy in substitution

### LINKED ISSUE #6005: Drop `++` in `@@` in Substitution?
Can we do it?

### PR DESCRIPTION
**Pull request by mlutze**
fixes #6005

### CODE REVIEW

**Comment by mlutze** [comment]
Note: this may have an effect on BU evaluation.

**Comment by mlutze** [comment]
If the test runner performance is to be trusted, then this seems to have a substantial performance impact. 12:30 vs (13-14 mins)

**Comment by magnus-madsen** [comment]
Could we check that the substitution is structurally equal?

**Comment by magnus-madsen** [comment]
For all our test cases

**Comment by mlutze** [comment]
Assertions show that the substitutions are always structurally the same.

**Pull request merged**
