### PR TITLE
feat: ignore recursive calls when checking for uses of definitions

### PR DESCRIPTION
**Pull request by mlutze**
Fixes https://github.com/flix/flix/issues/3255

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Can I get a TLDR for the changes?

**Comment by mlutze** [comment]
I introduce a `RecursionContext` which stores the DefSym/SigSym of the function that we're in. Local functions desugar to LetRec, so when that happens, I also store the VarSym bound in the LetRec. Since LetRecs can be nested, I store multiple VarSyms in a set.

When I run into a use of a symbol that is in the RecursionContext, I do **not** record it as a use, because it is a recursive call.

**Comment by magnus-madsen** [comment]
Dang, I was hesitant, and now there are conflicts. 

In general, how much code/complexity in the compiler do we want to spend on corner cases like this?

**Comment by mlutze** [comment]
What percentage of functions are recursive? It seems to me that we'd leave a fairly large hole in the dead code check if we don't include this kind of thing.

**Comment by magnus-madsen** [comment]
OK, I am convinced. Lets merge it.

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
