### PR TITLE
docs: effect examples

### PR DESCRIPTION
**Pull request by JonathanStarup**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Note: There is an issue where subfolders in the example folder are not compiled nor tested.

**Comment by magnus-madsen** [comment]
@JonathanStarup Do you want to wrap these up and we can merge them? Then I can ask @jaschdoc to port more examples.

**Comment by magnus-madsen** [comment]
@JonathanStarup The scheduler example gives me ClassCastException.

**Comment by magnus-madsen** [comment]
> removed the failing example

But why? It is a nice example. Can it not be made to work?

**Comment by JonathanStarup** [comment]
I just wanted to debug it while these could be merged. also i cant reference the source

**Comment by magnus-madsen** [comment]
> I just wanted to debug it while these could be merged. also i cant reference the source

OK, so you are looking into it?

**Comment by magnus-madsen** [comment]
Did you want to extend `ExampleSuite.scala` so these are actually compiled?

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
