### PR TITLE
chore: improve performance of `ParOps.mapValues`

### PR DESCRIPTION
**Pull request by sockmaster27**
Related to #2974

### CODE REVIEW

**Comment by sockmaster27** [comment]
This is just here to document this failed experiment. 

With the changes introduced to the Lowering phase in #6512, this change increases time spent in this phase from ~100ms to ~230ms :(

I'm guessing this is caused by the many conversions which are done internally anyway: immutable map -> iterator -> parallel map -> mutable map -> iterator -> immutable map.

**Comment by magnus-madsen** [comment]
Indeed. Also this does not respect `--threads` nor the threadpool we use.

**Comment by sockmaster27** [comment]
> Indeed. Also this does not respect `--threads` nor the threadpool we use.

Really? What makes it different from `parMap`?

**Comment by sockmaster27** [comment]
> > Indeed. Also this does not respect `--threads` nor the threadpool we use.
> 
> Really? What makes it different from `parMap`?

@magnus-madsen ?

**Pull request closed without merging**
