### PR TITLE
Rename `LazyList` to `DelayList`

### LINKED ISSUE #3200: Rename `LazyList` to `DelayList`

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes #3200 

There's a TODO note in `Bench.Fusion.flix`. Should this be removed?

### CODE REVIEW

**Comment by magnus-madsen** [comment]
What to do is this?

**Comment by jaschdoc** [comment]
> What to do is this?

https://github.com/flix/flix/blob/14ca3a8c87b17b256787cbd39376c7ce61c21f5c/main/src/library/Benchmark/Bench.Fusion.flix#L288

And also

https://github.com/flix/flix/blob/14ca3a8c87b17b256787cbd39376c7ce61c21f5c/main/src/library/Benchmark/Bench.Fusion.flix#L393

**Comment by magnus-madsen** [comment]
Nothing.  I don't think those benchmarks are used.

**Comment by jaschdoc** [comment]
So should we just remove these benchmarks, or should we wait to pull the trigger?

**Comment by magnus-madsen** [comment]
Let's wait

**Pull request merged**
