### PR TITLE
feat: add fallback text to type variables

### PR DESCRIPTION
**Pull request by mlutze**
related to #3481

### CODE REVIEW

**Comment by mlutze** [comment]
@magnus-madsen Before I go too far, is this approximately what you were thinking?

**Comment by magnus-madsen** [comment]
Yes, but how about (1) we focus on Typer in this PR (leaving other phases for later) and (2) maybe we just import `FallBack` text directly? Or perhaps even better change the signature of freshTypeVar/add a new variant?

**Comment by magnus-madsen** [comment]
Maybe names should also not be overly specific. Perhaps complete a few more and we can synch

**Comment by magnus-madsen** [comment]
I think this seems reasonable. How about you add the rest and then we can always discuss them. :)

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
