### PR TITLE
experiment: use `VirtualThread`s for `parMap`

### PR DESCRIPTION
**Pull request by magnus-madsen**
Performance before:

```
====================== Flix Compiler Throughput ======================

Throughput (best): 33.902 lines/sec (with 24 threads.)

  min:  7.255, max: 33.902, avg: 28.358, median: 31.888

  The highest throughput was in iteration: 8 (out of 10).
  The ratio between the best and worst iteration was: 4,7x.

Finished 10 iterations on 65.953 lines of code in 28 seconds.
```

Performance after:

```
====================== Flix Compiler Throughput ======================

Throughput (best): 35.641 lines/sec (with 24 threads.)

  min:  7.418, max: 35.641, avg: 29.879, median: 34.401

  The highest throughput was in iteration: 9 (out of 10).
  The ratio between the best and worst iteration was: 4,8x.

Finished 10 iterations on 65.953 lines of code in 27 seconds.
```

### CODE REVIEW

**Comment by magnus-madsen** [comment]
!!!jar

**Comment by magnus-madsen** [comment]
Just for fun, could one of you: @mlutze , @JonathanStarup, @jaschdoc, @sockmaster27 see if they can reproduce the speedup using `--Xbenchmark-phases`

**Comment by jaschdoc** [comment]
On it

**Comment by jaschdoc** [comment]
Using `--Xbenchmark-phases` (you used `--Xbenchmark-throughput`?)

Before (master)

```
====================== Flix Compiler Phases ======================

Mean runtime per phase (low to high):
  EntryPoint                       0.0 ms (00.0%)
  Deriver                          2.6 ms (00.0%)
  Tailrec                          9.8 ms (00.2%)
  VarNumbering                    15.4 ms (00.2%)
  Reducer                         25.5 ms (00.4%)
  Safety                          26.1 ms (00.4%)
  Reader                          26.5 ms (00.4%)
  LambdaLift                      37.0 ms (00.6%)
  PatternExhaustiveness           39.6 ms (00.6%)
  Stratifier                      43.7 ms (00.7%)
  EarlyTreeShaker                 45.8 ms (00.7%)
  LateTreeShaker                  74.2 ms (01.1%)
  Simplifier                      81.3 ms (01.3%)
  ClosureConv                     89.9 ms (01.4%)
  Lowering                        96.2 ms (01.5%)
  Kinder                         105.2 ms (01.6%)
  Lexer                          136.9 ms (02.1%)
  Namer                          145.8 ms (02.3%)
  Redundancy                     150.1 ms (02.3%)
  MonomorphEnums                 151.0 ms (02.3%)
  Weeder                         161.2 ms (02.5%)
  Instances                      192.6 ms (03.0%)
  Optimizer                      294.6 ms (04.6%)
  Resolver                       315.7 ms (04.9%)
  Parser                         460.7 ms (07.1%)
  Monomorph                      640.1 ms (09.9%)
  JvmBackend                     880.3 ms (13.6%)
  Typer                          2225.7 ms (34.4%)

Finished 10 iterations on 65,953 lines of code in 55 seconds.
```

After (virtual threads)

```
====================== Flix Compiler Phases ======================

Mean runtime per phase (low to high):
  EntryPoint                       0.0 ms (00.0%)
  Deriver                          2.6 ms (00.0%)
  Tailrec                         11.0 ms (00.2%)
  Reader                          25.4 ms (00.4%)
  Safety                          27.4 ms (00.4%)
  VarNumbering                    32.3 ms (00.5%)
  LambdaLift                      32.9 ms (00.5%)
  Reducer                         40.1 ms (00.6%)
  EarlyTreeShaker                 42.4 ms (00.7%)
  PatternExhaustiveness           46.0 ms (00.7%)
  Stratifier                      49.2 ms (00.8%)
  ClosureConv                     63.7 ms (01.0%)
  LateTreeShaker                  81.4 ms (01.3%)
  Lowering                       101.8 ms (01.6%)
  Lexer                          102.0 ms (01.6%)
  Simplifier                     108.8 ms (01.7%)
  Kinder                         115.3 ms (01.8%)
  Redundancy                     145.5 ms (02.2%)
  MonomorphEnums                 147.8 ms (02.3%)
  Namer                          159.1 ms (02.4%)
  Weeder                         182.9 ms (02.8%)
  Instances                      211.8 ms (03.3%)
  Optimizer                      291.1 ms (04.5%)
  Resolver                       314.1 ms (04.8%)
  Parser                         502.7 ms (07.7%)
  Monomorph                      593.3 ms (09.1%)
  JvmBackend                     874.2 ms (13.4%)
  Typer                          2201.2 ms (33.8%)

Finished 10 iterations on 65,953 lines of code in 56 seconds.
```

**Comment by magnus-madsen** [comment]
Oops. I meant --Xbenchmark-throughput. Can you update your comment?

**Comment by jaschdoc** [comment]
Before (master)

```
====================== Flix Compiler Throughput ======================

Throughput (best): 16,118 lines/sec (with 8 threads.)

  min:  5,115, max: 16,118, avg: 13,769, median: 15,688

  The highest throughput was in iteration: 6 (out of 10).
  The ratio between the best and worst iteration was: 3.2x.

Finished 10 iterations on 65,953 lines of code in 54 seconds.
```

After (virtual threads)

```
====================== Flix Compiler Throughput ======================

Throughput (best): 16,322 lines/sec (with 8 threads.)

  min:  5,139, max: 16,322, avg: 13,403, median: 14,664

  The highest throughput was in iteration: 7 (out of 10).
  The ratio between the best and worst iteration was: 3.2x.

Finished 10 iterations on 65,953 lines of code in 55 seconds.
```

**Pull request closed without merging**
