### PR TITLE
Add `DelayMap.{insertWith, insertWithKey}`

### PR DESCRIPTION
**Pull request by jaschdoc**
Related to #2534 phase 2

- [x] Add implementation
- [x] Add tests

### CODE REVIEW

**Comment by jaschdoc** [comment]
This currently produces the type error
```
>> The type scheme: '∀(k, v). k -> v -> v -> v -> k -> v -> DelayMap[k, v] -> DelayMap[k, v]' cannot be generalized to '∀(k, v, ef). k -> v -> v -> v & ef -> k -> v -> DelayMap[k, v] -> DelayMap[k, v] & ef'.

77 |     pub def insertWithKey(f: (k, v, v) -> v & ef, k: k, v: v, m: DelayMap[k, v]): DelayMap[k, v] & ef with Order[k] =
                 ^^^^^^^^^^^^^
                 unable to generalize the type scheme.


  Declared: ∀(k, v, ef). k -> v -> v -> v & ef -> k -> v -> DelayMap[k, v] -> DelayMap[k, v] & ef
  Inferred: ∀(k, v). k -> v -> v -> v -> k -> v -> DelayMap[k, v] -> DelayMap[k, v]
```
I've been arguing with the compiler and trying to insert effect type casts everywhere but the type inference insists. Not quite sure what's wrong here.

**Comment by magnus-madsen** [comment]
I am taking a look.

**Comment by magnus-madsen** [comment]
```
    pub def insertWithKey(f: (k, v, v) -> v & ef, k: k, v: v, m: DelayMap[k, v]): DelayMap[k, v] & ef with Order[k] =
        let DMap(t) = m;
        if (reify ef)
            let f1 = (k1, v2, v1) -> lazy (f(k1, force v2, force v1) as & Pure);
            DMap(RedBlackTree.insertWith(f1, k, lazy v, t))
        else
            let f1 = (k1, v2, v1) -> {
                let x = f(k1, force v2, force v1);
                lazy x
            };
            DMap(RedBlackTree.insertWith(f1, k, lazy v, t))
```

If you ever write `lazy e` then `e` must be pure. (In this case it is, but the type system does not know yet, so you can safely cast it).

**Comment by magnus-madsen** [comment]
Is it correct that `v2` and `v1` are swapped?

**Comment by jaschdoc** [comment]
> Is it correct that `v2` and `v1` are swapped?

Yeah it's a bit messy, but the documentation is
    ///
    /// Updates `m` with `k -> f(k, v, v1)` if `k -> v1` is in `m`.
    ///
    /// Otherwise, updates `m` with `k -> v`.
    ///
so I wanted to let `v1` always have the same position in the argument list.

**Pull request merged**
