### PR TITLE
Type classes 3 retry

### PR DESCRIPTION
**Pull request by mlutze**
In case the other PR doesn't work, maybe this one will?

### CODE REVIEW

**Comment by magnus-madsen** [comment]
It is simply not showing up here: https://github.com/flix/flix/actions

No idea why :(

**Comment by magnus-madsen** [comment]
It is like it is still using travis

**Comment by magnus-madsen** [comment]
Oh, not it is unstuck.

**Comment by magnus-madsen** [comment]
Just okay any PR and I will merge it.

**Comment by mlutze** [comment]
I'll okay this one since I just rebased and pushed it. Thanks!

**Pull request closed without merging**
