### PR TITLE
refactor: generic `CofiniteSet`

### PR DESCRIPTION
**Pull request by JonathanStarup**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Why does it need to be generic?

**Comment by magnus-madsen** [comment]
YAGNI?

**Comment by JonathanStarup** [comment]
Yagni? We have both `CofiniteIntSet` and `CofiniteEffSet` which is bad for code maintenance

**Comment by magnus-madsen** [comment]
OK; then lets do it! - Add the generic one

**Pull request closed without merging**
