### PR TITLE
chore: rename foreach functions to forEach and forall functions to forAll (see #4860)

### PR DESCRIPTION
**Pull request by stephentetley**
This PR fixes the name clash between `foreach` used by the new comprehension syntax and the `foreach` iteration functions in the stdlib - the functions are now renamed to `forEach`.

The PR also fixes the clash between `forall` syntax used for laws and `forall` functions in the stdlib - the functions become `forAll`.

For consistency with `forEach`, `foreachWithIndex` functions in the stdlib are now called `forEachWithIndex`.

### CODE REVIEW

**Comment by mlutze** [comment]
@magnus-madsen I think this qualifies for the "1 migration release" idea?

**Comment by magnus-madsen** [comment]
@stephentetley 

Sorry, I sat on this for too long and now there are some conflicts. But if you resolve those we can move forward :)

**Comment by stephentetley** [comment]
Thanks Magnus, the PR should be up-to-date with the second commit.

Magnus / @mlutze - Do you want me to add compatibility stubs for migration? e.g.:

~~~                                               


    ///
    /// `foreach` is deprecated and will be removed, please change client code to use `forEach`.
    ///
    pub def foreach(f: a -> Unit \ ef, l: List[a]): Unit \ ef = foreach(f, l)
    
~~~

**Comment by magnus-madsen** [comment]
No, let's just do the rename

**Pull request merged**
