### PR TITLE
Derive examples

### PR DESCRIPTION
**Pull request by mlutze**
I may have gone a bit overkill with the implementation of the game. I was having fun.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Very cool! 😃 

I wonder if your Order instance on Card is compatible with its Eq instance?

**Comment by mlutze** [comment]
I'll get rid of the Order instance and do comparisons on the ranks.

Other than that, I was concerned that the implementation might take away focus from what we're supposed to be showcasing (the derived instances). What do you think?

**Comment by magnus-madsen** [comment]
An indent four spaces

**Comment by magnus-madsen** [comment]
I think the example is still nice.

**Pull request merged**
