### PR TITLE
refactor: add regions to `Random`

### PR DESCRIPTION
**Pull request by JonathanStarup**
Also added shuffles definitions which might not belong here.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
What does it mean to have a Random in a region? 

If you have a Random in a region does it always give the same result?

**Comment by magnus-madsen** [comment]
To follow-up; when is shuffling pure?

**Comment by JonathanStarup** [comment]
My idea was that a seeded Random would be deterministic which would then be pure inside its region. This is only true when the call order is the same for each run.  I believe this is also okay maybe this doesn't work for nested regions of random using eachother to branch and cause different calls

**Comment by magnus-madsen** [comment]
Its hard for me to see how this can work. Randomness is by its nature an example of impurity-- a function that does not return the same result. I think, down the road, it could be an algebraic effect with an appropriate handler.

**Pull request closed without merging**
