### PR TITLE
chore: tidy up some closure-related cruft

### LINKED ISSUE #4313: chore: closure tidyup
As per discussion with @magnus-madsen, remove unused `freeVars` member of `SimplifiedAst.Expression.Closure` and `tpe` argument to `getClosureClassType`.

### PR DESCRIPTION
**Pull request by paulbutcher**
Fixes #4313

### CODE REVIEW

**Comment by paulbutcher** [comment]
@magnus-madsen, this didn't allow me to get rid of `getFunctionTypeTemporaryToBeRemoved` as I hoped, as it is used elsewhere.

In fact, the more I look at it, the more I'm unsure why we think this can be removed? Don't we need something that encodes the argument and return types of the closure?

**Comment by magnus-madsen** [comment]
> @magnus-madsen, this didn't allow me to get rid of `getFunctionTypeTemporaryToBeRemoved` as I hoped, as it is used elsewhere.
> 
> In fact, the more I look at it, the more I'm unsure why we think this can be removed? Don't we need something that encodes the argument and return types of the closure?

I don't recall, but the name suggests there is a 'structural' issue with that function.

**Comment by paulbutcher** [comment]
So after some more code spelunking, I think we can get rid of it and replace it with something that encodes just the return type of the closure. The argument types are encoded within the `closureArgs` member of `Expression.Closure`?

**Comment by paulbutcher** [comment]
But we couldn't get rid of it entirely.

**Comment by magnus-madsen** [comment]
I think the concern with the function is indeed the duplication of information; there should be one source of ground truth. Thus your proposal makes sense, but lets do it in yet another PR :)

**Comment by paulbutcher** [comment]
> lets do it in yet another PR

👍

**Comment by paulbutcher** [comment]
Actually, this turns out to be much easier than I thought: there is already a `tpe` member in `Expression.Closure`. I have another PR ready to roll as soon as this one is merged.

**Comment by magnus-madsen** [comment]
Ill merge this one and then I have to leave the PC :)

**Pull request merged**
