### PR TITLE
chore: use consistent icons in HTML documentation

### PR DESCRIPTION
**Pull request by sockmaster27**
This replaces the hacky unicode character icons with the equivalent from Google's Material Symbols icon set. This makes the generated pages look subtly more professional, and ensures consistency between devices.

Before:
image

After:
image

Note that the light/dark-mode icons have now been swapped, as this seems to be more conventional.
This PR also introduces use of the `:has()` CSS selector, which has recently gained [wider support](https://caniuse.com/css-has), which happens to eliminate the need for some of the JS.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Thanks-- this is more professional indeed. A few questions:

1. Do we need to have a license file somewhere or how does it work?
2. Do the icons work well on mobile too?

**Comment by sockmaster27** [comment]
> 1. Do we need to have a license file somewhere or how does it work?

It's Apache 2.0, but since it's kind of a font, I'm not entirely sure. For the generated website, it shouldn't be necessary, but we might want to include it for the compiler itself to be safe. Do we have some established way of doing this beyond just including it in the source code?

> 2. Do the icons work well on mobile too?

Yes.

**Comment by magnus-madsen** [comment]
How about putting the license file in the icons folder?

**Comment by sockmaster27** [comment]
Can this be merged or should it be discussed further?

**Comment by magnus-madsen** [comment]
We can merge this, but make the following changes:

- Drop LICENSE
- Add LICENSE.md with the following text:

The following files in this directory:

- foo
- bar

are part of the XYZ project and licensed under the Apache 2.0 license. See:

url to project

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
