### PR TITLE
refactor: move exps to `ErasedAst.IntrinsicOperator3`

### PR DESCRIPTION
**Pull request by jaschdoc**
Related to https://github.com/flix/flix/issues/5434

### CODE REVIEW

**Comment by jaschdoc** [comment]
@magnus-madsen RFM, just failing community build with usual pipeline problem

**Comment by magnus-madsen** [comment]
Yeah. I am just not sure about ite which is why I have been holding of.

**Comment by jaschdoc** [comment]
Still undecided on this?

**Comment by magnus-madsen** [comment]
No. We leave ite because its a control operator.

**Pull request closed without merging**
