### PR TITLE
feat: `let*` to use `Monad.flatMap`.

### PR DESCRIPTION
**Pull request by magnus-madsen**

### CODE REVIEW

**Comment by mlutze** [comment]
Note that this breaks a lot of stuff since `Result` is not currently a monad.

**Comment by magnus-madsen** [comment]
> Note that this breaks a lot of stuff since `Result` is not currently a monad.

Hmm. That is true.

**Comment by magnus-madsen** [comment]
But the fix is to support Result as a Monad *and* to reverse its arguments (breaking even more code) right?

**Comment by mlutze** [comment]
> But the fix is to support Result as a Monad _and_ to reverse its arguments (breaking even more code) right?

True, but that change can be largely automated, whereas it's much more of a pain to turn all my  `let*` into properly nested `flatMaps`, only to be changed back once we do the parameter switch

**Comment by mlutze** [comment]
That said, I am okay just holding on to the nightly I'm using for now :)

**Comment by magnus-madsen** [comment]
Reverted. We need to resolve the other issue(s) first.

**Pull request merged**
