### PR TITLE
feat: lsp completions for ```import (static) ... ```

### PR DESCRIPTION
**Pull request by Daniel-Anker-Hermansen**
related to #4554 
image
image
image
image

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Thanks!

**Comment by magnus-madsen** [comment]
@Daniel-Anker-Hermansen There is a bug where the "this" object should be the first argument.

For example:

This is obviously wrong:

```
import java.lang.String.toUpperCase(): String \ IO;
```

You cannot call toUpperCase with an object. It should be

```
import java.lang.String.toUpperCase(String): String \ IO;
```

**Comment by Daniel-Anker-Hermansen** [comment]
@magnus-madsen
```
pub def foo(): Unit \ IO =
    import java.lang.String.toUpperCase(): String \ IO;
    "Hello, world!" |> toUpperCase |> println
```
compiles, runs and produces the expected result while
```
pub def foo(): Unit \ IO =
    import java.lang.String.toUpperCase(String): String \ IO;
    "Hello, world!" |> toUpperCase |> println
```
does not compile.
If the receiver this is supposed to be typed explicitly this too is a bug in the compiler.

**Comment by magnus-madsen** [comment]
Ah right! I don't even understand my own language! 😛

**Pull request merged**
