### PR TITLE
Update function signatures in String to use labelled arguments

### PR DESCRIPTION
**Pull request by ninaandrup**
#2257

Todo:
- [x] startsWith
- [x] endsWith
- [x] contains
- [x] splitOn
- [x] split
- [x] isMatch
- [x] isSubmatch
- [x] indices
- [x] replace
- [x] replaceMatches
- [x]  replaceFirstMatch
- [x]  indexOf (+ indexOfLeft + indexOfRight)
- [x]  indexOfLeftWithOffset + indexOfRightWithOffset
- [x]  breakOnLeft + breakOnRight
- [x]  countSubstring
- [x]  stripPrefix +  stripSuffix

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Thanks! I will take a look soon. Meanwhile, could I ask you to browse through `String.flix` to see if there are any other functions that take two strings where one could be confused about which string is which and where it would be useful to use labelled/record arguments. Just compile a small list and paste it here. Then we can discuss each! :)

**Comment by mlutze** [comment]
> `patch`

Took me a while to understand what this function even does. IMO a named param for this one could be useful.

**Comment by magnus-madsen** [comment]
> 
> 
> > `patch`
> 
> Took me a while to understand what this function even does. IMO a named param for this one could be useful.

Do you have a suggestion?

**Comment by mlutze** [comment]
If we're using `to` for other substitutions, that might be ok. Though since we're lacking a `from` in this case, maybe it's not so good?

**Comment by magnus-madsen** [comment]
Merged! Congratulations on landing the first real PR :)

**Comment by magnus-madsen** [comment]
@stephentetley This may cause breakages. The rationale is here: https://github.com/flix/flix/issues/2257

But at least its better than silently changing the semantics :)

**Comment by magnus-madsen** [comment]
@stephentetley I am glad you like it. Here is a free tip: You can write `foo(abc = ...)` as sugar for `foo({abc = ...})`. Thanks to #2345

**Pull request merged**
