### PR TITLE
Add intrinsics and type classes for Add, Sub and Div

### PR DESCRIPTION
**Pull request by esbenbjerre**
#1586

### CODE REVIEW

**Comment by esbenbjerre** [comment]
Hmm. Lots of tests failing due to missing standard library. Should I close my eyes and add `(Options.TestWithLibrary)` to them all or does this force us to consider #1590?

**Comment by magnus-madsen** [comment]
> 
> 
> Hmm. Lots of tests failing due to missing standard library. Should I close my eyes and add `(Options.TestWithLibrary)` to them all or does this force us to consider #1590?

Yes

**Comment by esbenbjerre** [comment]
> > Hmm. Lots of tests failing due to missing standard library. Should I close my eyes and add `(Options.TestWithLibrary)` to them all or does this force us to consider #1590?
> 
> Yes

The former, the latter or the infamous "yes to both"?

**Comment by magnus-madsen** [comment]
Oh sorry. Add Options.TestWithLibrary for now.

**Comment by esbenbjerre** [comment]
Hmm. Not I have errors in `TestRedundancy` and `TestTyper`. I'm not sure what should be done here.
```
- ShadowedVar.Lambda.01 *** FAILED ***
3859
  Expected an error of type ShadowedVar, but found class ca.uwaterloo.flix.language.errors.ResolutionError$UndefinedName. (TestUtils.scala:46)
```

**Comment by magnus-madsen** [comment]
> 
> 
> Hmm. Now I have errors in `TestRedundancy` and `TestTyper`. I'm not sure what should be done here.
> 
> ```
> - ShadowedVar.Lambda.01 *** FAILED ***
> 3859
>   Expected an error of type ShadowedVar, but found class ca.uwaterloo.flix.language.errors.ResolutionError$UndefinedName. (TestUtils.scala:46)
> ```

They probably use + or so, so open the Scala classes and modify the tests.

**Comment by magnus-madsen** [comment]
Excellent!

**Pull request merged**
