### PR TITLE
feat: add `ForEach` type class

### LINKED ISSUE #3899: Add `ForEach` type class
Add a type class:

```
///
/// A type class for data structures whose elements can be visited from left to right.
///
pub class ForEach[t : Type -> Type] {
    ///
    /// Applies `f` to each element in `t`.
    ///
    pub def foreach(f: a -> Unit & ef, t: t[a]): Unit & ef
}
```

- [ ] Add the above type class.
- [ ] Make `Foldable` extend `ForEach`.
- [ ] Add instances for all immutable data structures and add tests.

(This type class will be used as the basis for our imperative for loop).

### PR DESCRIPTION
**Pull request by ninaandrup**
Closes #3899

### CODE REVIEW

**Comment by mlutze** [comment]
> @magnus-madsen I do not understand, why it is not possible to make `Foldable` extend `ForEach`
> 
> ```
> >> Undefined class 'ForEach'.
> 
> 20 | pub class Foldable[t : Type -> Type] with ForEach[t] {
>                                                ^^^^^^^
>                                                class not found
> ```

Don't forget to add your new file to the standard library

**Comment by magnus-madsen** [comment]
@ninaandrup Seems like some tests fail.

**Comment by ninaandrup** [comment]
Seems like I forgot to push the last changes

**Comment by ninaandrup** [comment]
I need to make sure we have an instance for all immutable data structures before RFR :)

**Pull request merged**
