### PR TITLE
chore: new example png

### LINKED ISSUE #3039: update `readme.md`
The readme shows an old screenshoot without formatting

### PR DESCRIPTION
**Pull request by JonathanStarup**
Fixes #3039.

### CODE REVIEW

**Comment by mlutze** [comment]
Nitpick: `freshVar()` can't actually be `Pure`, right?

**Comment by JonathanStarup** [comment]
> Nitpick: `freshVar()` can't actually be `Pure`, right?

Yeah I though about that too but just wanted to recreate the example with the updated look. Maybe it should just be impure, or maybe more properly create a statemonad

**Comment by magnus-madsen** [comment]
I try to Google the correct width to use, but I could not find anything.

**Comment by JonathanStarup** [comment]
> Thanks for doing this!
> 
> One more nitpick-- I seem to remember carefully messing around with the resolution to ensure that it would show "correctly" on the GitHub landing page. Your image is wider, so it would be scaled.

Now its the same width as before

**Comment by magnus-madsen** [comment]
Thanks!

**Comment by magnus-madsen** [comment]
Png looks squished. I think you need to edit README.md too.

**Pull request merged**
