### PR TITLE
feat: add background color support for `Console`

### PR DESCRIPTION
**Pull request by ninaandrup**
#2853

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Overall looks good. I think the local `let isFg = true` are not necessary. But maybe you want to use a record for isFG?

Do you know if we can support underline or bold?

**Comment by ninaandrup** [comment]
> Overall looks good. I think the local `let isFg = true` are not necessary. But maybe you want to use a record for isFG?
> 
> Do you know if we can support underline or bold?

Yes, I thought about using a record instead. And I will look into supporting underline and bold, too.

**Comment by magnus-madsen** [comment]
We can do underline and bold in separate PR. "Take small steps" as Henrik would say :)

**Comment by ninaandrup** [comment]
> We can do underline and bold in separate PR. "Take small steps" as Henrik would say :)

What about the bright bg colors? We want to support that as well, right?

**Comment by magnus-madsen** [comment]
> > We can do underline and bold in separate PR. "Take small steps" as Henrik would say :)
> 
> What about the bright bg colors? We want to support that as well, right?

Yes. Next PR or the one after :)

**Comment by magnus-madsen** [comment]
Thanks and happy holidays! :)

**Comment by ninaandrup** [comment]
> Thanks and happy holidays! :)

Happy holidays to you too! :-)

**Pull request merged**
