### PR TITLE
refactor: remove `ArrayLit`

### PR DESCRIPTION
**Pull request by jaschdoc**
Related to https://github.com/flix/flix/issues/4760

### CODE REVIEW

**Comment by jaschdoc** [comment]
- [ ] Fix test type annotations and syntactic errors
- [ ] Rename FArray to ArrayLit
- [ ] Refactor `Option[Expression]` to `Expression` for the region parameter in AST-nodes

**Comment by magnus-madsen** [comment]
@jaschdoc Unfortunately `Iterator` has changed, but hopefully there is not too much to fix.

**Comment by magnus-madsen** [comment]
I will start my review.

**Comment by magnus-madsen** [comment]
I think this is ready to be merged 👍

**Pull request merged**
