### PR TITLE
refactor: use regions in `_.toArray`

### LINKED ISSUE #3610: Refactor `toMutDeque`, `toMutList`, `toMutMap`, `toMutSet` to use regions
Refactor all:

- [ ] toArray
- [ ] toMutDeque
- [ ] toMutList
- [ ] toMutMap
- [ ] toMutSet

to use regions. 

This applies both to collection namespaces and to classes. 

The region parameter should be last. (At least that's the current thinking).

### PR DESCRIPTION
**Pull request by jaschdoc**
Related to #3610
Depends on #3453

### CODE REVIEW

**Comment by jaschdoc** [comment]
Compiler hangs on current commit (4df189b) for some reason. No idea what's causing it.

**Comment by jaschdoc** [comment]
@magnus-madsen This PR is blocked due to issues with boolean unification. I've spent a couple of hours trying to decide whether there's a bug in the library code in this PR, but I can't find it. When running tests the compiler runs out of memory:
```
An exception or error caused a run to abort: Java heap space 
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:520)
	at java.base/java.lang.invoke.DirectMethodHandle$Holder.newInvokeSpecial(DirectMethodHandle$Holder)
	at java.base/java.lang.invoke.Invokers$Holder.linkToTargetMethod(Invokers$Holder)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:62)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:66)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:66)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:66)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:66)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:66)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:66)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:66)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:65)
```

**Comment by magnus-madsen** [comment]
Can we split the PR into smaller pieces and try to locate the functions that causes the problem?

**Comment by jaschdoc** [comment]
> Can we split the PR into smaller pieces and try to locate the functions that causes the problem?

The best I can give you is that it happened after refactoring `copyOfRange` but reverting that doesn't seem to solve the issue. The problem is that `List.toArray` and tests have an enormous set of dependencies. So refactoring `List.toArray` (and some other `_.toArray` functions) has cascading changes for the rest of the library.

**Comment by magnus-madsen** [comment]
> > Can we split the PR into smaller pieces and try to locate the functions that causes the problem?
> 
> The best I can give you is that it happened after refactoring `copyOfRange` but reverting that doesn't seem to solve the issue. The problem is that `List.toArray` and tests have an enormous set of dependencies. So refactoring `List.toArray` (and some other `_.toArray` functions) has cascading changes for the rest of the library.

Could you add `List.toArrayWithRegion` and then try to incrementally use that?

**Comment by jaschdoc** [comment]
> Could you add `List.toArrayWithRegion` and then try to incrementally use that?

Sure! Why hadn't I considered that option originally? :thinking:

**Comment by magnus-madsen** [comment]
> > Could you add `List.toArrayWithRegion` and then try to incrementally use that?
> 
> Sure! Why hadn't I considered that option originally? 🤔

You live, and you learn :)

**Comment by jaschdoc** [comment]
See #3733

**Pull request closed without merging**
