### PR TITLE
Abbreviate pattern match syntax

### PR DESCRIPTION
**Pull request by esbenbjerre**
Remove `with` from all uses of pattern match as per #861.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Feel free to change: https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Parser.scala#L779

Simply remove this part `optional(WS ~ atomic("with") ~ WS)`.

**Comment by esbenbjerre** [comment]
> Feel free to change: https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Parser.scala#L779
> 
> Simply remove this part `optional(WS ~ atomic("with") ~ WS)`.

Done and done. The "with" syntax is no more!

**Comment by esbenbjerre** [comment]
Hmm tests are failing. I'm looking into it.

**Comment by esbenbjerre** [comment]
Some of the tests contains code fragments as strings which my search didn't account for. I'm refactoring these now.

**Comment by magnus-madsen** [comment]
Merged, thanks! :)

**Pull request merged**
