### PR TITLE
Add Uninitialized type class

### PR DESCRIPTION
**Pull request by esbenbjerre**
Partial fix for #1561.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Thanks for implementing this. It made me realize that the `Uninitialized`  type signature can propagate quite far!

**Comment by esbenbjerre** [comment]
> Thanks for implementing this. It made me realize that the `Uninitialized`  type signature can propagate quite far! 

Yes, same ;)
Are you considering dropping it?

**Comment by magnus-madsen** [comment]
> > Thanks for implementing this. It made me realize that the `Uninitialized`  type signature can propagate quite far!
> 
> Yes, same ;)
> Are you considering dropping it?

I don't know yet. But it clearly exposes some consequences that I had not really thought of!

**Comment by esbenbjerre** [comment]
> I don't know yet. But it clearly exposes some consequences that I had not really thought of!

Yes it surprised me too.

**Comment by magnus-madsen** [comment]
We are not doing this, but the experiment was very interesting!

**Pull request closed without merging**
