### PR TITLE
feat: create missing return type error

### LINKED ISSUE #3696: Suggestion: better error message when top level definition lacks type annotations
While [this restriction is mentioned here](https://doc.flix.dev/functions/) I was quite mystified at first.

The definition

```Flix
def fib(n: Int32) = n
```

produces a syntax error saying `Invalid input ") ="`.

The definition

```Flix
def fib(n) = n
```

produces an error saying `Invalid input "n) ="`.  I think an error in the vein of "top level definitions must explicitly declare parameter and return types" would be better.

Incidentally, is there a grammar for Flix anywhere?

### PR DESCRIPTION
**Pull request by mlutze**
fixes #3696

### CODE REVIEW

**Comment by JonathanStarup** [comment]
Can this differentiate between inner defs and outer defs? I want to promote #3663 because I think we will hit problems during our improvement parsing of defs/inner defs

**Comment by magnus-madsen** [comment]
Top-level functions will always require signatures whereas for inner definitions its up to the user.

**Comment by JonathanStarup** [comment]
> Top-level functions will always require signatures whereas for inner definitions its up to the user.

But this still means that inner definitions can look identical to toplevel ones. Maybe its not actually ambiguous like I thought but I think that it will at least make errors more pleasant and code nicer.

```
def a(): Int32 = 15 + 
def b(): Int32 = println("42"); 42
```
At this point the error would be that b is unused
```
def a(ref: Int32): Int32 = 12 + ref
def b(): Int32 & Impure = println("15"); 15
```
`>> Unable to unify the types: 'Int32' and 'ScopedRef[Int32, false]'.`
this one could be fixed by the parser not allowing keywords as variables but this a correct program that is parsed incorrectly if the inner functions can be annotated with a return type

**Comment by magnus-madsen** [comment]
How do you want to differentiate between top-level and local defs?

**Comment by JonathanStarup** [comment]
> How do you want to differentiate between top-level and local defs?

when you see `def test(): Something = {` you know that all defs are local until the matching `}` is reached

**Comment by mlutze** [comment]
@magnus-madsen The merging of this isn't dependent on the resolution of the above, right?

**Comment by magnus-madsen** [comment]
> @magnus-madsen The merging of this isn't dependent on the resolution of the above, right?

No. But I am holding off because I am not entirely convinced we want to go down this path.

**Comment by magnus-madsen** [comment]
Lets not do this just yet. I am not convinced of adding ad-hoc parsing  rules just to handle certain cases.

**Pull request closed without merging**
