### PR TITLE
refactor: use regions in `Iterator` (Part I)

### LINKED ISSUE #3589: Refactor `Iterable` and `Iterator` to use regions
Starting point:

```
pub class Iterable2[t: Type -> (Bool -> Type)] {

    pub def iterator[t: Type -> (Bool -> Type), a: Type, r: Region](t: t[a, r]): Iterator2[a, r] & r

}

pub enum Iterator2[a: Type, r: Bool] {
    case Iterator2(Done2[r], Next2[a, r])
}

type alias Done2[ef: Bool] = Unit -> Bool & ef

type alias Next2[a: Type, ef: Bool] = Unit -> a & ef

```

The ugly signature on `iterator` seems necessary.

### PR DESCRIPTION
**Pull request by jaschdoc**
Related to #3589

### CODE REVIEW

**Comment by magnus-madsen** [comment]
If this is turning out to be cumbersome, it might be worth starting on `Array` and taking it piece-by-piece.

This would also help us identify potential issues with Boolean unification.

**Comment by magnus-madsen** [comment]
Can we revisit this now? Was there something blocking?

**Comment by jaschdoc** [comment]
Should we split this into several PRs and accept a brief transition phase?

**Comment by magnus-madsen** [comment]
> Should we split this into several PRs and accept a (hopefully) brief transition period?

Sure, and is that split now?

**Comment by jaschdoc** [comment]
I think so. ~400 lines is what we usually want :)

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
