### PR TITLE
refactor: introduce RegionSym

### PR DESCRIPTION
**Pull request by mlutze**
related to #4653

### CODE REVIEW

**Comment by mlutze** [comment]
This seems to have the same issue we faced before:

We build up a substitution that includes something like
```
a -> a and r
```

The type of our expression is inferred to be
```
a and r
```

We purify `r` and the type becomes
```
a
```

and then we apply the substitution and `r` returns:
```
a and r
```

**Comment by magnus-madsen** [comment]
So, we need more information in the substitution or we need to split it somehow.

**Comment by magnus-madsen** [comment]
Should we apply the substitution first and then purify?

**Comment by magnus-madsen** [comment]
> > Should we apply the substitution first and then purify?
> 
> I don't think that can work.
> 
> ```scala
>       case KindedAst.Expression.Scope(sym, regionVar, exp, pvar, loc) =>
>         for {
>           // don't make the region var rigid if the --Xflexible-regions flag is set
>           _ <- if (flix.options.xflexibleregions) InferMonad.point(()) else rigidifyM(regionVar)
>           _ <- unifyTypeM(sym.tvar, Type.mkRegion(regionVar, loc), loc)
>           (constrs, tpe, pur, eff) <- visitExp(exp)
>           purifiedPur <- purifyEffM(regionVar, pur)
>           resultPur <- unifyTypeM(pvar, purifiedPur, loc)
>           _ <- noEscapeM(regionVar, tpe)
>           resultTyp = tpe
>           resultEff = eff
>         } yield (constrs, resultTyp, resultPur, resultEff)
> ```
> 
> The `resultPur <- ...` triggers another substitution and cannot be done before purifying.

I am not saying this is the right solution, but does the purify need to happen in purifyM, what if we do it in the yield?

**Comment by mlutze** [comment]
> I am not saying this is the right solution, but does the purify need to happen in purifyM, what if we do it in the yield?

I think that still breaks because `pvar` needs to be purified too.

**Comment by magnus-madsen** [comment]
A lot of conflicts. Should we close and revisit?

**Comment by mlutze** [comment]
Yep

**Pull request closed without merging**
