### PR TITLE
feat: add `toMapWith`

### PR DESCRIPTION
**Pull request by ninaandrup**
#2872

To:
- [x] `List`
- [x] `Nel`
- [x] `Set`
- [x] `Option`
- [x] `Result`
- [x] `Foldable`

### CODE REVIEW

**Comment by ninaandrup** [comment]
Let's start with the first three, and then I will make a new PR for the rest

**Comment by magnus-madsen** [comment]
Very good. Just one thing; could I ask you to place `toMapWith` right after `toMap` in the respective files? Thanks!

**Comment by ninaandrup** [comment]
> Very good. Just one thing; could I ask you to place `toMapWith` right after `toMap` in the respective files? Thanks!

Yes, of course. That makes more sense

**Comment by ninaandrup** [comment]
> Very good. Just one thing; could I ask you to place `toMapWith` right after `toMap` in the respective files? Thanks!

Done

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
