### PR TITLE
Add `Array.copyOfRange`

### LINKED ISSUE #2358: Add Support for Arrays.copyOf
Either as a new array primitive or some other way.

(The challenge here is that each is specialized, so how do we call the right one?)

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes #2358 

I would love an explanation or the `ErasedType` case and what to do with Strings, BigInts, Unit, and Tuples with multiple types. I'm not quite sure if I'm doing the right thing currently and what magic is going on :)

### CODE REVIEW

**Comment by jaschdoc** [comment]
Hmm...
`Array.copyOfRange(1, 4, [['a', 'b', 'c'], ['d', 'e', 'f', 'g'], ['h', 'i', 'j']]) == [['d', 'e', 'f', 'g'], ['h', 'i', 'j'], default]`
throws a `NullPointerException`. Not sure it's supposed to do that. Thoughts?

**Comment by jaschdoc** [comment]
I've refactored the tests which had the problems you mentioned above, however, `reifyType` doesn't work for tuples and possibly other non-primitive types.

**Comment by magnus-madsen** [comment]
This?

```
    @test
    def copyOfRange28(): Bool & Impure =
        Array.copyOfRange(0, 3, [Some(1), Some(2), None]) == [Some(1), Some(2), None]
```

I need the concrete example and the concrete error :)

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
