### PR TITLE
feat: Disallow Type, Type Aliases using pre-defined in Weeder

### PR DESCRIPTION
**Pull request by nicdard**
Milestones 2 and 3 of #1965

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I think #3269 this PR is trying to target the same issue.

**Comment by nicdard** [comment]
> I think #3269 is trying to target the same issue.

Yes I think too, but the provided functionality here is not already implemented in the other ticket (it's mentioned in the next steps)

**Comment by mlutze** [comment]
> > I think #3269 is trying to target the same issue.
> 
> Yes I think too, but the provided functionality here is not already implemented in the other ticket (it's mentioned in the next steps)

If/when #3269 is merged, you can build on it; my plan for handling types was a little different from what you laid out here though. I intended to add built-in types to the parser, so that we have only one file to scan through to find all the keywords.

**Comment by nicdard** [comment]
> > > I think #3269 is trying to target the same issue.
> > 
> > 
> > Yes I think too, but the provided functionality here is not already implemented in the other ticket (it's mentioned in the next steps)
> 
> If/when #3269 is merged, you can build on it; my plan for handling types was a little different from what you laid out here though. I intended to add built-in types to the parser, so that we have only one file to scan through to find all the keywords.

I see, so if I understand correctly you want to enforce the check directly in the parser right?

**Comment by mlutze** [comment]
> I see, so if I understand correctly you want to enforce the check directly in the parser right?

Not quite. Enforcing things in the parser tends to result in poor error messages. Instead, my idea is this:

In the parser, when parsing types, we specifically parse `Int32`, `Int64`, etc., before falling back to a generic "match capital identifier" matcher. Each of those will be marked via the `keyword` function in the parser (or `builtIn` or some such). That way, when we need to get a list of reserved terms (for example, when making the list to use in the Weeder), we can simply grep through the parser and pull out anything that looks like `keyword("xyz")`.

It's slightly hacky, in that we're almost doing a kind of metaprogramming. But I think it's important to have an easy way to get a canonical list of keywords and reserved terms.

Thoughts?

**Comment by nicdard** [comment]
Oh I see the problem you are trying to solve, and indeed I remember I was asking for a list of keywords myself at the beginning, so this makes a lot of sense to me, as I was also wondering on how to encode the keywords list once for all the project

Nevertheless, the thing is that we are still encoding this list in the parser in some way to actually parse it, wouldn't it be less hacky to just have the list properly somewhere to be used both from the parser and from other parts of the code? I could also be the case that we want to split the list of keywords in categories maybe

**Comment by nicdard** [comment]
> Oh I see the problem you are trying to solve, and indeed I remember I was asking for a list of keywords myself at the beginning, so this makes a lot of sense to me, as I was also wondering on how to encode the keywords list once for all the project
> 
> Nevertheless, the thing is that we are still encoding this list in the parser in some way to actually parse it, wouldn't it be less hacky to just have the list properly somewhere to be used both from the parser and from other parts of the code? I could also be the case that we want to split the list of keywords in categories maybe

I also agree that an easy way to access this information is cool in general and avoids stupid errors or redundancy in the code

**Comment by mlutze** [comment]
> Nevertheless, the thing is that we are still encoding this list in the parser in some way to actually parse it, wouldn't it be less hacky to just have the list properly somewhere to be used both from the parser and from other parts of the code? I could also be the case that we want to split the list of keywords in categories maybe

As I understand, you're suggesting we have something like
```scala
object Keywords {
  val pub = "pub"
  val select = "select"
  ...
}
```

or something like

```scala
object Keywords {
  val keywords = List("pub", "select", ...)
}
```

and then we use those in the parser.

I think there are a couple problems with these solutions.
* Option 1:
  * We don't actually have a list to use to compare an identifier against all keywords at once.
  * Some keywords, such as `def`, would have to be mangled to be allowed by Scala syntax, meaning another mental step to take when examining the parser
  * I'm not sure whether the parser's macros allow for non-literals (probably constants like this are fine though)
* Option 2:
  * The parser can't access the keywords individually.

If we combine them, (have the constants and a list), then we still end up having to do some metaprogramming to build the list (albeit much simpler), and we still end up with the mangling drawback.

**Comment by nicdard** [comment]
I see your point, makes sense, actually I am still not that proficient with Scala in general as a programming language and I was thinking that there were a way to define an enumeration like in Java which could have given us also a way to easily get the values from the Enums.

Apparently it should be possible in option 1 to overcome the first limitation of not having a list to use that you mentioned by using `Enumeration`:

```scala
object Keywords extends Enumeration {
  type builtIn = Value
  val Pub = Value(0, "pub") // Value as also an index 
  val Select = Value(1, "select")
  ...
}
```

The same can be achieved by defining a internal case class which overrides the [super.Val](https://www.scala-lang.org/api/2.13.5/scala/Enumeration.html). The list of values is then accessible by `Keywords.values`. We can also directly encode a method in to give us the list of string literals.

With this trick we can solve also the second problem, as we can just use uppercase names for the values objects in the enumeration.

Regarding the third issue, I don't have any clue :sweat_smile: 

Finally I would say that this is maybe less hacking than using the parser to mark the keywords/builtIns in the sense that there will be a static list where we can go and look at while the other solution is more dynamic and maybe less easy to be discovered when approaching the code base without an explanation, but this is just a personal note/taste at first glance.

Sorry for the long message :)

**Comment by mlutze** [comment]
I wasn't familiar with `Enumeration`. Definitely worth looking into!

**Comment by nicdard** [comment]
> I wasn't familiar with `Enumeration`. Definitely worth looking into!

Cool, I am glad!

**Comment by magnus-madsen** [comment]
`Enumeration` is actually deprecated. The pattern with `sealed traits` and case objects is the way to go 👍

**Comment by mlutze** [comment]
Ah darn. You can't enumerate over the members of a sealed traits, as far as I am aware.

**Comment by magnus-madsen** [comment]
I think this was fixed in another PR? Maybe we can close?

**Comment by mlutze** [comment]
> I think this was fixed in another PR? Maybe we can close?

Not yet. That PR only took care of sigs, laws, and defs.

**Comment by nicdard** [comment]
> > I think this was fixed in another PR? Maybe we can close?
> 
> Not yet. That PR only took care of sigs, laws, and defs.

If you need any help count on me :)

**Comment by mlutze** [comment]
I think the conclusion is that we will go with the "tagging in the Parser" approach for now.

This means that the implementation will need to:
* add the built-in types to the Parser
* add the built-in types from the Parser to the built-in list in the Weeder
* apply the check to identifiers (as done in this PR)

Let me know if you have any questions/concerns.

**Comment by nicdard** [comment]
> I think the conclusion is that we will go with the "tagging in the Parser" approach for now.
> 
> This means that the implementation will need to:
> 
> * add the built-in types to the Parser
> * add the built-in types from the Parser to the built-in list in the Weeder
> * apply the check to identifiers (as done in this PR)
> 
> Let me know if you have any questions/concerns.

Ok perfect :) I will work on this probably during the weekend if I don't manage to find free time before

**Comment by nicdard** [comment]
I think the PR should be ready now, as by adding the error for type aliases the standard library cannot be compiled

**Comment by nicdard** [comment]
I have seen that the build is failing due to some examples containing redefinition of builtin types, I will update them :)

**Comment by magnus-madsen** [comment]
I am closing this; pending further discussion.

**Pull request closed without merging**
