### PR TITLE
feat: Allow doc-comments above effect handlers

### LINKED ISSUE #7643: Parser: Gets stuck on comments
@herluf-ba 

From https://github.com/flix/flix/pull/7252 at file https://github.com/flix/flix/blob/d678d791359a8483c78e0e4cde64cce142f4b4d7/examples/effects/Queens.flix (commit https://github.com/flix/flix/commit/d678d791359a8483c78e0e4cde64cce142f4b4d7 )

```
ca.uwaterloo.flix.util.InternalCompilerException: [examples/effects/Queens.flix:107:1] Parser is stuck
	at ca.uwaterloo.flix.language.phase.Parser2$.ca$uwaterloo$flix$language$phase$Parser2$$nth(Parser2.scala:336)
	at ca.uwaterloo.flix.language.phase.Parser2$.ca$uwaterloo$flix$language$phase$Parser2$$atAny(Parser2.scala:360)
	at ca.uwaterloo.flix.language.phase.Parser2$.ca$uwaterloo$flix$language$phase$Parser2$$comments(Parser2.scala:787)
	at ca.uwaterloo.flix.language.phase.Parser2$.ca$uwaterloo$flix$language$phase$Parser2$$close(Parser2.scala:266)
	at ca.uwaterloo.flix.language.phase.Parser2$Decl$.docComment(Parser2.scala:1263)
	at ca.uwaterloo.flix.language.phase.Parser2$Decl$.declaration(Parser2.scala:882)
	at ca.uwaterloo.flix.language.phase.Parser2$.root(Parser2.scala:806)
	at ca.uwaterloo.flix.language.phase.Parser2$.parse(Parser2.scala:146)
	at ca.uwaterloo.flix.language.phase.Parser2$.$anonfun$run$2(Parser2.scala:133)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMap$2(ParOps.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
(examples/effects/Queens.flix:107:1,CurlyR)
#
# An unexpected error has been detected by the Flix compiler:
#
#   [examples/effects/Queens.flix:107:1] Parser is stuck
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : 0.46.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 21.0.1 (2023-10-17)
# JVM Vendor   : GraalVM Community
# JAVA_HOME    : /home/_/.sdkman/candidates/java/21.0.1-graalce
# System       : Linux
#
# -- Stack Trace --
ca.uwaterloo.flix.util.InternalCompilerException: [examples/effects/Queens.flix:107:1] Parser is stuck
	at ca.uwaterloo.flix.language.phase.Parser2$.ca$uwaterloo$flix$language$phase$Parser2$$nth(Parser2.scala:336)
	at ca.uwaterloo.flix.language.phase.Parser2$.ca$uwaterloo$flix$language$phase$Parser2$$atAny(Parser2.scala:360)
	at ca.uwaterloo.flix.language.phase.Parser2$.ca$uwaterloo$flix$language$phase$Parser2$$comments(Parser2.scala:787)
	at ca.uwaterloo.flix.language.phase.Parser2$.ca$uwaterloo$flix$language$phase$Parser2$$close(Parser2.scala:266)
	at ca.uwaterloo.flix.language.phase.Parser2$Decl$.docComment(Parser2.scala:1263)
	at ca.uwaterloo.flix.language.phase.Parser2$Decl$.declaration(Parser2.scala:882)
	at ca.uwaterloo.flix.language.phase.Parser2$.root(Parser2.scala:806)
	at ca.uwaterloo.flix.language.phase.Parser2$.parse(Parser2.scala:146)
	at ca.uwaterloo.flix.language.phase.Parser2$.$anonfun$run$2(Parser2.scala:133)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMap$2(ParOps.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

### PR DESCRIPTION
**Pull request by herluf-ba**
Closes #7643

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Question: Before you go crazy with bug fixing. Since these bugs were _not_ covered by existing code, it might actually be worth adding them to TestParser or somewhere else.

**Comment by magnus-madsen** [comment]
Thoughts? Or do just want to fix them and get on with life? :P

**Comment by magnus-madsen** [comment]
What's the policy on doc comments? Can they appear anywhere or what?

**Comment by herluf-ba** [comment]
The policy on doc comments is that they can appear pretty much anywhere (Same as other comments). We have to do that right now to avoid going through the std. library and refactoring, although that's something I'd like to do in the future.

Ideally I think doc-comments should only be allowed above a declaration (either top-level or with a module).

>Thoughts? Or do just want to fix them and get on with life? :P

I don't think this particular change warrants a test. Especially since I am looking to change this behavior in the future.
So yea, let's fix this and move on for now haha. I have a good idea about how to handle this sort of stuff neatly, but I think other stuff is higher priority (performance, adding semantic contexts the right places,)

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
