### PR TITLE
Use derivations in the standard library

### PR DESCRIPTION
**Pull request by mlutze**
Completing Phase 2 of https://github.com/flix/flix/issues/2154

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Thanks!

**Comment by magnus-madsen** [comment]
I think there are a few more enums the library where we could use the derive mechanism (e.g. in the solver). A search for instance might be useful.

**Comment by magnus-madsen** [comment]
Best kind of PR:

image

**Comment by mlutze** [comment]
> I think there are a few more enums the library where we could use the derive mechanism (e.g. in the solver). A search for instance might be useful.

Ah right, I only looked though the base folder. I'll take another look.

**Pull request merged**
