### PR TITLE
refactor: fix jvm tuple string

### PR DESCRIPTION
**Pull request by JonathanStarup**
As found by @Sintrastes, our code relies on some weird coersion, so I've rewritten the toString of tuple, which should also be more null resistant

### CODE REVIEW

**Comment by magnus-madsen** [comment]
What toString is this? We have `ToString` and `stringify` right?

**Comment by magnus-madsen** [comment]
Paging @mlutze too: How many "toString"s do we have? :D

**Comment by mlutze** [comment]
We have two general front-end stringifications: ToString and stringify.

But I recall we've already had to do more in the back-end for tuples

**Comment by JonathanStarup** [comment]
> What toString is this? We have `ToString` and `stringify` right?

`stringify` doesn't match on composite things like tuples so it just calls `Objects.toString(x)`, at which point the generated tuple object needs to have a sensible toString implementation, which essentially requires a backend version of `stringify`. So we have a magic toString in the backend also.

This PR is not altering that state of affairs, just correctly using whats there already

**Comment by magnus-madsen** [comment]
Yikes, okay.

**Pull request merged**
