### PR TITLE
refactor: simplify `Purity.fromType`

### PR DESCRIPTION
**Pull request by magnus-madsen**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@JonathanStarup I am making this simplification until proper sets arrive.

**Comment by JonathanStarup** [comment]
I guess its fine but doesnt i just lose performance? whats the upside?

**Comment by magnus-madsen** [comment]
> I guess its fine but doesnt it just lose performance? whats the upside?

The upside is that its obviously correct-- which is important now that we have big issues with some other parts of the compiler :(

**Comment by JonathanStarup** [comment]
This would just mask away effect errors id think (a lot of things just become Control Impure)

I feel like evaluate formula is also obviously correct.

**Review by JonathanStarup — APPROVED** [review]

**Review by mlutze — APPROVED** [review]

**Comment by magnus-madsen** [comment]
> This would just mask away effect errors id think (a lot of things just become Control Impure)
> 
> I feel like evaluate formula is also obviously correct.

If we had the Verifier then I would be more inclined to keep it.

**Comment by magnus-madsen** [comment]
Also this change is only meant to be temporary.

**Comment by JonathanStarup** [comment]
This code is just 1 to 1 evaluating the formula so I don't think this has any errors - but you can do it if you want, it just seems counterproductive to mask errors if we're currently weeding out effect bugs

**Pull request closed without merging**
