### PR TITLE
test: add palindrome datalog example

### PR DESCRIPTION
**Pull request by JonathanStarup**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
The example is a bit complex, so I would suggest some comments. At least I was not able to fully understand it.

**Comment by magnus-madsen** [comment]
Also it should be added to the test cases.

**Comment by JonathanStarup** [comment]
should be better now @magnus-madsen

**Comment by magnus-madsen** [comment]
Will merge after #2759

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
