### PR TITLE
chore: parboiled2: 2.2.1 → 2.4.1

### PR DESCRIPTION
**Pull request by fabianhjr**
split from https://github.com/flix/flix/pull/5751

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Any impact on the running time of `gradlew test`?

**Comment by fabianhjr** [comment]
Doing 3 runs main branch + 3 runs this branch, brb

**Comment by fabianhjr** [comment]
Using `time ./gradlew check`

This branch:

```
BUILD SUCCESSFUL in 3m 50s
4 actionable tasks: 1 executed, 3 up-to-date

________________________________________________________
Executed in  231.01 secs    fish           external
   usr time    2.29 secs  590.00 micros    2.28 secs
   sys time    0.26 secs  113.00 micros    0.26 secs

BUILD SUCCESSFUL in 3m 49s
4 actionable tasks: 1 executed, 3 up-to-date

________________________________________________________
Executed in  229.64 secs    fish           external
   usr time    2.18 secs  326.00 micros    2.18 secs
   sys time    0.26 secs   63.00 micros    0.26 secs

BUILD SUCCESSFUL in 3m 45s
4 actionable tasks: 1 executed, 3 up-to-date

________________________________________________________
Executed in  226.20 secs    fish           external
   usr time    2.31 secs    0.00 micros    2.31 secs
   sys time    0.13 secs  604.00 micros    0.13 secs
```

**Comment by magnus-madsen** [comment]
Check only builds right? I am worried about the performance of Flix itself, so it would have to be `gradlew test`?

**Comment by fabianhjr** [comment]
Main branch:

```
BUILD SUCCESSFUL in 3m 45s
4 actionable tasks: 1 executed, 3 up-to-date

________________________________________________________
Executed in  225.99 secs    fish           external
   usr time    2.06 secs  385.00 micros    2.06 secs
   sys time    0.25 secs   88.00 micros    0.25 secs

BUILD SUCCESSFUL in 3m 46s
4 actionable tasks: 1 executed, 3 up-to-date

________________________________________________________
Executed in  226.85 secs    fish           external
   usr time    2.35 secs    0.00 micros    2.35 secs
   sys time    0.24 secs  495.00 micros    0.24 secs


> Task :test UP-TO-DATE
> Task :check UP-TO-DATE

BUILD SUCCESSFUL in 3m 51s
4 actionable tasks: 1 executed, 3 up-to-date

________________________________________________________
Executed in  231.71 secs    fish           external
   usr time    2.36 secs  338.00 micros    2.36 secs
   sys time    0.26 secs   80.00 micros    0.26 secs
```

**Comment by fabianhjr** [comment]
> Check only builds right? I am worried about the performance of Flix itself, so it would have to be `gradlew test`?

check does test too.

```
- flatMap06
- traverse01
- traverse02
- traverse03
- traverse04
- traverse05
- traverse06
- foldRight01
- toSoftFailure01
- toSoftFailure02
- toSoftFailure03
- recoverOne01
- recoverOne02
- recoverOne03
- recoverOne04
Run completed in 3 minutes, 50 seconds.
Total number of tests run: 1606
Suites: completed 38, aborted 0
Tests: succeeded 1606, failed 0, canceled 0, ignored 33, pending 0
All tests passed.

> Task :test UP-TO-DATE
> Task :check UP-TO-DATE

BUILD SUCCESSFUL in 3m 51s
4 actionable tasks: 1 executed, 3 up-to-date
```

**Comment by fabianhjr** [comment]
Looks like no impact to performance.

**Pull request merged**
