### PR TITLE
feat: fill out associated types in `InstanceCompleter`

### LINKED ISSUE #7443: InstanceCompleter should fill in associated types and effects

### PR DESCRIPTION
**Pull request by sockmaster27**
Fixes #7443

### CODE REVIEW

**Comment by sockmaster27** [comment]
This would really benefit from some sort of type-holes

**Comment by magnus-madsen** [comment]
Do you have a screenshot? Thanks!

**Comment by sockmaster27** [comment]
image

image

image

image

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
I think one of @mlutze recent changes broke something.

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
