### PR TITLE
refactor: prepare `DelayList` release

### LINKED ISSUE #3122: Prepare `DelayList` for release
I've looked over `DelayList` and here are some of the issues I found.

~~**Functions that could be added**~~
~~`init`~~

~~**Use LetRec?**~~

~~**Docs that need fixing**~~
~~`append`~~
~~`intersperse`~~

**Rename these**
~~`x: a` to `a: a`~~
~~`mapL` to `mapLazy` and `mapE` to `mapEager` etc.~~
~~`ks -> ks` to use `identity`~~

**Functions**
~~- `intersperse` - Could be more lazy. I don't like the `LCons` case that forces the tail, maybe adding an `insert` helper function could alleviate the problem? I'm not sure about this~~
~~- `intercalate` - Same as above~~
~~- `zip` - Simplify. Have the base cases with `ENil` and otherwise just delegate to `zipHelper` and wrap in `LList` i.e. `LList(lazy zipHelper(l1, l2))`~~

~~Discussion: Should private lazy functions have the `@Lazy` annotation? Currently, some do and some don't.~~

~~Maybe the file should also be reordered again. `Map` is in the middle, `fold`s and `filter` is near the bottom and maybe they should be at the top s.t. the further down the file you read the functions are less commonly used and perhaps more complex?~~

@magnus-madsen What's your input?

**Edit**
Add `SemiGroup` instance
Add `Monoid` instance
Add `Applicative` instance
Add `Monad` instance
Add `Traversable` instance

Related to #3153

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes #3122 

- [x] Reorder file
- [x] Add missing TC instances

### CODE REVIEW

**Comment by jaschdoc** [comment]
A couple of questions:
Should we annotate TC instance functions with `@LazyWhenPure` if it applies to that function?
I'm not really sure what's going on in the functions `sequence` and `traverse` for the `Traversable` instance, however, I have a hunch that these could be lazier and potentially also purity reflective (only relevant for `traverse`) but I haven't had the time to look into it and study the implementation of the function yet (I just lifted it from `List`). Is this worth pursuing?

**Comment by magnus-madsen** [comment]
> Should we annotate TC instance functions with `@LazyWhenPure` if it applies to that function? I

No.

> I'm not really sure what's going on in the functions `sequence` and `traverse` for the `Traversable` instance, however, I have a hunch that these could be lazier and potentially also purity reflective (only relevant for `traverse`) but I haven't had the time to look into it and study the implementation of the function yet (I just lifted it from `List`). Is this worth pursuing?

Not at the moment, I think.

**Comment by jaschdoc** [comment]
@magnus-madsen RFR

**Comment by jaschdoc** [comment]
Also note that previous commits are unverified. I've started signing commits locally so that's why they're flagged

**Pull request merged**
