### PR TITLE
fix: broken annotation completions

### PR DESCRIPTION
**Pull request by LoZander**
This fixes an issue where annotation completions aren't suggested as expect. For instance, typing `@T` would not give us the suggestion `@Test`. Now it does.

If only typing `@` we only get suggestions by invoking the suggestions using ctrl+space. However, when typing for instance `@D` we immediately get the suggestion `@Deprecated`.

For now I've given the priority 1 to the new `getSyntacticContext` case. I believe that what really matters is that it's prioritised above parse error, but I'm unsure. Currently, it seems to have the intended behaviour.

Related to #8638

### CODE REVIEW

**Comment by mlutze** [comment]
!!!rerun

**Comment by JonathanStarup** [comment]
I think the line
```scala
case err => pos.line <= err.loc.beginLine
```
is pretty weird, maybe you should keep it mind that restricting this range might lead to better contexts (it looks like all errors after your cursor can decide the context, instead of just the nearby errors)

**Comment by LoZander** [comment]
Hm. I havent really looked much at this `getSyntacticContexts` function. It was from before my time. I'm not sure why the tests fail, I simply added a case, didn't touch anything else...
and I agree about that one line with that bound. That's weird. I don't know what to make of that, but I can look into it

**Comment by LoZander** [comment]
yeah, I think the tests failing was something else somewhere else

**Comment by JonathanStarup** [comment]
I don't think you have to change anything now, but just keep it in mind if you have multiple errors and have bad contexts

**Review by JonathanStarup — APPROVED** [review]

**Comment by magnus-madsen** [comment]
@LoZander Would it make sense to add a specific AnnotationCompleter?

**Pull request merged**
