### PR TITLE
refactor: use `Iterator.foreach` in `foreach` loops

### PR DESCRIPTION
**Pull request by jaschdoc**
Related to #3950

### CODE REVIEW

**Comment by magnus-madsen** [comment]
What happened?

**Comment by jaschdoc** [comment]
I have no clue. Not sure I meant to do this.

**Comment by magnus-madsen** [comment]
Does it look good? Should I review?

**Comment by jaschdoc** [comment]
Yeah I think this is ready

**Comment by magnus-madsen** [comment]
Looks simple enough 👍

**Pull request merged**
