### PR TITLE
feat: improve color support for `Console`

### PR DESCRIPTION
**Pull request by ninaandrup**
#2853

### CODE REVIEW

**Comment by magnus-madsen** [comment]
This blog post has some information:

https://www.lihaoyi.com/post/BuildyourownCommandLinewithANSIescapecodes.html

**Comment by magnus-madsen** [comment]
I think we should split into two PRs. This one and the one where you extend:

`formatAnsi`, `formatTrueColor`, and `rgb` to take a Boolean which indicates if it is a "foreground" color or a "background" color. 

The helper functions would then look like:

```
    pub def bgBlue(s: String): String =
        rgb(Blue |> toRGB, s, true)
```

Something this like the above. But I suggest to experiment with that in a new PR. Hope it makes sense.

**Comment by ninaandrup** [comment]
> This blog post has some information:
> 
> https://www.lihaoyi.com/post/BuildyourownCommandLinewithANSIescapecodes.html

This will be helpful!

**Comment by ninaandrup** [comment]
> I think we should split into two PRs. This one and the one where you extend:
> 
> `formatAnsi`, `formatTrueColor`, and `rgb` to take a Boolean which indicates if it is a "foreground" color or a "background" color.
> 
> The helper functions would then look like:
> 
> ```
>     pub def bgBlue(s: String): String =
>         rgb(Blue |> toRGB, s, true)
> ```
> 
> Something this like the above. But I suggest to experiment with that in a new PR. Hope it makes sense.

I think that is a good idea

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
