### PR TITLE
allow wildcard type in function declarations

### PR DESCRIPTION
**Pull request by mlutze**
Fixes https://github.com/flix/flix/issues/874

Still need to add more tests and ensure type parameters in other locations are appropriately handled.

### CODE REVIEW

**Comment by mlutze** [comment]
I added some tests and it seems to be working well. Marking as ready for review.

**Comment by magnus-madsen** [comment]
I merging this, but I actually feel that the feature is a bit suspect.

What is the best example of where you want to use something like this?

**Comment by mlutze** [comment]
I think a lot of the value may be in increasing readability of code, analagously to wildcard terms.

`{ x: Int | _ }` tells us immediately that we don't care about the rest of the record whereas `{ x: Int | r }` implies that `r` may be used for something.

So something like
```
def length(list: List[_}) = {
    ...
}
```

Then we could even go as far as redundancy checking the type variables.

But maybe that exposes implementation details too much, if we see a signature with a wildcard type?

**Comment by magnus-madsen** [comment]
For records,

I really wonder if `{x: Int}` should not just simply be secret sugar for `{x: Int | _}`. (which would imply that underscores are not needed here)

For `List.length` that is indeed an example, but how many such examples can we come up with? It seems pretty rare.

**Comment by mlutze** [comment]
> I really wonder if `{x: Int}` should not just simply be secret sugar for `{x: Int | _}`. (which would imply that underscores are not needed here)

Yes, I agree that this is worth exploring. It would also be nice to have more consistency between records and schemas, since I think this is already the case for schemas.

> For `List.length` that is indeed an example, but how many such examples can we come up with? It seems pretty rare.

I think we could generalize the idea for enums to something like "A function that depends on the structure of an enum but not its contents." So for example, `isCyclic(graph: Graph[_]): Bool`. 

But I think you're right that this may not be common enough to warrant the added complexity of a feature like this.

**Pull request merged**
