### PR TITLE
feat: add mkNewDef to CodeActionProvider

### PR DESCRIPTION
**Pull request by stormckey**
According to #9125, we introduce mkNewDef, a quickfix that will introduce a function definition for a undefined name.

### CODE REVIEW

**Comment by stormckey** [comment]
> Can we add some snippets so that one can fill out the return type and body by pressing tab? Is that possible?

Maybe not? I'm not 100% sure. But when returning a CodeAction of kind quickfix, there is no place for us to make it a snippet. Also, there is no such CodeActionKind that is relative to snippet.

**Comment by magnus-madsen** [comment]
> > Can we add some snippets so that one can fill out the return type and body by pressing tab? Is that possible?
> 
> Maybe not? I'm not 100% sure. But when returning a CodeAction of kind quickfix, there is no place for us to make it a snippet. Also, there is no such CodeActionKind that is relative to snippet.

What does the language server protocol spec say? Is it support or no? (It could be our data types are too simple...)

**Comment by stormckey** [comment]
> What does the language server protocol spec say? Is it support or no? (It could be our data types are too simple...)

Still I can't find fields that can make quickfix a snippet. You could double check through this [link](https://code.visualstudio.com/api/references/vscode-api#CodeAction).

**Comment by magnus-madsen** [comment]
Hmm okay. Could you try some other language server, e.g. the one for Rust and see what they support?

If we cannot add holes/snippets then I would say this feature is less useful.

**Comment by stormckey** [comment]
Well it do works for rust, although it's not exactly snippet:
image

image

image

We can not jump between holes by striking tab, but it do help us select the region to be edited(only one place)

**Comment by stormckey** [comment]
You can search `generate_function` on  the rust-analyzer [manual](https://rust-analyzer.github.io/manual.html). I can't tell which CodeActionKind they are using. But it's possible for us to first fill in the parameters automatically as shown in the manual.

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
