### PR TITLE
Remove switch statement

### PR DESCRIPTION
**Pull request by mlutze**
First commit changes all `switch` statements to `if-else`s in standard library and other `*.flix` files.
Compiler changes to come.

Looks like I added extra parentheses for a lot of these (a fault of my partial automation of changes). I'll fix that in a future revision.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Great! :) Let me know when this is ready to be looked at.

**Comment by mlutze** [comment]
Should be good to go. I had a mistake in the IntervalInf.flix file that wasn't caught by tests. It might be a good idea to add tests at least to be sure all the Flix code in the repository compiles.

**Comment by magnus-madsen** [comment]
Can I ask you to do a project-wide search for "switch" to confirm that all relevant AST nodes and code has been updated? (If you have not done so already?)

**Comment by magnus-madsen** [comment]
Code looks good to me!

Could I ask you to add three tests to `Test.Expression.IfThenElse` that ensures that an if-then-else works correctly with multiple if-else?

**Comment by mlutze** [comment]
The only remaining "switch" strings in code are referring to scala `@switch` annotations.

Since you asked for three more tests, I assumed you wanted to test the `if`, `else if`, and `else` part of the expression in each respective test. Let me know if that wasn't exactly what you were looking for.

**Comment by magnus-madsen** [comment]
> The only remaining "switch" strings in code are referring to scala `@switch` annotations.
> 
> Since you asked for three more tests, I assumed you wanted to test the `if`, `else if`, and `else` part of the expression in each respective test. Let me know if that wasn't exactly what you were looking for.

Yes, exactly!

**Pull request merged**
