### PR TITLE
feat: allow `debug` for all types

### PR DESCRIPTION
**Pull request by JonathanStarup**
Anything can be printed, the string isn't to meaningful for tags, tuples, etc, but that can be improved in the backend. Related to #4646.

### CODE REVIEW

**Comment by JonathanStarup** [comment]
<details>
<summary> Example and output </summary>

```scala
enum Test(Int32)

def main(): Unit \ IO = {
    let _ = debug("hello");
    let _ = debug(Test(2));
    let _ = debug(());
    let _ = debug(true);
    let _ = debug('a');
    let _ = debug(32.5f32);
    let _ = debug(64.5f64);
    let _ = debug(8i8);
    let _ = debug(16i16);
    let _ = debug(32i32);
    let _ = debug(64i64);
    let _ = debug([1, 2, 3]);
    let _ = debug(x -> x+1);
    let _ = debug((1, 2, "hello"));
    ()
}
```

Output
```
[main\src\personal\test.flix:4] hello
[main\src\personal\test.flix:5] Test
[main\src\personal\test.flix:6] ()
[main\src\personal\test.flix:7] true
[main\src\personal\test.flix:8] a
[main\src\personal\test.flix:9] 32.5
[main\src\personal\test.flix:10] 64.5
[main\src\personal\test.flix:11] 8
[main\src\personal\test.flix:12] 16
[main\src\personal\test.flix:13] 32
[main\src\personal\test.flix:14] 64
[main\src\personal\test.flix:15] [I@25a6944c
[main\src\personal\test.flix:16] Clo%main%175449@5e1fa5b1
[main\src\personal\test.flix:17] Tuple3
```
</details>

**Comment by JonathanStarup** [comment]
!!!jar

**Comment by magnus-madsen** [comment]
- I am OK with two exps in `Debug`
- I am not so OK with all the test cases (this seems to cost 4minutes!)
- I am not sure how this can handle enums (will expand in other ticket).

**Comment by JonathanStarup** [comment]
> I am not so OK with all the test cases (this seems to cost 4minutes!)

It's not so nice. It makes sense that debug uses these toString methods, though, unless we inline them in the prelude.

The other option is to have `$Magic$` in the prelude and let the backend differentiate the types (with the aid of monomorphization)

**Comment by magnus-madsen** [comment]
Isnt e.g. `Float32.toString` just a call to a Java method anyway?

**Comment by mlutze** [comment]
You can improve array output with Java's `Arrays.deepToString`

If we just use Java functions for everything then we can avoid using the full lib in the tests.

**Comment by magnus-madsen** [comment]
I like this solution. I think its a pretty elegant given the complexity of the problem.

One question: Do we want to separate "magic" from the "debug"? Because then you can do:

```
debug("complex string x = ${magic(x))
```

Of course it should not be called magic but something else.

**Comment by JonathanStarup** [comment]
@magnus-madsen enums are "nice" now (multi arity just display the ugly tuple string)
```
enum Test {
    case TestA(Int32)
    case TestB(Test, Test)
}

enum Poly[a, b] {
    case PolyA(a)
    case PolyB(b)
}

def main(): Int32 =
    let _ = debug(TestB(TestA(1), TestA(2)));
    let _ = debug(PolyA(42));
    let _ = debug(PolyB(true));
    42
```

output

```
[main\src\personal\test.flix:12] Test.TestB(Tuple2)
[main\src\personal\test.flix:13] Poly.PolyA(42)
[main\src\personal\test.flix:14] Poly.PolyB(true)
42
```

**Comment by JonathanStarup** [comment]
> Looks good. We could merge and iterate? (See my comments about having two functions.)

It could be done, the current debug function just has to be written in jvm instead

**Comment by JonathanStarup** [comment]
> Looks good. We could merge and iterate? (See my comments about having two functions.)

Here's your magic string function

**Pull request merged**
