### PR TITLE
feat: add `iterator` and `enumerator` to Prelude

### PR DESCRIPTION
**Pull request by jaschdoc**
Related to #4224

### CODE REVIEW

**Comment by jaschdoc** [comment]
Hmm I'm not sure this is a good idea. This introduces a lot of dependencies into the core lib (i.e. all that `Iterator` depends on).

**Comment by magnus-madsen** [comment]
Cheap trick: Instead of adding them to add `Prelude` add them to `Iterator` but outside the namespace; at the top.

**Comment by jaschdoc** [comment]
RFR

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
