### PR TITLE
feat: save fonts locally in HTML documentation

### PR DESCRIPTION
**Pull request by sockmaster27**
Should finalize #6374

### CODE REVIEW

**Comment by sockmaster27** [comment]
I'm not sure I'm a big fan of using both Inter and Noto Sans btw. They're very similar.

**Comment by magnus-madsen** [comment]
I am not sure about adding these fonts to the repo. What is the problem with depending on Google? (I guess it does not work offline).

**Comment by sockmaster27** [comment]
@magnus-madsen 
Yes, exactly

**Comment by sockmaster27** [comment]
Plus, I believe it allows us to set a content security policy that's just like `default-src: 'self'`, since we don't need to load anything from any other domains.

**Comment by magnus-madsen** [comment]
(Converted to draft while I decide what to do.)

**Comment by sockmaster27** [comment]
@magnus-madsen 
What's the holdup? 🤔

**Comment by magnus-madsen** [comment]
> @magnus-madsen What's the holdup? 🤔

My indecision about whether this is a good idea and whether to add 1MB of binary data to the repo.

**Comment by magnus-madsen** [comment]
I have decided against including fonts-- for now at least.

**Pull request closed without merging**
