### PR TITLE
Added primitive instances and tests for LowerBound and UpperBound 

### PR DESCRIPTION
**Pull request by stephentetley**
Hi Magnus

I noticed the LowerBound and UpperBound classes only had Tuple instances so I've added instances for Unit, Bool, Char and the number types (except BigInt). 

I've also added tests.

Happy Christmas, please don't rush to review the changes.

### CODE REVIEW

**Comment by stephentetley** [comment]
Oh no, it looks like the LibrarySuite tests (which I'd run and passed) but the LangSuite tests fail due to library files (*.flix) not being loaded.

**Comment by magnus-madsen** [comment]
Hello Stephen.

The `LowerBound` and `UpperBound` type classes are part of the "core" standard library which is always loaded.

For many tests, we do not load the entire library, but only the core. 

Thus, instances in e.g. `LowerBound` and `UpperBound` should not depend on the standard library (but the other way is OK).

The solution here is to move the implementations from e.g. `Int32.minValue()` into `LowerBound` and then have `Int32.minValue` call the type class.

**Comment by magnus-madsen** [comment]
As a side-note, I wonder how useful these instances actually are?

**Comment by stephentetley** [comment]
> 
> 
> As a side-note, I wonder how useful these instances actually are?

I see them as a preliminary towards an `Enum` or `BoundedEnum` class. 

Incidentally Haskell's `Enum` class is quite old and not really best practice anymore (partial functions), I've been looking at PureScript's version for inspiration.

**Comment by stephentetley** [comment]
> 
> The solution here is to move the implementations from e.g. `Int32.minValue()` into `LowerBound` and then have `Int32.minValue` call the type class.

Thanks Magnus, I'll look to do this tomorrow.

**Comment by stephentetley** [comment]
Moving the implementations from the "type" modules (e.g. Int32) into the UpperBound.flix and LowerBound.flix files had a problem that it dragged in more than just the `minValue` and `maxValue` functions (for instance `Int32.minValue` also uses `Int32.size`). Instead I've moved the instances into their respective files, putting them at the top so they are in the global namespace.

Is this a viable solution? 

Also, if it is do you want me to move the tests on Int32 etc into their respective modules rather than have them in TestLowerBound.flix and TestUpperBound.flix ?

The instances for `Unit` remain in LowerBound.flix and UpperBound.flix as there is no Unit module.

**Comment by magnus-madsen** [comment]
Excellent! Thanks

**Pull request merged**
