### PR TITLE
Tighten restrictions on class tparams

### PR DESCRIPTION
**Pull request by mlutze**
Fixes https://github.com/flix/flix/issues/1750

Also separates type parameters from type constraints.

### Features
* Disallow type constraints on class tparams
  * [x] impl
  * [x] test
* Disallow type constraints on enum tparams
  * [x] impl
  * [x] test
* Disallow type constraints on lattice tparams
  * [x] impl
  * [x] test
* Disallow type constraints on relation tparams
  * [x] impl
  * [x] test
* Disallow type constraints on opaque type tparams
  * [x] impl
  * [x] test
* Disallow type constraints on type alias tparams
  * [x] impl
  * [x] test

### General requirements
* [x] Don't make a complete mess
* [x] Don't break anything else
* [x] Provide documentation
* [x] Add license to new files

### CODE REVIEW

**Comment by mlutze** [comment]
@magnus-madsen RFR

**Comment by magnus-madsen** [comment]
Very good. I have no comments. Always nice to see the code become more regular. Will you rebase and then I can merge?

**Comment by mlutze** [comment]
> rebase

Yep, done.

**Comment by magnus-madsen** [comment]
Nice!

**Pull request merged**
