### PR TITLE
feat: prepare stdlib for namespace migration

### PR DESCRIPTION
**Pull request by mlutze**
related to #4967. Some minor breaking changes include moving RedBlackTree and Random up a level to use companion namespacing

### CODE REVIEW

**Comment by magnus-madsen** [comment]
RFR/RFM?

**Comment by magnus-madsen** [comment]
There is also one conflict.

**Comment by mlutze** [comment]
Actually, it might be easier on you if we migrate the tests separately, since that will likely be fairly large as well.

**Comment by magnus-madsen** [comment]
> Actually, it might be easier on you if we migrate the tests separately, since that will likely be fairly large as well.

Ok

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
