### PR TITLE
chore: use system font in sidebar items in HTML documentation

### PR DESCRIPTION
**Pull request by sockmaster27**
I think the system font is the best font to use here to stay consistent.

Related to #6327

### CODE REVIEW

**Comment by magnus-madsen** [comment]
What is the system font? I would prefer we actually set the font.

**Comment by sockmaster27** [comment]
The system font is the one that matches the headings in the sidebar

**Comment by magnus-madsen** [comment]
> The system font is the one that matches the headings in the sidebar

Right, but it would be different depending on Windows/Linux/Mac. I would like us to fix a font. If you don't have a suggestion, I can look once I am home. But maybe 'Roboto'?

**Comment by sockmaster27** [comment]
I think [Inter](https://fonts.google.com/specimen/Inter/about?category=Sans+Serif&vfonly=true&subset=latin) would be the safe choice.

**Comment by magnus-madsen** [comment]
Let's try it

**Comment by sockmaster27** [comment]
May I change the font in the doc strings too?

**Comment by magnus-madsen** [comment]
> May I change the font in the doc strings too?

Just the menu for now. 

But later there will be an opportunity to play :)

**Comment by sockmaster27** [comment]
I'll just drop some options here...

Roboto:
image

Open Sans:
image

Geologica:
image

Noto Sans:
image

Inter:
image


I think I'm somewhere between the last two, slightly leaning towards Noto Sans. Any thoughts?

**Comment by sockmaster27** [comment]
We have to remember that picking the right font is the most important part of this whole project.

**Comment by magnus-madsen** [comment]
How about this: If you give me 'Roboto' but only in the menu then later I will allow you to experiment with a different palette :)

**Pull request closed without merging**
