### PR TITLE
fix: maven JAR paths

### LINKED ISSUE #6272: Maven dependencies problems
Hello!

I'm trying build anything using Flix to see how work. I liked very much of language. I'm trying add some maven dependencies on my tom file, but something is not right.

1 - Apparently I can't use a dependency whose version has anything other than numbers.

```
[mvn-dependencies]
"org.junit.jupiter:junit-jupiter-api" = "5.9.2"
"io.netty:netty-all" = "5.0.0.Alpha2"
```

```
 This toml file has a version number which includes things that are not numbers: 5.0.0.Alpha2.
 For input string: "Alpha2"
 The toml file was found at /mnt/data/sources/flix/app/flix.toml.
```

2 - There seems to be something wrong with resolving maven dependencies

```
[mvn-dependencies]
"org.junit.jupiter:junit-jupiter-api" = "5.9.2"
"com.linecorp.armeria:armeria" = "1.24.2"
"ch.qos.logback:logback-classic" = "1.4.7"
"org.slf4j:log4j-over-slf4j" = "1.7.36"
```
```
Dependency resolution completed.                                                                                                                     
java.lang.IllegalArgumentException: '/mnt/data/sources/flix/app/lib/cache/https/repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.1.94.Final/netty-transport-native-epoll-4.1.94.Final.jar' must be a file.                                                                                  
        at ca.uwaterloo.flix.api.Flix.addJar(Flix.scala:429)                                                                                         
        at ca.uwaterloo.flix.api.Bootstrap.$anonfun$reconfigureFlix$6(Bootstrap.scala:438)                                                           
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)                                                                          
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)                                                                         
        at scala.collection.AbstractIterable.foreach(Iterable.scala:933)                                                                             
        at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:903)                                                                       
        at ca.uwaterloo.flix.api.Bootstrap.reconfigureFlix(Bootstrap.scala:437)                                                                      
        at ca.uwaterloo.flix.api.Bootstrap.build(Bootstrap.scala:491)                                                                                
        at ca.uwaterloo.flix.api.Bootstrap.run(Bootstrap.scala:597)                                                                                  
        at ca.uwaterloo.flix.Main$.$anonfun$main$17(Main.scala:206)                                                                                  
        at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:462)
        at ca.uwaterloo.flix.Main$.main(Main.scala:201)
        at ca.uwaterloo.flix.Main.main(Main.scala)

```

The dependency `netty-transport-native-epoll-4.1.94.Final.jar` was downloaded on  `.m2` folder, but not was copy to `cache` folder. If I manually copy the file, I get the following error:

```
java.lang.IllegalArgumentException: '/mnt/data/sources/flix/app/lib/cache/https/repo1.maven.org/maven2/com/aayushatharva/brotli4j/native-linux-x86/64/1.12.0/64-1.12.0.jar' must be a file.
        at ca.uwaterloo.flix.api.Flix.addJar(Flix.scala:429)
        at ca.uwaterloo.flix.api.Bootstrap.$anonfun$reconfigureFlix$6(Bootstrap.scala:438)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
        at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:903)
        at ca.uwaterloo.flix.api.Bootstrap.reconfigureFlix(Bootstrap.scala:437)
        at ca.uwaterloo.flix.api.Bootstrap.build(Bootstrap.scala:491)
        at ca.uwaterloo.flix.api.Bootstrap.run(Bootstrap.scala:597)
        at ca.uwaterloo.flix.Main$.$anonfun$main$17(Main.scala:206)
        at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:462)
        at ca.uwaterloo.flix.Main$.main(Main.scala:201)
        at ca.uwaterloo.flix.Main.main(Main.scala)

```

This lib `64-1.12.0.jar` isn't a valid dependency. I couldn't find it in the maven repositories.

If you can help me I would appreciate it. Keep up the amazing work!

### PR DESCRIPTION
**Pull request by magnus-madsen**
Fixes #6272

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@mlutze Can you approve?

**Comment by magnus-madsen** [comment]
@stephentetley Could I ask you to confirm that this does not break your code?

**Comment by magnus-madsen** [comment]
!!!jar

**Comment by mlutze** [comment]
Can you explain the change?

**Comment by magnus-madsen** [comment]
> Can you explain the change?

We were manually constructing paths to the JAR-files, but sometimes incorrectly.

Turns out that `run` seemingly just returns `File` objects pointing to the downloaded JARs.

**Comment by stephentetley** [comment]
I've run it on my projects with the most complicated Maven deps and it seems fine.

**Review by mlutze — APPROVED** [review]

**Pull request merged**
