### PR TITLE
Add scopedness rules to typer

### PR DESCRIPTION
**Pull request by mlutze**
Step 3 of https://github.com/flix/flix/issues/770

### Features
* A scoped value cannot be returned from a function.
  * [x] impl
  * [x] test
* A scoped value cannot be stored in a reference or array, or sent on a channel.
  * [x] impl
  * [x] test
* Otherwise, scoped values work as normal values.
  * [x] impl
  * [x] test
* Scopedness carries through value construction.
  * [x] impl
  * [x] test
* Scopedness carries through value destruction.
  * [x] impl
  * [x] test
* Scopedness can be declared through function parameters.
  * [x] impl
  * [x] test
* Scopedness can be declared through a `let`.
  * [x] impl
  * [x] test
* Scopedness can be declared through a lambda parameter.
  * [x] impl
  * [x] test

### General requirements
* [x] Don't make a complete mess
* [x] Don't break anything else
* [x] Provide documentation
* [x] Add license to new files
* [x] Manually check new error formatting
* [x] Manually check diff

### CODE REVIEW

**Comment by mlutze** [comment]
!!!benchmark

**Comment by mlutze** [comment]
!!!benchmark

**Comment by mlutze** [comment]
Should I be doing extensive testing now, or should that wait until we do the _Great Type Refactoring_?

**Comment by magnus-madsen** [comment]
> Should I be doing extensive testing now, or should that wait until we do the _Great Type Refactoring_?

How about some positive tests (and a few negative tests) for the parts that should work already?

**Comment by mlutze** [comment]
@magnus-madsen I added several tests. Do you have any thoughts on additional positive tests to include?

**Pull request closed without merging**
