### PR TITLE
refactor: remove `{mod, rem}` for floats

### PR DESCRIPTION
**Pull request by jaschdoc**
Depends on #2908

### CODE REVIEW

**Comment by magnus-madsen** [comment]
We might as well remove `$FLOAT32_REM$` and its friend from the entire compiler pipeline. 

If you do a search for it you should be able to find the relevant parts.

**Comment by jaschdoc** [comment]
Doesn't look like there is anything else to change. Same result for `Float64`.
Screenshot from 2021-12-27 18-29-43

**Comment by magnus-madsen** [comment]
Try without dollars. I think.

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
