### PR TITLE
feat: add `TwoList`

### PR DESCRIPTION
**Pull request by magnus-madsen**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
The plan is to use this for e.g. Union two ensure it is non-empty and non-trivial.

**Comment by JonathanStarup** [comment]
imagine how jealous the Nel issue will be that has waited for years 😄

**Comment by magnus-madsen** [comment]
> imagine how jealous the Nel issue will be that has waited for years 😄

:D

**Review by JonathanStarup — APPROVED** [review]

**Comment by mlutze** [comment]
> imagine how jealous the Nel issue will be that has waited for years 😄

What in blazes

**Pull request merged**
