### PR TITLE
refactor: change java import keywords

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes https://github.com/flix/flix/issues/7331

### CODE REVIEW

**Comment by jaschdoc** [comment]
I can update the parser to still support the old syntax?

**Comment by magnus-madsen** [comment]
> I can update the parser to still support the old syntax?

Yes, let us allow both for now.

Can you also take a look at `ImportCompleter` and all its subcompleters? They need to be adjusted.

Ditto for the book.

**Comment by magnus-madsen** [comment]
- [ ] Book
- [ ] Highlight.js
- [ ] VSCode
- [ ] Completion providers for everything related to import

**Comment by magnus-madsen** [comment]
Also let us _NOT_ allow both syntaxes. My goal is to get the "pain" over this week, so by next week Herluf has a clean slate.

**Comment by jaschdoc** [comment]
- [ ] Book
- [ ] Highlight.js
- [ ] VSCode
- [ ] Completion Providers

**Comment by jaschdoc** [comment]
What must be updated in the vscode extension?

**Comment by magnus-madsen** [comment]
> What must be updated in the vscode extension?

`Syntax.tm`

**Comment by magnus-madsen** [comment]
@jaschdoc This:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ImportFieldCompleter.scala#L28-L31

must also be updated. Ditto for the other Import* classes.

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
