### PR TITLE
Create Statistics phase

### PR DESCRIPTION
**Pull request by mlutze**

### CODE REVIEW

**Comment by mlutze** [comment]
Output when I add this after `Typer` and run on just the StdLib:
```
Var,12093
Apply,7232
Def,3377
Sig,2630
True,1922
Lambda,1634
Int32,1534
Tag,1245
Unit,1112
Let,1104
Binary,1075
Match,930
Tuple,806
Str,645
IfThenElse,529
Cast,449
ArrayLoad,239
Stm,213
InvokeMethod,180
Deref,176
InvokeStaticMethod,112
Lazy,105
Universal,100
False,74
Int64,57
ArrayLit,44
Int8,43
Int16,43
Unary,42
TryCatch,41
Assign,40
Hole,40
Ref,37
ArrayStore,30
BigInt,27
RecordSelect,25
InvokeConstructor,18
Float32,15
Spawn,14
RecordExtend,14
Float64,13
Char,13
Ascribe,12
Choose,12
NewChannel,11
Default,10
ArrayLength,7
GetStaticField,6
RecordEmpty,5
ArrayNew,5
ArraySlice,4
PutChannel,4
MatchEff,2
GetChannel,1
Force,1
SelectChannel,1
```

**Comment by magnus-madsen** [comment]
Could we add a flag `--Xstatistics`? I remember it existed at one point.

**Comment by magnus-madsen** [comment]
image

**Comment by magnus-madsen** [comment]
image

**Pull request merged**
