### PR TITLE
feat: basic regex support (issue #5614)

### PR DESCRIPTION
**Pull request by stephentetley**
This PR adds basic regex support to the stdlib. It provides a `Pattern` module wrapping `java.util.regex.Pattern` and twenty text manipulation functions mostly patterned after functions in Flix's existing `String` module.

Intentionally, it doesn't handle user defined iteration schemes over a matcher (Java's regex library provides a Matcher object which is a mutable iterator like object), or expose "match results" which would be the way to extract capture groups or start / end of the current match. For the time being, these are avoided being because they really need a monad (or an effect) to give them a nice functional interface.

Discussion points:

Maybe `Regex.Text` is not the best name for the String-like functions?

The String-like functions use named arguments (one element records) where the String library does. The Regex versions of the functions enjoy different types (Pattern and String) for the "needle" and the "haystack" that the String library doesn't (String and String). Perhaps the Regex functions don't need named arguments?

Regex.Text API: 

~~~

pub def isMatch(patt: Pattern, s: String): Bool
pub def isSubmatch(patt: Pattern, s: String): Bool
pub def indices(substr: {substr = Pattern}, s: String): List[Int32]
pub def submatches(substr: {substr = Pattern}, s: String): List[String]
pub def countSubmatches(substr: {substr = Pattern}, s: String): Int32
pub def split(pattern: {pattern = Pattern}, s: String): List[String]
pub def replace(from: {from = Pattern}, to: {to = String}, s: String): String
pub def replaceFirst(from: {from = Pattern}, to: {to = String}, s: String): String
pub def startsWith(prefix: {prefix = Pattern}, s: String): Bool
pub def endsWith(suffix: {suffix = Pattern}, s: String): Bool
pub def stripPrefix(substr: {substr = Pattern}, s: String): Option[String]
pub def stripSuffix(substr: {substr = Pattern}, s: String): Option[String]
pub def indexOfFirst(substr: {substr = Pattern}, s: String): Option[Int32]
pub def indexOfLast(substr: {substr = Pattern}, s: String): Option[Int32]
pub def indexOfFirstWithOffset(substr: {substr = Pattern}, offset: {offset = Int32}, s: String): Option[Int32]
pub def indexOfLastWithOffset(substr: {substr = Pattern}, offset: {offset = Int32}, s: String): Option[Int32]
pub def breakOnFirst(substr: {substr = Pattern}, s: String): (String, String)
pub def breakAfterFirst(substr: {substr = Pattern}, s: String): (String, String)
pub def breakOnLast(substr: {substr = Pattern}, s: String): (String, String)
pub def breakBeforeLast(substr: {substr = Pattern}, s: String): (String, String)

~~~

An implementation note - string scanning is different between Regex (subsequent matches, always left-to-right) and the String module (character by character, left-to-right or right-to-left), hence some functions are slightly different between the two modules:

~~~

String.indexOfLeft ~> Regex/Text.indexOfFirst
String.breakOnRight ~> Regex/Text.breakOnLast

etc.

~~~~

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I am wondering whether to reorganize the modules since some functionality that is "private" is currently public.

**Comment by magnus-madsen** [comment]
For example, maybe we should throw everything into `Regex` and add compiler support for `Pattern`.

**Comment by magnus-madsen** [comment]
> > For example, maybe we should throw everything into `Regex` and add compiler support for `Pattern`.
> 
> Yes that would make sense. `Matcher` could be a public module later when we decide whether it should be an interator, effect, monad...

Yes, for now I just want a simple lean interface.

**Comment by magnus-madsen** [comment]
At some point there should be a discussion about what goes into the std lib and what goes into packages, but I think there is space for regex library in the std lib.

**Comment by stephentetley** [comment]
I'm on holiday today, so I've updated the PR to put all the regex code in a single module.

**Comment by stephentetley** [comment]
I've kept the `Pattern` type inside the `Regex` namespace. "Pattern" seemed a too general name to be be at the top level.

**Comment by stephentetley** [comment]
Just pushed a new change to use `forM` rather than `let*`.

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
