### PR TITLE
chore: exclude `@Internal` definitions from completions

### LINKED ISSUE #3514: LSP: Hide `@Internal` names from autocomplete, etc.

### PR DESCRIPTION
**Pull request by paulbutcher**
Fixes #3514.

This works, but there are a couple of things that might need looking at:

* I copied the definition of `isInternal` from `Documentor`. There should probably just be a single copy somewhere, but I'm not sure where would be the best place to put it?
* The code within `Documentor` also checks for `@Internal` annotations on classes and enums. But I can't find any examples of classes and enums which are marked as internal? Am I missing something?

### CODE REVIEW

**Comment by paulbutcher** [comment]
Can you point me at them, because I really can't find any examples:

```
% grep "@Internal" --context=2 -r | grep -i class
% grep "@Internal" --context=2 -r | grep -i enum 
```

Having said that, even if it's not currently used, if it's possible then I should handle it in the language server. I'll update the PR to do so.

**Comment by paulbutcher** [comment]
Did you have any thoughts on where (or if) I should put a shared implementation of `isInternal`?

**Comment by magnus-madsen** [comment]
> Did you have any thoughts on where (or if) I should put a shared implementation of `isInternal`?

I think its so small that duplication is okay. Its not like it does anything complicated.

**Comment by magnus-madsen** [comment]
I guess we don't complete on enums/tags yet, so then this PR is also complete?

**Comment by paulbutcher** [comment]
If you're OK with it as it is, then I am too 👍

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
