### PR TITLE
refactor: add explicit wild type in effect casts

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes https://github.com/flix/flix/issues/2755

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I suggest to enforce that you write either:

- `cast exp as Type \ Effect` or 
- `cast exp as _ \ Effect` 

but nothing with `&`. Can we try that?

**Comment by jaschdoc** [comment]
Ok it works now. I'd forgotten about some whitespace I'd previously put in the wrong place.

**Comment by magnus-madsen** [comment]
@stephentetley This changes the cast syntax to require an underscore if you don't cast the type, e.g. now you must write `unsafe_cast exp as _ \ {}` for example.

**Comment by magnus-madsen** [comment]
Thanks!

**Comment by stephentetley** [comment]
Thanks for the heads up Magnus, it should be an easy change now I'm already using `unsafe_cast`.

**Pull request merged**
