### PR TITLE
refactor: rename `Optimizer` and friends

### PR DESCRIPTION
**Pull request by jaschdoc**
Rename to `Optimizer2`, `OccurrenceAnalyzer2`, `Inliner2`

This is to allow for the new `Optimizer` which runs before `ClosureConv`, following the same naming scheme as `TreeShaker`

### CODE REVIEW

**Comment by magnus-madsen** [comment]
But, I thought the old Optimizer would be removed?

**Comment by jaschdoc** [comment]
It will, I just wanted to rename it before adding the new one, which could then safely allow me to remove the old one

**Comment by magnus-madsen** [comment]
Hmm. Just call the new one for 1 or 2? :)

**Comment by magnus-madsen** [comment]
Then we don't break arewefast etc.

**Pull request closed without merging**
