### PR TITLE
feat: Zhegalkin to SetFormula

### PR DESCRIPTION
**Pull request by JonathanStarup**
now without superexponential blowup

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I suppose this helps, but how can I know if the translation is still too costly? (since it is not linear)

**Comment by JonathanStarup** [comment]
to costly compared to what? They are both worst case `O(|vars| * 2 ^ |vars|)` big so it should be around the same size

**Comment by magnus-madsen** [comment]
The translation is not linear, is what I meant.

**Comment by JonathanStarup** [comment]
The runtime of the translation is `O((|vars| * 2 ^ |vars|)^2)` i think. but i think its the best we can do, going directly to set formula

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
> The runtime of the translation is `O( (|vars| * 2 ^ |vars|) * (2^|vars|) )` i think. but i think its the best we can do, going directly to set formula

What I mean is that we should add `Xor` to SetFormula so the translation is one-to-one.

I can merge this PR and do experiments, but they will not really tell me whether it performs well, right?

**Pull request merged**
