### PR TITLE
Add `import pure` expression

### PR DESCRIPTION
**Pull request by mlutze**
Fixes https://github.com/flix/flix/issues/2498

### CODE REVIEW

**Comment by magnus-madsen** [comment]
What happened to the prettier syntax with `as & Pure` at the end?

**Comment by magnus-madsen** [comment]
Presumably this should also lead to some refactorings in the std lib?

**Comment by mlutze** [comment]
> What happened to the prettier syntax with `as & Pure` at the end?

Currently it clashes with the renaming import syntax.

**Comment by mlutze** [comment]
> Presumably this should also lead to some refactorings in the std lib?

Yes, I think so.

**Comment by magnus-madsen** [comment]
> 
> 
> > What happened to the prettier syntax with `as & Pure` at the end?
> 
> Currently it clashes with the renaming import syntax.

Does it actually. I would assume that the `&` would distinguish them. 

Do you want to wait for that PR to make it in?

**Comment by mlutze** [comment]
Syntactically unambiguous maybe, but conceptually confusing to a user I would think. If that one is on the way soon, we can wait for it. Otherwise I'll change this one

**Comment by magnus-madsen** [comment]
How do you want to go about the changes? I think the most productive is if the standard library does not have to be updated twice. If we have the compiler changes ready then I can ask a student programmer to take over and update the std. lib.

**Comment by mlutze** [comment]
I agree with only changing the library once. Should I add the other import changes (https://github.com/flix/flix/issues/2512) to this PR?

**Comment by magnus-madsen** [comment]
Yes, but just so we agree, the {} will not be necessary if you import a single thing, right?

**Comment by mlutze** [comment]
> Yes, but just so we agree, the {} will not be necessary if you import a single thing, right?

Agreed

**Comment by mlutze** [comment]
> Yes, but just so we agree, the {} will not be necessary if you import a single thing, right?

The way the current implementation is headed, the `{}` will be necessary if you import a single thing and need to rename it. This is to match the `use` restrictions. Is that ok?

```scala
use ##java.lang.Object.toString(); // ok
use ##java.lang.Object.{toString() => javaToString}; // renaming requires {...}
```

**Comment by JonathanStarup** [comment]
Another difference between the two: `import java.lang.Object.toString()` results in an error if it isn't used but `use Int32.max` is fine to not use

**Comment by magnus-madsen** [comment]
> Another difference between the two: `import java.lang.Object.toString()` results in an error if it isn't used but `use Int32.max` is fine to not use

This is just missing implementation. We need to keep the Use nodes and check that they are used.

I think putting stuff at the front is a mistake, e.g. `import pure ...` or even `import get ... `. I think we need to find something that Java programs would find familiar.

btw. where is the ticket with the general syntax discussion?

**Comment by JonathanStarup** [comment]
#2512

**Comment by magnus-madsen** [comment]
I will close this because we are going in a different direction.

**Pull request closed without merging**
