### PR TITLE
proposal: SVE on table form

### PR DESCRIPTION
**Pull request by JonathanStarup**
frontend throughput with all subeffecting is 10% faster on my PC

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@JonathanStarup There is some conflict. If you resolve it and rebase/merge then I can run it on the server to see if there is any real impact.

**Comment by magnus-madsen** [comment]
The conclusion was that this is faster, but some tests seem to fail.

**Comment by JonathanStarup** [comment]
Since `tableForm` is actually tested, my current thinking is that it triggers the purification error. The failures look similar to the last time I did it with the variable bias.

**Comment by magnus-madsen** [comment]
Do we just mark it as blocked then and leave it be?

**Pull request closed without merging**
