### PR TITLE
feat: optimize monoTypes

### PR DESCRIPTION
**Pull request by JonathanStarup**
* before
  * discover enums in defs, when a new enum is found, immediately specialize
* Trick 1
  * first discover enums in defs in parallel, then recursively specialized enums with frontier synchronization.
  * Performance gain: 1.2x (1 vs 8 cores)
* Trick 2
  *  don't synchronize `get`, only put
  * (I don't know if this is actually safe in the scala hashmap)
  * Performance gain (with trick 1) 2.6x (1 vs 8 cores)

### CODE REVIEW

**Comment by JonathanStarup** [comment]
@magnus-madsen this is not polished but i think the takeaway is that we should take advantage of the fact that enum2enum has no updates, only insertions. Seems everybody is slamming the map lock

**Comment by magnus-madsen** [comment]
I think you have to synchronize on `get` otherwise the map could be outdated. It is a race condition (like in MonoDefs-- which should be fixed).

**Comment by magnus-madsen** [comment]
Try to swap the Scala map for https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html

**Comment by magnus-madsen** [comment]
I think you have to use [computeIfAbsent](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#computeIfAbsent-K-java.util.function.Function-)

**Comment by JonathanStarup** [comment]
> I think you have to synchronize on `get` otherwise the map could be outdated. It is a race condition (like in MonoDefs-- which should be fixed).

how would it be outdated? either its there, which will always have the same mapping; or it's not there, in which case it goes to the synchronized getOrPut

**Comment by JonathanStarup** [comment]
> Try to swap the Scala map for https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html

but yeah this also doesn't always block on get so it should be perfect

**Comment by magnus-madsen** [comment]
You are both accessing and updating a mutable data structure concurrently-- that is a not generally allowed.

**Comment by magnus-madsen** [comment]
What was the conclusion here?

**Comment by JonathanStarup** [comment]
Ill write it up in tickets

**Pull request closed without merging**
