### PR TITLE
feat: unexpected effect

### PR DESCRIPTION
**Pull request by mlutze**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
What, exactly, does this change do? :)

**Comment by mlutze** [comment]
This just adds two new errors: unexpected effect and possible effect upcast. If we're expecting a supereffect of the inferred effect, it suggests to upcast. Note that there is no special casing for when we are looking at the top level, so there's no "add this to the effect annotation" prompt.

**Comment by magnus-madsen** [comment]
> This just adds two new errors: unexpected effect and possible effect upcast. If we're expecting a supereffect of the inferred effect, it suggests to upcast. Note that there is no special casing for when we are looking at the top level, so there's no "add this to the effect annotation" prompt.

Can we use this to build a quickfix or not yet?

**Comment by magnus-madsen** [comment]
Like what's the improvement?

**Comment by mlutze** [comment]
Not the quickfix you want. The improvement is that before it was something like "mismatched effects: type one: ... type two: ..." so now it's at least a bit more specific and tells you that you can upcast.

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
