### PR TITLE
refactor: use let rec in `LazyList`

### LINKED ISSUE #3122: Prepare `DelayList` for release
I've looked over `DelayList` and here are some of the issues I found.

~~**Functions that could be added**~~
~~`init`~~

~~**Use LetRec?**~~

~~**Docs that need fixing**~~
~~`append`~~
~~`intersperse`~~

**Rename these**
~~`x: a` to `a: a`~~
~~`mapL` to `mapLazy` and `mapE` to `mapEager` etc.~~
~~`ks -> ks` to use `identity`~~

**Functions**
~~- `intersperse` - Could be more lazy. I don't like the `LCons` case that forces the tail, maybe adding an `insert` helper function could alleviate the problem? I'm not sure about this~~
~~- `intercalate` - Same as above~~
~~- `zip` - Simplify. Have the base cases with `ENil` and otherwise just delegate to `zipHelper` and wrap in `LList` i.e. `LList(lazy zipHelper(l1, l2))`~~

~~Discussion: Should private lazy functions have the `@Lazy` annotation? Currently, some do and some don't.~~

~~Maybe the file should also be reordered again. `Map` is in the middle, `fold`s and `filter` is near the bottom and maybe they should be at the top s.t. the further down the file you read the functions are less commonly used and perhaps more complex?~~

@magnus-madsen What's your input?

**Edit**
Add `SemiGroup` instance
Add `Monoid` instance
Add `Applicative` instance
Add `Monad` instance
Add `Traversable` instance

Related to #3153

### LINKED ISSUE #3153: LetRec: Refactor `LazyList`

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes #3153

### CODE REVIEW

**Comment by jaschdoc** [comment]
This PR is paused / blocked for now.

**Comment by magnus-madsen** [comment]
Pending my feedback, I assume? Ill try to get to it!

**Comment by jaschdoc** [comment]
I tried making `partition` more readable by using `identity` and a record instead of a continuation function that takes two parameters but I fear it may be far worse than before. Thoughts? Maybe @mlutze has some input too.
Link to `partition`: https://github.com/jaschdoc/flix/blob/bbc5c8d45b54130eeba92df02534ffde3fd4d66f/main/src/library/LazyList.flix#L745

**Comment by jaschdoc** [comment]
@magnus-madsen RFR

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
