### PR TITLE
refactor: rename `--github-key` to `--github-token`

### LINKED ISSUE #6973: Rename `--github-key` to `--github-token`

### PR DESCRIPTION
**Pull request by bathtub-01**
Resolves #6973

- renamed the command line option from `--github-key` to `--github-token`
- renamed the field `githubKey` to `githubToken` in `Options` and `CmdOpts` classes

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Hi @bathtub-01 and welcome :)

**Comment by magnus-madsen** [comment]
Your PR looks good. 

Could I ask you to add your name to `AUTHORS.md` as a way to confirm that you make your contributions open source.

Thanks!

**Comment by bathtub-01** [comment]
OK. It's my pleasure!

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
Merged! Congratulations on your first PR.

**Pull request merged**
