### PR TITLE
refactor: allow pure upcast to any effect

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes https://github.com/flix/flix/issues/4939

### CODE REVIEW

**Comment by jaschdoc** [comment]
I'm not quite sure what's wrong here. It errors with
```flix
namespace Foldable {
// ...
    pub def foldLeftM(f: (b, a) -> m[b] \ ef, s: b, t: t[a]): m[b] \ ef with Monad[m] =
        let f1 = (x, acc) -> z -> Monad.flatMap(acc, f(z, x));
        s |> Foldable.foldRight(f1, upcast x1 -> Applicative.point(x1), t)
}
```
```
-- Type Error -------------------------------------------------- Foldable.flix

>> No instance of the 'Applicative' class for the type ''0'.

354 |         s |> Foldable.foldRight(f1, upcast x1 -> Applicative.point(x1), t)
                                                       ^^^^^^^^^^^^^^^^^^^^^
                                                       missing instance
```
so it seems like `x1` is cast to type variable which isn't substituted with the concrete type so a TC instance can be derived? Or is that just wrong? :see_no_evil:

**Comment by magnus-madsen** [comment]
Can you try to leave in the parens?

**Comment by jaschdoc** [comment]
> Can you try to leave in the parens?

Same result
```
-- Type Error -------------------------------------------------- Foldable.flix

>> No instance of the 'Applicative' class for the type ''0'.

354 |         s |> Foldable.foldRight(f1, upcast (x1 -> Applicative.point(x1)), t)
                                                        ^^^^^^^^^^^^^^^^^^^^^
                                                        missing instance
```

**Comment by magnus-madsen** [comment]
I think we need to ask @mlutze for help.

**Comment by mlutze** [comment]
This is because upcast kind of separates the expression from the rest of the function.

Roughly, the inference goes:

Visited Expression | Inferred Types | Inferred Type Constraints
--- | --- | ---
`x1` | `x1: t1` | 
`body = Applicative.point(x1)` |  `x1: t1`, `body: t2[t1]` | `Applicative[t2]`
`lam = x1 -> Applicative.point(x1)` | `x1: t1`,  `body: t2[t1]`, `lam: t1 -> t2[t1]` |  `Applicative[t2]`
`up = upcast x1 -> Applicative.point(x1)` | `x1: t1`,  `body: t2[t1]`, `lam: t1 -> t2[t1]` `up: t3`| `Applicative[t2]`

The important part is the `up: t3`. Now when we get the type of the whole expression, we have something involving `t3` but not `t1` and `t2`, which means that when we unify with the signature of the function that says that `Monad[m]`, there is nothing that connects `m` with `t2`.

I think the easy fix is to add an ascription in the expression, something like this: `upcast x1 -> Applicative.point(x1): m[b]`

**Comment by jaschdoc** [comment]
Should work now! Hopefully, we can start to remove the `upcast` function from the Prelude and start to merge `super_cast` with `upcast`.

**Pull request merged**
