### PR TITLE
fix: check kinds of associated type

### PR DESCRIPTION
**Pull request by mlutze**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I think you found a bug in a test suite :)

**Comment by magnus-madsen** [comment]
The space for kind errors is much larger, including some of the examples I gave. Can we extend the tests?

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
Test suite still mad at you :)

**Comment by mlutze** [comment]
> Test suite still mad at you :)

The feeling is mutual

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
