### PR TITLE
fix: remove erasure on `[""; 12]`-like expressions

### LINKED ISSUE #3332: JVM interop - marshaling "constructed" arrays causes crash ("literal" arrays don't crash)
Java interop has a problem where "constructed" arrays (e.g by `List.toArray`) cause a crash when they are passed to a native Java method. Literal arrays (i.e. statically specified with Flix's array syntax) can be passed successfully to the native Java method:

Toggling the version of `newPath` in the code below shows the problem:

~~~

def main(_args: Array[String]): Int32 & Impure = 
    println("Test1...");
    newPath("/home", Nil) |> pathToString |> println;
    println("Test2...");
    newPath("/home", "work" :: "flix" :: Nil) |> pathToString |> println;
    0

pub def newPath(s: String, rest: List[String]): ##java.nio.file.Path & Impure =
    import static java.nio.file.Path.of(String, Array[String]): ##java.nio.file.Path & Impure as of1;
    let arr1 = List.toArray(rest);    
    of1(s, arr1)


/// pub def newPath(s: String, _rest: List[String]): ##java.nio.file.Path & Impure =
///     import static java.nio.file.Path.of(String, Array[String]): ##java.nio.file.Path & Impure as of1;
///     let arr1 = ["work", "flix"];
///     of1(s, arr1)


pub def pathToString(p1: ##java.nio.file.Path): String =
    import java.nio.file.Path.toString(): String & Pure;
    toString(p1)

~~~

The error message from using the proper version of `newPath` - note that via the implementation of `List.toArray` Test1 actually uses an array created with the literal syntax: 

~~~

> java -jar ..\bin\flix-working.jar .\temp\test-marshal-arr2.flix
Test1...
\home
Test2...
Exception in thread "main" java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.String; ([Ljava.lang.Object; and [Ljava.lang.String; are in module java.base of loader 'bootstrap')
        at Clo%newPath%819994.invoke(Unknown Source)
        at Cont%Obj.unwind(Cont%Obj)
        at Def%main.invoke(Unknown Source)
        at Cont%Int32.unwind(Cont%Int32)
        at Ns.m_main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$link$1(JvmBackend.scala:285)
        at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$getCompiledMain$2(JvmBackend.scala:246)
        at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$getCompiledMain$2$adapted(JvmBackend.scala:244)
        at ca.uwaterloo.flix.Main$.main(Main.scala:217)
        at ca.uwaterloo.flix.Main.main(Main.scala)

~~~

### PR DESCRIPTION
**Pull request by JonathanStarup**
This removes the erasure on ArrayNew expresssions in the backend. This means that `["a"; 12]` is of jvm type `String[]` instead of `Object[]`. This seems to be fine but I haven't thought it through yet. It might generate wrong code with nested arrays? maybe?

One argument for is that ArrayLit has its actual non-erased type so this constructor should probably do the same?

Fixes #3332.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Will you add some test cases? Not sure how...

**Comment by magnus-madsen** [comment]
Could you add some tests? I think the smartest would be to extend "TestClass" with methods that expect specific arrays, e.g. `Int[]`, `Double[]`, `String[]` etc and then call those. If you add the test file, update the test class, and show how to do it for two specific types, I can ask one of the student programmers to fill in the rest.

Btw, what about multidim arrays?

**Comment by JonathanStarup** [comment]
> Btw, what about multidim arrays?

That is the reason I think this might be dangerous but I'm not sure. Some places in the backend it hardcoded checks for arrays of dimension 1 or 2 i think. I don't fully understand how they work with erasure either. I might just crash somewhere if there is a three dimensional array instead of a one dimensional array of type object.

**Comment by magnus-madsen** [comment]
OK, but could you try some tests etc. I know Stephen is running into this issue.

**Comment by magnus-madsen** [comment]
Close or merged?

**Comment by JonathanStarup** [comment]
im leaning towards close

**Pull request closed without merging**
