### PR TITLE
chore: format Unit -> X signatures correctly

### LINKED ISSUE #3401: `fmt.FormatSignature` must format Unit functions correctly.

### PR DESCRIPTION
**Pull request by mlutze**
fixes #3401

### CODE REVIEW

**Comment by mlutze** [comment]
!!!jar

**Comment by mlutze** [comment]
Screenshot from 2022-03-24 10-26-08

**Comment by magnus-madsen** [comment]
Should we have a formatSig or formatDef or something?

**Comment by mlutze** [comment]
> Should we have a formatSig or formatDef or something?

What do you mean? This is already in the `FormatSignature` object.

**Comment by magnus-madsen** [comment]
> > Should we have a formatSig or formatDef or something?
> 
> What do you mean? This is already in the `FormatSignature` object.

OK

**Pull request merged**
