### PR TITLE
fix: remove casts from benchmark and benchmarks

### LINKED ISSUE #3992: Benchmarks being optimized away rather than run
It looks like Benchmark code (wrapped as a function `Unit -> Unit`) might be getting compiled away.

For instance running `Bench.Chain.flix` with options `--benchmark main/src/library/BenchMark/Bench.Chain.flix` I see:

~~~ {.console}

------------------------------ Running Benchmarks ------------------------------

Warmup: ........

Benchmark                                         Iterations          Time (avg)
List.ofArray                                         1000000             0 us/op
List.cons                                            1000000             0 us/op
List.snoc                                            1000000             0 us/op
List.append                                          1000000             0 us/op
Chain.ofArray                                        1000000             0 us/op
Chain.cons                                           1000000             0 us/op
Chain.snoc                                           1000000             0 us/op
Chain.append                                         1000000             0 us/op

Total time elapsed: 0 seconds. Time budget was: 250 seconds.

Process finished with exit code 0

~~~

### PR DESCRIPTION
**Pull request by JonathanStarup**
Fixes #3992. Related to #4047.

* All benchmark functions are impure by cast
* Benchmark files use namespaces
* Benchmark files use fewer arrays
* main is renamed to `runBenchmarks`.
* All unsafe purity casts are replaced by safe upcasts to Impure

### CODE REVIEW

**Comment by JonathanStarup** [comment]
!!!jar

**Comment by magnus-madsen** [comment]
Proper title? Remove casts from benchmarker?

**Comment by magnus-madsen** [comment]
Conflict, sorry :(

**Comment by magnus-madsen** [comment]
Looks good.

**Comment by JonathanStarup** [comment]
Will you merge this @magnus-madsen? Then ill do another round of graphs

**Pull request merged**
