### PR TITLE
refactor: polish `Tailrec`

### PR DESCRIPTION
**Pull request by JonathanStarup**

### CODE REVIEW

**Comment by JonathanStarup** [comment]
Somehow its wrong to say that the body of letrec (`e2` in `letrec x = e1; e2`) is in tail position 🤔

**Comment by magnus-madsen** [comment]
> Somehow its wrong to say that the body of letrec (`e2` in `letrec x = e1; e2`) is in tail position 🤔

What was the solution to this?

**Comment by JonathanStarup** [comment]
The inliner also didn't look at letrec when rewriting recursive calls

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
