### PR TITLE
feat: turn --doc into doc

### LINKED ISSUE #3717: Don't launch REPL on `--doc`

### PR DESCRIPTION
**Pull request by mlutze**
fixes #3717, related to #3720

Currently requires the user to be in a Flix project, which I assume is too annoying.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
> Currently requires the user to be in a Flix project, which I assume is too annoying.

Yes, because how to generate for std lib.

**Comment by magnus-madsen** [comment]
This kind of blocks the way I build the documentation.

**Comment by magnus-madsen** [comment]
Should all package commands just work without being in a package format?

**Comment by mlutze** [comment]
> This kind of blocks the way I build the documentation.

Can you elaborate?



> Should all package commands just work without being in a package format?

Maybe someday, but for now there's a difference between `--test` and `test`, and `build-pkg` doesn't really work for non-package projects.

**Comment by magnus-madsen** [comment]
> 

I would work on unifying these. (Not sure about the build-pkg etc.)

**Comment by magnus-madsen** [comment]
We will revisit.

**Pull request closed without merging**
