### PR TITLE
feat: configurable max iterations

### PR DESCRIPTION
**Pull request by mlutze**
just for Jonathan

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I am very skeptical of this. Why do we need it? If the number is too low either there is a bug or it can be increased.

**Comment by JonathanStarup** [comment]
But we will never guess the correct number? now the user has a way out when they make weird 300 case enums

**Comment by JonathanStarup** [comment]
Its also nice for us for testing typing changes etc. It seems like a nice flexibility that doesn't really cost anything. its also an X flag

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
I will allow it because its an X flag, so it can be removed at any time.

**Pull request merged**
