### PR TITLE
feat: add propagation to SetSubstitution

### PR DESCRIPTION
**Pull request by JonathanStarup**
XPerf runs now

### CODE REVIEW

**Comment by JonathanStarup** [comment]
@magnus-madsen ping

**Review by magnus-madsen — APPROVED** [review]

**Comment by JonathanStarup** [comment]
Slight throughput increase on disabled subeffecting on my pc

**Comment by magnus-madsen** [comment]
Sounds good. Lets see what the server says 👍

**Comment by magnus-madsen** [comment]
@JonathanStarup When merged, I will report the results. Does this fix ford fulkerson?

**Pull request merged**
