### PR TITLE
feat: `FindReferencesProvider` with LSP visitor instead of Index

### PR DESCRIPTION
**Pull request by LoZander**
This PR changes the `FindReferenceProvider` to use the LSP visitor instead of the Index.

The provider uses two different searches using the LSP provider

1. Search for the most precise LSP node under the cursor. If this is a symbol that Flix supports "find references" for, then this will be the one we'll find the references to.
2. Search for all occurrencess of the aforementioned symbol.

In practice, since we assume a thin cursor, we repeat the first search for the symbol under the cursor for both the location on the immediate left and right of the cursor. This means that a total of three searches take place. In theory, it would only be necessary to start searching on the opposite side of the cursor if the initial searches on the first side finds nothing. This means that we don't always have to do three searches but instead sometimes only two. In fact, only when the cursor is at the very end of a symbol is it necessary to do three searches. But in practice we simply always do search 1) twice, based on the assumption that the cost of this redudent search is negligble. Further testing to see if this assumption holds might be warranted however.

Related to #9449.

### CODE REVIEW

**Comment by LoZander** [comment]
I still need to filter out references to the std library. But then I think this one is basically done

**Comment by magnus-madsen** [comment]
Here are also some tests to look into.

**Comment by magnus-madsen** [comment]
I think this just needs some polish and to figure out what is going on with the tests and then we are good to go?

**Comment by LoZander** [comment]
> I think this just needs some polish and to figure out what is going on with the tests and then we are good to go?

Yes. I believe that's what's left. I'll look into that now :)

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
Merged 🚀

**Pull request merged**
