### PR TITLE
feat: add `Foldable.join`

### LINKED ISSUE #3046: Add `Foldable.join` and `X.join`
Add 

```scala
pub def join(sep: String, f: f[a]): String with ToString[a] = ...
```

to `Foldable`. 

Add

```scala
pub def join(sep: String, l: List[a]): String with ToString[a] = ...
```

and similar to each collection namespace. (These can just call Foldable, except for mutable data structures which must be impure).

In each case , the implementation should use a `StringBuilder` for efficiency. (Note this requires a cast)

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes #3046 

- [x]  `List`
- [x]  `Nel`
- [x]  `Mutlist`
- [x]  `LazyList`
- [x]  `DemandList`
- [x]  `Array`
- [x]  `Iterator`
- [ ]  `Option` - does this even make sense?
- [ ]  `Result` - does this even make sense?
- [x]  `RedBlackTree`
- [x]  `Map`
- [x]  `DelayMap`
- [x]  `MutMap`
- [x]  `Set`
- [x]  `MutSet`
- [x]  `Chain`
- [x]  `MutDeque`

### CODE REVIEW

**Comment by jaschdoc** [comment]
@magnus-madsen I've added `{Map, RedBlackTree}.{joinValues, joinKeys}` but should we just stick to 1 `join` function that returns the mapping as the string `k => v`? For instance
```flix
Map#{1 => 2, 2 => 3} |> Map.join(", ") // returns "1 => 2, 2 => 3"
```

**Comment by jaschdoc** [comment]
@magnus-madsen RFR, also note my earlier comment

**Comment by magnus-madsen** [comment]
> @magnus-madsen I've added `{Map, RedBlackTree}.{joinValues, joinKeys}` but should we just stick to 1 `join` function that returns the mapping as the string `k => v`? For instance
> 
> ```
> Map#{1 => 2, 2 => 3} |> Map.join(", ") // returns "1 => 2, 2 => 3"
> ```

I think your choice to have two is the right one. (The one from Foldable will then be the joinValues).

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
