### PR TITLE
chore: experiment with migrating to Scala 3

### PR DESCRIPTION
**Pull request by jaschdoc**
Just submitting this pull request to make the Gradle pipeline work for me, as it's quirky on my own machine.

This is just something I wanted to try out and experiment with for a bit.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I guess this gets stuck with parboiled?

**Comment by jaschdoc** [comment]
This PR has low priority compared to the other issues btw

**Comment by magnus-madsen** [comment]
> This PR has low priority compared to the other issues btw

Definitely. Please don't spend any time on it. I was just curious where it got stuck. I suspected Parboiled is the issue and we will have to rewrite the Parser and that seems to be what you have just confirmed :)

**Comment by magnus-madsen** [comment]
This will not happen before we have reimplemented the parser.

**Pull request closed without merging**
