### PR TITLE
refactor: add phase names

### PR DESCRIPTION
**Pull request by JonathanStarup**
stored names for later prettyprinting interfacing

### CODE REVIEW

**Comment by magnus-madsen** [comment]
But why? 200 lines just for this abstraction? And you won't be able to reflect the strings into `flix.cachedXYZ` anyway?

**Comment by JonathanStarup** [comment]
> But why? 200 lines just for this abstraction? And you won't be able to reflect the strings into `flix.cachedXYZ` anyway?

Each phase name will show up in 4 places (showAstProvider, AstPrinterx3), so I thought it might be nice to have for ease of modification.  I can remove a lot of lines by removing the comments if you want.

**Comment by magnus-madsen** [comment]
Why can't we just have a single function: `String -> TheAstAsString`?

**Comment by JonathanStarup** [comment]
like 
```
enum PhaseString { case Parser, Eraser, .. }
def parse(s: String): PhaseString = match s {
    case "Parser" => Parser
    ..
}
```

**Comment by magnus-madsen** [comment]
I don't know why that would be needed either. Perhaps you can start by adding support for 3 ASTs to be printed and then we can use that to see what is needed.

**Pull request closed without merging**
