### PR TITLE
chore: rework Datalog debugging

### PR DESCRIPTION
**Pull request by magnus-madsen**
I believe (unchecked) effects casts are fundamentally broken, including `masked_cast`.

This does not solve the problem at all, but merely makes it go away.

### CODE REVIEW

**Review by mlutze — APPROVED** [review]

**Comment by JonathanStarup** [comment]
In my perspective `masked_cast` isn't broken, its meaning and use is just a bit odd.

**Comment by JonathanStarup** [comment]
did you figure out how specifically? it still seems weird to me

**Comment by magnus-madsen** [comment]
> did you figure out how specifically? it still seems weird to me

No exactly. I suspect that inlining leads to effects that are strange which causes miscompilation.

E.g. things like a pure expression having subexpressions with control-effects!

**Comment by JonathanStarup** [comment]
> pure expression having subexpressions with control-effects

Yeah, but as long as it isn't control effects then it should be okay. Here its just impure not control impure. but yeah i do think effects might not all be updated in the backend transformations. some of the effect recomputation seems a little dubious as far as i remember

**Comment by magnus-madsen** [comment]
It was typed as control impure.

**Pull request merged**
