### PR TITLE
docs: add thread effect example

### PR DESCRIPTION
**Pull request by jaschdoc**
WIP port from https://v2.ocaml.org/manual/effects.html

I'm not sure Flix allows it, though...

Related to https://github.com/flix/flix/issues/7093

### CODE REVIEW

**Comment by jaschdoc** [comment]
I think we can close this but there is a weird type error I'm not entirely sure is correct:

```scala
pub enum Status {
    case Complete(
    case Suspended(Int32, Int32 -> Int32)
}


def cont(m, c): Int32 = match c(m) {
    case Complete(v)       => v
    case Suspended(m1, c2) => cont(m1, c2)
};
Suspended(n, m -> cont(m, k))
```

```
-- Type Error -------------------------------------------------- examples/effects/Threads.flix

>> Expected type: 'Int32' but found type: 'Status'.

25 |                 Suspended(n, m -> cont(m, k))
                                       ^^^^
                                       expression has unexpected type.
```

**Comment by JonathanStarup** [comment]
I've made it work .. in some sense. It was a good exercise

It doesn't actually work as intended though since we have deep handlers (from the code assume ocaml has shallow handlers?)
```
///
/// From OCaml version 5.1 chapter 12
///
mod EffectExamples.Threads {
    use Status.{Complete, Suspended};

    pub eff Exchangeable {
        pub def exchange(n: Int32): Int32
    }

    pub enum Status {
        case Complete(Int32)
        case Suspended(Int32, Int32 -> Int32 \ Exchangeable)
    }

    def step(f: Unit -> Int32 \ Exchangeable): Status =
        try {
            Complete(f())
        } with Exchangeable {
            def exchange(n, k) = {
                def cont(m, c): Int32 = match c(m) {
                    case Complete(v)       => v
                    case Suspended(m1, c2) => cont(m1, c2 >> Complete)
                };
                Suspended(n, m -> cont(m, tmp -> checked_ecast(k(tmp))))
            }
        }

    pub def runBoth(f: Unit -> Int32 \ Exchangeable, g: Unit -> Int32 \ Exchangeable): (Int32, Int32) =
        match (step(f), step(g)) {
            case (Complete(vf), Complete(vg)) => (vf, vg)

            case (Suspended(m1, k1), Suspended(m2, k2)) =>
                runBoth(() -> k1(m2), () -> k2(m1))

            case (Complete(vf), Suspended(m2, k2)) =>
                runBoth(() -> checked_ecast(vf), () -> k2(m2))

            case (Suspended(m1, k1), Complete(vg)) =>
                runBoth(() -> k1(m1), () -> checked_ecast(vg))
        }
}


def minus(n: Int32, m: Int32): Int32 \ EffectExamples.Threads.Exchangeable =
    match EffectExamples.Threads.Exchangeable.exchange(dbg(m)) {
        case 0 => n
        case _ if m < 0 => minus(n+1, m+1)
        case _ if m > 0 => minus(n-1, m-1)
        case _ => ??? // unreachable
    }

def main(): (Int32, Int32) = {
    EffectExamples.Threads.runBoth(() -> minus(5, 3), () -> minus(5, -3))
}
```

**Comment by JonathanStarup** [comment]
Yeah, looking at the ocaml notes, it seems to for us we need to "inline" the step function, since we cant transform effect operations into `Status` "one at a time"

**Comment by magnus-madsen** [comment]
> @magnus-madsen I don't know if its comprehensible by text, but this is a somewhat nice example of deep vs shallow handlers

My brain is too fried today, but I would enjoy a walk through at some point.

**Comment by jaschdoc** [comment]
So do we close this and move to issue or discussion?

**Comment by magnus-madsen** [comment]
Yes

**Pull request closed without merging**
