### PR TITLE
fix: disallow for-loops only containing guard fragments

### LINKED ISSUE #4570: Fix foreach / for-yield fragment parsing
Currently allows `foreach (x > 2) exp` i.e. only a guard.

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes #4570

### CODE REVIEW

**Comment by magnus-madsen** [comment]
The solution seems pretty complex. What's the advantage? You want to disallow this:

```
def main(): Unit \ IO = 
    let x = 1232;
    foreach (if x >= 2) 
        println("Hello World!")
```

but is that really bad?

**Comment by magnus-madsen** [comment]
Is there a more harmful example?

**Comment by jaschdoc** [comment]
No, but it seems like it could lead to awkward bugs where a loop could be used as an if statement but where it wasn't intentional. Arguably, that would be undefined behavior.

**Comment by magnus-madsen** [comment]
> No, but it seems like it could lead to awkward bugs where a loop is used as an if expression but where it wasn't intentional. Arguably, that would be undefined behavior.

Do you have an example?

**Pull request closed without merging**
