### PR TITLE
feat: move classes to own page in HTML documentation

### PR DESCRIPTION
**Pull request by sockmaster27**
Related to #6327

### CODE REVIEW

**Comment by sockmaster27** [comment]
This undoes  #6437 so enums are no longer merged with their companion module

**Comment by magnus-madsen** [comment]
!!!jar

**Comment by magnus-madsen** [comment]
This seems to be moving in the right direction 👍

**Comment by magnus-madsen** [comment]
What's the plan for effects etc? We do them in a separate PR later?

**Comment by magnus-madsen** [comment]
!!!jar

**Comment by sockmaster27** [comment]
> What's the plan for effects etc? We do them in a separate PR later?

Yeah, that's what I was thinking

**Comment by magnus-madsen** [comment]
Documentation for signatures seem to be missing:

image

**Comment by magnus-madsen** [comment]
Are they missing in the Flix compiler?

**Comment by magnus-madsen** [comment]
Sometimes it works:

image

So maybe a bug in Flix processing of comments.

**Comment by magnus-madsen** [comment]
Any thoughts on the "instances" part or are we happy with it?

**Comment by sockmaster27** [comment]
> Any thoughts on the "instances" part or are we happy with it?

I think it's absolutely fine for now

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
