### PR TITLE
refactor: introduced `TypedAst.Binder`

### PR DESCRIPTION
**Pull request by magnus-madsen**
Related #8955

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@mlutze This seems reasonable, what do you think?

**Comment by magnus-madsen** [comment]
(Obv. more needs to be refactored- but I was going to let Alexander do that)

**Comment by mlutze** [comment]
Is the type necessary? It may be confusing, as one's assumption may be that it corresponds to the `Foo` of `let x: Foo = ...`

**Review by mlutze — APPROVED** [review]

**Comment by magnus-madsen** [comment]
> Is the type necessary? It may be confusing, as one's assumption may be that it corresponds to the `Foo` of `let x: Foo = ...`

It is because we need the type for e.g. hovering, but the VarSym only has the type variable.

**Comment by magnus-madsen** [comment]
@LoZander Please take a look at the diff here and then refactor to use `Binder` for all occurrences of `VarSym` in `TypedAst`. 

Makes sense?

**Comment by LoZander** [comment]
> @LoZander Please take a look at the diff here and then refactor to use `Binder` for all occurrences of `VarSym` in `TypedAst`.
> 
> Makes sense?

Yep, that makes sense :)

**Pull request merged**
