### PR TITLE
feat: implement different HTTP methods

### PR DESCRIPTION
**Pull request by sockmaster27**
The only left out method for now is [`CONNECT`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT).

Related to  #9035

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Check the design of Logger:

https://github.com/flix/flix/blob/master/main/src/library/Logger.flix#L25

I think it makes sense for the eff to have one general operation and the offer helpers in the companion module.

**Comment by magnus-madsen** [comment]
RFR/RFM?

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
Ill merge and then you can iterate. See also #9391 which is probably blocking for @jaschdoc

**Comment by jaschdoc** [comment]
> Ill merge and then you can iterate. See also #9391 which is probably blocking for @jaschdoc

No worries it was just an edge case I wanted to try by manually disconnecting. Works fine when I'm online

**Comment by magnus-madsen** [comment]
OK, but its still a pretty big issue, so lets get it resolved ASAP.

**Pull request merged**
