### PR TITLE
feat: contains function for SourceLocation

### PR DESCRIPTION
**Pull request by LoZander**
This adds a `contains` function to `SourceLocation`s as well as a partial ordering on `SourcePosition`s used by the aforementioned.

This is related to #4276 and will be used by the `HighlightProvider`.

### CODE REVIEW

**Comment by LoZander** [comment]
Right, yes. I'll get on that. Late night :p

**Comment by LoZander** [comment]
Documentation and tests have been added :)

**Review by magnus-madsen — APPROVED** [review]

**Comment by JonathanStarup** [comment]
i've though about this for a while, nice :)

Is this for the location verifier? or just for nicer code in general?

**Comment by LoZander** [comment]
> i've though about this for a while, nice :)
> 
> Is this for the location verifier? or just for nicer code in general?

Do you mean the `InsideAcceptor`?

I just needed it for the effect highlighting to filter out expressions not in the function we're concerned with, and instead of adding it as a local private function, I thought I might as well add it to SourceLocations in general, since arguably that is where this kinda thing belongs and I could see it being useful in general :)

**Pull request merged**
