### PR TITLE
feat: put effects on their own page in HTML documentation

### PR DESCRIPTION
**Pull request by sockmaster27**
Related to https://github.com/flix/flix/issues/6327

### CODE REVIEW

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
!!!jar

**Comment by magnus-madsen** [comment]
Looks fishy:

image

**Comment by magnus-madsen** [comment]
```
def main(): Unit \ IO = 
    println("Hello World!")

pub eff MyConsole {
    pub def warn(s: String): Unit

    pub def error(s: String): Unit
}


```

**Comment by sockmaster27** [comment]
image

**Pull request merged**
