### PR TITLE
chore: remove `TypeMinimization`

### PR DESCRIPTION
**Pull request by magnus-madsen**
Experimental results shows that it has no impact on performance.

While it might simplify some types shown to the user -- all of that will break once we switch to set effects anyway.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
The advantage of removing this and doing it now is that it simplifies BU in the compiler and understanding performance implications.

**Comment by magnus-madsen** [comment]
In particular this would probably skew some performance experiments slightly in unpredictable directions.

**Comment by magnus-madsen** [comment]
!!!jar

**Comment by magnus-madsen** [comment]
A concern is memory consumption. I need to check that.

**Comment by magnus-madsen** [comment]
Memory usage is fine too.

**Review by mlutze — APPROVED** [review]

**Pull request merged**
