### PR TITLE
LSP: Improve support for errors with multiple source locations

### LINKED ISSUE #1454: LSP: Errors with multiple locations are not reported correctly
For example, try to redefine `>>`.

### PR DESCRIPTION
**Pull request by magnus-madsen**
Fixes #1454

### CODE REVIEW

**Comment by mlutze** [comment]
Have you considered refactoring to allow more than one location for a given error, rather than showing multiple separate errors?

**Comment by magnus-madsen** [comment]
> 
> 
> Have you considered refactoring to allow more than one location for a given error, rather than showing multiple separate errors?

Yes, but I have not been able to come up with something that seems reasonable in all cases.

This is just a temporary fix that seems reasonable for LSP.

**Comment by magnus-madsen** [comment]
By the way, this is almost entirely for duplicate definitions-- where I think it is fine to show to error messages.

**Comment by magnus-madsen** [comment]
For example, I am not duplicating ShadowedVar etc.

**Pull request merged**
