### PR TITLE
chore: remove `debug` functions

### PR DESCRIPTION
**Pull request by magnus-madsen**

### CODE REVIEW

**Comment by JonathanStarup** [comment]
😮

**Comment by JonathanStarup** [comment]
I guess not having these means that `debug` is just a regular keyword like `ref` - you also cannot use `ref` as a function

**Review by JonathanStarup — APPROVED** [review]

**Comment by magnus-madsen** [comment]
Yes

**Comment by magnus-madsen** [comment]
It was an ugly hack anyway

**Pull request merged**
