### PR TITLE
refactor: `Int64` functions to subject last

### LINKED ISSUE #3963: Numeric functions and subject last
It seems to me that many of the numeric functions, like `Int64.clampToInt` does not adhere to subject last.
```
pub def clampToInt32(x: Int64, minimum: Int32, maximum: Int32): Int32
```

### PR DESCRIPTION
**Pull request by ninaandrup**
Related to #3963

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Lets rename minimum -> min and so forth.

**Comment by ninaandrup** [comment]
Done :)

**Comment by magnus-madsen** [comment]
@ninaandrup Will you update `dist` in this PR and the others? Thanks! :)

**Comment by magnus-madsen** [comment]
Maybe I merge now and then you can open more PRs :)

**Pull request merged**
