### PR TITLE
feat: thunk shorthand `-> exp`

### PR DESCRIPTION
**Pull request by JonathanStarup**
parse `-> exp` as `() -> exp`

This is very nice with handler-type functions like `def run(f: Unit -> a \ ef): a \ (ef - Console) + IO`

`run(() -> exp)` becomes `run(-> exp)`

a very small change, most of the diff is changing `() -> exp` to `-> exp` in lib

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Lets talk more. In particular, what are your thoughts on going full "block mode"? 

In particular, I think `while(-> ...)(-> ...)` is just not good enough. Thoughts?

**Comment by JonathanStarup** [comment]
yeah I've also though about that. but `while{..}{..}` also seems to implicit and magic

**Comment by magnus-madsen** [comment]
We can discuss, but I don't think any programmers will accept having to write `while(-> ...)(-> ...)`.

**Comment by JonathanStarup** [comment]
I think its better than `while{..}{..}` unless its built-in syntax

**Pull request closed without merging**
