### PR TITLE
refactor: fix access modifiers

### PR DESCRIPTION
**Pull request by jaschdoc**
Related to  #2819

### CODE REVIEW

**Comment by jaschdoc** [comment]
Making `Channel.select` private breaks a lot of tests. Maybe @JonathanStarup should look into that before I simply remove those tests?

**Comment by magnus-madsen** [comment]
> Making `Channel.select` private breaks a lot of tests. Maybe @JonathanStarup should look into that before I simply remove those tests?

Leave it public, and tag it `@Internal` instead :)

**Comment by jaschdoc** [comment]
Ready to merge

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
