### PR TITLE
fix: Parser2 should return an AST so that Weeder2 runs

### PR DESCRIPTION
**Pull request by magnus-madsen**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@herluf-ba This ensures that the Weeder2 is run, but of course now if Parser2 fails the whole thing fails. 
So run silent is not really run silent anymore.

**Comment by magnus-madsen** [comment]
So I am not entirely sure what to do. What we have now _IS_ running the Lexer and Parser-- which is good. It is just not running the Weeder yet.

**Comment by herluf-ba** [comment]
I agree that we should try to run the Weeder too if possible. My worry is that before we have recover sets, users could get a ton of errors from the chatty parser. But I think `toHardResult`  gets around that? It cast `SoftFailure` to `Result.Err` too right?

**Comment by herluf-ba** [comment]
Yep, that seems reasonable. With a bad file the parser gets silenced, but with an ok file we catch a potential chrash.

**Comment by magnus-madsen** [comment]
I think I have a reasonable solution: If Parser2 succeeds then we pass the AST on to the Weeder2. If Parser2 fails then we do not know what to do and we simply return the empty AST (successfully). Thus Weeder2 will be tested when Parser2 succeeds.

**Comment by magnus-madsen** [comment]
@herluf-ba If you agree, I need you to click review, and approve the PR :)

Now the rubber-band is on the other glove!

**Review by herluf-ba — APPROVED** [review]

**Comment by herluf-ba** [comment]
Being on this side of things is new to me 😅

**Comment by magnus-madsen** [comment]
Ah, you must also submit a review. Even if it is empty.

**Comment by magnus-madsen** [comment]
Files Changed -> Review Changes -> Approve

**Review by herluf-ba — APPROVED** [review]

**Comment by herluf-ba** [comment]
I did that. It seems it's not enough since I don't have write access to flix

**Comment by magnus-madsen** [comment]
Hmm

**Comment by magnus-madsen** [comment]
I cannot figure it out. I think we need to sit down and look at persmissions at some point.

Meanwhile, @mlutze can you approve?

**Review by mlutze — APPROVED** [review]

**Pull request merged**
