### PR TITLE
feat: improve `java.lang.Object.toString` of record objects

### PR DESCRIPTION
**Pull request by JonathanStarup**
Related to #4664.
* `{}` is `{}`
* `{ field = 42}` is `{field = 42}`
* `{ fieldA = 1, fieldB = 123 }` is `{fieldA = 1, fieldB = 123}` (order not defined I suppose)

### CODE REVIEW

**Comment by magnus-madsen** [comment]
RFM?

**Comment by JonathanStarup** [comment]
> RFM?

oops, parsing error. just left uni. ill fix it later

**Comment by JonathanStarup** [comment]
Should be ready now.
(Fun fact, reformat breaks the `BackendObjType` file because intellij decides to collapse multiple imports to `_` and thereby shadow another import)

**Comment by magnus-madsen** [comment]
> Should be ready now. (Fun fact, reformat breaks the `BackendObjType` file because intellij decides to collapse multiple imports to `_` and thereby shadow another import)

So wildcard imports are evil?

**Pull request merged**
