### PR TITLE
chore: disable deprecated features for tests

### PR DESCRIPTION
**Pull request by magnus-madsen**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@chanattan Needs to refactor:

image

before this can be merged in.

**Review by mlutze — APPROVED** [review]

**Comment by magnus-madsen** [comment]
@chanattan What's the status on this?

**Comment by chanattan** [comment]
> @chanattan What's the status on this?

I am working on it, some errors don't match so I have to use different code patterns.

**Comment by magnus-madsen** [comment]
@chanattan With Matts recent fix, can we get the last test cases refactored?

**Comment by chanattan** [comment]
I think we should support IntConsumer, ... also to get a more decent refactoring.

**Comment by magnus-madsen** [comment]
@chanattan What's the status on #8212 and #8213? Would it be possible to get those in, so we can merge this one in?

**Comment by magnus-madsen** [comment]
@jaschdoc FYI: deprecated features are now disabled for tests.

**Pull request merged**
