### PR TITLE
feat: add restrictable enum to weeder

### PR DESCRIPTION
**Pull request by JonathanStarup**
Related to #5229

### CODE REVIEW

**Comment by JonathanStarup** [comment]
@mlutze Do you think it's fine just to copy the Ast nodes like this? even though `RestrictableCase` is identical to normal `Case`

**Comment by mlutze** [comment]
Yeah, it will make experimental changes eaiser

**Comment by JonathanStarup** [comment]
Magnus voted for reuse, so now I'm in a pickle 🥒

But its likely that we wont change anything in the enum declaration case right?

Do you want to make a decision @magnus-madsen?

**Comment by magnus-madsen** [comment]
We keep the copy. @mlutze Can you review?

**Comment by mlutze** [comment]
LGTM. It will make my life harder with the namespace migration, but that was inevitable.

**Pull request merged**
