### PR TITLE
Import native static inner classes

### PR DESCRIPTION
**Pull request by rrramiro**
This is a proposal for handling native static inner classes.
It would allow importing for example the `Map.Entry` class, this way:
```
import java.util.Map$Entry.getKey();
```

### CODE REVIEW

**Comment by mlutze** [comment]
Hi @rrramiro, thanks for the contribution, and welcome to the community!

Before your PR is merged, could you please add yourself to the [AUTHORS.md](https://github.com/flix/flix/blob/master/AUTHORS.md) file? (Or, if you prefer, state in a comment here that you  you agree to release all your contributions to Flix under the [Apache 2.0 License](https://github.com/flix/flix/blob/master/LICENSE.md).)

**Comment by rrramiro** [comment]
Hi @mlutze,
Thanks, I'm glad to join the community!

**Review by mlutze — CHANGES_REQUESTED** [review]
This looks good to me, I just have a couple of requests for additional test cases:

* Static fields in the nested class
* Fields in a doubly-nested class

It may be a little while before this gets merged, as the _Merge Button Officer_ is on vacation :)

**Comment by rrramiro** [comment]
Thanks for the review :) I've added the additional test cases as requested.

**Comment by magnus-madsen** [comment]
Hello @rrramiro, thanks for your contribution and welcome to our little, but growing community :)

Your PR looks good - with the additional test cases - so I am merging it! :)

The native interop still has some way to go, but everything helps!

**Comment by rrramiro** [comment]
Hello @magnus-madsen, 
Thanks for the warm welcome :)
Flix is an exciting language :)

**Pull request merged**
