### PR TITLE
chore: update import syntax in test files `InvokeConstructor`, `InvokeMethod2.Overload.Subtypes`, `InvokeStaticMethod` and `InvokeMethod`

### PR DESCRIPTION
**Pull request by chanattan**
Related to #8096.
Should be merged in after #8126.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@chanattan conflicted

**Comment by magnus-madsen** [comment]
@chanattan Still no go

**Comment by chanattan** [comment]
> @chanattan Still no go

Yes I think it didn't get the last commit from main. I'm merging again.

**Comment by chanattan** [comment]
Ok I'm doomed

**Comment by chanattan** [comment]
@magnus-madsen your PR worked :)

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
