### PR TITLE
fix: mark unification tvars as synthetic in `Kinder`

### PR DESCRIPTION
**Pull request by mlutze**
I think we should have a more robust solution moving forward. Specifically, we know that any time we introduce a type variable without text, its location must be generic, so we should enforce this somehow.

related to #3463

### CODE REVIEW

**Comment by mlutze** [comment]
Screenshot from 2022-04-04 12-26-10

**Comment by magnus-madsen** [comment]
@mlutze Just to make sure: This does not break type hovering, right?

**Comment by magnus-madsen** [comment]
!!!jar

**Comment by magnus-madsen** [comment]
Looks ok to me 👍 . Thanks!

**Pull request merged**
