### PR TITLE
Update to Scala 2.12 and updated all dependencies.

### PR DESCRIPTION
**Pull request by magnus-madsen**

### CODE REVIEW

**Comment by mhyee** [comment]
You should also update and test `build.sbt`.

**Comment by magnus-madsen** [comment]
I updated `build.sbt` but I have no good way of testing it.

**Comment by mhyee** [comment]
Would it be possible to add a second CI build that does `sbt test`?

**Comment by magnus-madsen** [comment]
I never got SBT to work on travis/circle. :/

**Comment by magnus-madsen** [comment]
See also #250

**Comment by mhyee** [comment]
Ugh, that's unfortunate.

I tested sbt on my computer. Turns out `asm` version is `5.2` and not `5.2.0`.

You can get the correct version number by searching for the package on [Maven](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.ow2.asm%22) (click "all"), which is where sbt downloads the dependencies.

I'll push a fix shortly, when the tests finish running.

**Comment by magnus-madsen** [comment]
When `5.2` is not the same as `5.2.0` :gun:

**Comment by magnus-madsen** [comment]
Fixes #501

**Pull request merged**
