### PR TITLE
refactor: add `CompilationMessage.messageWithLoc`

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes https://github.com/flix/flix/issues/6735

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@jaschdoc Did you run it? Won't it print the header twice now because all the error messages contain the header?

**Comment by jaschdoc** [comment]
Oops yes haha, forgot to remove it from all `message` definitions!

**Comment by magnus-madsen** [comment]
> Oops yes haha, forgot to remove it from all `message` definitions!

Righto. And perhaps do a few tests to see that its look correct.

**Comment by magnus-madsen** [comment]
It should like now, i.e. header, then one blank line, and then the message beginning with >

**Comment by jaschdoc** [comment]
I went through the diffs and `line` calls and wrote a test. Everything should be fine now.

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
