### PR TITLE
fix: deprecated use of URL

### PR DESCRIPTION
**Pull request by magnus-madsen**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@AnnaBlume99 One last thing, could you take a look at this problem? (See the failing test case in the CI).

The issue is that we are not supposed to use `new URL` because it is deprecated, so I switched to `URI`, but now a test fails. 

Maybe my fix combined with some fix from your side can solve it?

**Comment by magnus-madsen** [comment]
I merged with the test marked as ignored.

**Comment by AnnaBlume99** [comment]
Do you still want me to look at it? It's no problem for me to take a look :)

**Comment by magnus-madsen** [comment]
Yes please :)

**Pull request merged**
