### PR TITLE
fix: return exit code 1 on packager failure

### PR DESCRIPTION
**Pull request by mlutze**
Some manual testing seems to indicate that it's working properly.
I didn't do anything for the internal options (`--Xbenchmark-compiler`), only packager commands.

fixes https://github.com/flix/flix/issues/2964

### CODE REVIEW

**Comment by mlutze** [comment]
!!!jar

**Review by magnus-madsen — COMMENTED** [review]
Everything looks good exception genericSuccess/Failure.

I would inline genericSuccess and replace genericFailure by actual type that contains some errors, e.g. CompilationError etc.

**Comment by magnus-madsen** [comment]
Also, do we need some try catches around all the file operations?

**Comment by mlutze** [comment]
> replace genericFailure by actual type that contains some errors, e.g. CompilationError etc.

I didn't do this because the packager already handles these errors (by printing out their message), so keeping them in the returned object would seem to communicate that something still needs to be done with the error.

> try catches

Maybe. I think the _right_ solution is to get rid of all the `throw RuntimeException(...)`s throughout the packager and move to a monadic style. But I'd chalk that up to future work. Meanwhile, all errors are caught in a big try-catch in `Main`, so I'm not sure whether it's worth it to catch them earlier.

**Comment by magnus-madsen** [comment]
> > replace genericFailure by actual type that contains some errors, e.g. CompilationError etc.
> 
> I didn't do this because the packager already handles these errors (by printing out their message), so keeping them in the returned object would seem to communicate that something still needs to be done with the error.

OK, but ultimately printing things does not work so well for clients using the API (VSCode, playground, etc.). We don't have to fix that now of course, but we should move in that direction.

> > try catches
> 
> Maybe. I think the _right_ solution is to get rid of all the `throw RuntimeException(...)`s throughout the packager and move to a monadic style. 

Agreed.

**Comment by magnus-madsen** [comment]
Ill merge this as a useful stepping stone.

**Pull request merged**
