### PR TITLE
Improved CodeGen for `Lazy`

### LINKED ISSUE #2328: Speed-up Lazy?
How can we speed-up lazy? Things to try:

- Remove the `initialized` Boolean and instead use the null/non-nullness of the closure?
- Delay the lock: Check the `value` field. If non-null return it. Otherwise, lock, re-read it and so forth.

@JonathanStarup If I update the ticket with a suitable benchmark and can you experiment with the above?

### PR DESCRIPTION
**Pull request by JonathanStarup**
Fixes #2328

Current benchmark:
```flix
use Benchmark.Benchmark;
use Benchmark.defBenchmark;

pub def bench1(): Benchmark = 
     defBenchmark("List", () -> { 
         List.range(1, 10_000) |>
         List.map(x -> x + 1) |>
         List.map(x -> x + 1) |>
         List.map(x -> x + 1)
    })

pub def bench2(): Benchmark = 
     defBenchmark("LazyList", () -> { 
         LazyList.range(1, 10_000) |>
         mapE(x -> x + 1) |>
         mapE(x -> x + 1) |>
         mapE(x -> x + 1 as & Impure)
    } as & Pure)

pub def mapE(f: a -> b & ef, l: LazyList[a]): LazyList[b] & Impure =
    let r = MutList.new();
    mapERec(f, l, r);
    MutList.foldRight((x, xs) -> ECons(x, xs), ENil, r)

def mapERec(f: a -> b & ef, l: LazyList[a], r: MutList[b]): Unit & Impure =
    match l {
        case ENil         => ()
        case ECons(x, xs) => 
            MutList.push!(f(x), r);
            mapERec(f, xs, r)
        case LCons(x, xs) => 
            MutList.push!(f(x), r);
            mapERec(f, force xs, r)
        case LList(xs)    => mapERec(f, force xs, r)
    }
    
def main(_args: Array[String]) : Int32 & Impure = 
    let bs = [bench1(), bench2()];
    Benchmark.runWithBudget(bs, 300_000_000_000i64);
    0
    

```
Results:
```
Benchmark                                         Iterations          Time (avg)
List                                                   27704          4368 us/op
LazyList                                                5740         14153 us/op (x3.24)

Total time elapsed: 202 seconds. Time budget was: 600 seconds.
```
```
Benchmark                                         Iterations          Time (avg)
List                                                   13568          4530 us/op
LazyList                                                2827         19872 us/op (x4.39)

Total time elapsed: 117 seconds. Time budget was: 300 seconds.
```
```
Benchmark                                         Iterations          Time (avg)
List                                                    6506          5089 us/op
LazyList                                                1240         19368 us/op (x3.81)

Total time elapsed: 57 seconds. Time budget was: 150 seconds.
```

### CODE REVIEW

**Comment by magnus-madsen** [comment]
How does it compare before vs. after?

**Comment by JonathanStarup** [comment]
There is also a question about exceptions. Right now exceptions stop lock unlocking (which ill fix here), but an exception would still break the value initialization part, such that the next need for the lazy value re-evaluates the thunk, but I suppose it should only rethrow the exception but not reevaluate other sideeffect. My current idea is:
```java
package ca.uwaterloo.flix;

class LazyInt<A> {
    public A value;
    public boolean init;
    private Cont<A> thunk;

    public LazyInt(Cont<A> thunk) {
        this.thunk = thunk;
        this.init = false;
    }

    public A force() {
        synchronized (this) {
            if (init) return value; // avoid double computation when threads are racing to initialize
            value = thunk.unwind();
            init = true;
        }
        thunk = null; // locking not needed as init and value are setup which will handle the other use cases
        return value;
    }

    // this should be generated inline, not called
    public A getValue() {
        if (init) return value;
        else return force();
    }

}

interface Cont<A> {
    A unwind();
}

```

**Comment by JonathanStarup** [comment]
Lazy Obj
```java
import Cont$Obj;

public final class Lazy$Obj {
    public Object expression;
    public Object value;

    public final synchronized Object force(Context var1) {
        if (this.expression == null) {
            return this.value;
        } else {
            var1.continuation = this.expression;

            Obj var2;
            do {
                Object var10001 = var1.continuation;
                var1.continuation = null;
                (var2 = (Cont$Obj)var10001).invoke(var1);
            } while(var1.continuation != null);

            this.value = var2.getResult();
            this.expression = null;
            return this.value;
        }
    }

    public Lazy$Obj(Object var1) {
        this.expression = var1;
    }
}
```
Results:
```
...
```

**Comment by JonathanStarup** [comment]
Without the synchronzied method, using the old flawed Monitorenter/exit:
```
Benchmark                                         Iterations          Time (avg)
List                                                   15530          4571 us/op
LazyList                                                3554         15429 us/op

Total time elapsed: 125 seconds. Time budget was: 300 seconds.
```
```
Benchmark                                         Iterations          Time (avg)
List                                                    6228          4394 us/op
LazyList                                                1457         18106 us/op

Total time elapsed: 53 seconds. Time budget was: 150 seconds.
```

**Comment by JonathanStarup** [comment]
Time budget | Master | Reduced locking | Reduced locking + synchronized force
--- | --- | --- | ---
150 | x3.81 | x4.12 | x3.33
300 | x4.39 | x3.38 | x3.11
600 | x3.24 | x3.39 | x2.89

**Comment by magnus-madsen** [comment]
OK, so this is definitely a benefit right?

**Comment by magnus-madsen** [comment]
By the way, I guess the `expression` can still be private.

**Comment by JonathanStarup** [comment]
The tests here are a bit volatile, but it seems a faster yes.

expression is used in compileExp in genExpression to check lazy.expression == null.

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
