### PR TITLE
test: use regions in `Test.Exp.ArrayLoad`

### PR DESCRIPTION
**Pull request by jaschdoc**
Related to #3366

### CODE REVIEW

**Comment by jaschdoc** [comment]
Hmm not sure what's wrong here. Why does it infer impure arrays for the code below?
```flix
    @test
    def testArrayLoad34(): Int32 = region r {
        let x: ScopedArray[ScopedArray[Int32, Pure], Pure] = [[1, 2] @ r, [1, 2] @ r] @ r;
        x[1][0]
    }
```
```
>> Unable to unify the Boolean formulas: 'true' and 'false'.

203 |         let x: ScopedArray[ScopedArray[Int32, Pure], Pure] = [[1, 2] @ r, [1, 2] @ r] @ r;
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                                   mismatched boolean formulas.

Type One: ScopedArray[ScopedArray[Int32, true], true]
Type Two: ScopedArray[ScopedArray[Int32, false], false]
```

**Comment by magnus-madsen** [comment]
Rebase onto master!

**Comment by magnus-madsen** [comment]
Oh, but also, it is wrong.

**Inside** a region the array is NOT pure. It is only outside!

**Comment by magnus-madsen** [comment]
Recall your program:

```
    region r {

        /// Create a new `MutSet` at region `r`.
        /// This will be used to keep track of
        /// unique elements in `l`.
        let s = new MutSet(r);

        /// The lambda used in the call to `filter`
        /// would be impure without a region.
        List.filter(x -> {
            if (MutSet.memberOf(x, s))
                false // `x` has already been seen.
            else {
                MutSet.add!(x, s); // this is impure. Hence everything inside filter is impure.
                true
            } // Hence everything inside the scope is impure (or rather has the effect r)
        }, l)
    }
```

**Comment by magnus-madsen** [comment]
Currently there is no way for you to write the type of the array.

**Comment by magnus-madsen** [comment]
> Currently there is no way for you to write the type of the array.

I need to add that.

**Comment by jaschdoc** [comment]
> Oh, but also, it is wrong.
> 
> 
> 
> **Inside** a region the array is NOT pure. It is only outside!

Oh yes of course!

**Comment by jaschdoc** [comment]
> Oh, but also, it is wrong.
> 
> **Inside** a region the array is NOT pure. It is only outside!

Yes but now something funny happens:
```flix
    @test
    def testArrayLoad34(): Int32 = region r {
        let x = [[1, 2] @ r, [1, 2] @ r] @ r;
        x[1][0]
    }
```
produces the error:
```
>> Impure function declared as pure.

202 |     def testArrayLoad34(): Int32 = region r {
              ^^^^^^^^^^^^^^^
              impure function.
```
(also every other test is impure even though its body is inside a region)

**Comment by magnus-madsen** [comment]
Found a bug. Thanks! 👍  ⚡

**Comment by magnus-madsen** [comment]
The problem should disappear when #3505 is merged and you rebase on top :)

**Comment by jaschdoc** [comment]
@magnus-madsen RFR

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
