### PR TITLE
refactor: reduced closure duplication using thread id

### PR DESCRIPTION
**Pull request by JonathanStarup**
new `getUniqueThreadClosure` function:
```java
public Clo1%Obj%Obj getUniqueThreadClosure() {
        if (Thread.currentThread().getId() == this.threadId) {
            return this;
        } else {
            Clo%main%121576 var10000 = new Clo%main%121576();
            var10000.threadId = Thread.currentThread().getId();
            return var10000;
        }
    }
```

### CODE REVIEW

**Comment by JonathanStarup** [comment]
# PR
====================== Flix Benchmark ======================
. | . 
:--- | ---:
BenchmarkList.benchmark01 | 23.298 ns.
BenchmarkList.benchmark02 | 34.108 ns.
BenchmarkList.benchmark03 | 26.147 ns.
BenchmarkList.benchmark04 | 35.671 ns.
BenchmarkList.benchmark05 | 44.052 ns.
BenchmarkList.benchmark06 | 85.564 ns.
BenchmarkList.benchmark07 | 53.655 ns.
BenchmarkList.benchmark08 | 27.273 ns.
BenchmarkList.benchmark09 | 39.577 ns.
BenchmarkList.benchmark10 | 51.200 ns.
BenchmarkList.benchmark11 | 78.326 ns.
BenchmarkList.benchmark12 | 103.961 ns.
BenchmarkList.benchmark13 | 32.500 ns.
BenchmarkList.benchmark14 | 28.761 ns.
BenchmarkList.benchmark15 | 68.112 ns.
BenchmarkList.benchmark16 | 134.376 ns.
BenchmarkList.benchmark17 | 30.110 ns.
BenchmarkList.benchmark18 | 53.612 ns.

Finished 18 benchmarks with 25000 iterations each.

**Comment by JonathanStarup** [comment]
@magnus-madsen looks good for performance even in this version

**Comment by magnus-madsen** [comment]
Yes, so seems like worth doing.

**Comment by magnus-madsen** [comment]
RFR?

**Comment by magnus-madsen** [comment]
@JonathanStarup Did you test it on parMap for RBTree? :)

**Comment by JonathanStarup** [comment]
> @JonathanStarup Did you test it on parMap for RBTree? :)

[This](https://github.com/flix/flix/issues/2336#issuecomment-980541504) works fine if that's what you mean

**Comment by magnus-madsen** [comment]
Could you also post the impact on the Datalog engine? Thanks!

**Comment by JonathanStarup** [comment]
> Could you also post the impact on the Datalog engine? Thanks!

Benchmark | Iterations(PR) | Time (avg)(PR) | Iterations(Master) | Time (avg)(Master)
:--- | ---: | ---: | ---: | ---:
Project (Int, Int) into A (n = 16) | 114103 | 15 us/op | 141442 | 13 us/op
Project (Int, Int) into A (n = 256) | 35483 | 416 us/op | 37832 | 381 us/op
Project (Int, Int) into A (n = 4096) | 1713 | 11319 us/op | 1606 | 9321 us/op
Project (Int, Int) into A (n = 65536) | 76 | 213013 us/op | 74 | 207281 us/op
Project (Int, Int) into A (n = 1048576) | 3 | 4472140 us/op | 3 | 4348798 us/op
Select (Int, Int) from A (n = 16) | 2571 | 277 us/op | 3030 | 201 us/op
Select (Int, Int) from A (n = 256) | 7260 | 140 us/op | 9320 | 121 us/op
Select (Int, Int) from A (n = 4096) | 2126 | 424 us/op | 1887 | 388 us/op
Select (Int, Int) from A (n = 65536) | 352 | 6573 us/op | 333 | 6498 us/op
Select (Int, Int) from A (n = 1048576) | 86 | 208482 us/op | 107 | 187040 us/op
Solve (Closure) (n = 64) | 2076 | 601 us/op | 2094 | 383 us/op
Solve (Closure) (n = 256) | 1027 | 751 us/op | 971 | 615 us/op
Solve (Closure) (n = 1024) | 428 | 2740 us/op | 311 | 2397 us/op
Solve (Closure) (n = 4096) | 141 | 11771 us/op | 144 | 11001 us/op
Solve (Closure) (n = 16384) | 59 | 53764 us/op | 60 | 52300 us/op
Solve (Closure) (n = 65536) | 32 | 259256 us/op | 27 | 255597 us/op
Solve (Closure) (n = 262144) | 9 | 1302932 us/op | 11 | 1313500 us/op
Solve (Cross Product 2) (n = 256) | 3644 | 560 us/op | 6873 | 503 us/op
Solve (Cross Product 2) (n = 1024) | 2047 | 2486 us/op | 3161 | 2356 us/op
Solve (Cross Product 2) (n = 4096) | 653 | 11960 us/op | 239 | 11508 us/op
Solve (Cross Product 2) (n = 16384) | 239 | 60201 us/op | 232 | 54675 us/op
Solve (Cross Product 2) (n = 65536) | 57 | 260331 us/op | 49 | 249499 us/op
Solve (Cross Product 2) (n = 262144) | 12 | 1189148 us/op | 12 | 1138940 us/op
Solve (Cross Product 2) (n = 1048576) | 2 | 5500383 us/op | 2 | 5175403 us/op
Solve (Cross Product 3) (n = 4096) | 1137 | 11905 us/op | 1267 | 10862 us/op
Solve (Cross Product 3) (n = 32768) | 113 | 127763 us/op | 124 | 122686 us/op
Solve (Cross Product 3) (n = 262144) | 10 | 1240251 us/op | 11 | 1221653 us/op
Solve (Intersect) (n = 16) | 8022 | 64 us/op | 6681 | 76 us/op
Solve (Intersect) (n = 256) | 6557 | 606 us/op | 6844 | 646 us/op
Solve (Intersect) (n = 4096) | 960 | 13603 us/op | 992 | 14718 us/op
Solve (Intersect) (n = 65536) | 53 | 268487 us/op | 55 | 260609 us/op
Solve (Intersect) (n = 1048576) | 2 | 5273125 us/op | 2 | 5198168 us/op
Compile Rules (n = 16) | 492 | 1149 us/op | 610 | 1116 us/op
Compile Rules (n = 256) | 52 | 20353 us/op | 49 | 18791 us/op
Compile Rules (n = 4096) | 9 | 335207 us/op | 9 | 310581 us/op

**Comment by magnus-madsen** [comment]
What's the conclusion? That it's a tiny bit slower?

**Comment by JonathanStarup** [comment]
> What's the conclusion? That it's a tiny bit slower?

yeah, but also faster on list. takes more benchmarking if we want the exact effect I think.

**Comment by magnus-madsen** [comment]
I'd like you to explore two things:

- If it helps to cache the current thread id.
- What the generated machine code looks like. 


The latter should be fun to explore. The starting point is a tiny program and the flags `-XX:+PrintCompilation`, `-XX:-TieredCompilation`, `-XX:+PrintCompilation`, and `-XX:+UnlockDiagnosticVMOptions -XX:+PrintAssembly`.

**Comment by magnus-madsen** [comment]
Wait until `List` functions have been refactor to use a local `loop` and then re-benchmark.

**Comment by magnus-madsen** [comment]
List has now been refactored, if you want to redo the experiments.

**Comment by magnus-madsen** [comment]
I am closing this. I think a better way is to ensure our local letrecs are rewritten to loops-- when possible.

**Pull request closed without merging**
