### PR TITLE
style: update errors & tests for `Resolver`

### PR DESCRIPTION
**Pull request by jaschdoc**
- [ ] Ensure every error has at least 3 tests
- [x] Ensure errors occur in alphabetical order
- [x] Ensure errors are tagged with `Recoverable` or `Unrecoverable`
- [x] Ensure tests occur in alphabetical order
- [x] Check that test names and errors match

Related to https://github.com/flix/flix/issues/6817

### CODE REVIEW

**Comment by jaschdoc** [comment]
This should be a failure, right?

```scala

  test("MismatchedOpArity.InvalidOpParamCount.Do.01") {
    val input =
      """
        |eff E {
        |    pub def op(): Unit
        |}
        |
        |def foo(): Unit \ E = do E.op(123)
        |""".stripMargin
    val result = compile(input, Options.TestWithLibNix)
    expectError[ResolutionError.MismatchedOpArity](result)
  }

```

**Comment by magnus-madsen** [comment]
@jaschdoc What happened to this PR? Stuck in purgatory? I guess its not particularly urgent.

**Comment by jaschdoc** [comment]
Yeah I guess I just bailed after the merge conflict, but I can try to finish it. Seems silly, though, if we do not maintain that tests should be in sorted order etc.

**Comment by magnus-madsen** [comment]
I think this got desynched and should be redone at a later time.

**Pull request closed without merging**
