### PR TITLE
fix: fix intersection construction

### PR DESCRIPTION
**Pull request by JonathanStarup**
also added some optimizations

### CODE REVIEW

**Comment by JonathanStarup** [comment]
I've run this on the tests of #5315 and they all still pass

**Comment by JonathanStarup** [comment]
based on slight testing, not notisable no

**Review by mlutze — APPROVED** [review]

**Comment by magnus-madsen** [comment]
should this be merged  then or no?

**Comment by mlutze** [comment]
At least for the bugfix yes. The other stuff shouldn't hurt.

**Pull request merged**
