### PR TITLE
feat: update syntax for `InvokeMethod2`

### PR DESCRIPTION
**Pull request by magnus-madsen**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@JonathanStarup @mlutze @stephentetley If I could ask you to update your packages in the community build to use `#` for record access instead of `.` Thanks!

**Review by mlutze — APPROVED** [review]

**Comment by mlutze** [comment]
!!!rerun

**Comment by magnus-madsen** [comment]
@mlutze Just flixball :)

**Comment by mlutze** [comment]
!!!jar

**Comment by mlutze** [comment]
!!!rerun

**Pull request merged**
