### PR TITLE
feat: add `Array.shuffle`

### PR DESCRIPTION
**Pull request by ninaandrup**
Related to #3697

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@JonathanStarup Can you review?

**Comment by JonathanStarup** [comment]
Looks good to to me, clearly corresponds to Wiki code 👍

I used random somewhere with arrays once and I was questioning how to use regions. In this code its written in such a way that it would be pure if the randomness wasn't there but since the functions are impure anyway the regions doesn't really give you anything, so should you use regions here or not?

**Comment by ninaandrup** [comment]
> If you use any of these words instead of "Related to" then the issue will be closed automatically when the PR is merged [(source)](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) close closes closed fix fixes fixed resolve resolves resolved

I just wanted to do the second part of the issue after, but I guess it should be a new issue instead : " _Then, we should add `shuffle` impure functions to the various namespaces that essentially do `x |> toArray |> shuffle |> toX `._ "

**Comment by ninaandrup** [comment]
@magnus-madsen What do you say about the region stuff? Should I just delete the region stuff, since `Random` makes the function `impure` anyways?

**Comment by magnus-madsen** [comment]
It's fine to keep the region stuff in the tests.

**Comment by ninaandrup** [comment]
I'll change to the syntax `Array[a, r]`

**Comment by ninaandrup** [comment]
> It's fine to keep the region stuff in the tests.

What about the function. It could in principle just be `pub def shuffle(r: Random.Random, a: Array[a, r]): Unit & Impure`, right?

**Comment by magnus-madsen** [comment]
Yes. Just impure.

**Comment by magnus-madsen** [comment]
Thanks-- now we can add shuffles for the other collections (by calling Array.shuffle).

**Pull request merged**
