### PR TITLE
feat: improve array formatting for stringify

### PR DESCRIPTION
**Pull request by mlutze**
related to #4664

### CODE REVIEW

**Comment by magnus-madsen** [comment]
All that code and only 3 test cases. Inflation must be hitting hard!

**Comment by magnus-madsen** [comment]
Also could you not just call deepToString in all cases?

**Comment by mlutze** [comment]
> All that code and only 3 test cases. Inflation must be hitting hard!

Yeah, turned a lot bigger than I thought it would be. I'll go make more tests :(

> Also could you not just call deepToString in all cases?

Nope. `deepToString` takes a `Object[]` so it cannot be used for e.g. `Array[Bool, Static]`

**Comment by JonathanStarup** [comment]
> > All that code and only 3 test cases. Inflation must be hitting hard!
> 
> Yeah, turned a lot bigger than I thought it would be. I'll go make more tests :(
> 
> > Also could you not just call deepToString in all cases?
> 
> Nope. `deepToString` takes a `Object[]` so it cannot be used for e.g. `Array[Bool, Static]`

It's funny I also just coped this in jvm buts its not really reusable. deepToString must also have this kind of logic inside. A showcase of a pain point of the java type system.

**Comment by magnus-madsen** [comment]
RFM?

**Pull request merged**
