### PR TITLE
Add Functor type class

### LINKED ISSUE #1647: Add Functor Type Class
```
class Functor[m :# Type -> Type] {
  ///
  /// Applies the function `f` to `s` preserving its structure.
  ///
  def map(f: a ->b & e, s: m[a]): m[b] & e
}

namespace Functor {
  ///
  /// Lifts the function `f` into the functor.
  ///
  def lift[a, b, e, m: Functor](f: a -> b & e): m[a] -> m[b] & e = Functor.map(f)

  //
  // Replaces the value `a` in `s` by the given value `x` preserving the structure of `s`.
  //
  def as[a, b, m: Functor](s: m[a], x: b): m[b] = Functor.map(_ -> x)
}
```

List of instances: 
- [ ] Add instance for `Option`.
- [ ] Add instance for `List`.
- [ ] Add instance for `Nel`.
- [ ] Add instance for `Array`.
- [ ] Add instance for `MutList`.

### PR DESCRIPTION
**Pull request by esbenbjerre**
Fixes #1647.

### CODE REVIEW

**Comment by esbenbjerre** [comment]
Do we want tests?

**Comment by magnus-madsen** [comment]
No tests. For now.

**Comment by magnus-madsen** [comment]
I added two more operations in the original ticket and some documentation for `map`.

**Comment by esbenbjerre** [comment]
I'm not sure if this is because of some missing syntax or something?
```
-- Resolution Error -------------------------------------------------- Functor.flix

>> Illegal type application: 'm' applied to 'a'.

31 |   def lift[a, b, e, m : Functor](f: a -> b & e): m[a] -> m[b] & e = Functor.map(f)
                                                      ^^^^
                                                      illegal type application.

Type constructor kind: 'Type'.Argument kind: 'Type'.
Possible fixes:

  (1)  Ensure the first type is a type constructor.
  (2)  Ensure the type has the correct number of parameters.
  (3)  Ensure the type constructor accepts the given argument kinds.

-- Resolution Error -------------------------------------------------- Functor.flix

>> Illegal type application: 'm' applied to 'a'.

36 |   def as[a, b, m : Functor](s: m[a], x: b): m[b] = Functor.map(_ -> x)
                                    ^^^^
                                    illegal type application.

Type constructor kind: 'Type'.Argument kind: 'Type'.
Possible fixes:

  (1)  Ensure the first type is a type constructor.
  (2)  Ensure the type has the correct number of parameters.
  (3)  Ensure the type constructor accepts the given argument kinds.
```

**Comment by mlutze** [comment]
I think you'll need to provide both a kind and class annotation for m. So `m :# Type -> Type : Functor`

**Comment by esbenbjerre** [comment]
> I think you'll need to provide both a kind and class annotation for m. So `m :# Type -> Type : Functor`

```
Exception in thread "main" ca.uwaterloo.flix.util.InternalCompilerException: Unexpected type: 'class ca.uwaterloo.flix.language.ast.Type$Apply'.
	at ca.uwaterloo.flix.language.debug.FormatType$.visit$1(FormatType.scala:101)
	at ca.uwaterloo.flix.language.debug.FormatType$.$anonfun$formatType$9(FormatType.scala:214)
	at scala.collection.immutable.List.map(List.scala:219)
	at ca.uwaterloo.flix.language.debug.FormatType$.visit$1(FormatType.scala:214)
	at ca.uwaterloo.flix.language.debug.FormatType$.formatType(FormatType.scala:249)
	at ca.uwaterloo.flix.language.debug.FormatScheme$.formatScheme(FormatScheme.scala:34)
	at ca.uwaterloo.flix.language.errors.TypeError$GeneralizationError.message(TypeError.scala:48)
	at ca.uwaterloo.flix.Main$.$anonfun$main$7(Main.scala:210)
	at ca.uwaterloo.flix.Main$.$anonfun$main$7$adapted(Main.scala:210)
	at scala.collection.immutable.LazyList.foreach(LazyList.scala:302)
	at ca.uwaterloo.flix.Main$.main(Main.scala:210)
	at ca.uwaterloo.flix.Main.main(Main.scala)
```

**Comment by esbenbjerre** [comment]
Hmm now I get redundancy errors.
```
-- Redundancy Error -------------------------------------------------- Functor.flix

>> Unused definition 'as'. The definition is never referenced.

36 |   def as[a, b, m :# Type -> Type : Functor](s: m[a], x: b): m[b] = Functor.map(_ -> x, s)
           ^^
           unused definition.
```

**Comment by mlutze** [comment]
Created a ticket for the crash: https://github.com/flix/flix/issues/1671

> redundancy errors

Should be `pub`?

**Comment by esbenbjerre** [comment]
> Created a ticket for the crash: #1671
> 
> > redundancy errors
> 
> Should be `pub`?

Gotcha, thank you!

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
