### PR TITLE
chore: remove `File` and `Files` modules

### PR DESCRIPTION
**Pull request by magnus-madsen**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@stephentetley @mlutze I would like to get rid of these two modules. You seem to use them. Would either of you be interested in maintaining them (even temporarily) as a package, so I can merge this.

Also, please see: #9448

**Comment by mlutze** [comment]
I'm happy with whatever's easier for Stephen.

**Comment by stephentetley** [comment]
I'm happy for Files / File to be dropped from the stdlib, I'll change `pretty` and `htmldoc` to use the new interop directly.

I might not have time to do the changes until tomorrow evening though.

**Comment by magnus-madsen** [comment]
> I'm happy for Files / File to be dropped from the stdlib, I'll change `pretty` and `htmldoc` to use the new interop directly.
> 
> I might not have time to do the changes until tomorrow evening though.

No rush

**Comment by magnus-madsen** [comment]
@mlutze Do you want to maintain a package then?

**Comment by mlutze** [comment]
> @mlutze Do you want to maintain a package then?

Yes, I will do so.

**Review by mlutze — APPROVED** [review]

**Pull request merged**
