### PR TITLE
feat: add --Xflexible-regions flag

### PR DESCRIPTION
**Pull request by mlutze**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Does this ensure that no rigid Boolean variables are ever introduced? (Except for with type scheme checking?)

**Comment by mlutze** [comment]
> Does this ensure that no rigid Boolean variables are ever introduced? (Except for with type scheme checking?)

Yes, as far as I can tell.

There are only 3 places `markRigid` is used:
1. here
2. type scheme checking
3. safety checks

Note that activating this flag will cause boolean formula explosions for some reason.

**Comment by magnus-madsen** [comment]
> Note that activating this flag will cause boolean formula explosions for some reason.

To the extent that type checking does not complete?

**Comment by mlutze** [comment]
> > Note that activating this flag will cause boolean formula explosions for some reason.
> 
> To the extent that type checking does not complete?

Correct.

**Pull request merged**
