### PR TITLE
refactor: explicit unit tag optimization

### PR DESCRIPTION
**Pull request by JonathanStarup**
This boolean (which in current is just `tpe == MonoType.Unit` will allow this optimization to continue even with erasure.

It would be nicer to have this information in the structure of the case but the wide span of this AST makes it cumbersome. This solution is in #6968

### CODE REVIEW

**Comment by magnus-madsen** [comment]
What is the problem with checking if `tpe == MonoType.Unit`?

**Comment by JonathanStarup** [comment]
@magnus-madsen the erasure phase will make `MonoType.Unit` become `MonoType.Object`, making it false always.

**Comment by JonathanStarup** [comment]
Im beginning to be a bit unsure why we do erasure "so soon"

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
This is broken now. Perhaps it can be done as part of the reordering of backend phases? 

(Closing since this is less than 15 lines).

**Pull request closed without merging**
