### PR TITLE
refactor: remove `Bool.{not, and, or}`

### PR DESCRIPTION
**Pull request by jaschdoc**
Related to https://github.com/flix/flix/issues/7163

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I think some tests should be removed?

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
@mlutze Broke your code. What a sad day :(

**Comment by mlutze** [comment]
Will there be a replacement?

**Comment by magnus-madsen** [comment]
No. You can make your own. (But don't use keywords as identifiers, if you do).

**Pull request merged**
