### PR TITLE
refactor: use Vector literals in TestVector plus feat: add Vector instances (issues #5433 and #5432)

### PR DESCRIPTION
**Pull request by stephentetley**
This PR adds instances equivalent to List to Vector and uses the Eq instance and Vector literals to clean up TestVector.

To implement `Traversable` I've added `sequence` and `traverse` to the `Vector` module. Likewise I've added `zipWithA` to Vector so it can implement `MonadZip`. The implementations of `sequence` , `traverse` and `zipWithA` are a bit "tricksy" - basically they follow the List versions except the output array exists in advance so there is no consing (the helper `putA!` replaces `consA`) but to allow "failure" for applicatives like `Option` `putA!` takes and returns an array wrapped by the applicative rather than a direct reference to the array. Using a monad could short circuit failure but it uses too much power for the method types (see issue #4540 - which I need to return to at some point).

Note - there is a bug somewhere that is not revealed by the tests but is apparent when using the interpreter:

~~~

     __   _   _
    / _| | | (_)            Welcome to Flix v0.34.0
   | |_  | |  _  __  __
   |  _| | | | | \ \/ /     Enter an expression to have it evaluated.
   | |   | | | |  >  <      Type ':help' for more information.
   |_|   |_| |_| /_/\_\     Type ':quit' or press 'ctrl + d' to exit.
      
flix> Vector.sequence(Vector#{Some(1), Some(2)})
#
# An unexpected error has been detected by the Flix compiler:
#
#   Expected at most one matching definition for 'ToString.toString', but found 2 signatures.
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : v0.34.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 18.0.2 (2022-07-19)
# JVM Vendor   : Eclipse Adoptium
# JAVA_HOME    : C:\Program Files\Eclipse Adoptium\jdk-18.0.2.9-hotspot
# System       : Windows 10 (10.0)
#
# -- Stack Trace --
ca.uwaterloo.flix.util.InternalCompilerException: Expected at most one matching definition for 'ToString.toString', but found 2 signatures.
	at ca.uwaterloo.flix.language.phase.Monomorph$.specializeSigSym(Monomorph.scala:671)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:276)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:289)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:302)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:301)
	at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$specialize$2(Monomorph.scala:353)
	at scala.collection.immutable.List.map(List.scala:250)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:348)
	at ca.uwaterloo.flix.language.phase.Monomorph$.specialize(Monomorph.scala:627)
	at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$run$1(Monomorph.scala:226)
	at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:602)
	at ca.uwaterloo.flix.language.phase.Monomorph$.run(Monomorph.scala:168)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$3(Flix.scala:553)
	at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:103)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$2(Flix.scala:552)
	at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:103)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$1(Flix.scala:551)
	at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:103)
	at ca.uwaterloo.flix.api.Flix.codeGen(Flix.scala:550)
	at ca.uwaterloo.flix.runtime.shell.Shell.$anonfun$compile$1(Shell.scala:357)
	at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:440)
	at ca.uwaterloo.flix.runtime.shell.Shell.compile(Shell.scala:357)
	at ca.uwaterloo.flix.runtime.shell.Shell.run(Shell.scala:375)
	at ca.uwaterloo.flix.runtime.shell.Shell.execEval(Shell.scala:309)
	at ca.uwaterloo.flix.runtime.shell.Shell.execute(Shell.scala:170)
	at ca.uwaterloo.flix.runtime.shell.Shell.loop(Shell.scala:122)
	at ca.uwaterloo.flix.tools.SimpleRunner$.run(SimpleRunner.scala:68)
	at ca.uwaterloo.flix.Main$.main(Main.scala:134)
	at ca.uwaterloo.flix.Main.main(Main.scala)


Expected at most one matching definition for 'ToString.toString', but found 2 signatures.ca.uwaterloo.flix.util.InternalCompilerException: Expected at most one matching definition for 'ToString.toString', but found 2 signatures.
	at ca.uwaterloo.flix.language.phase.Monomorph$.specializeSigSym(Monomorph.scala:671)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:276)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:289)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:302)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:301)
	at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$specialize$2(Monomorph.scala:353)
	at scala.collection.immutable.List.map(List.scala:250)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:348)
	at ca.uwaterloo.flix.language.phase.Monomorph$.specialize(Monomorph.scala:627)
	at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$run$1(Monomorph.scala:226)
	at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:602)
	at ca.uwaterloo.flix.language.phase.Monomorph$.run(Monomorph.scala:168)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$3(Flix.scala:553)
	at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:103)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$2(Flix.scala:552)
	at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:103)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$1(Flix.scala:551)
	at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:103)
	at ca.uwaterloo.flix.api.Flix.codeGen(Flix.scala:550)
	at ca.uwaterloo.flix.runtime.shell.Shell.$anonfun$compile$1(Shell.scala:357)
	at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:440)
	at ca.uwaterloo.flix.runtime.shell.Shell.compile(Shell.scala:357)
	at ca.uwaterloo.flix.runtime.shell.Shell.run(Shell.scala:375)
	at ca.uwaterloo.flix.runtime.shell.Shell.execEval(Shell.scala:309)
	at ca.uwaterloo.flix.runtime.shell.Shell.execute(Shell.scala:170)
	at ca.uwaterloo.flix.runtime.shell.Shell.loop(Shell.scala:122)
	at ca.uwaterloo.flix.tools.SimpleRunner$.run(SimpleRunner.scala:68)
	at ca.uwaterloo.flix.Main$.main(Main.scala:134)
	at ca.uwaterloo.flix.Main.main(Main.scala)
flix> 


~~~

### CODE REVIEW

**Comment by magnus-madsen** [comment]
None of the tests trigger that crash?

**Comment by stephentetley** [comment]
No - just the interpreter. I can't see where the extra instance is coming from either, if I comment out the one in Vector.flix then I get a compiler failure for missing instance.

**Comment by magnus-madsen** [comment]
"Interesting"

**Comment by magnus-madsen** [comment]
@mlutze Any ideas?

**Comment by magnus-madsen** [comment]
Just for sanity, if you break one of the tests, it does fail right?

**Comment by magnus-madsen** [comment]
Did https://github.com/flix/flix/pull/5443 fix the issue?

**Comment by stephentetley** [comment]
Breaking a test in TestVector gets the usual, expected failure - Intellij reports `Tests failed: 1, passed: 1,551, ignored: 36 of 1,588 tests`.

~~~

    @test
    def zipWithA06(): Bool =
        let v = Vector.zipWithA((x, y) -> if (x + y > 5) None else Some(x + y), Vector#{1, 2, 3}, Vector#{1, 1, 1});
        v == None // Some(Vector#{2, 3, 4})
        
~~~

**Comment by stephentetley** [comment]
> Did #5443 fix the issue?

Testing now...

**Comment by stephentetley** [comment]
Yes - fixed...

~~~
     __   _   _
    / _| | | (_)            Welcome to Flix v0.34.0
   | |_  | |  _  __  __
   |  _| | | | | \ \/ /     Enter an expression to have it evaluated.
   | |   | | | |  >  <      Type ':help' for more information.
   |_|   |_| |_| /_/\_\     Type ':quit' or press 'ctrl + d' to exit.
      
flix> Vector.sequence(Vector#{Some(1), Some(2)})
Some(Vector#{1, 2})
flix> 

~~~

**Comment by magnus-madsen** [comment]
Nice. Thanks!

**Pull request merged**
