### PR TITLE
refactor: convert `Main` to `BackendObjectType`

### PR DESCRIPTION
**Pull request by JonathanStarup**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
We lack tests for main. Have you done some manual testing to see that it works as expected?

**Comment by magnus-madsen** [comment]
Especially w.r.t. argument passing from the command line.

**Comment by JonathanStarup** [comment]
good point, will do it asp and update here

**Comment by magnus-madsen** [comment]
Test list:

- You can run a main function from the repl in VSCode.
- You can run `java -jar flix.jar Foo.flix --args abc" to pass arguments.
- You can build a jar with `build-jar` and pass arguments to it the way you normally do.

**Comment by JonathanStarup** [comment]
!!!jar

**Comment by JonathanStarup** [comment]
I thought we removed this `java -jar flix.jar Foo.flix --args abc` :O cool
- `java -jar flix.jar Foo.flix --args abc` runs perfectly
- main function from the repl in VSCode. This works
- You can build a jar with build-jar and pass arguments to it the way you normally do. This works

**Comment by magnus-madsen** [comment]
So everything should work?

**Comment by JonathanStarup** [comment]
Yep

**Pull request merged**
