### PR TITLE
Integrate new Datalog solver

### PR DESCRIPTION
**Pull request by bdahse**

### CODE REVIEW

**Comment by bdahse** [comment]
I copied my Fixpoint sources into main/src/library/Fixpoint and built the feat-new-solver branch. Now there are lots of test failures because it can't compile my Flix sources.
Lots of 

> Undefined name 'Fixpoint.commaSeparate'.

Although that function is public in Fixpoint/ToString.flix and in the Fixpoint namespace.
There's also a compiler exception:

> java.util.NoSuchElementException: key not found: BodyPredicate
	at scala.collection.immutable.Map$Map2.apply(Map.scala:298)
	at ca.uwaterloo.flix.language.phase.jvm.JvmOps$.getTagsOf(JvmOps.scala:740)
	at ca.uwaterloo.flix.language.phase.jvm.JvmOps$.nestedTypesOf(JvmOps.scala:1047)
	at ca.uwaterloo.flix.language.phase.jvm.JvmOps$.nestedTypesOf(JvmOps.scala:1040)
	at ca.uwaterloo.flix.language.phase.jvm.JvmOps$.$anonfun$typesOf$18(JvmOps.scala:1012)

**Comment by magnus-madsen** [comment]
You probably need to include the files in `Flix.scala`.

**Comment by bdahse** [comment]
> 
> 
> You probably need to include the files in `Flix.scala`.

That got rid of the undefined name errors from the Flix source, but there is still the same

> java.util.NoSuchElementException: key not found: BodyPredicate

exception that crashes most tests.

**Comment by magnus-madsen** [comment]
> 
> 
> > You probably need to include the files in `Flix.scala`.
> 
> That got rid of the undefined name errors from the Flix source, but there is still the same
> 
> > java.util.NoSuchElementException: key not found: BodyPredicate
> 
> exception that crashes most tests.

Yes, but there should be broken tests... We don't have guards nor app nor lattice semantics.

**Comment by bdahse** [comment]
> 
> 
> > > You probably need to include the files in `Flix.scala`.
> > 
> > 
> > That got rid of the undefined name errors from the Flix source, but there is still the same
> > > java.util.NoSuchElementException: key not found: BodyPredicate
> > 
> > 
> > exception that crashes most tests.
> 
> Yes, but there should be broken tests... We don't have guards nor app nor lattice semantics.

Some breakage is expected, but I can't tell if this is related to missing features. I guess we will find out if I try to run it on my own code.

**Pull request closed without merging**
