### PR TITLE
refactor: introduce CaseSym

### PR DESCRIPTION
**Pull request by mlutze**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
> [fix thing that any sane language would make illegal](https://github.com/flix/flix/pull/4423/commits/7c64de4e7ece29a205519382e8c6e33408b5438d)

👍

**Comment by magnus-madsen** [comment]
I see a problem with `choose` is it fundamental or can it be fixed?

**Comment by mlutze** [comment]
> I see a problem with `choose` is it fundamental or can it be fixed?

It's unlikely that it's fundamental. I just don't know what it is yet :D

**Comment by magnus-madsen** [comment]
Added some conflicts 😭

**Pull request merged**
