### PR TITLE
refactor: use `phase` in phases that return errors

### PR DESCRIPTION
**Pull request by jaschdoc**
Uses the old `phase` instead of `phaseNew` to avoid redundant let-matches. Makes the code more readable / less cluttered.

Related to https://github.com/flix/flix/issues/8815

### CODE REVIEW

**Comment by magnus-madsen** [comment]
My plan is to get rid of old phase and only have new phase -- which should be renamed.

**Comment by jaschdoc** [comment]
> My plan is to get rid of old phase and only have new phase -- which should be renamed.

But isn't it sort of awkward to always return a tuple? I think it's prettier to only return one thing when there is only one result of the computation

**Comment by magnus-madsen** [comment]
> > My plan is to get rid of old phase and only have new phase -- which should be renamed.
> 
> But isn't it sort of awkward to always return a tuple? I think it's prettier to only return one thing when there is only one result of the computation

Possibly. But I did code duplication in newPhase/phase so that would have to be fixed.

**Comment by magnus-madsen** [comment]
I suggest we do the Unit, Errors thing first and then refactor later.

**Comment by jaschdoc** [comment]
> I suggest we do the Unit, Errors thing first and then refactor later.

Roger that

**Pull request closed without merging**
