### PR TITLE
experiment: principled CLI

### PR DESCRIPTION
**Pull request by mlutze**
Properly separates commands from options

This should help with several issues:
* #3717
* #3720
* an issue I can't find where options are not passed to LSP

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I am not so sold on this approach. I would rather deal with one "option" at a time and figure out how it should work. I think we need more discussion, possibly offline.

**Comment by magnus-madsen** [comment]
We also have a big problem with "file" versus "project" mode that needs to be resolved.

**Comment by magnus-madsen** [comment]
We don't have to close, but lets discuss more.

**Comment by mlutze** [comment]
I've added this as a discussion topic for the next language design meeting.

**Comment by magnus-madsen** [comment]
I am OK with this, but I want to do it gradually, flag by flag.

**Pull request closed without merging**
