### PR TITLE
improve MissingImplementation error

### LINKED ISSUE #1747: Improve MissingImplementation Error
The following program:

```
lawless class Foo[a] {
    def bar(): a
}

instance Foo[String] {
    def xyz(): String = ""
}
```

correctly gives:

image

But:

- [ ] The error message should start with a message, e.g. "Missing implementation of X defined in class Y" (with proper colors)
- [ ] The error message should *not* report the *entire* instance as wrong (too much red). Better to just report "Foo" as the location.

### PR DESCRIPTION
**Pull request by mlutze**
Fixes #1747 

### Features
* The error message should start with a message, e.g. "Missing implementation of X defined in class Y" (with proper colors)
  * [x] impl
  * [ ] test
* The error message should not report the entire instance as wrong (too much red). Better to just report "Foo" as the location.
  * [x] impl
  * [ ] test

### General requirements
* [x] Don't make a complete mess
* [x] Don't break anything else
* [x] Provide documentation
* [x] Add license to new files

Screenshot from 2021-03-07 11-29-05

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Can we move the message up? Like so:

image

This makes it easier to see in VSCode etc.

**Comment by magnus-madsen** [comment]
And maybe replace "defined in class C" by "required by class C".

**Comment by mlutze** [comment]
Screenshot from 2021-03-08 11-18-41

**Comment by mlutze** [comment]
I'll take this opportunity to promote issue #1261, which could make it easier to maintain this uniformity.

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
