### PR TITLE
feat: lsp completions for exhaustive match

### PR DESCRIPTION
**Pull request by Daniel-Anker-Hermansen**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Can you post a screenshot of what it currently gives?

**Comment by magnus-madsen** [comment]
!!!jar

**Comment by magnus-madsen** [comment]
It seems to work pretty well.

**Comment by mlutze** [comment]
Is this the exhaustive match generator I've been praying for?

**Comment by magnus-madsen** [comment]
Two things:

- We should decide what enums to include. Probably not all from the library.
- I think we should fill out with temp variables, e.g `_x` and so forth. Because otherwise the program will not compile until complete.

**Comment by Daniel-Anker-Hermansen** [comment]
I was considering making it so only local types and imports would be considered, but I do not know if that is too restrictive.
I think filling out with temp variables is a good idea. I had not thought about that possibility.

**Comment by magnus-madsen** [comment]
> 

Lets do a new version with temp variables and some form of restriction on what types are considered (I leave that to you)

**Comment by magnus-madsen** [comment]
@Daniel-Anker-Hermansen What's the status on this?

**Comment by Daniel-Anker-Hermansen** [comment]
It now does not complete on enums with less than two cases. It also only considers enums withing the same source uri. It also places temp variables.

**Comment by magnus-madsen** [comment]
I see conflicts

**Comment by magnus-madsen** [comment]
!!!jar

**Comment by magnus-madsen** [comment]
A few issues that should be resolved:

- The variables are sometimes named `elem` and other times `_elem`. Stick to one.
- The cases are prefixed by the enum name. I don't think that should be the default.
- It would be nice to suggest all public enums (but give priority to the one in the current file. Enums from other files would be given lower priority).

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
