### PR TITLE
fix: validation errors in HTML documentation

### PR DESCRIPTION
**Pull request by sockmaster27**
All files should now pass the https://validator.w3.org/nu/ validator.

Maybe it should be included in the test suite?

### CODE REVIEW

**Comment by sockmaster27** [comment]
Wait I've made a mistake

**Comment by sockmaster27** [comment]
Okay there you go

**Comment by sockmaster27** [comment]
Turns out this also happens to fix this: 
image

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
