### PR TITLE
test: add `Test.Handler.NewObject.X.flix`

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes https://github.com/flix/flix/issues/7099

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I had something much smaller in mind. Like 100 lines because in this case we do not need to test different types. 

Simple suggestion: rename `Test.Handler.NewObject.Int32.flix` to just `Test.Handler.NewObject.flix` and nuke all the other files.

**Comment by jaschdoc** [comment]
This also has the same bug as #7112

**Comment by jaschdoc** [comment]
I copied the style that works which we also had in the other PR but the tests should use the other style :)

**Comment by magnus-madsen** [comment]
For both spawn and new object, I had something much simpler in mind.

Really here we just need to check that you can handle an effect.

The code path for the rest is pretty much the same.

So I would like to keep this "PR-style", drop all tests except those for Int32, and merge it in. Ditto for spawn.

Later, if necessary, we can revisit.

**Comment by magnus-madsen** [comment]
The typing rule will not be fixed now, anyway. So it makes sense to merge in something that works until that day arrives.

**Comment by jaschdoc** [comment]
Roger

**Comment by jaschdoc** [comment]
RFR

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
