### PR TITLE
feat: add `Witherable`

### LINKED ISSUE #1927: Type Classes: Add Witherable type class
Propose a design.

See https://typelevel.org/cats/api/cats/TraverseFilter.html for inspiration.

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes #1927

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I would like this to be called `Witherable`.

The central signature is something like:

```
def traverseFilter(x: f[a], f: a -> g[Option[b]]): g[f[b]] = ???
```

(compare to traverse)

**Comment by jaschdoc** [comment]
I've tried my best to add the laws, but the ones I couldn't figure out / experimented with for a while are still left there as comments. Not sure if you have any feedback on that? I'm not quite sure they're even trying to state the right thing hehe...

**Comment by magnus-madsen** [comment]
> I've tried my best to add the laws, but the ones I couldn't figure out / experimented with for a while are still left there as comments. Not sure if you have any feedback on that? I'm not quite sure they're even trying to state the right thing hehe...

Lets just drop the laws for now.

**Comment by jaschdoc** [comment]
All of the laws or just the ones that were commented out?

**Comment by magnus-madsen** [comment]
> All of the laws or just the ones that were commented out?

Just kill all of them

**Comment by jaschdoc** [comment]
Roger

**Pull request merged**
