### PR TITLE
test: add `BoolTable` tests

### LINKED ISSUE #3561: Add BoolTable test cases
See TestBoolTable

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes #3561

### CODE REVIEW

**Comment by jaschdoc** [comment]
I think I found a bug? See test `Minimize.Var1AndVar2AndVar3.02`
```
Expected (and (and x1 x2) x0), but got (and (and x2 x1) x0)
```

**Comment by magnus-madsen** [comment]
> I think I found a bug? See test `Minimize.Var1AndVar2AndVar3.02`
> 
> ```
> Expected (and (and x1 x2) x0), but got (and (and x2 x1) x0)
> ```

I think that's the same formula. Just with different order of variables? Or maybe I am missing something.

**Comment by jaschdoc** [comment]
> > I think I found a bug? See test `Minimize.Var1AndVar2AndVar3.02`
> 
> > 
> 
> > ```
> 
> > Expected (and (and x1 x2) x0), but got (and (and x2 x1) x0)
> 
> > ```
> 
> 
> 
> I think that's the same formula. Just with different order of variables? Or maybe I am missing something.
> 
> 

Yes but for the smaller test cases the equality check does not consider the ordering of the formulas e.g. `Conj(Var(0), Var(1)) == Conj(Var(1), Var(0))`

**Comment by magnus-madsen** [comment]
> > > I think I found a bug? See test `Minimize.Var1AndVar2AndVar3.02`
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > Expected (and (and x1 x2) x0), but got (and (and x2 x1) x0)
> > 
> > 
> > > 
> > 
> > 
> > I think that's the same formula. Just with different order of variables? Or maybe I am missing something.
> 
> Yes but for the smaller test cases the equality check does not consider the ordering of the formulas e.g. `Conj(Var(0), Var(1)) == Conj(Var(1), Var(0))`

Right. That's what I explained poorly by saying you have to adapt the tests.

**Comment by jaschdoc** [comment]
> > > > I think I found a bug? See test `Minimize.Var1AndVar2AndVar3.02`
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Expected (and (and x1 x2) x0), but got (and (and x2 x1) x0)
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > I think that's the same formula. Just with different order of variables? Or maybe I am missing something.
> 
> > 
> 
> > Yes but for the smaller test cases the equality check does not consider the ordering of the formulas e.g. `Conj(Var(0), Var(1)) == Conj(Var(1), Var(0))`
> 
> 
> 
> Right. That's what I explained poorly by saying you have to adapt the tests. 

Hehe great, we're on the same page then :)

**Comment by jaschdoc** [comment]
Oh so the "error" I had before was due to not calling `minimizeFormula` at all... great :+1:

**Comment by jaschdoc** [comment]
Does it respect De Morgan's Law? Or rather implement it?

```scala
  test("Minimize.Var1AndVar2AndVar3AndVar4.03") {
    assertResult(expected = Conj(Conj(Var(0), Var(1)), Conj(Var(2), Var(3))))(actual = minimizeFormula(Neg(Disj(Conj(Neg(Neg(Var(0))), Neg(Neg(Var(1)))), Conj(Neg(Neg(Var(2))), Neg(Neg(Var(3))))))))
  }
```
Errors with:
```
Expected (and (and x0 x1) (and x2 x3)), but got !((or (and x0 x1) (and x2 x3)))
```

**Comment by jaschdoc** [comment]
Hmm... shouldn't this be true equivalent?
```scala
  test("Minimize.Var1AndVar2AndVar3AndVar4.04") {
    assertResult(expected = Disj(Disj(Var(0), Var(1)), Disj(Var(2), Var(3))))(actual = minimizeFormula(Neg(Neg(Disj(Disj(Var(0), Var(1)), Disj(Var(2), Var(3)))))))
  }
```
Errors with:
```
Expected (or (or x0 x1) (or x2 x3)), but got !(!((or (or x0 x1) (or x2 x3))))
```

**Comment by magnus-madsen** [comment]
> 

Yes, but we don't support more than 3 variables yet. So your example fails to minimize :)

**Comment by magnus-madsen** [comment]
Its good you are finding these  because these turn out to be expected limitations/things which means that there are probably not any "real" bugs.

**Comment by magnus-madsen** [comment]
I think the scope of this is about right.

**Comment by jaschdoc** [comment]
Okay so what do we do about the test that fails?

**Comment by magnus-madsen** [comment]
> Okay so what do we do about the test that fails?

But I thought that we discussed those? Is there a test that fails which you think should not?

Paste it here and we can discuss.

**Comment by magnus-madsen** [comment]
Ah- the test that fails we cannot handle yet. Just delete it?

**Comment by magnus-madsen** [comment]
I promised Gold, not Unobtanium

**Comment by jaschdoc** [comment]
Haha okay roger that :smile:

**Comment by jaschdoc** [comment]
Ready for review

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
