### PR TITLE
Remove unused `apply` on Def classes

### PR DESCRIPTION
**Pull request by magnus-madsen**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@JonathanStarup Do you think we can merge this?

**Comment by magnus-madsen** [comment]
@JonathanStarup I merged it, but still please have a look :)

**Comment by JonathanStarup** [comment]
Looks good but documentation is a bit dated, I can try and fix it

**Comment by JonathanStarup** [comment]
Did this cause this jump? 
image

**Comment by magnus-madsen** [comment]
> Did this cause this jump? image

Yes! :)

**Comment by magnus-madsen** [comment]
Interestingly there was no increase in performance, only in the size of the generated code.

**Comment by JonathanStarup** [comment]
We could try artificially generating 10 times the code, see what the performance impact is

**Pull request merged**
