### PR TITLE
fix: address issues relating to arrows, type aliases, and enums

### PR DESCRIPTION
**Pull request by mlutze**
related to #3589

### CODE REVIEW

**Comment by magnus-madsen** [comment]
What's this about?

**Comment by mlutze** [comment]
This fixes two issues:
1. We (I) erroneously assumed substitution would only be used on kinded types. That's not the case so substitution needs to handle unkinded types properly.
2. Redundancy looks at the translated type of an alias instead of the original type. This is wrong in the case of phantom types. E.g., if I have `type alias T[_a] = Int32` and then I do `T[b]` somewhere, the `b` is not counted as used.

**Comment by magnus-madsen** [comment]
RFM?

**Comment by mlutze** [comment]
Ready.

**Pull request merged**
