### PR TITLE
test: additional `NewObject` tests

### PR DESCRIPTION
**Pull request by paulbutcher**
This concludes, I believe, all the "happy path" tests for NewObject (shout if you think I've missed any)

### CODE REVIEW

**Comment by magnus-madsen** [comment]
> This concludes, I believe, all the "happy path" tests for NewObject (shout if you think I've missed any)

I think this covers everything I can think of.

**Comment by magnus-madsen** [comment]
The next steps would be abstract classes?

**Comment by magnus-madsen** [comment]
Oh- what happened to interfaces with generics?

**Comment by paulbutcher** [comment]
> Oh- what happened to interfaces with generics?

https://github.com/paulbutcher/flix/blob/d588b4862350541f7ec6cc1dc9072f8b91cbaf29/main/test/flix/Test.Exp.Jvm.NewObject.flix#L219-L237

**Comment by paulbutcher** [comment]
> The next steps would be abstract classes?

https://github.com/paulbutcher/flix/blob/d588b4862350541f7ec6cc1dc9072f8b91cbaf29/main/test/flix/Test.Exp.Jvm.NewObject.flix#L274-L284

**Comment by magnus-madsen** [comment]
Goodie. Do we have any tests with generics and *primitive values*. I guess they would negative tests because Java does not allow that?

**Comment by paulbutcher** [comment]
> Goodie. Do we have any tests with generics and _primitive values_. I guess they would negative tests because Java does not allow that?

I'm not sure how I would write such a test (given that it wouldn't compile)?

**Comment by magnus-madsen** [comment]
> > Goodie. Do we have any tests with generics and _primitive values_. I guess they would negative tests because Java does not allow that?
> 
> I'm not sure how I would write such a test (given that it wouldn't compile)?

Indeed.

**Pull request merged**
