### PR TITLE
docs: update Swing example

### PR DESCRIPTION
**Pull request by jaschdoc**
Now updated to the same style as the original example: https://docs.oracle.com/javase/tutorial/uiswing/examples/start/HelloWorldSwingProject/src/start/HelloWorldSwing.java

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Not sure I like that. As @JonathanStarup said, why not just do it in the straightforward way. It feels like THEIR docs are outdated.

**Comment by jaschdoc** [comment]
Maybe `SwingUtilities.invokeLater` manages the lifecycle of Swing stuff? Also, if the app does several other things, you would not want the main thread to be handling UI stuff, right?

**Comment by jaschdoc** [comment]
Of course this is just a hello world app but still

**Comment by magnus-madsen** [comment]
@JonathanStarup Thoughts?

**Comment by magnus-madsen** [comment]
I would prefer to keep it simple unless there is an argument against.

**Comment by JonathanStarup** [comment]
maybe this is the more proper way after some quick reading. I think there is both pros for not using invokelater (simplicity) and for using it (showing people how to use new object, which is pretty relevant when using swing with listeners etc)

**Comment by magnus-madsen** [comment]
> maybe this is the more proper way after some quick reading. I think there is both pros for not using invokelater (simplicity) and for using it (showing people how to use new object, which is pretty relevant when using swing with listeners etc)

We will have listener examples though

**Comment by magnus-madsen** [comment]
I have not heard a good argument yet for the extra complexity, so let us keep it simple.

**Pull request closed without merging**
