### PR TITLE
chore: simplify `LiftedAst` and `LoweredAst`

### PR DESCRIPTION
**Pull request by magnus-madsen**

### CODE REVIEW

**Comment by mlutze** [comment]
Is the new rule that back-end ASTs are not-fully qualified?

**Comment by magnus-madsen** [comment]
> Is the new rule that back-end ASTs are not-fully qualified?

Yes, ultimately all ASTs. We are trying to slim down the visual space.

Obviously some phases will still be prefixed, e.g. when translating from one AST to another AST.

**Comment by magnus-madsen** [comment]
I don't see the benefit (anymore) in having them prefix. You?

**Comment by mlutze** [comment]
The main thing is that in the front end we have e.g. `NamedAst.Type` and `Type`. I _think_ there's no AST wherein we could have confusion, but I'm not totally sure.

**Comment by magnus-madsen** [comment]
> The main thing is that in the front end we have e.g. `NamedAst.Type` and `Type`. I _think_ there's no AST wherein we could have confusion, but I'm not totally sure.

Yeah, but probably we should resolve such situations when we discover them.

**Pull request merged**
