### PR TITLE
refactor: remove dead code from `Validation`

### PR DESCRIPTION
**Pull request by jaschdoc**
Related to https://github.com/flix/flix/issues/5026

### CODE REVIEW

**Comment by jaschdoc** [comment]
# Benchmarks

**We seem to have regained some performance compared to** https://github.com/flix/flix/pull/5174

## This branch 807b2b54792df3b2597d47aa869fd39571d48e66

```
====================== Flix Compiler Throughput ======================

Throughput (best): 13,230 lines/sec (with 8 threads.)

  min:  4,620, max: 13,230, avg: 10,762, median: 11,903

  The highest throughput was in iteration: 9 (out of 10).
  The ratio between the best and worst iteration was: 2.9x.

Finished 10 iterations on 62,779 lines of code in 64 seconds.


====================== Flix Compiler Throughput ======================

Throughput (best): 13,211 lines/sec (with 8 threads.)

  min:  4,470, max: 13,211, avg: 10,668, median: 11,976

  The highest throughput was in iteration: 8 (out of 10).
  The ratio between the best and worst iteration was: 3.0x.

Finished 10 iterations on 62,779 lines of code in 64 seconds.


====================== Flix Compiler Throughput ======================

Throughput (best): 13,028 lines/sec (with 8 threads.)

  min:  4,859, max: 13,028, avg: 10,908, median: 11,910

  The highest throughput was in iteration: 9 (out of 10).
  The ratio between the best and worst iteration was: 2.7x.

Finished 10 iterations on 62,779 lines of code in 62 seconds.
```

## Main c9dcf3b7b3fe3c7ebd8b6e5ecce9481077a3fe85

**This commit is before the refactor validation in** https://github.com/flix/flix/pull/5174

```                                                                                
====================== Flix Compiler Throughput ======================

Throughput (best): 13,137 lines/sec (with 8 threads.)

  min:  4,786, max: 13,137, avg: 10,707, median: 11,672

  The highest throughput was in iteration: 7 (out of 10).
  The ratio between the best and worst iteration was: 2.7x.

Finished 10 iterations on 62,779 lines of code in 63 seconds.

                                                                                
====================== Flix Compiler Throughput ======================

Throughput (best): 12,856 lines/sec (with 8 threads.)

  min:  4,755, max: 12,856, avg: 10,561, median: 11,597

  The highest throughput was in iteration: 8 (out of 10).
  The ratio between the best and worst iteration was: 2.7x.

Finished 10 iterations on 62,779 lines of code in 64 seconds.


====================== Flix Compiler Throughput ======================

Throughput (best): 11,464 lines/sec (with 8 threads.)

  min:  3,902, max: 11,464, avg:  9,268, median: 10,394

  The highest throughput was in iteration: 9 (out of 10).
  The ratio between the best and worst iteration was: 2.9x.

Finished 10 iterations on 62,779 lines of code in 74 seconds.
```

**Comment by magnus-madsen** [comment]
Thanks, let us see what happens on arewefast.flix.dev :)

**Comment by magnus-madsen** [comment]
I don't see any change, so I think we can keep what we have.

However, I would like to get rid of the unused `combineFailureStreams` etc.

**Comment by jaschdoc** [comment]
RFR

**Comment by jaschdoc** [comment]
Looks like there's a type error in @mlutze `flix-json`?

```
 -- Type Error -------------------------------------------------- src/Jsonable.flix

>> Expected type: 'Int32' but found type: 'JsonElement'.

223 |             case JsonArray(l) => l |> List.zipWithIndex |> Result.traverse(match (val, i) -> Json/FromJson.fromJsonAt(p !! i, val))
                                                                                                                 ^^^^^^^^^^
                                                                                                                 expression has unexpected type.
```

**Comment by mlutze** [comment]
> Looks like there's a type error in @mlutze `flix-json`?
> 
> ```
>  -- Type Error -------------------------------------------------- src/Jsonable.flix
> 
> >> Expected type: 'Int32' but found type: 'JsonElement'.
> 
> 223 |             case JsonArray(l) => l |> List.zipWithIndex |> Result.traverse(match (val, i) -> Json/FromJson.fromJsonAt(p !! i, val))
>                                                                                                                  ^^^^^^^^^^
>                                                                                                                  expression has unexpected type.
> ```
> 
> Have we swapped the type parameters for `Result` on main?

It's due to the zip with index changes. I'll get around to it :)

**Comment by jaschdoc** [comment]
Alright, coolio :)

**Pull request merged**
