### PR TITLE
refactor: reduce purity casts in datalog engine

### LINKED ISSUE #2811: Reduce effect casts in Datalog solver
The Datalog solver currently has a lot of casts to pure. This is unsafe. I think most functions should simply be impure and then only the top-level functions should be marked as pure and have a cast.

@JonathanStarup I suggest that you take a look and then we can discuss before you start making any changes.

### PR DESCRIPTION
**Pull request by JonathanStarup**
fixes #2811

### CODE REVIEW

**Comment by JonathanStarup** [comment]
Right now there is an issue regarding `queryWith` in MutMap that cannot receive an impure condition argument. Do you have input on this @magnus-madsen?

**Comment by magnus-madsen** [comment]
> Right now there is an issue regarding `queryWith` in MutMap that cannot receive an impure condition argument. Do you have input on this @magnus-madsen?

I think we should make `query` and `queryWith` effect polymorphic.

**Comment by JonathanStarup** [comment]
> > Right now there is an issue regarding `queryWith` in MutMap that cannot receive an impure condition argument. Do you have input on this @magnus-madsen?
> 
> I think we should make `query` and `queryWith` effect polymorphic.

Okay, ill fix that then. I wasn't sure if it was a design choice. But it makes sense.

**Comment by JonathanStarup** [comment]
Status:
* There are unsafe casts in some ToString instances but these only touch debugging code
* There is a single unsafe cast using `MutMap.queryWith` unfixable by #2854.
* There are unsafe top-level casts in Solver.flix to the functions that lowering uses. These are however only locally impure
* There are unsafe casts in Tuple ordering and equality. This is used in non-debug code (there is a Map with tuple keys fx). Maybe you can judge this @magnus-madsen?

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
