### PR TITLE
Ant build

### PR DESCRIPTION
**Pull request by magnus-madsen**
I am merging this into master. Feel free to undo the changes to build.sbt.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
The build still fails on travis due to memory usage. But there are some fixes in master that may (or may not) solve this.

**Comment by mhyee** [comment]
I will look at the diff it later.

I've already expressed my preference for having SBT as the sole build system, because it's the default -- and expected -- build system for Scala projects.

**Comment by paulp** [comment]
@mhyee Trying to support both sbt and ant seems even less pleasant than supporting either one. I don't know what the history is with ant vs. sbt but I think you can have a working sbt build with modest changes (see #180) at which point sbt alone feels like the lesser evil.

**Comment by magnus-madsen** [comment]
There is an on-going debate. I think for now we will try to maintain both. We still have issues with how to package Z3 (which is only necessary for the verifier) and how to get all the tests to run on travis (apparently we hit resource limits there).

**Comment by paulp** [comment]
For what it's worth, I've also [faced off with z3](https://github.com/paulp/pspz3).

**Pull request merged**
