### PR TITLE
chore: support `AtomicOps` in `Verifier`

### LINKED ISSUE #6001: Extend `Verifier` to handle `AtomicOp`s

### PR DESCRIPTION
**Pull request by sockmaster27**
Related to #6001

### CODE REVIEW

**Comment by sockmaster27** [comment]
Am I on the right track?

**Comment by sockmaster27** [comment]
Should a test file be added?
Should the `Verifier` be inserted [here](https://github.com/flix/flix/blob/24f967a9ef00c6eb2d19a4e806d683f8808f0d0b/main/src/ca/uwaterloo/flix/api/Flix.scala#L523), and in that case in which position?

**Comment by magnus-madsen** [comment]
It should be inserted around here:

https://github.com/flix/flix/blob/24f967a9ef00c6eb2d19a4e806d683f8808f0d0b/main/src/ca/uwaterloo/flix/api/Flix.scala#L598

**Comment by magnus-madsen** [comment]
> Should a test file be added?

No test file. You insert it and if it does not fail, we are happy :)

**Comment by magnus-madsen** [comment]
> Am I on the right track?

Not yet. You should follow the same style that was already there. Match on one operation at a time. Do not worry about code duplication for now. The goal is "obviously correct", not "smart".

**Comment by sockmaster27** [comment]
Is the `Verifier` only used when debugging?

**Comment by magnus-madsen** [comment]
> Is the `Verifier` only used when debugging?

More or less. We may decide to enable it by default later.

**Comment by magnus-madsen** [comment]
> The verifier is spitting out a lot of errors that aren't related to this

Hmm. Like what?

**Comment by magnus-madsen** [comment]
> Right now runtime errors thrown by the verifier are only printed to the terminal and do not fail the tests. Is this intentional?

Maybe all the errors was the reason it was made this way? (At least until they have been fixed).

**Comment by magnus-madsen** [comment]
Ugh. I think @mlutze or @JonathanStarup needs to look deeper into this.

But how about we merge in your changes?

**Comment by sockmaster27** [comment]
Sure, but this only covers the unary and binary operations

**Comment by magnus-madsen** [comment]
@sockmaster27 Convert to non-draft.

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
