### PR TITLE
feat: remove `do` keyword from frontend

### PR DESCRIPTION
**Pull request by magnus-madsen**

### CODE REVIEW

**Review by mlutze — APPROVED** [review]

**Comment by magnus-madsen** [comment]
@mlutze @JonathanStarup @stephentetley We no longer need `do` in front of a call to an effect operation.

In fact this PR removes `do`. Could you update your community packages? All you need is to go from `do F.f` to `F.f`

**Comment by stephentetley** [comment]
Thanks for the heads up Magnus.

Is Community Build looking at the head of the repository or the latest release tarball? I've updated both, but I doth think I was using do in the previously release version.

**Comment by magnus-madsen** [comment]
> Thanks for the heads up Magnus.
> 
> Is Community Build looking at the head of the repository or the latest release tarball? I've updated both, but I doth think I was using do in the previously release version.

I think it uses the latest master. (so one does not have to create new releases).

**Comment by magnus-madsen** [comment]
@stephentetley 
On a related note, I am hoping #8848 lands this week. This master will support proper set effects - which should enable effects and handlers. The documentation has already been updated here: https://doc.flix.dev/effect-system.html

**Comment by magnus-madsen** [comment]
@mlutze @JonathanStarup I am merging this. Please update your packages :)

**Pull request merged**
