### PR TITLE
refactor: migrate EntryPoint to before Typer

### PR DESCRIPTION
**Pull request by mlutze**
related to #3338

### CODE REVIEW

**Comment by mlutze** [comment]
So far the error for bad return type seems reasonable. But the args error might be confusing:

### Bad return type
```
❌ -- Type Error -------------------------------------------------- file:///home/matt/Documents/flix-home/flix/personal/flix-sandbox/Main.flix

>> ToString is not defined on E123. Define or derive an instance of ToString.

129 | def main(): E123 = Asdf
          ^^^^
          missing ToString instance


Explanation:
To define a string representation of 'E123', either:

  (a) define an instance of ToString for 'E123', or
  (b) derive an instance of ToString for 'E123'.

To automatically derive an instance, you can write:

  enum Color with ToString {
    case Red, Green, Blue
  }
```

### Bad arguments
```
❌ -- Type Error -------------------------------------------------- file:///home/matt/Documents/flix-home/flix/personal/flix-sandbox/Main.flix

>> Unable to unify the types: 'String' and 'Unit'.

129 | def main(x: String): Unit = Asdf
          ^^^^
          mismatched types.

Type One: String -> Unit
Type Two: Unit ->{eff} result

❌ -- Type Error -------------------------------------------------- file:///home/matt/Documents/flix-home/flix/personal/flix-sandbox/Main.flix

>> The type scheme: 'String -> E123' cannot be generalized to 'String -> Unit'.

129 | def main(x: String): Unit = Asdf
          ^^^^
          unable to generalize the type scheme.

The declared type does not match the inferred type:

  Declared: String -> Unit
  Inferred: String -> E123

Explanation:

The declared type variables:
  << no type variables >>

The inferred type variables:
  << no type variables >>
```

**Comment by magnus-madsen** [comment]
What was the goal here and is it still relevant?

**Comment by mlutze** [comment]
I don't recall exactly. But my best guess is that we wanted to move this phase before the Typer because the Typer introduces more information such as inferred scheme, so it would be less complex to do entrypoint stuff before the Typer. (Note the diff size: net -70 LOC)

**Comment by magnus-madsen** [comment]
Maybe we close this or ?

**Comment by mlutze** [comment]
> Maybe we close this or ?

Yeah we can revisit later if needed

**Pull request closed without merging**
