### PR TITLE
feat: add compiler support for BigDecimal (related to #4736)

### PR DESCRIPTION
**Pull request by stephentetley**
This PR adds compiler support for BigDecimal. The new type is called `BigDecimal` and the suffix for literals is "ff".

Support for `BigDecimal` is directly patterned after the existing support for `BigInt`, basically I ran the following two `greps` on the Flix compiler codebase and copied the code for `BigInt` changing it to support `BigDecimal`:

~~~ 

find . -name "*.scala" | xargs grep -n "BigInt"

find . -name "*.flix" | xargs grep -n "BigInt"

~~~

`BigInt` has support for logical operations and bit shifting which I didn't copy as `BigDecimal` is obviously a floating point type.

I've left out general support for `BigDecimal` in the stdlib but have included some support (e.g. `Eq` and `Boxable` instances) so that `BigDecimal` can support the same tests as `BigInt` in the `test.flix` test suite (a further PR will extend stdlib support).

There is one non- `BigDecimal` code change in `main/src/ca/uwaterloo/flix/language/dbg/FormatExpression.scala` where formatting `BigInt` used the `Int64` suffix which I took to be an error and corrected.

~~~

-    case TypedAst.Expression.BigInt(lit, _) => s"${lit}i64"
+    case TypedAst.Expression.BigInt(lit, _) => s"${lit}ii"

~~~

### CODE REVIEW

**Comment by mlutze** [comment]
I haven't looked at this, but I know that `BigDecimal.equals` in Java compares scale as well as value. How is/should this be handled?

**Comment by stephentetley** [comment]
@mlutze - good spot.

I'd lean towards leaving the Flix `Eq.eq` as Java's `equals` but adding a function to the `BigInteger` library for "numerically equals" i.e allowing different scales.

**Comment by magnus-madsen** [comment]
There are three things I would like to discuss (post merge):

- The choice of suffix.
- What is `0.0ff / 0.0ff`?
- `BigDecimal` or `BigInt`?

**Comment by magnus-madsen** [comment]
@stephentetley Merged! Thanks for all the hard work :) It must have been quite an adventure to modify the compiler.

**Comment by magnus-madsen** [comment]
If you have time, would you be willing to update: https://doc.flix.dev/primitive-types.html (there is a nice edit link top right) :)

**Comment by stephentetley** [comment]
> @stephentetley Merged! Thanks for all the hard work :) It must have been quite an adventure to modify the compiler.

Yes the only other time I've done it was a one-liner.

**Comment by stephentetley** [comment]
> If you have time, would you be willing to update: https://doc.flix.dev/primitive-types.html (there is a nice edit link top right) :)

Yes I'll look into it after I've submitted the stdlib changes PR.

**Pull request merged**
