### PR TITLE
refactor: make `Array` functions take region as first parameter

### PR DESCRIPTION
**Pull request by jaschdoc**
Related to #4089

### CODE REVIEW

**Comment by jaschdoc** [comment]
I'm not quite sure why it fails with this error message after simply changing the order of parameters:
```
Unable to compile. Failed with: 2 errors.

-- Type Error -------------------------------------------------- main/test/ca/uwaterloo/flix/library/TestToString.flix

>> ToString is not defined on Array[Char, r]. Define or derive an instance of ToString.

368 |         toString(Array.new(r, 'a', 3)) == "[a, a, a]"
              ^^^^^^^^
              missing ToString instance


-- Type Error -------------------------------------------------- main/test/ca/uwaterloo/flix/library/TestToString.flix

>> ToString is not defined on Array[Array[Int32, r], r]. Define or derive an instance of ToString.

377 |         toString(Array.new(r, [1, 2, 3], 3)) == "[[1, 2, 3], [1, 2, 3], [1, 2, 3]]"
              ^^^^^^^^
              missing ToString instance
```

**Comment by magnus-madsen** [comment]
I wonder if it is calling Array.toString or ToString.toString?

**Comment by jaschdoc** [comment]
`ToString.toString`

**Comment by jaschdoc** [comment]
Ah I found the issue! Thanks :)

**Pull request merged**
