### PR TITLE
refactor: use regions in `StringBuilder`

### LINKED ISSUE #3609: Refactor `StringBuilder` to use regions

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes #3609

### CODE REVIEW

**Comment by jaschdoc** [comment]
I think this is ready to be merged but there are some issues with `String` functions that crash the compiler. I've made some issues with the errors I've encountered but I think we should refactor `String` in a separate PR.

**Comment by magnus-madsen** [comment]
Looks good 👍

**Comment by jaschdoc** [comment]
@magnus-madsen ready to merge btw :smile:

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
