### PR TITLE
feat: store the arguments array in the `Global` object.

### PR DESCRIPTION
**Pull request by JonathanStarup**
As discussed in #3338. Main.class is now also accepts entry points of either array[string] or no arg

### CODE REVIEW

**Comment by JonathanStarup** [comment]
@magnus-madsen there is a problem regarding our jvm class loading hack of our generated class. There is a mock class in the project to allow the class lookup to succeed. This is however an actual link so the mock class actually gets used. The mock args field is used by the flix import and the assignment of of the field happens on the generated args field. I'm not sure how to fix this.

**Comment by magnus-madsen** [comment]
Do you load the class with the right class loader?

**Comment by magnus-madsen** [comment]
Presumably the flix class loader needs to load the actual generated Global class.

**Comment by JonathanStarup** [comment]
> Presumably the flix class loader needs to load the actual generated Global class.

yes i think this is the problem

**Comment by JonathanStarup** [comment]
> I think the system is more rich than that. But you observation does present a solution, use a custom class loader for that part of the compiler. However I don't think this should be necessary.

We override findClass but call loadClass. loadClass only uses findClass if the class isn't loaded already, which the mock class is. I changed it to override loadClass so now the flix import uses the generated class but Main.class uses the mock class I think

**Comment by magnus-madsen** [comment]
I merged https://github.com/flix/flix/pull/3490

**Pull request merged**
