### PR TITLE
Iterator Phase 6

### PR DESCRIPTION
**Pull request by jaschdoc**
Related to #2459 
Has merge conflict with #2667

### CODE REVIEW

**Comment by mlutze** [comment]
While you're here, can you fix the tabs in this file?

**Comment by jaschdoc** [comment]
> While you're here, can you fix the tabs in this file?

I'm not quite sure I follow. The indentation looks okay to me?

**Comment by mlutze** [comment]
For example, this line has a tab instead of spaces: https://github.com/flix/flix/blob/b8f46bb98dab3eb19efa0e5c81aa535f8681d90f/main/src/library/Iterator.flix#L245

**Comment by jaschdoc** [comment]
Oh right yeah I'll have a look at it. The thing is that it looks okay in both intellij and vscode so it's really hard to tell when something is off

**Comment by mlutze** [comment]
> Oh right yeah I'll have a look at it. The thing is that it looks okay in both intellij and vscode so it's really hard to tell when something is off

Yep, I only noticed it when I was looking at it on Github :)

**Comment by jaschdoc** [comment]
Submitted this https://github.com/flix/flix/issues/2490

**Pull request merged**
