### PR TITLE
WIP n-ary enums

### PR DESCRIPTION
**Pull request by mlutze**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
What's important to me is that we push this through to the backend such that we have Tag0, Tag1, ...,Tagn savings memory on our representation of Cons.

**Comment by magnus-madsen** [comment]
I am not sure it is worth dealing with restrictable variants... I would only do it if it is easier.

**Comment by mlutze** [comment]
> I am not sure it is worth dealing with restrictable variants... I would only do it if it is easier.

The main complexity is in the back end. I won't be able to deal with that, so I'm closing this PR.

**Comment by magnus-madsen** [comment]
> > I am not sure it is worth dealing with restrictable variants... I would only do it if it is easier.
> 
> The main complexity is in the back end. I won't be able to deal with that, so I'm closing this PR.

Why is that so complicated?

**Comment by mlutze** [comment]
> > > I am not sure it is worth dealing with restrictable variants... I would only do it if it is easier.
> > 
> > 
> > The main complexity is in the back end. I won't be able to deal with that, so I'm closing this PR.
> 
> Why is that so complicated?

Something about monomorph and erasing... Jonathan explained it to me and it sounded like it fell into the "let's redesign monomorph instead" bucket.

**Comment by JonathanStarup** [comment]
> Why is that so complicated?

Our current monomorph tricks for enums are very particular and do not work if you remove the tuple inside the enum

**Comment by JonathanStarup** [comment]
Should be easy if we follow the ticket i just made

**Comment by JonathanStarup** [comment]
@magnus-madsen @mlutze The type of `None` is still `Option[t]` right (and not `Unit -> Option[t]`)?

**Comment by mlutze** [comment]
> @magnus-madsen @mlutze The type of `None` is still `Option[t]` right (and not `Unit -> Option[t]`)? 

Right

**Pull request closed without merging**
