### PR TITLE
refactor: Single call to `mkTestDir` in `CompilerSuite`

### PR DESCRIPTION
**Pull request by ninaandrup**
Related to https://github.com/flix/flix/issues/3144

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@ninaandrup Could you try to fix the last redundancy errors? And if not just say so, and @mlutze can swoop in :)

**Comment by mlutze** [comment]
If you're referring to the effect test redundancy errors, it's not currently possible to resolve them just due to the state of effects in the compiler. I would recommend just having a separate suite for the tests while under development, and we'll move it back when we can.

**Comment by magnus-madsen** [comment]
Could we remove these tests temporarily or put them somewhere else?

**Comment by magnus-madsen** [comment]
I think this can now be solved.

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
