### PR TITLE
Use sets for type constraints

### PR DESCRIPTION
**Pull request by mlutze**

### CODE REVIEW

**Comment by mlutze** [comment]
!!!benchmark

**Comment by magnus-madsen** [comment]
I think you need to benchmark locally.

If there is little difference, then I am not sure if it is worth it.

**Comment by mlutze** [comment]
Nothing significant in the local benchmark either:

stat | master throughput | feature throughput | absolute difference | percent difference
--- | --- | --- | --- | ---
max | 15173 | 15509 | +336 | +2.2%
avg | 12490 | 12300 | -190 | -1.5%
median | 13772 | 13483 | -289 | -2.1%
min | 3741 | 3798 | +57 | +1.5%

phase | master time | feature time | absolute difference | percent difference
--- | --- | --- | --- | ---
Stratifier | 15042350 | 16277584 | +1235234 | +8.2%
Simplifier | 12743200 | 15014194 | +2270994 | +17.8%
Eraser | 22032749 | 21452901 | -579848 | -2.6%
Namer | 68999623 | 69102351 | +102728 | +0.1%
Terminator | 4521898 | 5059829 | +537931 | +11.9%
Finalize | 40241532 | 41274640 | +1033108 | +2.6%
Reader | 1014117 | 989292 | -24825 | -2.4%
TreeShaker | 33945015 | 35000196 | +1055181 | +3.1%
Typer | 939526614 | 923423595 | -16103019 | -1.7%
Lowering | 13852715 | 14561761 | +709046 | +5.1%
Weeder | 18803030 | 22107489 | +3304459 | +17.6%
Resolver | 136147187 | 132222010 | -3925177 | -2.9%
Safety | 4679309 | 5687552 | +1008243 | +21.5%
Tailrec | 5575645 | 5546220 | -29425 | -0.5%
Documentor | 1504 | 2027 | +523 | +34.8%
Optimizer | 13596674 | 13411510 | -185164 | -1.4%
Redundancy | 49236762 | 52184525 | +2947763 | +6.0%
PatternExhaustiveness | 31187653 | 34880529 | +3692876 | +11.8%
LambdaLift | 14422783 | 14756114 | +333331 | +2.3%
Parser | 182935718 | 165349883 | -17585835 | -9.6%
JvmBackend | 948733157 | 939800346 | -8932811 | -0.9%
ClosureConv | 39221587 | 39891193 | +669606 | +1.7%
VarNumbering | 8491730 | 9192852 | +701122 | +8.3%
Monomorph | 243899522 | 245240661 | +1341139 | +0.5%
Instances | 2331603 | 2327371 | -4232 | -0.2%

**Comment by mlutze** [comment]
Closing for now since there's no significant performance impact.

**Pull request closed without merging**
