### PR TITLE
refactor: make `Ref` module use `struct`

### PR DESCRIPTION
**Pull request by dghosef**
I could potentially do more work to also get rid of `ref` in the compiler if that would be helpful.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
> I could potentially do more work to also get rid of `ref` in the compiler if that would be helpful.

We leave that extra work for later.

**Comment by magnus-madsen** [comment]
@mlutze Flixball needs to use Ref and not ref.

**Comment by mlutze** [comment]
!!!rerun

**Comment by magnus-madsen** [comment]
@stephentetley We are about to replace the internal implementation of `Ref` with a struct.

However, this breaks the `ref` and `deref` expressions. Instead one should use, `Ref.fresh`, `Ref.get`, and `Ref.put`.

Do you have a lot of code that uses `ref` and `deref`? If so, we can implement a grace period.

**Comment by stephentetley** [comment]
Thanks Magus, I haven't used ref cells much so I'm fine not to have a transition period.

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
