### PR TITLE
feat: use `ResolutionError.UndefinedName` to improve auto-completion

### PR DESCRIPTION
**Pull request by magnus-madsen**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Yikes, IDEA destroyed some formatting :/

**Comment by paulbutcher** [comment]
> Yikes, IDEA destroyed some formatting :/

It did, but it looks like it did that because some of my whitespace was out for some reason. I'll sort to avoid similar issues in the future.

**Comment by paulbutcher** [comment]
OK, I think I see what you have in mind. I'll have a crack at turning this into something that's in a fit state to be merged.

**Comment by paulbutcher** [comment]
Ah, you're thinking of this as an alternative to the `???` (I thought it was a both/and, not an either/or) 👍

**Comment by magnus-madsen** [comment]
> Ah, you're thinking of this as an alternative to the `???` (I thought it was a both/and, not an either/or) 👍

I think this style will eventually be able to cover the scenarios ??? cover and more precisely. (At least if we only consider auto-complete)

**Comment by paulbutcher** [comment]
Understood, and makes sense. In which case ignore my recent comments in #3954

**Comment by magnus-madsen** [comment]
image

**Comment by magnus-madsen** [comment]
I should probably have written something like `closestBefore`

**Pull request merged**
