### PR TITLE
Rework `Documentor`

### PR DESCRIPTION
**Pull request by ninaandrup**
#2528

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Let us get this in a state where it runs (without crashing). Its okay if does not produce all the output yet nor if it is incomplete. Then when it is in, I can start building on it and you can refine it :)

**Comment by ninaandrup** [comment]
> Let us get this in a state where it runs (without crashing). Its okay if does not produce all the output yet nor if it is incomplete. Then when it is in, I can start building on it and you can refine it :)

Er det fint, som det er nu?

**Comment by magnus-madsen** [comment]
@ninaandrup You still have some `???` which I run into. Just replace them by the string "placeholder" or whatever.

**Comment by magnus-madsen** [comment]
Ill merged it now and then we can work on it to revise.

**Pull request merged**
