### PR TITLE
refactor: support for `InvokeConstructor2` in `File.flix`

### PR DESCRIPTION
**Pull request by chanattan**
Part of #7944.

### CODE REVIEW

**Comment by chanattan** [comment]
Three things:
- Removed `File` enum as it had conflict with `java.io.File`, substitued File type with `##java.io.RandomAccess`
- The problem with import order is still present here, as in other parts of the STL all code was inside a module here imports had to be above doc because of outside-module code
- RandomAccessFile was imported both outside the module and inside, it seems like RandomAccessFile is not found in `open` function getting an `Undefined class` otherwise. I suspect there are some issues with import from point 1 too

**Comment by magnus-madsen** [comment]
It seems there are two things in play:

1. A different design which could possibly be better.
2. A refactor with just using the new `new` syntax.

Would it be possible to do just (2) and keep (1) for later?

**Comment by chanattan** [comment]
I tried to keep the File enum but renaming it, the tag wasn't found unfortunately.

I don't think doing (2) before (1) is possible, at least without considering partial refactor.
The conflicts appear when function arguments use the same enum name as a Java class, e.g.:
```scala
def foo(r: File) : Unit \ IO =
    // r has the type of the enum
    let File(r) = f;
    ...
```
So we can't really keep the enum that is used to be later unpacked, unless we go back to strong Java types, i.e., `##java.io.File` and no longer `File` inferred.

**Comment by magnus-madsen** [comment]
I think we should import the Java File as JFile:

```
import java.io.{File => JFile}
```

and work from there.

**Comment by chanattan** [comment]
Thank you. The renaming was used in Random.flix and not here, I probably tried to over-refactor it.

**Comment by magnus-madsen** [comment]
What's the plan here? Import File as JFile and use that everywhere?

**Comment by chanattan** [comment]
> What's the plan here? Import File as JFile and use that everywhere?

That's basically it, the changes are minimal since the renaming removes any conflict with File enum.

**Comment by magnus-madsen** [comment]
> > What's the plan here? Import File as JFile and use that everywhere?
> 
> That's basically it, the changes are minimal since the renaming removes any conflict with File enum.

Just replacing all the import java_new

**Comment by chanattan** [comment]
Yes and updating the instantiation. There is only one java_new in the file.

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
