### PR TITLE
feat: turn effects on by default

### PR DESCRIPTION
**Pull request by mlutze**

### CODE REVIEW

**Comment by mlutze** [comment]
!!!benchmark even though we all know it's unreliable

**Comment by mlutze** [comment]
Wow, benchmark bot is broken :(

**Comment by magnus-madsen** [comment]
Maybe run them locally?

**Comment by mlutze** [comment]
My machine says that the master branch is 50% slower than the feature branch :P

**Comment by mlutze** [comment]
A rerun says master is 10% faster

**Comment by magnus-madsen** [comment]
@stephentetley This enables the new effect system by default. Let us know if you encounter breakages. (Those would most likely involve enums with effect types).

**Comment by stephentetley** [comment]
Thanks Magnus, I'm switching my code over to use the effect set notation. I'll see if there are any breakages.

**Pull request merged**
