### PR TITLE
feat: add ToJava class (issue #6348)

### PR DESCRIPTION
**Pull request by stephentetley**
This PR adds the `ToJava` class from issue #6348 and several collection instances.

I think the only contentious instance is for (Flix) Vector which goes to ##java.util.List. Java's ##java.util.Vector would have been an alternative but Vector seems disfavoured in Java now and is not used so much as an argument or a result in API calls.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
> 

Yes, lets do that for now.

**Comment by magnus-madsen** [comment]
Ill ask @mlutze for a quick review, since he is leading on assoc types.

**Comment by stephentetley** [comment]
I've reverted Prelude so `toJava` is removed.

**Review by mlutze — APPROVED** [review]
Looks good. Thanks, Stephen!

**Pull request merged**
