### PR TITLE
feat: Add skeleton for mutation testing

### PR DESCRIPTION
**Pull request by magnus-madsen**

### CODE REVIEW

**Comment by Ibragimov11** [comment]
@magnus-madsen Hi! It seems I don't have the rights to push changes to this merge request. Is it better for me to create a new merge request through a fork, or can you give me the rights to edit this?

**Comment by magnus-madsen** [comment]
Best to create your own.

**Comment by magnus-madsen** [comment]
Feel free to open a work in progress PR for early feedback.

**Comment by Ibragimov11** [comment]
> Feel free to open a work in progress PR for early feedback.

Yes, thanks. I created my own [pull request](https://github.com/flix/flix/pull/6446), so this one should probably be closed. I just haven't had time to start the task yet, but I'll start soon.

**Pull request closed without merging**
