### PR TITLE
refactor: update `foreach` desugaring

### PR DESCRIPTION
**Pull request by jaschdoc**
Changes desugaring to `Iterator.foreach(f, Iterable.iterator(list))`

Related to #4224

### CODE REVIEW

**Comment by jaschdoc** [comment]
RFR

**Comment by magnus-madsen** [comment]
I think we should have some new tests :)

**Comment by jaschdoc** [comment]
Agreed, how could I forget? :+1:

**Comment by jaschdoc** [comment]
RFR

**Pull request merged**
