### PR TITLE
style: reorder `MonoAst`

### PR DESCRIPTION
**Pull request by jaschdoc**
Moved `ApplyAtomic` before `ApplyClo` because that's the alphabetical ordering.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Wait... I think pattern matches should also be reordered then or?

**Review by magnus-madsen — CHANGES_REQUESTED** [review]
.

**Comment by jaschdoc** [comment]
Ah okay I was only thinking about the apply ordering

**Comment by magnus-madsen** [comment]
We try to keep declaration order and pattern match order in synch.

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
