### PR TITLE
fix: use `String.valueOf`

### LINKED ISSUE #4726: `stringify` crash on `null`
```
pub def main(): String = stringify(null)
```

### PR DESCRIPTION
**Pull request by JonathanStarup**
Fixes #4726

### CODE REVIEW

**Comment by mlutze** [comment]
Would it be simpler just to check for null before checking the type?

**Comment by magnus-madsen** [comment]
> Would it be simpler just to check for null before checking the type?

Does not work if its a primitive?

**Comment by mlutze** [comment]
> > Would it be simpler just to check for null before checking the type?
> 
> Does not work if its a primitive?

Ok, fix `isNull` and then use it. Maybe a little less simple.

**Comment by JonathanStarup** [comment]
> > > Would it be simpler just to check for null before checking the type?
> > 
> > Does not work if its a primitive?
> 
> Ok, fix `isNull` and then use it. Maybe a little less simple.

I think thatd be better but we cant without expaning the minimum library. Im not sure what the least clumsy solution. I had really forgotten how much null suck

**Comment by mlutze** [comment]
> > > > Would it be simpler just to check for null before checking the type?
> > > 
> > > 
> > > Does not work if its a primitive?
> > 
> > 
> > Ok, fix `isNull` and then use it. Maybe a little less simple.
> 
> I think thatd be better but we cant without expaning the minimum library. Im not sure what the least clumsy solution. I had really forgotten how much null suck

ah the dang minlib issue...

**Comment by magnus-madsen** [comment]
Superseded by #4744

**Comment by JonathanStarup** [comment]
@magnus-madsen I don't see how it's fixed by typematch, this is about not calling `obj.toString` and instead call `String.valueOf(obj)` and things like that

**Comment by magnus-madsen** [comment]
> @magnus-madsen I don't see how it's fixed by typematch, this is about not calling `obj.toString` and instead call `String.valueOf(obj)` and things like that. Can you reopen this and ill remove the non-backend aspects?

Where else does the problem occur?

**Comment by JonathanStarup** [comment]
> > @magnus-madsen I don't see how it's fixed by typematch, this is about not calling `obj.toString` and instead call `String.valueOf(obj)` and things like that. Can you reopen this and ill remove the non-backend aspects?
> 
> Where else does the problem occur?

Enums just call `value.toString` on their value which fails with `null`.  I think there were other places

**Comment by magnus-madsen** [comment]
OK, I did not grasp that initially.

**Comment by JonathanStarup** [comment]
@magnus-madsen ready to merge. There's some commented tests for null fix in the flix part

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
