### PR TITLE
NewObject tests

### PR DESCRIPTION
**Pull request by paulbutcher**
This is not ready to be merged, but I've hit a problem I don't understand and could use some help.

The code as checked-in compiles and passes. But if I uncomment the commented out lines in `TestPrimitiveTypes.java` and `Test.Exp.Jvm.NewObject.flix", I get errors of the form:

```
-- Type Error -------------------------------------------------- main/test/flix/Test.Exp.Jvm.NewObject.flix

>> ToString is not defined on t23531. Define or derive an instance of ToString.

60 |         "${a}, ${b}, ${c}, ${d}, ${e}, ${f}, ${g}, ${h}"
              ^^^^
              missing ToString instance
```

What's really strange is that I only get these errors with `allTheTypes`. If I add `println` statements to other methods, it compiles just fine.

Suggestions for what might be going on gratefully received!

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I see some conflicts. Can you do a rebase?

**Comment by magnus-madsen** [comment]
The error suggests some type variables are under constrained or that the class constraints are not propagated. Thus we should look in the typer.

**Comment by magnus-madsen** [comment]
In the typer, we need to use the fparams for jvm methods

**Comment by magnus-madsen** [comment]
I can explain more later.

**Comment by magnus-madsen** [comment]
I took the liberty to make a fix in #4342 :)

**Comment by paulbutcher** [comment]
> I took the liberty to make a fix in #4342 :)

Thank you!

I'm currently trying to work out what's going on with the conflicts, once I've sorted them out I'll pull your changes.

**Comment by paulbutcher** [comment]
I'm not sure what I've done, but I've made a mess of this within Git and I'm struggling to work out how to rebase it cleanly. So I'm going to delete this PR, check out a clean master, and reapply these changes.

**Pull request closed without merging**
