### PR TITLE
feat: allow specification of GitHub API key for dependency resolution

### LINKED ISSUE #5668: Add support for `GitHub` token to package manager

### PR DESCRIPTION
**Pull request by mlutze**
fixes #5668

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Is it a good idea to pass as a program argument?

**Comment by magnus-madsen** [comment]
Also, do we really want to just pass it around as an `Option[String]`?

**Comment by mlutze** [comment]
You mean in terms of security?  I'm not sure what the best practices are.

**Comment by magnus-madsen** [comment]
Conflicts :[

**Pull request merged**
