### PR TITLE
feat: add `IntUnaryOperator` to respective function objects

### PR DESCRIPTION
**Pull request by JonathanStarup**
Fixes part of #4721.

Also fixes a bug where IntFunction did not properly use its argument

### CODE REVIEW

**Comment by JonathanStarup** [comment]
@mlutze Must IntUnaryOperator be Impure?

**Comment by mlutze** [comment]
> @mlutze Must IntUnaryOperator be Impure? is it the same for IntFunction?

I think so. If some java function returns a `IntUnaryOperator` then we have to assume it is impure.

**Comment by JonathanStarup** [comment]
> > @mlutze Must IntUnaryOperator be Impure? is it the same for IntFunction?
> 
> I think so. If some java function returns a `IntUnaryOperator` then we have to assume it is impure.

Wait is it a doublesided equality? that sounds like it can crash the backend

**Comment by mlutze** [comment]
> > > @mlutze Must IntUnaryOperator be Impure? is it the same for IntFunction?
> > 
> > 
> > I think so. If some java function returns a `IntUnaryOperator` then we have to assume it is impure.
> 
> Wait is it a doublesided equality? that sounds like it can crash the backend

Yes it is. Good thought...

**Comment by magnus-madsen** [comment]
You mean if someone returns a IntUnaryOperator  to us?

**Comment by mlutze** [comment]
> You mean if someone returns a IntUnaryOperator to us?

Yes, it gets translated by the typer to `Int -> Int \ IO`

**Comment by JonathanStarup** [comment]
> You mean if someone returns a IntUnaryOperator to us?

yeah, if you call someone else's Function object, then backend will try to `obj.arg0 = 2` or whatever.

I don't think these should be proper equalities

**Comment by magnus-madsen** [comment]
I think we can assume, for now, that we will not be getting Java closures back.

**Comment by mlutze** [comment]
Maybe we can make it upcastable instead of a direct translation?

**Comment by JonathanStarup** [comment]
Unless, we specialize function call on these specific types 😄(doesn't work for tailcall elimination though)

**Comment by magnus-madsen** [comment]
> Maybe we can make it upcastable instead of a direct translation?

Let's not over complicate. When was the last time you GOT a Java function back from somewhere?

**Comment by JonathanStarup** [comment]
> Maybe we can make it upcastable instead of a direct translation?

Yeah maybe this. Maybe we can abuse the unify method with an expected/required type?

> I think we can assume, for now, that we will not be getting Java closures back.

I just feel like we will all forget about this in a week 😄

**Pull request merged**
