### PR TITLE
refactor: `query` returns list

### LINKED ISSUE #1867: Datalog: What should `query` return?
It currently returns an array, but other options are: `List` or `LazyList`.

Edit it could return some "abstract value" that implements Foldable.

### PR DESCRIPTION
**Pull request by JonathanStarup**
Fixes #1867.

### CODE REVIEW

**Comment by JonathanStarup** [comment]
> Question/thought: Should we be using Foldable.XYZ instead of List.XYZ in this refactoring?

Ah 😪 yes, good point

**Comment by magnus-madsen** [comment]
I don't think you can return `m[v] with Foldable[m]`. 

The question is whether use Foldable or not. Advantages: We can change things later. Disadvantage: We teach programmers they have to use Foldable.

**Comment by magnus-madsen** [comment]
Let's sleep on it :)

**Comment by magnus-madsen** [comment]
Wanted to merge, but I merged Graph first leading to some conflicts. Sorry!

**Comment by JonathanStarup** [comment]
> 

Fixed

**Comment by magnus-madsen** [comment]
Thanks!!

**Pull request merged**
