### PR TITLE
feat: add links between types in HTML documentation

### LINKED ISSUE #6442: HtmlDocumenter: Add links between entities
If List.head returns an Option then it should link to Option.

### PR DESCRIPTION
**Pull request by sockmaster27**
Fixes #6442

### CODE REVIEW

**Comment by sockmaster27** [comment]
I'm not quite sure how this would be done the most cleanly. Right now I've modified `FormatTypes` to introduce a new function called `formatTypeMappingNames`.

**Comment by magnus-madsen** [comment]
We cannot make changes to formatType-- so indeed we are stuck. 

Let me think about it...

**Comment by magnus-madsen** [comment]
(meanwhile, I would like the refactoring of "modules" to be the top priority.)

**Comment by sockmaster27** [comment]
> We cannot make changes to formatType-- so indeed we are stuck.
> 
> Let me think about it...

Have you looked at the code? I don't think it's the best solution ideologically, but I don't see how we are ever going to get anything better, other than just effectively having a copy of the functionality.

**Comment by magnus-madsen** [comment]
> > We cannot make changes to formatType-- so indeed we are stuck.
> > Let me think about it...
> 
> Have you looked at the code? I don't think it's the best solution ideologically, but I don't see how we are ever going to get anything better, other than just effectively having a copy of the functionality.

Yes, but I am not sure we can pollute compiler code with tooling code. Imagine we did this for every tool that needs something.

**Comment by magnus-madsen** [comment]
But as I said, let me think about it. Maybe I will end up where you are :)

**Comment by sockmaster27** [comment]
@magnus-madsen 
Would it help if I called it a variation of the strategy pattern? 😅

**Comment by magnus-madsen** [comment]
Will revisit in the future.

**Pull request closed without merging**
