### PR TITLE
refactor: output bytecode to `build/class` dir

### LINKED ISSUE #6712: Code/Meta seperation in `build/`
Right now auxiliary information is put along side actual generated code, e.g. `build/asts/...` is right next to `build/Clo$main$146782`. We should have `build/code/` and `build/meta/` or something like that.

It also looks prettier when looking for meta stuff instead of immediately seeing 100s of compiled java classes.

### PR DESCRIPTION
**Pull request by sockmaster27**
Fixes #6712

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Can you confirm that build-jar still works as expected?

**Comment by sockmaster27** [comment]
Yes, running `build-jar` still succeeds

**Comment by magnus-madsen** [comment]
> Yes, running `build-jar` still succeeds

But is the jar non-empty? Does the jar actually work?

**Comment by magnus-madsen** [comment]
I suspect its broken-- take a look at `Bootstrap.scala`

**Comment by magnus-madsen** [comment]
Did you check that the built JAR works?

**Comment by magnus-madsen** [comment]
> > Did you check that the built JAR works?
> 
> The `Main.class` is now in the root of the JAR

Does it run?

**Comment by sockmaster27** [comment]
> > > Did you check that the built JAR works?
> > 
> > 
> > The `Main.class` is now in the root of the JAR
> 
> Does it run?

Yes

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
