### PR TITLE
refactor: disable safe mode in documentation parsing

### PR DESCRIPTION
**Pull request by sockmaster27**
Should be redundant when using panic mode

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Does this resolve the escaping issue? Whats the potential consequence/harm?

**Comment by sockmaster27** [comment]
No, it was just something I uncovered while looking at it. As far as I can tell, this should not have any consequences, since you shouldn't be able to inject anything without `<` and `>`.

**Comment by magnus-madsen** [comment]
OK, and now the HTML render correctly?

**Comment by sockmaster27** [comment]
No, it renders identically.

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
OK, so more work is needed to fix the problem?

**Comment by sockmaster27** [comment]
> OK, so more work is needed to fix the problem?

Yeah, I propose we switch to JetBrains' version as it seems significantly better maintained, hopefully saving us from future headaches.

**Comment by magnus-madsen** [comment]
Lets give it a try at least.

**Pull request merged**
