### PR TITLE
chore: remove `Index` and `Indexer`

### PR DESCRIPTION
**Pull request by magnus-madsen**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
!!!jar

**Comment by magnus-madsen** [comment]
@JonathanStarup I wonder if this makes VSCode more snappy on your machine or if it is not enough?

**Review by mlutze — APPROVED** [review]

**Comment by magnus-madsen** [comment]
@mlutze I would also like to know your experience.

**Comment by magnus-madsen** [comment]
@LoZander 🚀

**Pull request merged**
