### PR TITLE
feat: disallow handling `IO` in try-with

### LINKED ISSUE #7144: Enforce that the `IO` effect cannot be handled
Probably in `Safety`, i.e. one must not write a try-with that handles IO.

### PR DESCRIPTION
**Pull request by sockmaster27**
Fixes #7144

### CODE REVIEW

**Comment by sockmaster27** [comment]
See https://github.com/flix/flix/issues/7144#issuecomment-2302345872:
> I've implemented this check, but it doesn't seem to ever get to it. When writing
> 
> ```
> try println("Hello, World!") with IO {}
> ```
> 
> I get a parsing error
> 
> ```
> ❌ -- Parse Error (OtherExpr) -------------------------------------------------- file:///c%3A/Users/Holger/Documents/Flix/test/Main.flix
> 
> >> Expected at least one <with-rule>.
> 
> 2 |     try println("Hello, World!") with IO {}
>                                              ^
>                                              Here
> ```
> 
> and when writing
> 
> ```
> try println("Hello, World!") with IO {
>     def f() = ()
> }
> ```
> 
> I get a resolution error
> 
> ```
> ❌ -- Resolution Error -------------------------------------------------- file:///c%3A/Users/Holger/Documents/Flix/test/Main.flix
> 
> >> Undefined operation 'IO.f'.
> 
> 3 |         def f() = ()
>                 ^
>                 operation not found
> 
> 
> Explanation:
> Tip: Possible typo or non-existent operation?
> ```

**Comment by sockmaster27** [comment]
!!!rerun

**Comment by magnus-madsen** [comment]
We need you to start by changing the parser to allow zero rules:

```
>> Expected at least one <with-rule>.

2 |     try println("Hello, World!") with IO {}
```

Probably in a separate PR. Once that is done, this PR should become possible.

**Comment by magnus-madsen** [comment]
@sockmaster27 I believe @JonathanStarup has fixed in the underlying issue, so this PR can be resumed.

**Comment by magnus-madsen** [comment]
I will need to upgrade this to a range of effects, so let me get back to you.

**Comment by sockmaster27** [comment]
!!!rerun

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
