### PR TITLE
feat: disable autocomplete for `???`  #5226

### PR DESCRIPTION
**Pull request by yisraelU**
related to #5226  
first-time PR , just learning the ropes here

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Looks reasonable :-) Can I ask you to:

- Run `gradlew clean jar`. Take the jar from `build/libs`, place it into an empty directory, open that directory in VSCode (with the Flix plugin installed). It should start using your custom jar. Manually verify that `???` no longer triggers completion.
- Add your name to `AUTHORS.md` to confirm you agree to release your contributions under Apache 2.0

**Comment by magnus-madsen** [comment]
> @magnus-madsen Thanks , it works . 

Thanks!

> however I am wondering, is there a valid use case for having the autocomplete run with only 1 question mark ?

Yes. We use that for auto-completion like on the dot in Java. For example, you can try:

```
def foo(): Int32 = 
let x: String = "Hello";
let y: Int32 = x?
y
```

and see what it suggests :)

**Comment by magnus-madsen** [comment]
Merged. Thanks!

**Comment by yisraelU** [comment]
> > @magnus-madsen Thanks , it works .
> 
> Thanks!
> 
> > however I am wondering, is there a valid use case for having the autocomplete run with only 1 question mark ?
> 
> Yes. We use that for auto-completion like on the dot in Java. For example, you can try:
> 
> ```
> def foo(): Int32 = 
> let x: String = "Hello";
> let y: Int32 = x?
> y
> ```
> 
> and see what it suggests :)

right but that has no preceding whitespace, I am only matching cases with at minimum 1 preceding whitespace char

**Comment by magnus-madsen** [comment]
What do you mean? If one were to type ` ?`

**Comment by yisraelU** [comment]
yes

**Comment by magnus-madsen** [comment]
> yes

I sees. So rather we should give suggestions if we see `name?`, but not otherwise?

**Comment by yisraelU** [comment]
Yes , from my understanding(albeit very minimal) I cannot see a utility in an autocomplete on a whitespace isolated question mark

**Comment by magnus-madsen** [comment]
Roger. Feel free to take a stab at that :)

**Pull request merged**
