### PR TITLE
Introduce Kinder

### PR DESCRIPTION
**Pull request by mlutze**
Fixes https://github.com/flix/flix/issues/1791

Internal changes:
* Create `UnkindedType` which is used before the `Kinder`
* Move kind-related errors from resolver to `Kinder`

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Here is a nice real test case:

```
    pub def project3[f: Type -> Type, t1: Type, t2: Type, t3: Type, v: Type](p: PredSym, ts: f[(t1, t2, t3)]): 
        Datalog[v] with Boxable[t1], Boxable[t2], Boxable[t3], Foldable[f] =
        ???
```

where we would like to do without the type ascriptions.

**Comment by mlutze** [comment]
Notes from discussion:
* All tvars in expressions have to be known from the type signature, so there's no need to infer anything from the expression.
* Would be nice to have two source locations for kind errors

**Comment by magnus-madsen** [comment]
@mlutze I added another point to your list. (Apparently I have the power to change your text (!!))

**Comment by mlutze** [comment]
See https://github.com/flix/flix/pull/2037

**Pull request closed without merging**
