### PR TITLE
refactor: fix failing tests

### PR DESCRIPTION
**Pull request by chanattan**
Related to #8196.

### CODE REVIEW

**Comment by chanattan** [comment]
For `IllegalType.01` and `IllegalWildType.05` the errors are different, should I change the test names?
Also for `MismatchingReturnType` I changed them to `MismatchingType` as we no longer explicit the signature of an imported function but inference directly looks at types of the inferred function. @magnus-madsen

**Comment by magnus-madsen** [comment]
> For `IllegalType.01` and `IllegalWildType.05` the errors are different, should I change the test names? Also for `MismatchingReturnType` I changed them to `MismatchingType` as we no longer explicit the signature of an imported function but inference directly looks at types of the inferred function. @magnus-madsen

Sure, yes.

Just apply comment sense and add some comments on GitHub (You can comment on code here) and then I will take a look.

If a test is no longer relevant, feel free to remove it or rework it.

**Comment by magnus-madsen** [comment]
Could we deal with TestResolver in a PR separate from this one?

**Comment by chanattan** [comment]
> > For `IllegalType.01` and `IllegalWildType.05` the errors are different, should I change the test names? Also for `MismatchingReturnType` I changed them to `MismatchingType` as we no longer explicit the signature of an imported function but inference directly looks at types of the inferred function. @magnus-madsen
> 
> Sure, yes.
> 
> Just apply comment sense and add some comments on GitHub (You can comment on code here) and then I will take a look.
> 
> If a test is no longer relevant, feel free to remove it or rework it.

I did what seemed intuitive to me.
Now about Test.Java.Function.flix we should be working on another PR first that deals with IntPredicate and higher-order Flix functions, if I'm not wrong. It should be a specific case in TypeReduction.

**Comment by magnus-madsen** [comment]
What's the problem with Test.Java.Function?

**Comment by magnus-madsen** [comment]
Fixed in master.

**Pull request closed without merging**
