### PR TITLE
test: add typematch tests for records

### PR DESCRIPTION
**Pull request by mlutze**
related to #4773

### CODE REVIEW

**Comment by magnus-madsen** [comment]
> Doesn't work with schemas because monomorph comes after lowering :(

Indeed. What to do then? Reject such types?

**Comment by mlutze** [comment]
> > Doesn't work with schemas because monomorph comes after lowering :(
> 
> Indeed. What to do then? Reject such types?

Yes, that's the only solution I see.

**Comment by magnus-madsen** [comment]
That's fine, better than this behavior.

Same applies to channels then? What else?

**Comment by mlutze** [comment]
> That's fine, better than this behavior.
> 
> Same applies to channels then? What else?

I think that's all. But we need to remember to check recursively, e.g. no functions involving channels either.

**Comment by magnus-madsen** [comment]
Can we wrap this up? (Perhaps by dropping the scheme tests)?

**Pull request merged**
