### PR TITLE
fix: Makes sure that the best-pick completion is always on top

### PR DESCRIPTION
**Pull request by LukasRonn**
Change in priority to ensure that the "bestPick" calculated by `CompletionRanker` is always on top.

This keeps the original order (priority) of all other completions and only affect the "bestPick".

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Is there a reason boost could simply not return `0`?

**Comment by LukasRonn** [comment]
> Is there a reason findBest could simply not return `0`?

So the `sortText` for the `CompletionItem` (generated from the "best pick" `Completion`), should have the prefix value `0` instead of `1`?

**Comment by magnus-madsen** [comment]
> > Is there a reason findBest could simply not return `0`?
> 
> So the `sortText` for the `CompletionItem` (generated from the "best pick" `Completion`), should have the prefix value `0` instead of `1`?

Seems reasonable.

**Comment by LukasRonn** [comment]
> > > Is there a reason findBest could simply not return `0`?
> > 
> > 
> > So the `sortText` for the `CompletionItem` (generated from the "best pick" `Completion`), should have the prefix value `0` instead of `1`?
> 
> Seems reasonable.

I'll test it, and make sure it works.

**Comment by LukasRonn** [comment]
> > > > Is there a reason findBest could simply not return `0`?
> > > 
> > > 
> > > So the `sortText` for the `CompletionItem` (generated from the "best pick" `Completion`), should have the prefix value `0` instead of `1`?
> > 
> > 
> > Seems reasonable.
> 
> I'll test it, and make sure it works.

It works with 0.

**Pull request merged**
