### PR TITLE
feat: use && for intersection types

### PR DESCRIPTION
**Pull request by mlutze**
related to #4236

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I know I asked for it, but it also feels like a step back :) Is there any other way we could make it easier to distinguish the effects?

**Comment by magnus-madsen** [comment]
It is more the separation between the purity part and the effect part that is the problem, I think.

**Comment by mlutze** [comment]
Vertical pipe `|` is unused. Could that work?

**Comment by magnus-madsen** [comment]
Let's leave it.

**Pull request closed without merging**
