### PR TITLE
Retire `Int` part 1

### PR DESCRIPTION
**Pull request by ninaandrup**
#2588

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@ninaandrup How about we make this a non-draft and merge it in now? Then you can continue later.

**Comment by ninaandrup** [comment]
> @ninaandrup How about we make this a non-draft and merge it in now? Then you can continue later.

Yes, I think that would be a good idea so this is not just laying around waiting

**Comment by ninaandrup** [comment]
I'll just resolve the conflicts first

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
