### PR TITLE
Add Redundancy Checks for Classes/Instances

### PR DESCRIPTION
**Pull request by mlutze**
Fixes https://github.com/flix/flix/issues/1755
Fixes https://github.com/flix/flix/issues/1734

### Features
* UnusedFormalParam is not checked for sigs without implementation.
  * [x] impl
  * [x] test
* UnconditionalRecursion is checked for sigs with implementations.
  * [x] impl
  * [x] test
* Other redundancy checks are run for sigs.
  * [x] impl
  * [x] test

### General requirements
* [x] Don't make a complete mess
* [x] Don't break anything else
* [x] Provide documentation
* [x] Add license to new files

### CODE REVIEW

**Comment by mlutze** [comment]
@magnus-madsen RFR

**Comment by magnus-madsen** [comment]
The reason I have been particular slowly to review this one is because I am kind of dissatisfied with the complexity involved in checking for unconditional recursion. I have been trying to dream up another implementation, but so far nothing.

**Comment by mlutze** [comment]
Yes, I agree that that it's rather messy. The only option I've thought of was to separate the `Used` checking from the unconditional recursion checking, in two separate tree traversals. But you've mentioned before that this comes with a significant performance impact.

**Comment by magnus-madsen** [comment]
> 
> 
> Yes, I agree that that it's rather messy. The only option I've thought of was to separate the `Used` checking from the unconditional recursion checking, in two separate tree traversals. But you've mentioned before that this comes with a significant performance impact.

The performance cost is probably just 1-3%, but if we do that often it adds up. Maybe we should still split them up into two. 

Alternatively, in the (far) future, when someone does work on termination, it would probably be moved there.

**Comment by magnus-madsen** [comment]
We don't have to do any of that now though.

**Pull request merged**
