### PR TITLE
refactor: remove `Iterable` dependency in `Chain`

### PR DESCRIPTION
**Pull request by jaschdoc**
- [x] `isEmpty`
- [x] `head`
- [x] `map`
- [ ] `filter`
- [ ] `flatMap`
- [x] `exists`
- [ ] `forall`
- [x] `foreach`
- [x] `toSeq`
- [x] `mkString`

Depends on https://github.com/flix/flix/pull/7008
Related to https://github.com/flix/flix/issues/6989

### CODE REVIEW

**Comment by jaschdoc** [comment]
We can add the missing functions in another PR but at least now `Chain` no longer extends `Iterable`

**Comment by jaschdoc** [comment]
@magnus-madsen RFR :)

**Review by magnus-madsen — APPROVED** [review]

**Comment by jaschdoc** [comment]
Should I implement these functions as tail recursive functions in another PR?

**Comment by magnus-madsen** [comment]
> Should I implement these functions as tail recursive functions in another PR?

Yeah, we do one more pass. Let me merge this.

**Pull request merged**
