### PR TITLE
refactor: update signature of `main`

### PR DESCRIPTION
**Pull request by ninaandrup**
Related to #3518

### CODE REVIEW

**Comment by ninaandrup** [comment]
@magnus-madsen All tests pass when I run them in Intellij, but I'm not sure, why github complains about this
```
-- Entry Point Error -------------------------------------------------- src/Main.flix

>> Arguments to the entry point function are not permitted.

11 | def main(args: Array[String]): Int32 & Impure =
         ^^^^
         unexpected entry point argument(s).

Error: Process completed with exit code 1.
```
I can't find any `Main.flix` file in the project.

**Comment by mlutze** [comment]
> @magnus-madsen All tests pass when I run them in Intellij, but I'm not sure, why github complains about this
> 
> ```
> -- Entry Point Error -------------------------------------------------- src/Main.flix
> 
> >> Arguments to the entry point function are not permitted.
> 
> 11 | def main(args: Array[String]): Int32 & Impure =
>          ^^^^
>          unexpected entry point argument(s).
> 
> Error: Process completed with exit code 1.
> ```
> 
> I can't find any `Main.flix` file in the project.

@ninaandrup This error comes from the community build, not the Flix tests themselves. It will be updated soon, but you don't need to worry about it :)

**Comment by ninaandrup** [comment]
> > @magnus-madsen All tests pass when I run them in Intellij, but I'm not sure, why github complains about this
> > ```
> > -- Entry Point Error -------------------------------------------------- src/Main.flix
> > 
> > >> Arguments to the entry point function are not permitted.
> > 
> > 11 | def main(args: Array[String]): Int32 & Impure =
> >          ^^^^
> >          unexpected entry point argument(s).
> > 
> > Error: Process completed with exit code 1.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I can't find any `Main.flix` file in the project.
> 
> @ninaandrup This error comes from the community build, not the Flix tests themselves. It will be updated soon, but you don't need to worry about it :)

Good to know, thanks :)

**Comment by ninaandrup** [comment]
> I'm unsure of if [this line](https://github.com/flix/flix/blob/d9a0faa3496af72ebde95ec64e1e0d254b597a54/main/test/ca/uwaterloo/flix/language/phase/TestEntryPoint.scala#L150) should be changed or not.

This should be ready, but I'm still unsure of this and the `TestEntryPoint.scala` tests

**Comment by magnus-madsen** [comment]
@ninaandrup There was a merge conflict, I tried to fix it, but I screwed up :[ 

Can you take a look? its in `examples/using-get-opt.flix`.

Otherwise it looks perfect. Thanks!

**Comment by ninaandrup** [comment]
> @ninaandrup There was a merge conflict, I tried to fix it, but I screwed up :[
> 
> Can you take a look? its in `examples/using-get-opt.flix`.
> 
> Otherwise it looks perfect. Thanks!

Everything looks fine :-)

**Comment by magnus-madsen** [comment]
The build still seems to fail though:

```
  -- Type Error -------------------------------------------------- examples/using-get-opt.flix
  
  >> Unable to unify the types: 'List' and 'ScopedArray[String]'.
  
  45 |     let args2 = GetOpt.preprocess({quoteOpen = "'", quoteClose = "'", stripQuoteMarks = false}, args);
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                       mismatched types.
  
  Type One: { quoteClose :: String, quoteOpen :: String, stripQuoteMarks :: Bool } -> (List[String] -> List[String])
  Type Two: { quoteClose :: String, quoteOpen :: String, stripQuoteMarks :: Bool } -> (Array[String] ->{eff} result) (FlixSuite.scala:69)
                                                                                
- using-laziness-for-infinite-streams.flix *** FAILED ***
  Unable to compile. Failed with: 2 errors.
```

**Comment by mlutze** [comment]
It looks like you might not be on the latest version. The `GetOpt` library was modified by a recent PR, so it no longer uses arrays.

**Comment by ninaandrup** [comment]
My bad, it should be fixed now

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
