### PR TITLE
Use better precision for Timer.sleepAndSend

### LINKED ISSUE #3031: `Timer.sleepAndSend` could have better precision
Right now everything below milliseconds get rounded down, [this](https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#sleep(long,%20int)) more accurate function should be used.

### PR DESCRIPTION
**Pull request by KengoTODA**
This PR replaces `java.lang.Thread.sleep(Int64)` with `java.lang.Thread.sleep(Int64, Int32)`.
To convert Int64 to Int32, this PR uses [Int64.clampToInt32](https://api.flix.dev/#Int64) API.

close #3031

### CODE REVIEW

**Review by JonathanStarup — COMMENTED** [review]
Looks good :) I think it could be good for readability to use _ in numbers: `1_000_000i64` instead of `1000000i64`

**Comment by magnus-madsen** [comment]
Yes, lets use `_` in the big numbers and then we are good to go. Thanks 👍

**Comment by KengoTODA** [comment]
I've updated the branch, thanks for your review! :)

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
