### PR TITLE
fix: use Type.eraseAliases in Safety

### LINKED ISSUE #4358: Safety should use `Type.eraseAliases`

### PR DESCRIPTION
**Pull request by magnus-madsen**
Fixes #4358

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@paulbutcher Remember what I said about `!=` being iffy ;)

**Comment by magnus-madsen** [comment]
Woops. I forgot to it for the other arguments, not just for this.

**Comment by magnus-madsen** [comment]
https://github.com/flix/flix/issues/4361

**Comment by paulbutcher** [comment]
This could probably do with some tests? Are you going to add them, or would you like me to do so?

**Comment by magnus-madsen** [comment]
If you could add them or modify the ones we have

**Comment by paulbutcher** [comment]
> If you could add them or modify the ones we have

Will do (I'll wait until you've merged https://github.com/flix/flix/pull/4364)

**Pull request merged**
