### PR TITLE
chore: fork `scalac` and increase memory limit

### PR DESCRIPTION
**Pull request by magnus-madsen**

### CODE REVIEW

**Comment by paulbutcher** [comment]
This SO article suggests that we should use org.gradle.jvmargs

https://stackoverflow.com/a/44702686/268371

**Comment by paulbutcher** [comment]
Something else worth looking at?

https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:maxHeapSize

**Comment by magnus-madsen** [comment]
> This SO article suggests that we should use org.gradle.jvmargs
> 
> https://stackoverflow.com/a/44702686/268371

I swear to *** this Gradle thing is driving me nuts. See also https://github.com/flix/flix/issues/4188

**Comment by magnus-madsen** [comment]
_OH MY GOD_ Does it actually work? No gradle.properties, no jvmargs, but instead: 

```
    scalaCompileOptions.forkOptions.with {
        memoryMaximumSize = '4g'
    }
```

**Comment by paulbutcher** [comment]
> I swear to *** this Gradle thing is driving me nuts.

Build systems have ever been thus.

Q: What's the difference between Ant and Maven?
A: The creator of Ant has apologised.

**Comment by magnus-madsen** [comment]
> > I swear to *** this Gradle thing is driving me nuts.
> 
> Build systems have ever been thus.
> 
> Q: What's the difference between Ant and Maven? A: The creator of Ant has apologised.

OMG! That is amazing. Just what I needed right now. 

I had a friend a friend _who literally works for GitHub_ try to help me this afternoon, but we gave up after an hour.

**Pull request merged**
