### PR TITLE
refactor: lazy val `isGround`

### PR DESCRIPTION
**Pull request by JonathanStarup**
~2.3 % frontend throughput increase

(doing just `val` was 0.9 % faster)

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Is this measured on the server?

**Comment by JonathanStarup** [comment]
my (non laptop) pc. I am always hesitant to use server since we have no protocol for concurrent use

**Comment by magnus-madsen** [comment]
You can use `w` and `top` see if if anyone is logged in.

**Comment by JonathanStarup** [comment]
> You can use `w` and `top` see if if anyone is logged in.

Ah nice

---

Xperf --frontend --n 100
- master: 118.940 median
- PR: median X (+Y%)

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
