### PR TITLE
Unify non-parametric defs in Monomorph

### PR DESCRIPTION
**Pull request by mlutze**
Fixes some issues, but does not fix https://github.com/flix/flix/issues/2050. There are some constraint-specific problems at play here.

### CODE REVIEW

**Comment by mlutze** [comment]
@magnus-madsen Requesting a pre-review just to be sure the idea is valid. Then I'll clean it up

**Comment by magnus-madsen** [comment]
I think I need an explanation :)

**Comment by mlutze** [comment]
In a function like this:

```
pub def testLambda03(): (Int, Int) -> Int = (x, y) -> x + y
```

Monomorph says "this function has no type variables, therefore I don't need to monomorphize it".
The lambda underneath however is polymorphic, so it ends up being replaced by `Unit -> Unit -> Unit`.
This of course is wrong, so we get an error.

Unifying the declared and inferred schemes is my naive attempt at monomorphizing the lambda. (I don't think it would work if we had let-polymorphism)

**Comment by magnus-madsen** [comment]
> 
> 
> In a function like this:
> 
> ```
> pub def testLambda03(): (Int, Int) -> Int = (x, y) -> x + y
> ```
> 
> Monomorph says "this function has no type variables, therefore I don't need to monomorphize it".
> The lambda underneath however is polymorphic, so it ends up being replaced by `Unit -> Unit -> Unit`.
> This of course is wrong, so we get an error.
> 
> Unifying the declared and inferred schemes is my naive attempt at monomorphizing the lambda. (I don't think it would work if we had let-polymorphism)

Ugh. I feel out of my depth. 

Why do you think the lambda is polymorphic? Its type does not have any quantifiers.

I am guessing its because + has been instantiated with `Int32` and we need the Monomorph phase to "see" this. 

But we don't want a new copy of the function.

**Comment by magnus-madsen** [comment]
What is the actual internal type scheme of `testLambda03` in its entirety?

**Comment by mlutze** [comment]
From debugger:
Declared scheme: `Unit -> Int32 -> Int32 -> Int32`
Inferred scheme: `∀('13658). Unit -> '13658 -> '13658 -> '13658 with Add['13658]`

**Comment by magnus-madsen** [comment]
Ready for review?

**Comment by mlutze** [comment]
> Ready for review?

Yes. I was hoping this would fix https://github.com/flix/flix/issues/1966, but that appears to be a different problem.

**Comment by magnus-madsen** [comment]
Performance impact?

**Comment by magnus-madsen** [comment]
!!!benchmark

**Pull request merged**
