### PR TITLE
Array additions2

### PR DESCRIPTION
**Pull request by stephentetley**
This pull request replaces - Array additions #1031

Hi Magnus - I've done some of the simple changes:

+ Added my name to the copyright notices

+ Put TestArray in a namespace.

+ Reformatted various if-expressions, removing parens if they have a single line "else" expression and spacing some one-liner if-expressions onto multiple lines.

+ Moved the "base case" to the "then" part rather than the "else" part of several if-expressions.

+ Made `head` and `last` Impure.

I haven't started on making the other "queries" like `memberOf` Impure - I think I understood what you said about "equal under substitution" but I'll need to check.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
One philosophical issue is about naming. I constructed the following tables:

Arrays:

| Pure | Impure |
| ------------- | ------------- |
| map | mapInPlace |
| reverse  | reverseInPlace  |
| replace | replaceInPlace |
| patch | patchInPlace |
| update | updateInPlace |

I very much like that `Array.map` and `List.map` use the same name and have the same behavior.

The question is what to call the mutating methods. For `MutSet` I tried the following:

MutSet:

| Pure | Impure |
| ------------- | ------------- |
| insert| add |
| union | addAll |
| remove | delete* |
| difference | deleteAll* |
| intersection | retailAll |
| map | transform |

The idea being that "addAll" is like a "unionInPlace" with the first argument has the one being mutated.

*: The current implementation uses the wrong names, but this is what I would do today.

For MutSet, I used names from Java and I think it worked out okay-ish. But for Array this seems very hard. What would I call `reverseInPlace`?

Let me ponder this for a bit. And please let me know if you have any thoughts?

**Comment by magnus-madsen** [comment]
## How to name immutable and mutable functions

We have the array data type. We want to support many operations that either work by returning a new array or by mutating the array in place. For example, we might want to map a function over an array (to obtain a new array with the mapped elements) or to transform the array in place. As another example, we can return a reversed array or reverse an array in place.

How should such functions be named? Here are some possibilities:

### Option 1: Distinct names

We can try to come up with distinct names. For example, we might have `MutSet.map` and `MutSet.transform`. Similarly, we might have `MutSet.union` and `MutSet.addAll`. The challenge is to come up with reasonable names. For example, what should we call the two versions of `reverse`?

### Option 2: Prefixed or suffixed-names

We keep names like `map` and `reverse` for the functional variants. For the mutable in place variants, we prepend or append some specific words, e.g. `reverseInPlace` or `mutReverse`.

### Option 3: Prefixed or suffixed-names with symbols

We go old school. We keep the names `map` and `reverse` for the function variants. We name the mutable variants `map!` and `reverse!` using the bang (or some other symbol) to signify mutation. This seems very principled, but people might _really_ _really_ dislike the aesthetics. 

### Option 4: We leverage namespaces

We use namespaces to disambiguate the operations. For example, we might have `Array.reverse` and `MutArray.reverse`. Problem: For array there is one data structure trying to supports two types of operations. For `Set` and `MutSet` it is more complicated. We would need `Set.map`, `MutSet.Mut.map`, and `MutSet.Imm.map`. That is, `Set` is for the pure functional data structure, 
`MutSet.Mut` is for the mutable set where we use mutable map and `MutSet.Imm` is for the mutable set but where we use immutable map.

### Option 5: We drop the idea of multiple operations

If `Array` and `MutSet` are mutable then they simply do not come with a functional `map` or `reverse`. If you need that then you must convert the functional to an immutable version and then call the appropriate operation. For example, `a.toImmutable().reverse()`. Possibly `toImmutable()` (or maybe just `toImm`) can be implemented more efficiently than building the entire data structure (but maybe not). 

EDIT: It's a bit late, so I will probably come back and update this tomorrow.

**Comment by ifazk** [comment]
My preferences are a little weird, they are different between `MutSet` and `Array`s.
- For `MutSet`, I prefer just getting rid of pure versions of functions and providing a `.clone()` function. This way, the for a copying version of `.insert()` we can write `.clone().insert()`.
- For `Array`s, I prefer suffix-names, followed by name-spaces, followed by suffix-symbols.

I personally do not like distinct names. In my view, it goes against "economy of concepts". Having to remember two distinct names is also annoying, its easier to remember just one and then a modifier.

I took a quick look at `reverse()` in different standard libraries and here's what I found:
- Haskell: Doesn't seem to have reverse in the array package for `MArrays`.
- Ocaml: Between the four different standard libraries, jane-steet-base uses `reverse`/`reverse_inplace`, containers only offers `reverse_in_place`, ocaml-batteries uses `rev`/`rev_in_place`, stdlib doesn't have reverse in the `Array` module.
- Racket: Does not seem to have reverse builtin for vectors, but unsurprisingly uses lisp-style bangs (!) for other vector operations.
- Scala: Uses implicit conversion magic to figure out which `reverse` is meant.
- Rust: From a quick look, `std::vec::Vec.reverse()` does reverse in place. Not sure if there is a simpler way to do non-in-place reverse than `.clone().reverse()`.
- C++: Does not have reverse on vectors. But offers `iterator()` and `reverse_iterator()` methods.

**Comment by mlutze** [comment]
I agree with ifazk's view on distinct names. Analogous things should be named analogously. (Related: Flix principle "Consistent syntax")

Another option lying between distinct and suffixed (albeit one I don't like much) to throw out would be to follow python's `sort`/`sorted` functions:
We use the imperative `sort` or `map` for in-place to say "**sort** this array". Then the past participle `sorted` or `mapped` returns a new array to say "give me the **sorted** equivalent of this array". 
This kind of relegates functional programming to a secondary position by forcing the pure functions to change their standard names, so frankly it doesn't seem like a good option, but seemed worth mentioning.

My concern with using a symbol (`map!`) is that it establishes a convention which would not be enforced elsewhere. For example, someone might create their own collection data type and define a function `sort` which sorts in place. It reminds me of Scala's convention of using `()` only for impure functions which I'm not too fond of since there's no enforcement of it, only possibly compiler warnings. (Related: Flix principle "No warnings, only errors") The same could be said for the word-style affixes, but that inconsistency feels a little less offensive to me.

My top choice is suffix names, then suffix symbols, then namespaces. (2, 3, 4)

**Comment by stephentetley** [comment]
I've a "weak like" for the ! suffix as per Scheme as it is short and Scheme was my introduction to functional programming.

One thing to be aware of is that the "copying" and "in place" functions have different signatures with the InPlace version returning `Unit` indicating it has destructively updated the array:

~~~

pub def reverse(a: Array[a]): Array[a] & Impure =

pub def reverseInPlace(a: Array[a]): Unit & Impure =

~~~

The compiler or a linter check could be made to check that uses of (copying) `replace` do use the result array.

Also because `reverseInPlace` returns Unit is can't be used inside a chain of functions or inside UFCS, only at the end. So in the sense of programming *with them*, they are somewhat different functions.

**Comment by magnus-madsen** [comment]
As an addendum to Stephen's comment, I also note that the signature of `map` is different.

The usual map looks like:

```scala
pub def map(f: a -> b & e, a: Array[a]): Array[b] & Impure
```

The *in place* map looks like:
```scala
pub def mapInPlace(f: a -> a, a: Array[a]): Unit & Impure
```

Notice how it *cannot* change the type of the elements in the array. This is correct because changing the type of an array would be unsound (and disallowed by the JVM). For example, an array of integers cannot hold objects.

**Comment by stephentetley** [comment]
Hi Magnus

I've changed the "queries" to be Impure which means the all following:

~~~

memberOf
indexOf
indexOfLeft
indexOfRight
indices
find
findLeft
findRight
isPrefixOf
isInfixOf
isSuffixOf
count
exists
forall
findMap
findIndexOf
findIndexOfLeft
findIndexOfRight
findIndices
sameElements
    
~~~
    
By the same reasoning I think the folds and reduces should also be Impure though I haven't changed them yet. Is this correct?

Thanks

**Comment by magnus-madsen** [comment]
> By the same reasoning I think the folds and reduces should also be Impure though I haven't changed them yet. Is this correct?

Yes, just reading an array element is impure. The only possible thing that can be pure is if a function only reads the length of an array (which probably does not happen for any functions except for length).

**Comment by magnus-madsen** [comment]
Based on the discussion, I feel more convinced that the idea of having distinct names is bad.

It would be very nice if we had e.g. `reverse` and `reverse!` or `reverseInPlace` or something with namespaces so that it seems consistent.

However, while this looks nice for reverse, I want to point out that:

- If we keep the same names, e.g. `map` and `map!` (or `mapInPlace`) is it not counter-intuitive that these have different signatures? E.g. the return type is different but also that `mapInPlace` does not take a function from `a -> b`. 
- What about binary functions? For example `Set.union` is pretty clear, but what about `Set.unionInPlace` which of the two arguments would you expect to be changed? As opposed to `Set.addAll(s1, s2)` with the mnemonic that it "adds all in s1 to s2" (thus changing s2).

Thoughts?

**Comment by magnus-madsen** [comment]
> Another option lying between distinct and suffixed (albeit one I don't like much) to throw out would be to follow python's sort/sorted functions:

Good suggestion. But I also agree with your concern that it does not seem "functional-first" to relegate the functional names to `reversed` or `sorted`. And maybe it just to plain weird; people might be confused why there is both `sort` and `sorted`?

**Comment by magnus-madsen** [comment]
Stephen,

While you are revising the code, could I ask you to add the `mut` annotation appropriately. Here is how it is used:

```
    pub def addAll(s1: MutSet[a], s2: mut MutSet[a]): Unit & Impure =
```

It has absolutely no effect at the moment, but it might help with the current discussion and as a future documentation. You can see more examples here:

https://github.com/flix/flix/blob/master/main/src/library/MutSet.flix#L46

Thanks!

**Comment by stephentetley** [comment]
Thanks Magnus, I've just pushed a change that corrects folds and reducers. I'll look at `mut` annotations.

**Comment by stephentetley** [comment]
I've added `mut` annotations to the _InPlace functions and their respective helpers.

**Comment by magnus-madsen** [comment]
Hello Stephen,

It looked through the old PR, it looks like all my comments have already been fixed. Is that true? Did you have any thoughts about the switch expression?

**Comment by stephentetley** [comment]
Thanks Magnus

I think I've resolved all the issues.

As for switch expressions, I think I can manage comfortably with match/case. I wrote these two yesterday for the String additions wondering if switch would have helped and match/case seems easily sufficient: 


~~~

pub def abbreviateLeft(w: Int32, s: String): String =
    match length(s) {
        case len if len < w => s
        case _   if w < 3   => ""
        case len            => {
            let start = len - w + 3;
            "..." + slice(start, len, s)
        }
    }

pub def abbreviateRight(w: Int32, s: String): String =
    match length(s) {
        case len if len < w => s
        case _   if w < 3   => ""
        case _              => slice(0, w - 3, s) + "..."
    }
        
        
~~~

**Comment by magnus-madsen** [comment]
Here is an attempt at some principles:

### Mutable Data is Functional Data
In Flix, every mutable data structure can be used as a functional data structure. Mutable collections, such as `Array` and `MutSet` support functional operations such as `map`. Flix, being functional-first, reserves *functional names* for *functional operations*. Across all of the Flix standard library `map` has the same name and the same functionality.

### Destructive Operations are Marked with !
In Flix, every destructive operation is suffixed with an exclamation point. For example, `Array.reverse(a)` returns a new array with the elements of `a` in reverse order whereas `Array.reverse!(a)` destructively re-orders the elements of `a`.

### Name Consistency
In Flix, functional and destructive operations that share (i) similar behavior and (ii) similar type signatures share similar names. For example, `Array.reverse` and `Array.reverse!` share the same name because (i) their behavior is similar and (ii) their types are sufficiently similar:
```
def reverse(a: Array[a]): Array[a]
def reverse!(a: mut Array[a]): Unit
```

# Discussion

These are the principles. What do you think? 

Note: We have no requirement that says side-effecting operations must be named with `!`. Consequently, we are not renaming other functions such as File I/O or `Console.printLine`.

What does it mean to share the same behavior and type signature?

Example I: Insufficiently general type signature:
```
def map(f: a -> b & e, a: Array[a]): Array[b] & Impure
def map!(f: a -> a, a: mut Array[a]): Unit & Impure
```
A programmer might expect that he could map a function `x -> Some(x)` over an `Array[Int]` but this is not possible. Since this generality is an important part of `map` we must use a different name for `map!`. I propose `transform`.

Example II: Too Irregular type signature:
```
def union(xs: Set[a], ys: Set[a]): Set[a]
def union!(xs: MutSet[a], ys: MutSet[a]): Unit 
```
It is very unclear which set the `union!` operation would modify. This could lead to all kinds of bugs. The name `addAll` is slightly better because it can be read as `addAll` from `xs` to `ys`. At least the different name may give the programmer pause to think.

I made the following table to show how this might work out:

| Functional           | Destructive                                  |
|----------------------|----------------------------------------------|
| Array.map            | no equivalent, but see transform!         |
| Array.mapWithIndex   | no equivalent, but see transformWithIndex! |
| Array.reverse        | reverse!                                     |
| Array.replace        | replace!                                     |
| Array.patch          | patch!                                       |
| Array.updateSequence | updateSequence!                              |
| Array.sort           | sort!                                        |
| MutSet.union         | no equivalent, but see MutSet.addAll!                                |
| MutSet.intersection  | no equivalent, but see MutSet.retainAll!                             |
| MutSet.difference    | no equivalent, but see MutSet.removeAll!                             |
| MutSet.put           | MutSet.put!                                  |
| MutSet.remove        | MutSet.remove!                               |

Post-script 1: Is there a more standard name for `updateSequence`?
Post-script 2: I am still open to replacing "!" by something else, but for now I like "!" because it is short and already semi-established from Scheme.

**Comment by stephentetley** [comment]
I'm happy with those principles, but I was on the side of ! in the first place :)

The changes for the array PR would be:
~~~

mapInPlace => transform!
mapWithIndexInPlace => transformWithIndex!
reverseInPlace => reverse!
replaceInPlace => replace!
patchInPlace => patch!
updateSequenceInPlace => updateSequence!
sortByInPlace => sortBy!

~~~

Do you want me to make them or wait and give time for others to comment?

**Comment by magnus-madsen** [comment]
> Do you want me to make them or wait and give time for others to comment?

If there is no rush on your side, how about we at least give it 24h for people to comment and for us to sleep on.

**Comment by stephentetley** [comment]
That's fine by me.

**Comment by magnus-madsen** [comment]
Alright, let us make the renaming changes! :)

I also notice that `toListHelper` is non-tail recursive. If you have the time can you briefly check that functions are tail recursive. At least for the most critical functions where you would expect it, e.g. `toListHelper`. Thanks!

**Comment by magnus-madsen** [comment]
Oh, and `TestList.flix` still needs to be added to `TestLibrary.scala`.

**Comment by stephentetley** [comment]
I can't see the file `TestLibrary.scala` ?

To run the tests I've been running `LibrarySuite.scala`.

**Comment by stephentetley** [comment]
One oddity with ! is how do we name helper functions:

`transform!Helper` or `transformHelper!`

As helpers shouldn't be public it doesn't matter to the aesthetics of the API.

**Comment by magnus-madsen** [comment]
> 
> 
> One oddity with ! is how do we name helper functions:
> 
> `transform!Helper` or `transformHelper!`
> 
> As helpers shouldn't be public it doesn't matter to the aesthetics of the API.

I would put the ! at the end of the name.

Eventually we will get letrec, once that happens, we can move such functions into a more local scope and then their names becomes even less important. Probably most will simply be called `visit`. But that is for another day :)

**Comment by magnus-madsen** [comment]
> 
> 
> I can't see the file `TestLibrary.scala` ?
> 
> To run the tests I've been running `LibrarySuite.scala`.

You are right, but I do not see that file changed in the PR?

**Comment by stephentetley** [comment]
"TestArray" was in `LibrarySuite.scala` (line 24) before I started working on it.

**Comment by magnus-madsen** [comment]
> 
> 
> "TestArray" was in `LibrarySuite.scala` (line 24) before I started working on it.

Haha. D'oh!

**Comment by stephentetley** [comment]
I've just pushed the name changes and some tidying up of the comments.

Making `toListHelper` tail recursive and looking for others is to do.

**Comment by stephentetley** [comment]
Which version of `toList` / `toListHelper` do you prefer Magnus?

Using `reverse`:

~~~

    ///
    /// Returns the array `a` as a list.
    ///
    pub def toList(a: Array[a]): List[a] & Impure = toListHelper(a, 0, Nil)

    ///
    /// Helper function for `toList`.
    ///
    def toListHelper(a: Array[a], i: Int32, ac: List[a]): List[a] & Impure =
        if (i == length(a))
            List.reverse(ac)
        else {
            let x = a[i];
            toListHelper(a, i + 1, x :: ac)
        }
        
~~~        

Using a DList (Hughes list) which in this case is writing it in CPS:

~~~

    ///
    /// Returns the array `a` as a list.
    ///
    pub def toList(a: Array[a]): List[a] & Impure = toListHelper(a, 0, x -> x)

    ///
    /// Helper function for `toList`.
    ///
    def toListHelper(a: Array[a], i: Int32, ac: List[a] -> List[a]): List[a] & Impure =
        if (i == length(a))
            ac(Nil)
        else {
            let x = a[i];
            toListHelper(a, i + 1, tl -> ac(x :: tl))
        }
        
~~~~

**Comment by magnus-madsen** [comment]
Its up to you. I have a very slight preference for the one using `reverse` for its simplicity.

**Comment by stephentetley** [comment]
I'll go with the `reverse` one for now then. It can always be changed to CPS later if the performance of CPS is found to be better.

**Comment by stephentetley** [comment]
I've made `toListHelper` tail recursive and added a static argument for length rather than look it up each time. 

Plus these other minor changes to improve code quality:

* Removed helper for `range` (helper was used only to help casting to Pure, but `range` should have been Impure anyway).

* Renamed `transform!Helper` to `transformHelper!` (wrong name had crept in).

* Removed helper for `intersperse` (helper was used only to help casting to Pure, but `intersperse` should have been Impure anyway).

* Improved comment on `arrayWrites`.

* `foldLeftHelper` - added a static argument for length rather than look it up each time. 

* `reduceLeftHelper` - added a static argument for length rather than look it up each time. 

* `reduceRight` - bound length to len so `length()` isn't called twice.

* Made `groupByHelper` tail recursive.

* Changed if-expression in `agreeHelper` to have the "base case" first.

**Comment by magnus-madsen** [comment]
Let me know when it is ready and then I will merge it in soon.

**Comment by stephentetley** [comment]
I think it's ready unless you spot anything. Thanks.

**Comment by magnus-madsen** [comment]
OK; I will try to get it merged today then :)

**Comment by stephentetley** [comment]
Excellent - thanks!

**Comment by magnus-madsen** [comment]
I have re-generated the api at:

https://flix.dev/api/#/Array

Thanks again for your hardwork :)

**Comment by magnus-madsen** [comment]
Its kind of neat; if you search for ! you see all the destructive operations.

**Comment by stephentetley** [comment]
Thanks Magnus. 

I'm glad the Array additions in, I've just moved to a new branch for the String additions so I can use them.

**Pull request merged**
