### PR TITLE
refactor: avoid using Scheme in ClassEnvironment

### PR DESCRIPTION
**Pull request by mlutze**

### CODE REVIEW

**Comment by mlutze** [comment]
@magnus-madsen The only tests failing are associated types tests. Are we ok with letting associated types be broken during transition?

**Comment by magnus-madsen** [comment]
> @magnus-madsen The only tests failing are associated types tests. Are we ok with letting associated types be broken during transition?

Yes, I think so. Where are they used? We could mark those tests are ignore.

**Comment by magnus-madsen** [comment]
Can we (temporarily) remove associated types from the relevant TCs?

**Comment by mlutze** [comment]
It's only the tests specifically targeting associated types, so disabling them for now should be sufficient.

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
