### PR TITLE
feat: add a struct example with stack

### PR DESCRIPTION
**Pull request by dghosef**
This relies on https://github.com/flix/flix/pull/8334 to be merged first, so it is a draft for now

#8308

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I think this is a nice example. Do you have an idea for one more example?

**Review by magnus-madsen — COMMENTED** [review]
I have some small comments like:

- Probably we should be returning Options
- I would order the operations by complexity (since it is an example), so: newStack, peek, pop, and push
- What's the relation between arr.length and capacity? Are they not the same?

**Comment by dghosef** [comment]
>     * What's the relation between arr.length and capacity? Are they not the same?
Capacity is the total size of the underlying array. Length is the number of elements in the stack

**Comment by dghosef** [comment]
> I think this is a nice example. Do you have an idea for one more example?

Could do any number of mutable data structures(queue, hashmap, etc), though that's probably a bit repetitive.

Maybe have an array of `r, g, b` structs represent an image and mutate the image somehow?

**Comment by magnus-madsen** [comment]
> > I think this is a nice example. Do you have an idea for one more example?
> 
> Could do any number of mutable data structures(queue, hashmap, etc), though that's probably a bit repetitive.
> 
> Maybe have an array of `r, g, b` structs represent an image and mutate the image somehow?

Yeah. We want simple, not complex. It could be even simpler: just a struct that models some concept: Student? Animal? etc.

Take a look at https://doc.rust-lang.org/rust-by-example/custom_types/structs.html maybe?

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
