### PR TITLE
feat: add support for top-level imports

### PR DESCRIPTION
**Pull request by magnus-madsen**
NB: This desugars to type aliases. Later we will want to avoid desugarings.

### CODE REVIEW

**Comment by paulbutcher** [comment]
Is there a reason why we require a semicolon at the end of a top-level import? This seems out of step with other top-level constructs?

**Comment by paulbutcher** [comment]
> Is there a reason why we require a semicolon at the end of a top-level import? This seems out of step with other top-level constructs?

Hmm: I see that we require a semicolon after a `use` statement too.

But not after (e.g.) a `type alias`.

This seems inconsistent to me? Or am I missing something?

**Comment by magnus-madsen** [comment]
> > Is there a reason why we require a semicolon at the end of a top-level import? This seems out of step with other top-level constructs?
> 
> Hmm: I see that we require a semicolon after a `use` statement too.
> 
> But not after (e.g.) a `type alias`.
> 
> This seems inconsistent to me? Or am I missing something?

Its inconsistent. We just discussed in the office. 

One day we plan to have semi-colon inference, but because it is so brittle (and dangerous) it makes sense to add it as late as possible.

I am not sure what to do about the inconsistency today. Possibly we could drop it for top-level imports/uses.

**Comment by paulbutcher** [comment]
I agree about semicolon inference. In fact, I personally would recommend against even trying.

But this is a different question: this is whether the grammar requires a semicolon between (or more accurately, at the end of) top-level constructs. And for some (`use`, `import`) we do. For others (`type alias`, `enum`, ...) we don't. It strikes me that we should decide whether top-level constructs need a semicolon or not?

**Comment by magnus-madsen** [comment]
> I agree about semicolon inference. In fact, I personally would recommend against even trying.
> 
> But this is a different question: this is whether the grammar requires a semicolon between (or more accurately, at the end of) top-level constructs. And for some (`use`, `import`) we do. For others (`type alias`, `enum`, ...) we don't. It strikes me that we should decide whether top-level constructs need a semicolon or not?

We should and I think that semi-colons should not be required at the top-level.

**Pull request merged**
