### PR TITLE
test: use regions in `Test.Exp.Match.Array`

### LINKED ISSUE #3366: Restructure test cases for Ref/ScopedRef and Array/ScopedArray.

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes #3366

I think there are some match-expression related issues, though, I'm not sure I haven't made any mistakes.

### CODE REVIEW

**Comment by jaschdoc** [comment]
These tests simply crash the compiler. No error messages:
```flix
    @test
    def testMatchEmptyUnitArray01(): Bool = region r {
        match ([]: ScopedArray[Unit, Pure] @ r) {
            case [] => true
            case _  => false
        }
    }

    @test
    def testMatchEmptyBoolArray01(): Bool = region r {
        match ([]: ScopedArray[Bool, Pure] @ r) {
            case [] => true
            case _  => false
        }
    }

    @test
    def testMatchEmptyCharArray01(): Bool = region r {
        match ([]: ScopedArray[Char, Pure] @ r) {
            case [] => true
            case _  => false
        }
    }

    @test
    def testMatchEmptyFloat32Array01(): Bool = region r {
        match ([]: ScopedArray[Float32, Pure] @ r) {
            case [] => true
            case _  => false
        }
    }

    @test
    def testMatchEmptyFloat64Array01(): Bool = region r {
        match ([]: ScopedArray[Float64, Pure] @ r) {
            case [] => true
            case _  => false
        }
    }

    @test
    def testMatchEmptyInt8Array01(): Bool = region r {
        match ([]: ScopedArray[Int8, Pure] @ r) {
            case [] => true
            case _  => false
        }
    }

    @test
    def testMatchEmptyInt16Array01(): Bool = region r {
        match ([]: ScopedArray[Int16, Pure] @ r) {
            case [] => true
            case _  => false
        }
    }

    @test
    def testMatchEmptyInt64Array01(): Bool = region r {
        match ([]: ScopedArray[Int64, Pure] @ r) {
            case [] => true
            case _  => false
        }
    }

    @test
    def testMatchEmptyStringArray01(): Bool = region r {
        match ([]: ScopedArray[String, Pure] @ r) {
            case [] => true
            case _  => false
        }
    }

    @test
    def testMatchEmptyBigIntArray01(): Bool = region r {
        match ([]: ScopedArray[BigInt, Pure] @ r) {
            case [] => true
            case _  => false
        }
    }

    @test
    def testMatchEmptyOptionIntArray01(): Bool = region r {
        match ([]: ScopedArray[Option[Int32], Pure] @ r) {
            case [] => true
            case _  => false
        }
    }

    @test
    def testMatchEmptyResultArray01(): Bool = region r {
        match ([]: ScopedArray[Result[Int32, String], Pure] @ r) {
            case [] => true
            case _  => false
        }
    }
```

**Comment by jaschdoc** [comment]
Even though the array is impure inside the region `r`, how do I satisfy the type system in this expression?

```
>> Unable to unify the Boolean formulas: 'r' and 'false'.

462 |>         match ([1.1f32] @ r) {
463 |>             case [1.1f32] => true
464 |>             case _        => false
465 |>         }

mismatched boolean formulas.

Type One: ScopedArray[Float32, r]
Type Two: ScopedArray[Float32, false]
```

**Comment by mlutze** [comment]
```
    @test
    def testMatchEmptyUnitArray01(): Bool = region r {
        match ([]: ScopedArray[Unit, Pure] @ r) {
            case [] => true
            case _  => false
        }
    }
```

Shouldn't this just be `ScopedArray[Unit] @ r`?

**Comment by jaschdoc** [comment]
Oh did we update the syntax or did I misunderstand the type annotation?

**Comment by jaschdoc** [comment]
Ahh now it throws a parse error
```
-- Parse Error -------------------------------------------------- main/test/flix/Test.Exp.Match.Array.flix

>> Parse Error: Invalid input '@', expected ":", "and", "or", "->", '&', "as", Op, '`', <+>, **, *, /, mod, rem, +, - or <<< (line 5, column 38):
        match ([]: ScopedArray[Unit] @ r) {
    
```

**Comment by mlutze** [comment]
> Oh did we update the syntax or did I misunderstand the type annotation?

I could be wrong, but I thought `x @ r` was sugar for x[r]. Since ScopedArray is Type -> Bool -> Type, this would be an overapplication.

Still, this should have been caught by the Kinder.

**Comment by mlutze** [comment]
> Ahh now it throws a parse error
> 
> ```
> -- Parse Error -------------------------------------------------- main/test/flix/Test.Exp.Match.Array.flix
> 
> >> Parse Error: Invalid input '@', expected ":", "and", "or", "->", '&', "as", Op, '`', <+>, **, *, /, mod, rem, +, - or <<< (line 5, column 38):
>         match ([]: ScopedArray[Unit] @ r) {
>     
> ```

Wat.

**Comment by jaschdoc** [comment]
I guess that's why we have tests :joy:

**Comment by mlutze** [comment]
Try `ScopedArray[Unit, r]`?

**Comment by magnus-madsen** [comment]
The type rules for pattern matching on arrays are not right! I think I forgot about them. Will need to double check before you proceed :)

**Comment by magnus-madsen** [comment]
The syntax should be: `ScopedArray[Unit, r]` .. but I need to update the Typer.. I think :)

**Comment by magnus-madsen** [comment]
OK, so we need to fix one problem each:

- Type rules (for me)
- Syntax (for you)

**Comment by jaschdoc** [comment]
This test has a type error:
```flix
    @test
    def testMatchFloat32Array1(): Bool = region r {
        match ([1.1f32] @ r) {
            case [1.1f32] => true
            case _        => false
        }
    }
```
**Error**
```

-- Type Error -------------------------------------------------- main/test/flix/Test.Exp.Match.Array.flix

>> Unable to unify the Boolean formulas: 'r' and 'false'.

461 |>         match ([1.1f32] @ r) {
462 |>             case [1.1f32] => true
463 |>             case _        => false
464 |>         }

mismatched boolean formulas.

Type One: Array[Float32, r]
Type Two: Array[Float32, false]
```

All other tests share the same error, this is simply the top most error in IntelliJ.

**Comment by magnus-madsen** [comment]
Continued in #4125

**Pull request closed without merging**
