### PR TITLE
feat: add File a wrapper over the JDK's RandomAccessFile (see #6402)

### PR DESCRIPTION
**Pull request by stephentetley**
This PR adds a `File` module which is a wrapper over Java's `RandomAccessFile`. It changes the name of the existing `File` module to `Files` - this is a convention that Java uses: collect utility functions in a module with a pluralized name.

`File` is made an instance of `Reader`.

I've added a `ToString` instance to `IOError` (used in debugging but not needed in the final code) and an `IOError` version of `Result.tryCatch` which is very useful for wrapping IO functions that can fail.

Tests use a set of prepared files and also write to new files in the `testdata` directory.

Downsides: 
`RandomAccessFile` is not a modern Java class. The set of methods it provides seem biased towards serializing and deserializing Java data between Java programs. It is missing proper Unicode support and and reading and writing IEEE 754 floats and doubles (the format `RandomAccessFile` uses for Float and Double is a Java specific one). Also with Java not having unsigned types, the widening / truncation is not very pleasant - i.e. to work with unsigned "bytes" `Int32` is the chosen number type... 

My suspicion is that `File` (wrapping RandomAccessFile) isn't really going to be the general file type we would want as the canonical `File` type in the standard library in the long term. That said I thing it would be useful in the short term as the current `Files` module doesn't really support incremental reading and writing.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Thanks Stephen-- Looking forward to review it.

One quick thing: Could we do the rename of `File` to `Files` in a separate PR?

**Comment by stephentetley** [comment]
> One quick thing: Could we do the rename of File to Files in a separate PR?

Yes I'll do that.

**Comment by stephentetley** [comment]
PR  #6423

**Comment by stephentetley** [comment]
I'll make a new PR for this, the conflicts are a bit messy for me.

**Pull request closed without merging**
