### PR TITLE
Refactor `List.toMut`

### PR DESCRIPTION
**Pull request by jaschdoc**
`List.toMut` should construct a `MutList` using `MutList`'s interface.
Complements #2009.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
OK, you mean that it should not construct the value directly?

My concern is that this is slower than what we are currently doing (but of course only by a constant factor).

**Comment by jaschdoc** [comment]
Yes exactly. Is there anything we could do instead to make it faster?

**Comment by magnus-madsen** [comment]
> 
> 
> Yes exactly. Is there anything we could do instead to make it faster?

Instead of `ref length(xs)` we could ask the array for its length (introduce a local variable and then `.length`.)

**Comment by jaschdoc** [comment]
What about this version? I think it's messy since it leaks a lot of implementation details from `MutList` to `List`, or rather when reading the implementation of `List.toMut` it is required to know the implementation of `MutList`. This specific implementation should be faster than my previous suggestion.

Otherwise, I think using a tail recursive helper function could solve the issue such that `xs` is only iterated upon **once**. Again, this function would have to know the implementation details of `MutList`

**Comment by magnus-madsen** [comment]
I would actually like to backtrack my comments.

I had actually misunderstood the existing code. The call to `toArray` is also expensive.

I now agree with original solution you proposed:

```
        let v = MutList.new();
        xs |> foreach(x -> MutList.push!(x, v));
        v
```

I think this is what we should do for now

**Pull request merged**
